### ISSUE TITLE
[Bug]: it's actually a vital error.

### ISSUE THREAD

**Issue by egcash** [danny-avila/LibreChat#1001]
### What happened?

When I were making interaction with sydney,then I tried to intercept the requests.

I found that,cookies are clearly visible in the headers while sending requests,that can be used to perform any illegal purposes.

Please add a support to encrypt or any way to hide the original bing cookie to keep it private.

### Steps to Reproduce

1.I started chatting
2. After some conversation,i intercepted the requests.
3. Found critical Infos like bing cookies are public.

### What browsers are you seeing the problem on?

Chrome, Mobile (Android)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I don’t know what version you’re on but this concern is already taken care of on latest. It sounds like you’re not on latest.

First off, you need to submit your keys/cookies unencrypted the first time. From there on out the server will encrypt your credentials and they are not transmitted from frontend to server or vice versa any longer.

secondly, the only way to properly protect yourself from man-in-the-middle attacks is to use a secure transport layer (HTTPS): https://stackoverflow.com/questions/55284590/node-js-server-request-to-https-enough-for-encryption
