### ISSUE TITLE
Open-interpreter integration?

### ISSUE THREAD

**Issue by jordantgh** [danny-avila/LibreChat#1010]
### What features would you like to see added?

https://github.com/KillianLucas/open-interpreter

They have recently done an update which they say should allow integration into other tools more easily. Have you ever tried it out? It’s quite cool, at least on the terminal, and I think it suits the containerised approach quite well since the code environment is pretty isolated.

I’d totally be up for working on this but obviously only if it’s something appealing, and I’d need some guidance of how to approach it.

### More details

Open interpreter is a library for using letting chat models execute arbitrary code on your machine like ChatGPT WebUI Code Interpreter/Advanced Data Analysis.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I will eventually tackle this but not for a while (after file support is integrated). It doesn’t seem hard to replicate the source code (at least for 1.0 of open-interpreter since that’s what I looked at last), but this new chat feature for app integration seems handy.

since it’s in python, we could use my fastapi setup: https://github.com/danny-avila/ai-services

**Comment by MchLrnX** [comment]
Any updates on this now that files are supported? I've love to see more file formats supported, as well as the ability to interact with a file system.

**Comment by fuegovic** [comment]
> Any updates on this now that files are supported? I've love to see more file formats supported, as well as the ability to interact with a file system.

more file format will be supported when the assistants api is added to librechat, the current eta for the update is january

**Comment by finnless** [comment]
Here is another open source project that is more similar to OpenAI's Code Interpreter / Data Analytics: https://github.com/shroominic/codeinterpreter-api
It seems like [open-interpreter](https://github.com/KillianLucas/open-interpreter) is more focused on being run on users local machines.

**Comment by Techie5879** [comment]
Any updates on this?

**Comment by danny-avila** [comment]
> Any updates on this?

I have ideas on how to integrate an open source code-interpreting tool, it's not currently a priority but is on the roadmap for this year: https://librechat.ai/blog/2024-roadmap

**Comment by lix2k3** [comment]
Is open-interpreter integration on the roadmap?

**Comment by Buckler89** [comment]
I believe this feature is fantastic! Are there any updates on the release timeline?

**Comment by jordantgh** [comment]
> I believe this feature is fantastic! Are there any updates on the release timeline?

https://www.librechat.ai/blog/2024-02-19_2024_roadmap

It's no longer on the 2024 roadmap. Lots to do still, and I guess quite a complex feature to do right. Might be good for a PR to get the ball rolling (ngl it's outside of anything I can commit to right now as I'm writing my PhD thesis).

**Comment by danny-avila** [comment]
> https://www.librechat.ai/blog/2024-02-19_2024_roadmap
> 
> It's no longer on the 2024 roadmap. Lots to do still, and I guess quite a complex feature to do right. Might be good for a PR to get the ball rolling (ngl it's outside of anything I can commit to right now as I'm writing my PhD thesis).


The roadmap is flexible, I wrote it in February so it can definitely be adaptive.

Open Interpreter could be easy but not scalable. A more scalable solution is harder to implement
