### ISSUE TITLE
Enhancement: Predefined prompts

### ISSUE THREAD

**Issue by frankhommers** [danny-avila/LibreChat#1016]
### What features would you like to see added?

I would like to predefine prompts. Something like the prompt sidebar (right side) of https://github.com/mckaywrigley/chatbot-ui

### More details

![image](https://github.com/danny-avila/LibreChat/assets/7355878/b7415ec8-30db-4c7c-ba58-ac36318a3184)

![image](https://github.com/danny-avila/LibreChat/assets/7355878/48146d0c-e0a9-4e60-a67c-30b3b64f8d5f)

### Which components are impacted by your request?

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Great suggestion, I think this would definitely be welcome

**Comment by danny-avila** [comment]
closing in favor of https://github.com/danny-avila/LibreChat/issues/3023
