### ISSUE TITLE
 Can you add custom Reverse Proxy directly in Web UI instead of using env variable?

### ISSUE THREAD

**Issue by eienmojiki206** [danny-avila/LibreChat#1017]
### Contact Details

jirozen67@gmail.com

### What features would you like to see added?

Can you add custom Reverse Proxy directly in Web UI instead of using env variable?

### More details

It's will more flexible if added. Thank u!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Yes! This is already planned

**Comment by piwawa** [comment]
> Yes! This is already planned

So where is the **base_url** setting button??

![image](https://github.com/user-attachments/assets/314b22af-1434-44a5-a3b3-4e0e8bdf82d0)
