### ISSUE TITLE
[Bug]: Bing is not working properly (no problems in Sydney)

### ISSUE THREAD

**Issue by LKVK-Louis** [danny-avila/LibreChat#1022]
### Contact Details

Louis090822@hotmail.com

### What happened?

Recently I have just set up, in the test found that Bing can only return a sentence, and very slow, the second time will directly report an error: Something went wrong. Here's the specific error message we encountered: Unexpected server response: 200

### Steps to Reproduce

1. Ask a normal question
2. An error will be reported if you ask again

### Screenshots

![截屏2023-10-07 20 03 34](https://github.com/danny-avila/LibreChat/assets/138469333/1f571add-a4c8-4d31-bc8f-781672617a79)
![截屏2023-10-07 20 02 53](https://github.com/danny-avila/LibreChat/assets/138469333/e9716ef7-2cc9-4eaa-a683-99c567d3b2d1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
There are some issues that will be mitigated with this dependency PR merged: https://github.com/waylaidwanderer/node-chatgpt-api/pull/481
