### ISSUE TITLE
[Bug]: Cannot convert argument to a ByteString

### ISSUE THREAD

**Issue by OdinGitDat** [danny-avila/LibreChat#1030]
### What happened?

I added Bing api key following [the instructions](https://github.com/waylaidwanderer/node-chatgpt-api/issues/378#issuecomment-1559868368). When I try to use the model I get the following error:

`Cannot convert argument to a ByteString because the character at index 512 has a value of 8230 which is greater than 255.`

### Steps to Reproduce

1 add bing api key
2 submit any prompt
3 observe error message

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Sorry about this, but I can't reproduce it following the same instructions I wrote

![image](https://github.com/danny-avila/LibreChat/assets/110412045/ad47204b-7621-4381-807a-729a5d8b4044)

In general, any time you have issues with Bing, you should check the node-chatgpt-api repo to see if anyone has had your issue. In this case, it's true: https://github.com/waylaidwanderer/node-chatgpt-api/issues/302

https://github.com/waylaidwanderer/node-chatgpt-api/issues/393
