### ISSUE TITLE
[Bug]: Bing AI null error after giving cookie api key

### ISSUE THREAD

**Issue by Peteryhs11** [danny-avila/LibreChat#1032]
### What happened?

**After inputing the full cookie string into the browser end, bing ai is returning "Something went wrong. Here's the specific error message we encountered: null".**

I have also tried with modifying the bing ai key value in `.env` and the `_U` string.

However, none of them seems to work out.

**System: Zorion OS 16.3 (Ubuntu)**
**Installation method: Docker**

### Steps to Reproduce

1. Attempt to add an api key to the bing ai section
2. Attempt to send a message 

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Closing in favor of #1028 

There was an update to the Bing backend API. there is a fix, but not yet merged to the dependency we're using: https://github.com/waylaidwanderer/node-chatgpt-api/pull/481

**Comment by danny-avila** [comment]
I will probably fork the dependency at this point or we may be waiting weeks

**Comment by danny-avila** [comment]
https://github.com/danny-avila/LibreChat/pull/1050 fix is officially merged
