### ISSUE TITLE
[Question]: Hello, what is the reason for this problem when I call the bing cookie

### ISSUE THREAD

**Issue by hjfvhjmhj** [danny-avila/LibreChat#1041]
### What is your question?

Something went wrong. Here's the specific error message we encountered: null

### More Details

The cookie I use is the value of the cookie in the f12 network module, and this value can be used normally

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
See #1022

**Comment by hjfvhjmhj** [comment]
OK thanks

**Comment by danny-avila** [comment]
https://github.com/danny-avila/LibreChat/pull/1050 fix is officially merged
