### ISSUE TITLE
[Question]: Something went wrong. Here's the specific error message we encountered: null

### ISSUE THREAD

**Issue by Akolangt0** [danny-avila/LibreChat#1048]
### What is your question?

How do I fix this error in Bing Sydney?

### More Details

I did what the possible solutions are but this still pops up. Do you have any solution that you can provide?

### What is the main subject of your question?

Endpoints, User System/OAuth, Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
See #1022

**Comment by danny-avila** [comment]
https://github.com/danny-avila/LibreChat/pull/1050 fix is officially merged
