### ISSUE TITLE
Enhancement: respect the preferred language from http `Accept-Language` header

### ISSUE THREAD

**Issue by PeterDaveHello** [danny-avila/LibreChat#1054]
### What features would you like to see added?

Auto-detect user's preferred language via HTTP Accept-Language header for unauthenticated users.

### More details

The project already offers multilingual support, which is great. However, this feature is not fully utilized before a user logs in or registers. Currently, users cannot manually select a language before authentication, and the system does not automatically set the language based on the HTTP Accept-Language header, the language before login and manual setting will always be English only.

Implementing this would enhance the user experience by automatically presenting the UI in a language that aligns with the user's browser settings.

### Which components are impacted by your request?

General, UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thank you for your suggestion and your insight! Language support has been one of the most contributed features to this project from the community so this will surely be looked at and worked on

**Comment by PeterDaveHello** [comment]
Glad to know that! Would even be better if this setting can be stored for each user :star_struck:
