### ISSUE TITLE
[Bug]: Bing does not work again.

### ISSUE THREAD

**Issue by maggieqnr** [danny-avila/LibreChat#1078]
### What happened?

Bing can only chat one round and the second round will show errors. However this issue would not happen to Sydney. 

### Steps to Reproduce

![搜狗截图20231019220914](https://github.com/danny-avila/LibreChat/assets/146079448/67ab3561-7fa1-4c0e-9631-b3697c54ab5a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
It's a commun error, see:
#1011 
#1022 
#727 
#798
