### ISSUE TITLE
Enhancement: Restore BrowserOp

### ISSUE THREAD

**Issue by chokiproai** [danny-avila/LibreChat#1087]
### What features would you like to see added?

BrowserOp can be restored

### More details

I use the old version, it still works fine

### Pictures

![image](https://github.com/danny-avila/LibreChat/assets/128912789/d8adc724-1655-42ca-8b99-c5e79a295199)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I just tested it and you're right, I'll be adding it back

![image](https://github.com/danny-avila/LibreChat/assets/110412045/9b815ab5-16d2-4e84-88fd-84aa1ebfd1e6)
