### ISSUE TITLE
[Bug]: `Plugins` seem to ignore proxy?

### ISSUE THREAD

**Issue by Manouchehri** [danny-avila/LibreChat#1114]
### What happened?

When using plugins, it seems like the `PROXY` set in `.env` is completely ignored. Seems to work fine in other modes though.)

### Steps to Reproduce

1. Set a HTTP proxy in `.env`. e.g. `PROXY="http://1.2.3.4:31337"`
2. Switch to `Plugins` mode in a new conversation.
3. Start a thread. You'll notice that the requests to the endpoints are not going through the proxy.

### Screenshots

<img width="398" alt="image" src="https://github.com/danny-avila/LibreChat/assets/7232674/8df53095-1589-4048-9fad-3e10823437b9">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
this is a backlog item, I could see about implementing it soon: https://github.com/danny-avila/LibreChat/issues/642
