### ISSUE TITLE
[Question]: I can't use the GPT-4 model in the ChatGPT Endpoint

### ISSUE THREAD

**Issue by letiennam29** [danny-avila/LibreChat#1122]
### Contact Details

letiennam29@gmail.com

### What is your question?

use the GPT-4 model in the ChatGPT Endpoint

### More Details

I can't use the GPT-4 model in the ChatGPT Endpoint. I'm encountering an error as shown in the image below. 

<img width="931" alt="image" src="https://github.com/danny-avila/LibreChat/assets/5987534/d418d6df-fc3c-4212-93a4-7e64e8ead5ee">

### Screenshots

<img width="931" alt="image" src="https://github.com/danny-avila/LibreChat/assets/5987534/dc56ad1c-564f-451c-b5e2-a281e8c9aa49">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
The request is being blocked by OpenAI. Not much you can do here
