### ISSUE TITLE
Enhancement: store bing cookies in json file

### ISSUE THREAD

**Issue by Airkek** [danny-avila/LibreChat#1133]
### What features would you like to see added?

It would be nice if we can set bing cookies in json file so that we could change them without restarting entire app. Why? Bing always dropping login and we can use autologin scripts.

### More details

.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Berry-13** [comment]
We can add support to both of them, because for most of the users (including me) it is much simpler a string instead of a file (as on PaLM)

**Comment by Airkek** [comment]
> We can add support to both of them

It would be nice

**Comment by artificialartofficial** [comment]
Is there a script which could be run to automatically scrape the user's bing.com cookie on startup?
