### ISSUE TITLE
[Bug]: meilisearch error when running scripts

### ISSUE THREAD

**Issue by fuegovic** [danny-avila/LibreChat#1139]
### What happened?

For some reasons, some scripts are affected by an error related to meilisearch. Tested both local and docker, and both linux and windows

### Steps to Reproduce

as least 2 scripts are affected:
- npm run create-user
&
- npm run ban-user
(on windows passing the arg directly to "ban-user" seems to work)

### Relevant log output

```shell
> node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

MeiliSearchCommunicationError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: undefined,
  code: undefined
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
I tested on a third pc (windows) and on that 3rd one it is working, which surprised me since all were tested on the latest LibreChat update with the same .env file 🤷‍♂️

Side note, the "create-user" script, does not write the new user to the db when "successful"

**Comment by ivanushkaPr** [comment]
And what the solution to fix the bug?

**Comment by fuegovic** [comment]
> And what the solution to fix the bug?

This specific issue has been fixed afaik
