### ISSUE TITLE
Enhancement: Allow specifying EMAIL_SMTP_DOMAIN

### ISSUE THREAD

**Issue by Manouchehri** [danny-avila/LibreChat#1178]
### What features would you like to see added?

Adding `EMAIL_SMTP_DOMAIN` to `.env.`.

### More details

https://github.com/danny-avila/LibreChat/blob/e383ecba8589de40cc25ba8eaac9c09af6134c53/api/server/utils/sendEmail.js#L8C1-L13

We'd need to allow setting the `host` field at a minimum. 

```javascript
const transporter = nodemailer.createTransport({
  host: "smtp.forwardemail.net",
  port: 465,
  secure: true,
  auth: {
    // TODO: replace `user` and `pass` values from <https://forwardemail.net>
    user: "REPLACE-WITH-YOUR-ALIAS@YOURDOMAIN.COM",
    pass: "REPLACE-WITH-YOUR-GENERATED-PASSWORD",
  },
});
```

### Which components are impacted by your request?

General

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Pikaro** [comment]
PR here: https://github.com/danny-avila/LibreChat/pull/1219
