### ISSUE TITLE
Enhancement: Add DuckDuckGo

### ISSUE THREAD

**Issue by mmwong1984** [danny-avila/LibreChat#1181]
### Contact Details

me@mmw1984.link

### What features would you like to see added?

add this project as an search engine
https://github.com/binjie09/duckduckgo-api

### More details

For example I am going to search ChatGPT and this maximum results is 10
http://domain.com/search?q=ChatGPT&max_results=10

### Which components are impacted by your request?

Plugins

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jipok** [comment]
Why closed? DuckDuckGo even don't requires KEY/TOKEN. Just works out of box.

**Comment by danny-avila** [comment]
> @danny-avila Why closed? DuckDuckGo even don't requires KEY/TOKEN. Just works out of box.

If anyone wants to contribute it, it would be welcome.

**Comment by PratikCrimson** [comment]
is this added yet ?
