### ISSUE TITLE
Enhancement: Customise default model

### ISSUE THREAD

**Issue by mmwong1984** [danny-avila/LibreChat#1183]
### Contact Details

me@mmw1984.link

### What features would you like to see added?

The defalt model now is gpt-3.5-turbo
However, I want gpt-4 as the default model
I wish there are an env (DEFAULT_MODEL_OPENAI=gpt-4)

### More details

thx

### Which components are impacted by your request?

General

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
There will be an update within the week that should make your last selected model consistently your 'default' model. This is intended but is not always working right but I have a permanent fix along with other major changes.

Another workaround is to set the OPENAI_MODELS env variable explicitly and have your default at the top.

**Comment by mmwong1984** [comment]
Good, thx
