### ISSUE TITLE
[Bug]: Models are not fetching through proxy

### ISSUE THREAD

**Issue by Airkek** [danny-avila/LibreChat#1191]
### What happened?

I have Russian IP, since today OpenAI declines API requests from Russian addresses.
I use proxy for completions and it works fine but after restarting librechat i found this line:
```
Failed to fetch models from OpenAI API
```

### Steps to Reproduce

1. Go to api/server/ModelService.js
2. see line 44

### Relevant log output

```shell
Failed to fetch models from OpenAI API
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
fixing this now!
