### ISSUE TITLE
[Bug]: Minor colour bug

### ISSUE THREAD

**Issue by mmwong1984** [danny-avila/LibreChat#1193]
### What happened?

Hi, there seems to be some problems in the send button.
If I choose gpt-4, colour of the send button should be purple, but not green.

### Steps to Reproduce

![Screenshot_2023-11-17-09-12-39-953_com android chrome-edit](https://github.com/danny-avila/LibreChat/assets/103017331/1f12893d-b0e7-4ce8-9676-c39471b9ffed)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This is from a recent update but we are replacing the UI and removing this, so it's unplanned
