### ISSUE TITLE
Token rate is integer in db which doesn't work for gpt-3.5-turbo-instruct: $0.0015 / 1K tokens

### ISSUE THREAD

**Issue by myxgenius** [danny-avila/LibreChat#1229]
### What happened?

The minimal token rate 1 stands for 0.001 / 1k tokens, but gpt-3.5-turbo-instruct is $0.0015 / 1K tokens.

This may happen to more models when prices drop in the future.

### Steps to Reproduce

Use open AI model gpt-3.5-turbo-instruct to chat with balance enabled.

What happened:
An error message: Insufficient Funds! Balance: 8495.5. Prompt tokens: undefined. Cost: null.

Is it possible to define gpt-3.5-turbo-instruct with $0.0015 / 1K tokens rate?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
The bug isn't what you think it is, as the rate is correct. However I'm fixing it as we speak

**Comment by danny-avila** [comment]
The units for the balance are not generation tokens. They are token "credits" which means 1000 credits = $0.001 (1 mill USD)
