### ISSUE TITLE
[Bug]: Filter out duplicate models

### ISSUE THREAD

**Issue by Manouchehri** [danny-avila/LibreChat#1240]
### What happened?

<img width="519" alt="image" src="https://github.com/danny-avila/LibreChat/assets/7232674/557ea888-1f67-4800-bea6-7aa03e480e08">

### Steps to Reproduce

1. Use an OpenAI API proxy that returns multiple entries for the same model name
2. See duplicates in dropdown

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Mobile (iOS), Mobile (Android)

### Relevant log output

```shell
Related to https://github.com/BerriAI/litellm/issues/942.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Manouchehri** [comment]
I'm unsure if this should be fixed here or in LiteLLM.

**Comment by danny-avila** [comment]
> I'm unsure if this should be fixed here and/or in LiteLLM.

I’ve never had this issue so it may need to be on their end. If they are aggregating all models from all providers that could be it. 

Do nothing is always faster, as this will add an extra operation for an edge case, but if we do adjust this on our end it should be on the frontend

**Comment by danny-avila** [comment]
After looking at https://github.com/BerriAI/litellm/issues/942, I would rather have them fix it, as the server generating the list should be responsible for this.

**Comment by danny-avila** [comment]
> yep - we'll fix it on our end @danny-avila @Manouchehri

thank you! 🙏
