### ISSUE TITLE
Enhancement: allow choosing preset as default

### ISSUE THREAD

**Issue by squidpickles** [danny-avila/LibreChat#1256]
### What features would you like to see added?

When opening a new chat, currently the default model (first model in the list) is selected. However, no presets are loaded. Ideally, it would be possible to choose a preset to start with for each new chat.

### More details

For example, I have a system prompt that I would like to add to all of my new conversations. The way I've found to do that is to create a preset that has it enabled. But, whenever I start a new chat, I need to select the preset again to load it. It'd be helpful to have a single button press (New Chat) start the chat with all settings ready to go.

### Which components are impacted by your request?

General, UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squidpickles** [comment]
Oh, awesome, thanks. Should this be closed as a duplicate?

**Comment by squidpickles** [comment]
> Oh, awesome, thanks. Should this be closed as a duplicate?

Aha, just saw that wasn't listed as in issue. TIL about GitHub Discussions

**Comment by danny-avila** [comment]
it's done, will be testing and merge later today: https://github.com/danny-avila/LibreChat/pull/1275
