### ISSUE TITLE
[Bug]: Always reach Token Limit on OpenAI

### ISSUE THREAD

**Issue by OCT-Burnz** [danny-avila/LibreChat#1262]
### What happened?

On longer conversations i always reach the token limit when having a conversation with OpenAI. I'm then forced to remove some text in the backlog of the chat. Current work-around is to let it summarize the conversation and opening a new one. I've checked OpenAI already and their limit is capped at 10k for all Tiers.

Something went wrong. Here's the specific error message we encountered: Error: 429 Request too large for gpt-4-1106-preview in organization org-XXXXXX on tokens per min (TPM): Limit 10000, Requested 10005. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.

### Steps to Reproduce

Generate a long conversation and you will reach the OpenAI token limit.

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/13125500/91804437-633d-411d-9375-4130fc7821f8)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I see, you’re running into issues because you apparently need Tier 3 to unlock the 128k context, which it is configured to by default: https://www.reddit.com/r/ChatGPT/comments/17pp756/gpt4turbo_or_gpt41106preview_limit/

**Comment by OCT-Burnz** [comment]
Thanks for the clarification! Can confirm that sending API credit does indeed increase the limit. Solved my issue.
