### ISSUE TITLE
[Bug]: BingAI will say one less word in special cases

### ISSUE THREAD

**Issue by dcityteg** [danny-avila/LibreChat#1277]
### What happened?

When I ask BingAI some questions it will search for, it will write one word less (at the beginning) when outputting

Here's an example:
![image](https://github.com/danny-avila/LibreChat/assets/132677224/7f2c6e6b-00b2-461d-9514-6621b8f6a4cb)

### Steps to Reproduce

1.Ask BingAI some questions that require an internet connection
2.When BingAI finishes searching the web and is ready to output, it will write one less word at the beginning

### What browsers are you seeing the problem on?

Microsoft Edge

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/132677224/b2ef07b0-5c1e-4537-9637-e5d78f248605)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Please see the following discord channel for common solutions for Bing. This particular issue could be IP related.

https://discord.com/channels/1086345563026489514/1143941308684177429

**Comment by danny-avila** [comment]
BingAI access is hacky and not fully supported. There are too many issues that can be specific to your location/IP/microsoft account, etc.

**Comment by fuegovic** [comment]
yeah, this has been going on for a while, (since bing is showing `searching the web for:...`) It one of the thing we have to accept due to the hacky nature of the integration.
