### ISSUE TITLE
Enhancement: Option to Pre-filter with OpenAI Moderation Endpoint

### ISSUE THREAD

**Issue by omltcat** [danny-avila/LibreChat#1288]
### What features would you like to see added?

OpenAI provides a free [Moderation Endpoint](https://platform.openai.com/docs/guides/moderation/overview). You can use it to check if what you want to send complies with their policies. An option to toggle such functionality when using OpenAI API would be helpful. It can potentially be further integrated into existing moderation of LibreChat on user behaviors. 

### More details

OpenAI bans accounts for misuse of API. In many cases, the user is unaware of something making OpenAI unhappy. The optional moderation endpoint pre-filter may provide an additional layer of safeguard against accidentally getting banned while using their API.  

In an ideal world, we should be given the chance to choose if and how we want our APIs moderated, but this is what we have now. 

### Which components are impacted by your request?

Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks! We will definitely work on this, @Berry-13 mentioned it the other day
