### ISSUE TITLE
[Bug]: Preset not re-loaded upon login, had to refresh the page

### ISSUE THREAD

**Issue by myxgenius** [danny-avila/LibreChat#1320]
### What happened?

After signing in to an account, the preset settings are not reloaded unless I refresh the page.

### Steps to Reproduce

1. Sign in to account A, add preset named 'A's preset'
2. Sign out
3. Sign in to account B, check the preset, it shows 'A's preset' (unexpected, because that's account A's preset)
4. Refresh the page
5. Now it shows no preset because B hasn't add a preset yet.
6. Sign out
7. Sign in to account A, check the preset, it shows no preset
8. Refresh the page
9. Now it shows 'A's preset'

I would guess if sign in to an account in a new device/browser, the preset is not load until the page being refreshed'

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This is only happening because localStorage saves the last conversation setup, and you're using the same browser. I thought I added some handling to delete it on logout but I'll investigate and make it more robust.

**Comment by danny-avila** [comment]
Thanks for the report, this is now fixed on the latest commit on main
