### ISSUE TITLE
Enhancement: Drag or paste documents to provide context

### ISSUE THREAD

**Issue by eburnette** [danny-avila/LibreChat#1322]
### Contact Details

_Redacted_

### What features would you like to see added?

Note this is different from RAG and file upload. I just want it to work like Anthropic's claude site where I can drag files (pdf, txt, etc.) into the chat and have it included in the context. In addition, if I paste a large amount of text in there, it should treat it like I dragged a text file in (see the screenshot).

### More details

Both claude and chatgpt let you drag files into the chat window to provide additional context. It doesn't perform embedding or vector search on them, it just provides additional context. The experience should be identical to adding images.

### Which components are impacted by your request?

General

### Pictures

![image](https://github.com/danny-avila/LibreChat/assets/1093707/f419ab90-93a1-4850-a51e-b874f38b18ec)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UPman24** [comment]
I've got the same needs.

**Comment by UPman24** [comment]
> I've got the same needs.

Actually, dragging and dropping isn't necessary. As long as I can upload files like PDFs, Word docs, and PowerPoints, that works for me too.

**Comment by EmmaWebGH** [comment]
Would love to see RAG options included.

**Comment by iiitmahesh** [comment]
@danny-avila, I'm trying on adding vector database plugins, like connect Pinecone index. Any suggestions? Is this feature on your roadmap by any chance ?

**Comment by danny-avila** [comment]
> @danny-avila, I'm trying on adding vector database plugins, like connect Pinecone index. Any suggestions? Is this feature on your roadmap by any chance ?

Just released RAG API to the project: https://github.com/danny-avila/rag_api

I will close this issue today as I'll add an option to load the full context of the document

**Comment by danny-avila** [comment]
Closed by https://github.com/danny-avila/LibreChat/pull/2169

> - Adds experimental new variable `RAG_USE_FULL_CONTEXT` which will retrieve the full document and add it to the prompt instead of using semantic retrieval. 

```
RAG_USE_FULL_CONTEXT=true
```

There is still a frontend option yet to be implemented to allow toggling this behavior from a user level instead of from an environment variable.
