### ISSUE TITLE
Enhancement: Dedicated Reverse Proxy Endpoint

### ISSUE THREAD

**Issue by eburnette** [danny-avila/LibreChat#1344]
### Contact Details

_Redacted_

### What features would you like to see added?

Support models served by Anyscale (https://app.endpoints.anyscale.com/).

### More details

Anyscale supports a number of open source llms as fully managed API endpoints. The first million tokens are free so all you need is to sign up and get an API key. They support the OpenAI API, including function calls.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
https://docs.anyscale.com/endpoints/model-serving/openai-migration-guide

It should already work if you set `OPENAI_REVERSE_PROXY` to ANYSCALE_API_BASE

**Comment by fuegovic** [comment]
It seems to be working indeed:
```bash
OPENAI_API_KEY=esecret_xxxxxxxxxxxxxxxxja79 # Anyscale API key
OPENAI_REVERSE_PROXY=https://api.endpoints.anyscale.com/v1/chat/completions
```

![image](https://github.com/danny-avila/LibreChat/assets/32828263/1d6f4233-803e-40e6-861a-fbbcb0fbf66b)

**Comment by eburnette** [comment]
That works, but it still says OpenAI in the UI, and once you have this set up you can't switch to an OpenAI model.

BTW I found a similar site, portkey.ai (https://portkey.ai/docs/welcome/what-is-portkey) that supports more models. For all but OpenAI, though, you have to use their sdk.

**Comment by fuegovic** [comment]
> That works, but it still says OpenAI in the UI, and once you have this set up you can't switch to an OpenAI model.

This has been discussed on discord. Looks like it's planned, but it's not a priority.
![image](https://github.com/danny-avila/LibreChat/assets/32828263/e1d5664d-387d-4729-b261-e7065121b76b)

**Comment by fuegovic** [comment]
@eburnette @danny-avila I changed the title to better reflect the nature of the feature request, and re-opened it since a dedicated reverse proxy endpoint was requested more than once

**Comment by danny-avila** [comment]
Indeed this is planned and should actually be pretty simple to implement once I put the time in, thank you for clarifying @fuegovic @eburnette

**Comment by danny-avila** [comment]
Making progress with the Custom Endpoint (aka Dedicated Reverse Proxy Endpoint)

![image](https://github.com/danny-avila/LibreChat/assets/110412045/d8e2632f-16fb-434e-a830-2b0639ef5c80)

**Comment by danny-avila** [comment]
I'm also thinking about how to allow multiple custom endpoints. For example, if i want openrouter, mistral api, and openai available all at once
