### ISSUE TITLE
Enhancement: Hide email contact details in issue reports

### ISSUE THREAD

**Issue by eburnette** [danny-avila/LibreChat#1345]
### Contact Details

_Redacted_

### What features would you like to see added?

Please consider hiding, or not collecting, the contact details when someone adds an issue.

### More details

It's unusual to collect this info, but if you need it, it would be great to hide that from view except for the maintainers. I get enough spam as it is so I don't like to have my email on scrapeable websites.

Update: I just noticed it's optional so I just won't supply it. Still, I think it would be better not to ask or obscure it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
I do agree with you that it's not needed. We do not even collect the info. It was already included in the template we used and we never removed it. I'll do something about that soon. 

Just to be clear, that field is not required to submit an issue, it's completly optional and you can leave it empty. I'll still remove it.

**Comment by eburnette** [comment]
@fuegovic What do you think about removing the checkbox for the code of conduct? It already says, "By submitting this issue, you agree to follow our Code of Conduct" so the checkbox is superfluous.
