### ISSUE TITLE
Enhancement: Multiple Dall-e 3 generations per message

### ISSUE THREAD

**Issue by MoezGholami** [danny-avila/LibreChat#1354]
### What features would you like to see added?

Having multiple Dall-e 3 images generated per message.

### More details

In online communities, one of the major complaints about ChatGpt and Dall-e 3 is that the number of generated images per message has dropped from 4 to 1. This has been a major disappointment for many people (some examples [1](https://www.youtube.com/watch?v=oJAEjUVty3I), [2](https://www.reddit.com/r/ChatGPT/comments/17n5gym/only_1_image_per_query_dalle_3/), [3](https://www.reddit.com/r/ChatGPT/comments/17qzfj1/anyone_else_only_getting_one_dalle_3_image_now/), [4](https://www.reddit.com/r/ChatGPTPro/comments/17qz3uo/dalle_3_limited_to_only_one_image_per_request/), [5](https://www.reddit.com/r/ChatGPT/comments/17qxixy/dalle_in_chatgpt_now_only_generates_one_image_per/)).

As far as I can tell, there is currently no way to go back to how the things were before. The current alternatives are:
1. Midjourney: even if we agree that Midjourney has the same level of prompt understanding like Dall-e, its interface does not allow it to be embedded in conversations with chat bots.
2. Bing chat: Bing chat does not have the 1 (or 2) images per message constraint. It is also powered by ChatGpt and Dall-e 3. The problem is that there is [no way to find and continue previous chats in Bing](https://www.reddit.com/r/bing/comments/16lil6y/comment/k198rnk); also, typically, people are limited to 5 messages per conversation.
3. Stable diffusion (and other similar models): prompt comprehension is vastly inferior to Dall-e 3. Also, the ecosystem around it is complex and rapidly changing; in other words, it doesn't just work.

Implementing the similar functionality in Librechat will not only solve all these issues, but for people who pay for the API, can significantly reduce the wait time process (less throttling for API users).

Relevant issue: #1289

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MoezGholami** [comment]
Looking at the implementation details, I see that the [Dall-e.js](https://github.com/danny-avila/LibreChat/blob/main/api/app/clients/tools/DALL-E.js) should use structured Langchain tools; which is not the hardest part. The more complex part is dealing with the front-end view as the current abstraction (Md based view) does not simply support it.

**Comment by danny-avila** [comment]
This is planned with the Assistants API integration, and I've already experimented with this and it's very possible. LibreChat will be able to generate 10 images in the time it takes ChatGPT to generate one: 
![image](https://github.com/danny-avila/LibreChat/assets/110412045/efa2ca66-43bf-4376-8f1e-afc63922c060)
![1701132107332](https://github.com/danny-avila/LibreChat/assets/110412045/25779b5d-ab2f-4f52-baac-cf036500a629)

**Comment by danny-avila** [comment]
current progress on this here: https://x.com/lgtm_hbu/status/1749865914315530361?s=20

**Comment by MoezGholami** [comment]
@danny-avila if you have the code for the current progress somewhere, please share it. I (and I bet other people) can contribute to this issue now and we don't want to redo what you've already done (thanks btw).

**Comment by fuegovic** [comment]
@MoezGholami 

Here it is:
https://github.com/danny-avila/LibreChat/tree/assistants
https://github.com/danny-avila/LibreChat/pull/1696

**Comment by danny-avila** [comment]
Closed by https://github.com/danny-avila/LibreChat/pull/1696
