### ISSUE TITLE
[Bug]: Email address and password obscured in Welcome screen

### ISSUE THREAD

**Issue by eburnette** [danny-avila/LibreChat#1358]
### What happened?

When I open a LibreChat window in Edge, the browser fills in the email address and password for me, but the field hints are still visible, leading to an unreadable screen. See the screenshot.

### Steps to Reproduce

1. Start Edge
2. Navigate to the LibreChat URL
3. Observe the previous values filled into the Welcome screen

### What browsers are you seeing the problem on?

Microsoft Edge

### Screenshots

![Screenshot 2023-12-14 095543](https://github.com/danny-avila/LibreChat/assets/1093707/18d9ce68-dbb0-4789-8b48-01d6658ceeca)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I can confidently say this is an Edge issue as I tried a few things and is not reproducible on other browsers.

Also the labels should react as they should as soon as you click anywhere on the page

**Comment by fuegovic** [comment]
I also use edge, and while this happens, I can confirm that clicking anywhere on the page fixes it
