### ISSUE TITLE
Enhancement: Support for Azure OpenAI GPT-4-Vision Model

### ISSUE THREAD

**Issue by D1lanZ** [danny-avila/LibreChat#1367]
### What features would you like to see added?

Enable the image upload function/button in the OpenAIClient when using compactoable Azure OpenAI GPT-4-Vision Model

### More details

Ms has recently released the GPT-4-Vision model via Azure OpenAI.

### Which components are impacted by your request?

General, UI, Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
It's planned, maybe I can get to it this weekend

**Comment by danny-avila** [comment]
I've got it working, wrapping up my PR: 
![image](https://github.com/danny-avila/LibreChat/assets/110412045/e5dd1df6-9b03-4715-9d32-8efb177ae499)

Testing different deployments/models now to see if my changes have messed regular messages

Now that I'm testing with my own Azure setup, I've understood better how LibreChat can be configured to enable multiple deployments/alternative model names/ and vision support more seamlessly, but that is more involved and the simple setup will be enough to support this for now.

**Comment by D1lanZ** [comment]
Great work!!! thank you for your fast response and action.

**Comment by danny-avila** [comment]
This is now merged.

As of December 18th, 2023, Vision models seem to have degraded performance with Azure OpenAI when compared to [OpenAI](https://docs.librechat.ai/install/ai_setup.html#openai)

![7306185f-c32c-4483-9167-af514cc1c2dd](https://github.com/danny-avila/LibreChat/assets/110412045/13f8fbef-ca8c-4bff-b3dd-f7f85f86caa9)


Note: a change will be developed to improve current configuration settings, to allow multiple deployments/model configurations setup with ease: [#1390](https://github.com/danny-avila/LibreChat/issues/1390)
