### ISSUE TITLE
[Bug]: input hidden on firefox mobile

### ISSUE THREAD

**Issue by jonas-w** [danny-avila/LibreChat#1369]
### What happened?

I have my address bar at the bottom in firefox and the input is hidden unless you scroll down beneath it.

### Steps to Reproduce

See video, when scrolling down the address bar goes above the text input

### Screenshots

https://github.com/danny-avila/LibreChat/assets/32615971/89f181d6-016e-4c06-aec7-f620379ed05c

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
<img width="414" alt="image" src="https://github.com/danny-avila/LibreChat/assets/110412045/8e48190b-f615-4d49-aa56-933f7e12218a">
I’m also on the latest update of Firefox mobile and can’t reproduce.

**Comment by danny-avila** [comment]
> @danny-avila I'm on android. Firefox for iOS is just a wrapper around WebKit, so it's something completely different from the Android version :/

I understand but I'm not even sure where to begin here since it seems to be specific with the app's overlay keyboard. Note only that, there's no test environment I'm privy to, to even begin testing for this.

**Comment by danny-avila** [comment]
Related? https://github.com/mozilla-mobile/fenix/issues/2009

It's marked as "intended"

Maybe create an issue there? https://github.com/mozilla-mobile/firefox-android
