### ISSUE TITLE
Enhancement: support  chatglm3

### ISSUE THREAD

**Issue by leoterry-ulrica** [danny-avila/LibreChat#1370]
### What features would you like to see added?

support  llm chatglm3，and function  calling

### More details

no more detail

### Which components are impacted by your request?

Endpoints, Plugins

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
There may be a huggingFace integration soon but is not a priority. You could get any local large language model working with LiteLLM + VLLM or some other tool: https://docs.litellm.ai/docs/providers/vllm
