### ISSUE TITLE
[Bug]: Can't enter query or switch models on initial login

### ISSUE THREAD

**Issue by eburnette** [danny-avila/LibreChat#1375]
### What happened?

I brought my local git branch up to date, did a reinstall, and started the backend and frontend, created a new user, and got the initial "How can I help you today" screen. However there was no model selected:

![Screenshot 2023-12-17 100346](https://github.com/danny-avila/LibreChat/assets/1093707/1966f8b2-e5b2-4c42-be5f-4bbdbadac8f5)

There's a button at the top to select a preset but clicking on it shows a partially obscured unhelpful dropdown:

![Screenshot 2023-12-17 100439](https://github.com/danny-avila/LibreChat/assets/1093707/0e9c5aa8-fc58-43ac-8f88-1919e2f2da41)

Note that it lets you enter text at the bottom but nothing happens when you hit return or click on the submit button.

Clicking on "+ New Chat" fixes it, but this will be confusing to new users:

![Screenshot 2023-12-17 101611](https://github.com/danny-avila/LibreChat/assets/1093707/356ad0e1-0955-416d-b8da-703a9da75b75)

Note the text changes to "Set your Key in the Header menu to chat." like it's supposed to.

### Steps to Reproduce

1. git fetch
2. npm run reinstall
3. npm run backend:dev
4. npm run frontend:dev
5. try to log in with old user (that fails)
6. sign up with a new user
7. observe the problem

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
root@68c974f59e44:/workspaces/LibreChat# npm run backend:dev

> LibreChat@0.6.1 backend:dev
> cross-env NODE_ENV=development npx nodemon api/server/index.js

[nodemon] 3.0.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node api/server/index.js`
2023-12-17 15:01:32 info: `REDIS_URI` not provided, or `USE_REDIS` not set. Redis module will not be initialized.
2023-12-17 15:01:32 info: Connected to MongoDB
2023-12-17 15:01:33 info: Server listening on all interfaces at port 3080. Use http://localhost:3080 to access it
{"level":"error","message":"Passport Local Strategy - User Not Found","parameters":[{"name":"email","value":"myemail@gmail.com"}],"timestamp":"2023-12-17T15:01:52.446Z"}
{"level":"error","message":"[Login] [Login failed] [Username: myemail@gmail.com] [Request-IP: 127.0.0.1]","timestamp":"2023-12-17T15:01:52.447Z"}

EXECUTING: (requireLocalAuth) Error: No user
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks for the report. Never had these issues but I will try my best to reproduce later today

**Comment by danny-avila** [comment]
Steps to Reproduce

    > git fetch
    > npm run reinstall
    > npm run backend:dev

Note: Running `npm run backend:dev` runs the node with `NODE_ENV=development` which changes the handling of refresh tokens, which may or may not be affecting the issue of an existing user

> npm run frontend:dev
    > try to log in with old user (that fails)
    > sign up with a new user
    > observe the problem

To reproduce all of the above, I ran a fresh clone on a directory I never touched and opened the web app via private browsing on a browser I don't usually use. 

Noted my existing user in the local database to log into this first: 

![image](https://github.com/danny-avila/LibreChat/assets/110412045/e82c128f-4023-456d-8e39-d3171f23f17a)


Ran the following
```bash
# git cloned repo into a new folder
npm run reinstall
# setup .env file, using existing database
npm run backend
```

Once the app was running, I signed into an existing user, no issue: 

![image](https://github.com/danny-avila/LibreChat/assets/110412045/a0de509a-c6d7-4036-bf55-b0b8c171fe1f)

---

In good faith to repeat the process, I made a new user, started a conversation, and then repeated the steps above to reinstall

```bash
# git cloned repo into a new folder
npm run reinstall
# setup .env file, using existing database
npm run backend
```

I then noticed the issue with endpoint/model selectors not showing, but I couldn't reproduce not being able to login with an existing user.

From here, I could consistently reproduce the endpoint/models not showing by running `npm run reinstall`. Oddly enough, it was only with this scenario that I could recreate it, as logging in/out, refreshing, navigating across the app could reproduce it.

After some triaging, I realized that the initial conversation settings were being applied before all the needed data was fetched. curiously, this would only be the case after a fresh "reinstall."

Thankfully this was an easy fix once identified, and after retrying the consistent way to reproduce, this behavior is no longer exhibited. Submitting a PR soon

**Comment by eburnette** [comment]
Cool, thanks.

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=ZWQuYnVybmV0dGVAaGlkZGVubWluZC5haQ==>
