### ISSUE TITLE
[Bug]: Why is it necessary to log in again every time the page is refreshed?

### ISSUE THREAD

**Issue by leoterry-ulrica** [danny-avila/LibreChat#1384]
### What happened?

Why is it necessary to login again every time the page is refreshed?

### Steps to Reproduce

1、refresh the web page
2、need to login again

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Not a bug, this isn't the case if you use localhost or https. It could be a cookie issue if you are using http and not localhost: https://github.com/danny-avila/LibreChat/discussions/572#discussioncomment-7352331

Please review it as it may solve your issue.

The way around this in `production` mode is to use NGINX or something like Caddy for HTTPS if you are not outright accessing via `localhost`

**Comment by leoterry-ulrica** [comment]
thx so much

**Comment by leoterry-ulrica** [comment]
Unfortunately~~ @danny-avila 
Using Chrome's incognito mode, even when setting NODE_ENV=development, it's still unable to save cookie information.
