### ISSUE TITLE
Enhancement: Integrate Whisper to achieve voice recognition

### ISSUE THREAD

**Issue by leoterry-ulrica** [danny-avila/LibreChat#1385]
### What features would you like to see added?

Integrate Whisper to achieve voice recognition

### More details

nothing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leoterry-ulrica** [comment]
Is there any plan to adapt? @danny-avila

**Comment by fuegovic** [comment]
> Is there any plan to adapt?

Whisper integration is planned, but there's currently no ETA for this

**Comment by Tokyofloripa** [comment]
Suggestion, implement this TTS library instead of coding from scratch. It's uses Whisper and is the best implementation to include in a chat that I tested.

**Comment by danny-avila** [comment]
> Suggestion, implement this TTS library instead of coding from scratch. It's uses Whisper and is the best implementation to include in a chat that I tested.
> 
> https://github.com/lobehub/lobe-tts

Thanks for the suggestion. @Berry-13 I do think it's worth looking at since the modules are pretty small and condensed

**Comment by bpawnzZ** [comment]
There any update on this??  TTS would be and amazing addition!
