### ISSUE TITLE
Enhancement: automatically scroll when scrolling to the bottom 

### ISSUE THREAD

**Issue by SailFlorve** [danny-avila/LibreChat#1412]
### What features would you like to see added?

When generating response, if the user has scrolled to the bottom of the page, the page should automatically scroll to display the newly generated message. 

### More details

Currently, the automatic scrolling to the bottom aborts if the mouse wheel is scrolled, which is convenient for users to view historical messages. However, when the user scrolls back to the bottom, I would like it to continue to automatically scroll again to show latest response.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
The way to do this is to click the scroll to bottom button
