### ISSUE TITLE
Enhancement: Gemini & Anthropic conversation titles

### ISSUE THREAD

**Issue by myxgenius** [danny-avila/LibreChat#1422]
### What features would you like to see added?

Gemini conversations

### More details

It would be great if Gemini conversations can also auto generate titles.

Also, since Gemini is free, it would be even better if openAI conversation titles can be generated by Gemini instead one of the gpt modules.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This is planned, along with Anthropic!

**Comment by mhogstedt** [comment]
Titles for Anthropic conversations would be amazing now that they may have the most capable model for some tasks.

**Comment by danny-avila** [comment]
> Titles for Anthropic conversations would be amazing now that they may have the most capable model for some tasks.

Ttiles for anthropic are now live following this PR: https://github.com/danny-avila/LibreChat/pull/2184

**Comment by mhogstedt** [comment]
> Ttiles for anthropic are now live following this PR: #2184

Works perfectly! Thank you!

**Comment by jr4t-ksb** [comment]
The generated title is generated in English, not in the language used in the chat (Japanese in my case).  
Azure OpenAI Service generates them in the language I am using.  

It would be great if Gemini could generate them in the same language.

**Comment by danny-avila** [comment]
@jr4t-ksb yes, better yet to customize the titles which is on my list

**Comment by danny-avila** [comment]
Closed by #2983
