### ISSUE TITLE
[Question]: Code interpreter?

### ISSUE THREAD

**Issue by Kreijstal** [danny-avila/LibreChat#1429]
### What is your question?

How would you enable code interpreter?

### More Details

You have plugins but it's there any way to enable code interpreter?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
It's coming soon, see: https://github.com/danny-avila/LibreChat/pull/868#issuecomment-1845994504

quote:
> Integrating the official code interpreter will be part of the Assistants API update (...) no later than end of January.
