### ISSUE TITLE
slow countTokens function results in a slow conversation aborting

### ISSUE THREAD

**Issue by SailFlorve** [danny-avila/LibreChat#1430]
### What happened?

After clicking the stop button, I have to wait for a while before it stops because encountering network issues (?) , and may lead to a stop time of up to 10-20 seconds. I hope it stops immediately after clicking the stop button.

After debugging, I found

It is `const completionTokens = await countTokens(responseData?.text ?? '');`
at `abortMiddleware.js`
and `const model = await load(registry[models[modelName]]);`
at `countTokens.js`

costs a lot of time.

![image](https://github.com/danny-avila/LibreChat/assets/25448499/f05f1791-f5dd-41d6-90c3-ade399c5755f)

It might be due to my network (China),
`await load(registry[models["gpt-3.5-turbo"]]);`
takes me more than 10 seconds.
I directly use
`const model = require("tiktoken/encoders/cl100k_base.json");`
instead,

Now, the stopping speed is very fast.

It looks like every time the stop button is clicked, a .tiktoken file is downloaded from the internet? Even without network speed issues, I think this is not very reasonable.

But it causes stoped message is blank in mongodb. 
![image](https://github.com/danny-avila/LibreChat/assets/25448499/83490422-9a83-4d82-ac23-f8732be3dfaf)
After conversation stopped, several SaveMessage requests with empty text values were observed. And the database saved a blank message finally. However, reverting to `await load(registry[models[modelName]])` has no issues.

**Comment by SailFlorve** [comment]
It is const completionTokens = await countTokens(responseData?.text ?? '');
at abortMiddleware.js 
costs a lot of time.

![image](https://github.com/danny-avila/LibreChat/assets/25448499/50fc316a-8f96-4975-8b83-7b2ea1a4b429)

**Comment by SailFlorve** [comment]
It might be due to my network (China), 
`await load(registry[models["gpt-3.5-turbo"]]);` 
takes me more than 10 seconds. 
I directly use
`const model = require("tiktoken/encoders/cl100k_base.json");`
instead,

Now, the stopping speed is very fast.

**Comment by danny-avila** [comment]
Thanks this should be an easy fix
