### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by Reyasotiguejr** [danny-avila/LibreChat#1433]
### What is your question?

can i ask is this gpt4 in librechat must be paid ? 

### More Details

!
Something went wrong. Here's the specific error message we encountered: Encountered an error while attempting to respond: 404 The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
exact, the free tier doesn’t give access to gpt-4:

https://platform.openai.com/docs/guides/rate-limits/usage-tiers?context=tier-free
