### ISSUE TITLE
Enhancement: Delete user account

### ISSUE THREAD

**Issue by darkBuddha** [danny-avila/LibreChat#1435]
### What features would you like to see added?

Currently, it is not possible to delete your own user account.

### More details

It should be possible to delete a user account, preferably from the logged in user itself. I provided a demo access to my boss to convince him to use LibreChat in our company. Now I can't (quickly) get rid of his demo account.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Berry-13** [comment]
Currently, you have the option to manually delete the account from the database. Access the database using Mongo Express. If you're using online Mongo DB, go to "Database" and then select "Collections." Do you prefer a command (e.g., npm run delete-user) or a frontend button, similar to the one for deleting all chats in the current ChatGPT interface?

**Comment by danny-avila** [comment]
This is planned!

**Comment by marcobt15** [comment]
> Currently, you have the option to manually delete the account from the database. Access the database using Mongo Express. If you're using online Mongo DB, go to "Database" and then select "Collections." Do you prefer a command (e.g., npm run delete-user) or a frontend button, similar to the one for deleting all chats in the current ChatGPT interface?

Hello, I was looking to delete a user too and was wondering which collections you had to modify to achieve this. My first guess would be to get the user id and remove all other tables with a reference to it.

**Comment by berry-13** [comment]
> Hello, I was looking to delete a user too and was wondering which collections you had to modify to achieve this. My first guess would be to get the user id and remove all other tables with a reference to it.

hey, sorry for the hold-up! To totally remove a user (manually), you'll need to delete:

- user messages
- user sessions
- user transactions
- user keys
- user balances
- user presets
- user convos
- user plugin auth
- user files
- user
