### ISSUE TITLE
Enhancement: Support for Azure OpenAI's DALL-E 

### ISSUE THREAD

**Issue by derbuihan** [danny-avila/LibreChat#1449]
### What features would you like to see added?

I would like to see support added for Azure OpenAI's DALL-E. Currently, LibreChat supports OpenAI's DALL-E, but I would like to see support for Azure's version as well. This feature would be very beneficial for users like me who only use OpenAI through Azure.

### More details

Currently, Azure OpenAI only supports the following regions and models.

| Model ID | Feature Availability | Max Request (characters) |
|----------|----------------------|-------------------------|
| dalle2   | East US              | 1000                    |
| dalle3   | Sweden Central       | 4000                    |

Reference: https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#dall-e-models-preview

### Which components are impacted by your request?

Plugins

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks, this is already planned as part of the next minor release

**Comment by danny-avila** [comment]
I'm wrapping up a PR for this. Here's what I'm adding to the docs for reference.

### Generate images with Azure OpenAI Service (DALL-E)

| Model ID | Feature Availability | Max Request (characters) |
|----------|----------------------|-------------------------|
| dalle2   | East US              | 1000                    |
| dalle3   | Sweden Central       | 4000                    |

- First you need to create an Azure resource that hosts DALL-E
    - At the time of writing, dall-e-3 is available in the `SwedenCentral` region, dall-e-2 in the `EastUS` region.
- Then, you need to deploy the image generation model in one of the above regions.
    - Read the [Azure OpenAI Image Generation Quickstart Guide](https://learn.microsoft.com/en-us/azure/ai-services/openai/dall-e-quickstart) for further assistance
- Configure your environment variables based on Azure credentials:

**- For DALL-E-3:**

```bash
DALLE3_AZURE_API_VERSION=the-api-version # e.g.: 2023-12-01-preview
DALLE3_BASEURL=https://<AZURE_OPENAI_API_INSTANCE_NAME>.openai.azure.com/openai/deployments/<DALLE3_DEPLOYMENT_NAME>/
DALLE3_API_KEY=your-azure-api-key-for-dall-e-3
```

**- For DALL-E-2:**

```bash
DALLE2_AZURE_API_VERSION=the-api-version # e.g.: 2023-12-01-preview
DALLE2_BASEURL=https://<AZURE_OPENAI_API_INSTANCE_NAME>.openai.azure.com/openai/deployments/<DALLE2_DEPLOYMENT_NAME>/
DALLE2_API_KEY=your-azure-api-key-for-dall-e-2
```

**DALL-E Notes:**

- For DALL-E-3, the default system prompt has the LLM prefer the ["vivid" style](https://platform.openai.com/docs/api-reference/images/create#images-create-style) parameter, which seems to be the preferred setting for ChatGPT as "natural" can sometimes produce lackluster results.
- See official prompt for reference: **[DALL-E System Prompt](https://github.com/spdustin/ChatGPT-AutoExpert/blob/main/_system-prompts/dall-e.md)**
- You can adjust the system prompts to your liking:

```bash
DALLE3_SYSTEM_PROMPT="Your DALL-E-3 System Prompt here"
DALLE2_SYSTEM_PROMPT="Your DALL-E-2 System Prompt here"
```

- The `DALLE_REVERSE_PROXY` environment variable is ignored when Azure credentials for DALL-E are configured.

**Comment by shortm123** [comment]
Hi, I am trying to implement Dall-3-3 in Azure using the Librechat.yaml.

I have use the baseURL, API version and API Keys, but the reply back from the model is ""The chatCompletion operation does not work with the specified model, dall-e-3. Please choose different model and try again. You can learn more about which models can be used with each operation here"...

Can you assist with the required config for the yaml file?

Thanks for any help!

ms

**Comment by jsiegmund** [comment]
@shortm123 getting the same, did you manage to find a solution?

**Comment by shortm123** [comment]
Unfortunately not. Thanks for the comment, it's reassuring it's not just me. I'll try again after the next release and post here.
