### ISSUE TITLE
Enhancement: Support more file formats、add warn when the picture upload is not finish、set an adminverify for the register

### ISSUE THREAD

**Issue by assassinliujie** [danny-avila/LibreChat#1452]
### What features would you like to see added?

Support more file formats、
add warn when the picture upload is not finish、
set an adminverify for the register

### More details

the reverse proxy of chatgpt is now support uploading files. so really need to support more file formats

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
If this is for the ChatGPT endpoint, this is not planned.

**Comment by assassinliujie** [comment]
> If this is for the ChatGPT endpoint, this is not planned.

how about the askyourpdf plugin or other plugins that needs to upload files, I find out that no plugins could upload files

**Comment by assassinliujie** [comment]
> 如果这是针对 ChatGPT 端点的，则没有计划。

I mean it seems just set a white list for the format of files. if it is not planned, could I get access to change the whitelist

**Comment by danny-avila** [comment]
> > 如果这是针对 ChatGPT 端点的，则没有计划。
> 
> I mean it seems just set a white list for the format of files. if it is not planned, could I get access to change the whitelist

Extended file support for tools is planned, I misunderstood your request. It's already being developed.
