### ISSUE TITLE
Enhancement: Add Mistral AI service provider + model selection

### ISSUE THREAD

**Issue by Extremys** [danny-avila/LibreChat#1458]
### What features would you like to see added?

Hello! 
Recently Mistral AI, released its own OpenAI compatible API (so it should be easy to integrate). I think it would be great to add it to the list of service provider and add the preconfiguration for the 4 first models mistral-tiny/small/medium/embed 
What do you think?
I can help for testing, I've access to the API if needed.

### More details

List of models:
https://docs.mistral.ai/platform/endpoints/
API specs:
https://docs.mistral.ai/api/

### Which components are impacted by your request?

UI, Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Not a bad idea, I may revisit this later on as Mistral is pretty awesome. However, going to prioritize #1344 as this update will allow naming your own custom endpoint, baseURL, models, etc.

**Comment by danny-avila** [comment]
Making progress with the Custom Endpoint (aka Dedicated Reverse Proxy Endpoint)

![image](https://github.com/danny-avila/LibreChat/assets/110412045/d8e2632f-16fb-434e-a830-2b0639ef5c80)
