### ISSUE TITLE
Enhancement: Can't upload images to newbing

### ISSUE THREAD

**Issue by XianYuDaXian** [danny-avila/LibreChat#1459]
### What features would you like to see added?

Only under openai and google gemini can upload image , please add an upload button for newbing as well.

### More details

Only under openai and google gemini can upload image , please add an upload button for newbing as well.

### Pictures

![image](https://github.com/danny-avila/LibreChat/assets/20138259/aeb33a23-159d-4850-969c-1b091af21e1e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This is currently not planned. BingAI is considered an "Unofficial API" and here is a note in our docs about this:

> Stability for Unofficial APIs are not guaranteed. Access methods to these APIs are hacky, prone to errors, and patching, and are marked lowest in priority in LibreChat's development.
