### ISSUE TITLE
Enhancement: Rolling Context Window

### ISSUE THREAD

**Issue by drewdresser** [danny-avila/LibreChat#1487]
### What features would you like to see added?

Similar to the way ChatGPT web app works, I would like the application to intelligently avoid context length errors by rolling the context window forward once the limit is approaching.

### More details

OpenAI models have context lengths. Since the app is using the OpenAI model API, the context length can fill up and an error in the API call can occur. It seems like that error is happening silently and the app leaves the user in the dark about what is happening. Instead of hitting this error, it would be cool if the app was smart enough to use roll the context forward once it gets too big in a first-in-first-out algorithm. 

### Which components are impacted by your request?

General

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Hi @drewdresser, this is already implemented but perhaps you're hitting an edge case?

**Comment by danny-avila** [comment]
The only time I can think of that is "normal" to run into this is when the prompt itself is beyond the context size. 

However, there is also the [`OPENAI_SUMMARIZE`](https://docs.librechat.ai/install/configuration/dotenv.html#openai) feature that handles this, as well as summarizes as it goes along (similar to how you described FIFO). 

We are using the ConversationSummaryBufferMemory method to summarize messages: https://www.pinecone.io/learn/series/langchain/langchain-conversational-memory/

**Comment by danny-avila** [comment]
There was something that was overlooked but addressed in the following PR: https://github.com/danny-avila/LibreChat/pull/1573

This makes context errors on gpt-4 or any other models that are in 16k+ max range a lot less likely.

Rolling context is an inherent feature of the app. Other apps that don't run into this issue at all make the trade of making a bigger buffer for the response (usually 1000 tokens) while the implementation here allows your prompt to near max as there is a rolling context.

Also discussed this here for more info: https://github.com/danny-avila/LibreChat/discussions/1572
