### ISSUE TITLE
Enhancement: Helm chart for deployment into K8S

### ISSUE THREAD

**Issue by siriusfreak** [danny-avila/LibreChat#1489]
### What features would you like to see added?

Helm chart for deployment into K8S

### More details

Hello.

I can (and I want) to implement a helm chart and documentation to simplify the deployment of this project into k8s.

According to the contribution guide, I should ask if it is required for the project. 

### Which components are impacted by your request?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iamNoah1** [comment]
@danny-avila if you are interested I would love to take over, as I was building a helm chart to deploy it internally the other day.

**Comment by danny-avila** [comment]
@iamNoah1 someone from the community made this: https://github.com/Schluggi/helm-charts/tree/main/charts/librechat

It would be helpful for you to review it and to have docs for it since I'm a helm chart noob!
