### ISSUE TITLE
Enhancement: add docker image to ghcr.io

### ISSUE THREAD

**Issue by ineiti** [danny-avila/LibreChat#1534]
### What features would you like to see added?

I would like to have an official docker image on ghcr.io

### More details

Currently the docker image needs to be built by hand. But the `Dockerfile` is present and can be used to create a docker image for everybody.

### Which components are impacted by your request?

General

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Hi @ineiti we already have 4 different images being built out automatically and hosted on ghcr.io, including on latest changes and with different dockerfiles:

https://github.com/danny-avila?tab=packages&repo_name=LibreChat

The packages with `dev` are the latest changes to the main branch of the repo

The packages with `api` are using Dockerfile.multi

Unless you mean something else?

**Comment by danny-avila** [comment]
We have a lot of users building locally. Do you think it would be better to switch it to the image by default?

**Comment by ineiti** [comment]
> We have a lot of users building locally. Do you think it would be better to switch it to the image by default?

I prefer having the image by default, it removes an action in my ansible script :) Instead of
- update git
- build

I can
- fetch docker-compose.yml

At least for all of my docker-compose files I make the build optional and the image by default. I suppose that most of the users will not want to change the files before they build it, so why should they have to build it in the first place?

Plus I have the idea that errors I do (like searching for the image and not finding it), others will do as well :)
