### ISSUE TITLE
[Question]: Mistral Endpoint error 422 status code (no body)

### ISSUE THREAD

**Issue by euggen0106** [danny-avila/LibreChat#1540]
### What is your question?

I have deployed Mistral endpoint as per LibreChat instructions but, when I try to use any mistral model I get this response:
Something went wrong. Here's the specific error message we encountered: Error: 422 status code (no body).

### More Details

This is my librechat.yaml:
version: "3.4"
cache: true

endpoints:
  custom:
      # Example using Mistral AI API
    - name: "Mistral"
      apiKey: "my_api_key"
      baseURL: "https://api.mistral.ai/v1"
      models: 
        default: ["mistral-tiny", "mistral-small", "mistral-medium"]
      titleConvo: true
      titleModel: "mistral-tiny" 
      summarize: false
      summaryModel: "mistral-tiny" 
      forcePrompt: false 
      modelDisplayLabel: "Mistral"
      addParams:
        safe_mode: true
      # NOTE: For Mistral, it is necessary to drop the following parameters or you will encounter a 422 Error:
      dropParams: ["stop", "user", "frequency_penalty", "presence_penalty"]

### What is the main subject of your question?

Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Updated the example to [make Mistral AI API work:](https://discord.com/channels/1144547040454508606/1184444810279522374/1195108690353717369):
> We made the API stricter. We did not expect that change to break anything other than incorrect requests, but unfortunately we had not properly documented the safe_prompt flag, which was incorrectly named safe_mode in the documentation (fixed now) and implemented as such by some people. That’s on us - sorry about that.
