### ISSUE TITLE
[Bug]: Sending messages after the disconnected causes message switch pages and lost context.

### ISSUE THREAD

**Issue by SailFlorve** [danny-avila/LibreChat#1548]
### What happened?

After the server connection is interrupted (possibly the server where LibreChat is deployed or the API), the response will show as finished with a continue button. If a new message is sent, the context is lost and the messages switch pages upon refreshing.

### Steps to Reproduce

1. Send a message
2. The server run a `docker-compose down` while the message is still being generate
3. The server restarts the service `docker-compose up`
4. Send a message and find the context lost. After refreshing, find the message has been paged.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks for your report. I think it’s difficult to account for a sudden server shut down and handle this predictably. Best not to shut down the server while messages are generated. Maybe some shutdown procedure is needed and I will investigate how to incorporate this, but I’m closing this issue as it doesn’t relate to anything unusual in the normal runtime of the app.
