### ISSUE TITLE
[Bug]: APP_TITLE .env var seems to have no effect

### ISSUE THREAD

**Issue by igodsewer** [danny-avila/LibreChat#1551]
### What happened?

In my .env file I have:

```
APP_TITLE="Test"
CUSTOM_FOOTER="GPT Proxy"
```

But this seems to have no effect on the actual service as per screenshot below and it still displays LibreChat. 
![image](https://github.com/danny-avila/LibreChat/assets/5046970/31f488c5-9795-4aac-acea-e00b21fd7d77)

Though, CUSTOM_FOOTER works perfectly and has no issues. I believe, this happened after some of December updates in the repo.

PS - tested both with ticks and without them (but it should not matter)

### Steps to Reproduce

1. Get latest update following **Updating LibreChat** section in this manual https://docs.librechat.ai/install/installation/docker_compose_install.html
2. Set APP_TITLE .env var
3. It has no effect.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
sudo docker logs LibreChat

> LibreChat@0.6.5 backend
> cross-env NODE_ENV=production node api/server/index.js

2024-01-15 00:03:51 info: [Optional] Redis not initialized. Note: Redis support is experimental.
2024-01-15 00:03:55 info: Connected to MongoDB
2024-01-15 00:03:55 info: Server listening on all interfaces at port 3080. Use http://localhost:3080 to access it
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks for your report. It should have some effect already in the footer, as for the browser/tab title, I'm pushing a fix for this.

You might still see "LibreChat" show on refresh. There's no way to avoid this unless you edit `client/index.html`, in case this matters to you.
