### ISSUE TITLE
[Bug]: There may be garbled characters in Chinese

### ISSUE THREAD

**Issue by clickinfinite** [danny-avila/LibreChat#1554]
### What happened?

When using Chinese dialogue, some content is displayed as garbled characters, as shown in the picture
![1122333](https://github.com/danny-avila/LibreChat/assets/25527875/61d2e817-de4c-467b-a99b-f94b1dcbe5bb)

### Steps to Reproduce

Use Chinese dialogue, please test a few more times

### What browsers are you seeing the problem on?

Chrome

### Screenshots

![11223dd33](https://github.com/danny-avila/LibreChat/assets/25527875/a19e5c3f-dbab-4b9f-ae00-66c6e6414f55)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
This is an issue with Google

see: https://github.com/danny-avila/LibreChat/discussions/1398#discussioncomment-7908029
and the related Google issue: https://github.com/google/generative-ai-js/issues/35

**Comment by danny-avila** [comment]
I’ll update the dependency tomorrow, it might be fixed with a simple package update.
