### ISSUE TITLE
Enhancement: Restrict registration to certain domains (for small business use)

### ISSUE THREAD

**Issue by darkBuddha** [danny-avila/LibreChat#1555]
### What features would you like to see added?

Hi, it would be great, if e-mail registration could be restricted to company domains.

### More details

This prevents unauthorized users to register, and should be fairly trivial to add. Boosting business use is a good idea for any open-source project.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I agree it's somewhat trivial to add but why not use OpenID for this use case?

**Comment by danny-avila** [comment]
Now implemented through the librechat.yaml config file: https://docs.librechat.ai/install/configuration/custom_config.html#registration-object-structure

**Comment by fuegovic** [comment]
> @danny-avila clients have to click on a "confirm email" link on registering, right?
> 
> https://docs.librechat.ai/install/configuration/dotenv.html#registration-and-login

There's no confirmation email sent to the users on registration

**Comment by danny-avila** [comment]
Yeah there is not a lot of email service through this app, with the only exception made for password reset for the simple security that offers.

A bare-bones implementation of that would be good for a future PR but that is not yet implemented nor a priority.

Leaving this as reference of a very simple example to use as reference: https://blog.bitsrc.io/email-confirmation-with-react-257e5d9de725
