### ISSUE TITLE
Enhancement: Pass OpenAI Organization ID to OpenAI API requests

### ISSUE THREAD

**Issue by shaggy245** [danny-avila/LibreChat#1570]
### What is your question?

OpenAI documentation notes the ability to set [an explicit organization ID](https://platform.openai.com/docs/api-reference/organization-optional) via HTTP header (in addition to the API key). Is there an option to set an OpenAI organization ID in LibreChat's OpenAI configuration so that it is included in all API requests to OpenAI?

### More Details

I hope to lock down LibreChat to a specific OpenAI organization ID so that, in the event that the associated OpenAI user is added to multiple Open AI organizations, API calls from LibreChat are still associated with an explicitly configured OpenAI organization.

I searched LibreChat docs, GitHub issues, and code and did not see anything obvious. Thanks!

### What is the main subject of your question?

Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks for checking out the project!

Not currently but this a good suggestion and easily implemented, will mark this as planned.

**Comment by danny-avila** [comment]
You can now specify which organization to use for each API request to OpenAI. However, it is not required if you are only part of a single organization or intend to use your default organization. You can check your [default organization here](https://platform.openai.com/account/api-keys). 

This can also help you limit your LibreChat instance from allowing API keys outside of your organization to be used, as a mismatch between key and organization will throw an API error.

```bash
OPENAI_ORGANIZATION=org-Y6rfake63IhVorgqfPQmGmgtId
```

All outgoing requests to OpenAI, including langchain/plugin requests, should result in error 401 no such organization if the org id is invalid or there is a mismatch.

PR #1590
