### ISSUE TITLE
Enhancement: Option to send/not send context

### ISSUE THREAD

**Issue by FreSchCodes** [danny-avila/LibreChat#1584]
### What features would you like to see added?

This is likely chatGPT specific, and not that urgent a thing, but just something to consider if anyone feels like it I guess. 
Personally, I use GPT without conversation - mostly a question-answer style. This means context is usually irrelevant, and ups the token usage. Would be nice if there were some option added (toggle or something) to disable/change the context sent to chatGPT, to help save on tokens if you really need it.

### More details

Got the idea from this.
![image](https://github.com/danny-avila/LibreChat/assets/89890939/d6064d97-c204-4741-acc8-e8694322611b)

The implementation is rather clunky, but I think it gets the idea across - some option where you can disable sending the context to save on tokens. 

### Which components are impacted by your request?

General, UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Closing as not planned for now. Maybe reconsider if there are more "submit" options in the future.

**Comment by FreSchCodes** [comment]
alrighty, was worth a shot. Thanks for taking the time to read though.
