### ISSUE TITLE
[Bug]: Page title does not get set to appTitle

### ISSUE THREAD

**Issue by finnless** [danny-avila/LibreChat#1587]
### What happened?

The default page <title> is LibreChat instead of APP_TITLE env variable.

### Steps to Reproduce

Load a LibreChat page.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Mobile (iOS), Mobile (Android)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This was addressed in this PR: https://github.com/danny-avila/LibreChat/pull/1553

Relevant issue: https://github.com/danny-avila/LibreChat/issues/1551

Try updating. If it's still not as expected, open a troubleshooting discussion.
