### ISSUE TITLE
Enhancement: PWA on iOS

### ISSUE THREAD

**Issue by darkBuddha** [danny-avila/LibreChat#1600]
### What features would you like to see added?

Using Librechat as PWA currently only works on Android. It should work on iOS also.

### More details

iOS requires some additional headers: 

https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

especially `<meta name="apple-mobile-web-app-status-bar-style" content="black">`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
In my tests, this didn't really change anything: `<meta name="apple-mobile-web-app-status-bar-style" content="black">`

I had to use `<meta name="apple-mobile-web-app-capable" content="yes">` and specify the icon

See #1602 for details
![image](https://github.com/danny-avila/LibreChat/assets/32828263/a4432aa5-4d3a-4cc6-b874-e0ffd9e76a13)
![image](https://github.com/danny-avila/LibreChat/assets/32828263/50cb0983-28b6-4f54-b215-cc4d45ecce8f)

**Comment by fuegovic** [comment]
> Sorry, i posted the wrong one.
> 
> is the mandatory one I think
> 
> Thanks for testing +adding 🙏🏻

Thanks for investigating this and sharing the link for the apple doc on the subject!
