### ISSUE TITLE
[Bug]: Refresh browser then logged out

### ISSUE THREAD

**Issue by houniantang** [danny-avila/LibreChat#1605]
### What happened?

After login, when I perform F5 refresh operation on the interface, I am logged out to the login interface.

### Steps to Reproduce

After login, when I perform F5 refresh operation on the interface, I am logged out to the login interface.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Not a bug, see this: https://github.com/danny-avila/LibreChat/discussions/572

TLDR: you need to access the app via HTTPS if you are not on localhost. There are many ways to do this or run the app in dev mode (Not recommended if remote deployment)
