### ISSUE TITLE
[Bug]: Gemini: Garbled Characters in Chinese Outputs

### ISSUE THREAD

**Issue by Lawlietr** [danny-avila/LibreChat#1609]
### What happened?

It well hannened ever time if i'm asking Gemini with Traditional Chinese.

### Steps to Reproduce

This it's what the prompt i'm use:

`You are a helpful assistant. 你是一個樂於助人的助手。請你提供專業、有邏輯、內容真實、有價值的詳細回，並以繁體中文台灣用語回覆。`

And this it's a sample i'm asking for:
`太陽能板是誰發明的`

### What browsers are you seeing the problem on?

Chrome

### Screenshots

![11](https://github.com/danny-avila/LibreChat/assets/1248136/1bc28288-3ea9-4f55-9a2e-9e82254d8dae)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks for the report. This is a repeat of https://github.com/danny-avila/LibreChat/issues/1554

This is an issue with Google

see: https://github.com/danny-avila/LibreChat/discussions/1398#discussioncomment-7908029
and the related Google issue: https://github.com/google/generative-ai-js/issues/35

It was resolved on the latest google packages, but langchainjs has to bump their `@google/generative-ai` package.

I'll leave it open so I can remind myself to submit a ticket to langchainjs

**Comment by danny-avila** [comment]
I've opened an issue: https://github.com/langchain-ai/langchainjs/issues/4113

**Comment by danny-avila** [comment]
Addressed here: https://github.com/danny-avila/LibreChat/pull/1654

**Comment by RedwindA** [comment]
The issue appears to remain unfixed

**Comment by danny-avila** [comment]
> The issue appears to remain unfixed

Can you give more details? Vertex or Generate AI API? If it's not fixed, it's for one and not the other, or dependent on the model.

**Comment by danny-avila** [comment]
Seems to be Vertex AI, I'll look into it.

### Generative AI API:
![image](https://github.com/danny-avila/LibreChat/assets/110412045/653ba511-c595-4a3f-936a-e003c3a641e8)

### Vertex AI API:
![image](https://github.com/danny-avila/LibreChat/assets/110412045/3eacfd3d-6744-4671-8230-eccf5e61ed29)

**Comment by danny-avila** [comment]
https://github.com/danny-avila/LibreChat/pull/2905 bumping versions was enough to fix this for Vertex

**Comment by haoblackj** [comment]
I have similar symptoms with Cohere's Command R Plus.
Should I create a separate new Issue?

**Comment by danny-avila** [comment]
> I have similar symptoms with Cohere's Command R Plus. Should I create a separate new Issue?

Seems related to a cohere issue here:
https://github.com/cohere-ai/cohere-typescript/issues/151

I'll try it by updating their package, too.

**Comment by danny-avila** [comment]
> I have similar symptoms with Cohere's Command R Plus. Should I create a separate new Issue?

I can't reproduce the issue on the current build, how do you have cohere setup? what is your prompt?

**Comment by lazydogP** [comment]
> > I have similar symptoms with Cohere's Command R Plus. Should I create a separate new Issue?
> 
> Seems related to a cohere issue here: [cohere-ai/cohere-typescript#151](https://github.com/cohere-ai/cohere-typescript/issues/151)
> 
> I'll try it by updating their package, too.

Can confirm `cohere-ai@7.10.2` still has this issue.

**Comment by danny-avila** [comment]
> > > I have similar symptoms with Cohere's Command R Plus. Should I create a separate new Issue?
> > 
> > 
> > Seems related to a cohere issue here: [cohere-ai/cohere-typescript#151](https://github.com/cohere-ai/cohere-typescript/issues/151)
> > I'll try it by updating their package, too.
> 
> Can confirm `cohere-ai@7.10.2` still has this issue.

I can't reproduce it, when and how are you seeing the issue?

![image](https://github.com/danny-avila/LibreChat/assets/110412045/9334020f-544d-44be-9f4e-241fc4aa1aba)

**Comment by lazydogP** [comment]
> 
> I can't reproduce it, when and how are you seeing the issue?
> 
> ![image](https://private-user-images.githubusercontent.com/110412045/335289468-9334020f-544d-44be-9f4e-241fc4aa1aba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwODUyOTUsIm5iZiI6MTcxNzA4NDk5NSwicGF0aCI6Ii8xMTA0MTIwNDUvMzM1Mjg5NDY4LTkzMzQwMjBmLTU0NGQtNDRiZS05ZjRlLTI0MWZjNGFhMWFiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQxNjAzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjA5YWI0NGMwZmEyMTI2MjdkNzlkMGY3ZTRjYjE2ZmRjOWE2MWVhZDFkNTM0MWRmYTVjN2IzZDAyMGYxZDYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tFjsvK8ckpAQ0s28BofNDwbyEYa8sz6G1cAqlrUxqwU)

Prompt:

Write a story in Simplified Chinese in more than 3000 words.

![20240531000417](https://github.com/danny-avila/LibreChat/assets/9066530/fd1ae4ca-5e41-4957-8557-166a71a5fede)

**Comment by danny-avila** [comment]
I see it seems to be at the end of the stream

**Comment by danny-avila** [comment]
@lazydogP @haoblackj I have a quick workaround, seems we cannot rely on the `stream-end` event to avoid this issue

**Comment by haoblackj** [comment]
I am typing the prompt in Japanese. It's true that long prompts often seem to cause garbled characters.

The most recent prompt that caused the phenomenon is this one.

Prompt:
この日本語の文章を、表現豊かで洗練された文章になるよう修正しなさい。

Under this prompt, I'm giving a Japanese sentence of about 2000 characters.

Sorry, Cohere's API is limited and I don't know if the phenomenon still occurs (they say I use it too much).
