### ISSUE TITLE
Enhancement:  Option to show configurable links to privacy policy and legal notice on login page and footer of chat window

### ISSUE THREAD

**Issue by omueller54** [danny-avila/LibreChat#1610]
### What features would you like to see added?

It would be very useful to have the option to add a link to a privacy policy and a legal notice on the bottom of the login page (like on the Chat GPT/Open AI login page) and in footer of the chat window. The links should be configurable via the .env file. 

### More details

This is an important feature especially for libraChat ai instances hosted by institutions in the EU because of the GDPR and the duty to have a link to a legal notice (and a link to a privacy policy) on every hosted website. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks for letting me know. Will for sure work on this

**Comment by f1yn** [comment]
There's a PR ready at #2091
