### ISSUE TITLE
[Bug]: some \ too much if LaTeX rendering is enabled

### ISSUE THREAD

**Issue by darkBuddha** [danny-avila/LibreChat#1611]
### What happened?

v0.6.6

I noticed that some bash commands only worked after i removed \ from them. I guess that they were added to the LLM response, and there might be some flaw in the logic.

### Steps to Reproduce

Ask e.g. for an `awk` command, and see the $ that get prepended with `\`

LaTeX rendering enabled: 
![Screenshot from 2024-01-22 14-34-43](https://github.com/danny-avila/LibreChat/assets/3326929/38b858ae-cd40-4a3f-b636-5414ed04a280)

LaTeX rendering disabled:
![image](https://github.com/danny-avila/LibreChat/assets/3326929/b7cf7112-7085-48ef-b5b4-2d97dcb85795)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
The LaTeX parsing update is escaping dollar signs when LaTeX is not detected. It seems to be working too well.

This is already on my radar and I have a fix to ignore any dollar signs wrapped in backticks

**Comment by hhh2210** [comment]
I think it happens again，for models like gemini 2-flash, gemini-2-thinking
![image](https://github.com/user-attachments/assets/d8d205c5-9576-4fd7-a279-cc0356b43e20)
I've tried to add " use $$ to wrap up the fomula“ by few shots prompt and update the code, but it doesn't work.
