### ISSUE TITLE
[Bug]: Router behaviour for v6 vs health check

### ISSUE THREAD

**Issue by vectorkovacspeter** [danny-avila/LibreChat#1619]
### What happened?

The current version of the app seems to use different routing behaviour than the previous one, and for tehe /login endpont not responding a HTTP 200, even if running.
This makes hard to use this rout for health check purpose for containerised environment for exmaple.

Suggestion:
make new technical endpoints for the backend and frontend for health check purposes.

### Steps to Reproduce

1. pull the current source
2. deploy it to docker
3. check  curl -IL <your host>:<your port>/login

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks for your report. I agree with the resolution through a dedicated health check endpoint.
