### ISSUE TITLE
Enhancement: allow regular "new tab"-click on chat history (left menu bar)

### ISSUE THREAD

**Issue by darkBuddha** [danny-avila/LibreChat#1628]
### What features would you like to see added?

The UI items in the left menu bar (chat history) should be clickable as a regular link to allow "scrollwheel clicks". This was done for the "new chat" button in https://github.com/danny-avila/LibreChat/issues/1470, but would make sense for the chat history also.

### More details

In ChatGPT, this UI element can be "clicked regularly", i.e. when I click it with the mouse scrollwheel, it opens in a new tab, as any classic` <a href=` link.

I use this quite often when I want to add an additional chat, rather than navigating away from the open one. (muscle memory...)

Thank you for consideration, and this awesome project in general. 🙏🏻

### Which components are impacted by your request?

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Closed by https://github.com/danny-avila/LibreChat/pull/1708
