### ISSUE TITLE
[Bug]: Chat title does not update when using Google models

### ISSUE THREAD

**Issue by 0x33taji** [danny-avila/LibreChat#1658]
### What happened?

The chat title does not update when I use Google models like gemini-pro or gemini-pro-vision
It just says New Chat.

When I use other models, the chat title auto-updates

### Steps to Reproduce

1. In webui, select google gemini model
2. Chat with Ai
3. On the sidebar, the Chat title stays at New Chat

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Not yet implemented, already an open issue: https://github.com/danny-avila/LibreChat/issues/1422

**Comment by enieuwy** [comment]
@danny-avila but that issue is closed?

I have the same issue as OP. Seeing this in my container logs:
```
error: [GoogleClient] There was an issue generating the title User has requested a restricted HarmBlockThreshold setting BLOCK_NONE. You can get access either (a) through an allowlist via your Google account team, or (b) by switching your account type to monthly invoiced billing via this instruction: https://cloud.google.com/billing/docs/how-to/invoiced-billing.
```
