### ISSUE TITLE
[Question]: [Question]: After asking a question once, an error was reported the second time. What is the reason?

### ISSUE THREAD

**Issue by xillkoi** [danny-avila/LibreChat#1675]
### What is your question?

An error will be reported the second time you ask, and you can only create a new chat.
![企业微信截图_20240130151222](https://github.com/danny-avila/LibreChat/assets/82936603/868b6364-6ff2-4c0c-9092-9bdb441693ae)

### More Details
LibreChat         | 2024-01-30 07:27:21 error: There was an issue generating title with BingAI CaptchaChallenge: User needs to solve CAPTCHA to continue.
chat-meilisearch  | [2024-01-30T07:27:21Z INFO  actix_web::middleware::logger] 172.18.0.2 "GET /indexes/convos/documents/b8d859e0-ed58-4267-ad65-78819def81ad HTTP/1.1" 200 76 "-" "node" 0.000451
chat-meilisearch  | [2024-01-30T07:27:35Z INFO  actix_web::middleware::logger] 172.18.0.2 "GET /indexes/convos/documents/b8d859e0-ed58-4267-ad65-78819def81ad HTTP/1.1" 200 76 "-" "node" 0.000270
chat-meilisearch  | [2024-01-30T07:27:35Z INFO  actix_web::middleware::logger] 172.18.0.2 "POST /indexes/messages/documents HTTP/1.1" 202 136 "-" "node" 0.007627
chat-meilisearch  | [2024-01-30T07:27:35Z INFO  index_scheduler::batch] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 19 }
chat-meilisearch  | [2024-01-30T07:27:35Z INFO  index_scheduler] A batch of tasks was successfully completed.
LibreChat         | 2024-01-30 07:27:37 error: [/ask/bingAI] Error handling BingAI response Unexpected server response: 200
LibreChat         | 2024-01-30 07:27:37 error: [/ask/bingAI] Error handling BingAI response Unexpected server response: 200
chat-meilisearch  | [2024-01-30T07:27:37Z INFO  actix_web::middleware::logger] 172.18.0.2 "POST /indexes/messages/documents HTTP/1.1" 202 137 "-" "node" 0.007244
chat-meilisearch  | [2024-01-30T07:27:37Z INFO  index_scheduler::batch] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 20 }
chat-meilisearch  | [2024-01-30T07:27:37Z INFO  index_scheduler] A batch of tasks was successfully completed.

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
BingAI issues can be due to fail safes Microsoft introduces or the way they treat specific network connections.

In your case, you need to solve a CAPTCHA as shown in your logs:
> User needs to solve CAPTCHA to continue.

We have some common solutions listed on our discord you can try: https://discord.com/channels/1086345563026489514/1143941308684177429
