### ISSUE TITLE
[Bug]: Unable to include images for Gemini Pro chats after Firebase CDN setup

### ISSUE THREAD

**Issue by jinnotgin** [danny-avila/LibreChat#1687]
### What happened?

After setting up firebase CDN, I noticed that all picture media uploads are also processed as webp and then stored into Firebase storage.

However, I started encountering the following issue when trying to use Gemini Pro with an picture input:
![image](https://github.com/danny-avila/LibreChat/assets/14935308/684ddd5c-e430-4350-aab3-4ef5ab7f4337)
`Something went wrong. Here's the specific error message we encountered: Please provide image as base64 encoded data URL`
(I can confirm that the firebase CDN is working as expected, with the images URL being in firebase storage)

I have another Docker container in which firebase CDN is **not** set up (ie local), and the chat conversations with image works as expected.

### Steps to Reproduce

1. Set up firebase CDN fileStrategy
2. Set up Gemini Pro LLM endpoint
3. Add an image to chat using Gemini Pro (or Gemini Pro Vision)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Interesting, I will look into it, I have an idea of what it could be
