### ISSUE TITLE
Enhancement: re-add ChatGPTbrowser

### ISSUE THREAD

**Issue by chokiproai** [danny-avila/LibreChat#1688]
### What features would you like to see added?

Another project that can proxy chatgpt: https://github.com/gngpp/ninja

### More details

https://github.com/gngpp/ninja

### Which components are impacted by your request?

Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Berry-13** [comment]
you know, I don't want to come across as impolite, and I'm not sure about Danny's perspective on this. However, I don't believe we'll reintroduce a ChatGPT Browser, as all existing ones involve reverse engineering. The only exception I can consider is BingAI. I understand that in some countries, the use of certain LLMs may be restricted, but it's still an activity that is not very lawful

**Comment by fuegovic** [comment]
@chokiproai you can use "https://github.com/gngpp/ninja" in the same way PandoraNext was working. You'll have to deploy it yourself tho and use something like that in your `.env` config:

```bash
CHATGPT_TOKEN=user_provided
CHATGPT_MODELS=text-davinci-002-render-sha
CHATGPT_REVERSE_PROXY=http://localhost:7999/backend-api/conversation
```
![image](https://github.com/danny-avila/LibreChat/assets/32828263/29d1e06f-c3fb-4fc7-8829-828683c52af2)
