### ISSUE TITLE
No default value for "socialLogins" when not using librechat.yaml file

### ISSUE THREAD

**Issue by trevorswanson** [danny-avila/LibreChat#1729]
### What happened?

After https://github.com/danny-avila/LibreChat/commit/a2c35e841589f6cede194795202cb6559e85fa7a if you don't supply a value for socialLogins via librechat.yaml, then you get an error that socialLogins is undefined.

Providing a valid librechat.yaml and adding a socialLogins array allows the app to start successfully.

I believe a default value needs to be added if librechat.yaml is not present.

### Steps to Reproduce

Pull latest from main and attempt to start LibreChat without a librechat.yaml file

### Relevant log output

```shell
2024-02-05 14:31:05 info: Connected to MongoDB
2024-02-05 14:31:07 error: There was an uncaught error: Cannot read properties of undefined (reading 'socialLogins')
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by poloniumTacos** [comment]
Im trying to configure this in Unraid I set all my social params to true but get this error. 
> LibreChat@0.6.6 backend
> cross-env NODE_ENV=production node api/server/index.js
> 
> 2024-02-05 06:23:52 info: [Optional] Redis not initialized. Note: Redis support is experimental.
> 2024-02-05 06:23:53 info: Connected to MongoDB
> 2024-02-05 06:23:53 error: There was an uncaught error: Cannot read properties of undefined (reading 'socialLogins')`

**Comment by chetankumar** [comment]
I'm getting the same error.
I've setup the librechat.yml with the socialLogins

```yaml
registration:
  socialLogins: ["github", "google", "discord", "openid", "facebook"]
```
The docker exits with the following error.
```log
chat-mongodb      | {"t":{"$date":"2024-02-05T15:07:17.155+00:00"},"s":"I",  "c":"NETWORK",  "id":6788700, "ctx":"conn120","msg":"Received first command on ingress connection since session start or auth handshake","attr":{"elapsedMillis":3}}
chat-meilisearch  | [2024-02-05T15:07:17Z INFO  actix_web::middleware::logger] 172.22.0.4 "GET /indexes/convos/stats HTTP/1.1" 200 65 "-" "node" 0.000319
LibreChat         | 2024-02-05 15:07:17 error: There was an uncaught error: Cannot read properties of undefined (reading 'socialLogins')
```

**Comment by lehmand001** [comment]
i have social logins and social registration variables explicitly set to false, and still get this error after updating container. (unraid)

**Comment by danny-avila** [comment]
Interesting, there is a default value: https://github.com/danny-avila/LibreChat/blob/a2c35e841589f6cede194795202cb6559e85fa7a/api/server/services/AppService.js#L15

I'm looking into this.
