### ISSUE TITLE
[Bug]: Index/sort error when running against "Azure Cosmos DB for MongoDB"

### ISSUE THREAD

**Issue by robsaccone** [danny-avila/LibreChat#1731]
### What happened?

Running LibreChat in Azure App Service using Cosmos DB as backend, which can 'emulate' MongoDB.  After troubleshooting error I discovered that Conversation.js / getConvosByPage() changed to sort by updatedAt vs createdAt, and that no index in the conversations collection existed for updatedAt.  Apparently differences in capability between Cosmos/Mongo and real Mongo require an index to sort.  Manually adding an index for updatedAt field solved the issue.

Should probably add or change this index in the convos schema to address for others trying this same configuration, whether fully supported or otherwise.  Also note that using the default Azure Terraform deployment repo will reproduce this issue. 

### Steps to Reproduce

1. Use Cosmos DB instead of MongoDB container or Atlas database.
2. Get error immediately following successful login 

### Relevant log output

```shell
[getConvosByPage] Error getting conversations Error=2, Details='Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: 8fb6d4e6-49b5-46f0-842b-cdec0ebbbe1d; Reason: (Message: {"Errors":["The index path corresponding to the specified order-by item is excluded."]}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks, I've added the index field to updatedAt

**Comment by kezzzsVS** [comment]
I believe the same "updatedAt" index is required for the "files" collection when using gpt-4-vision-preview and "re-send images" is checked.

**Comment by danny-avila** [comment]
> @danny-avila I believe the same "updatedAt" index is required for the "files" collection when using gpt-4-vision-preview and "re-send images" is checked.

thanks I will look into it
