### ISSUE TITLE
Enhancement: Custom Endpoint /api/models request to include user information

### ISSUE THREAD

**Issue by drewdresser** [danny-avila/LibreChat#1738]
### What features would you like to see added?

We would like to do authorization on the GET /api/models so that we can display a different set of models to different users. 

### More details

To do that, we need some user information in that request, similar to how `/api/chat/completions` gets some information.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Hi @drewdresser 👋 

Sure, do you mean the user.id or some other identifying information?

**Comment by drewdresser** [comment]
Hi @danny-avila - yes the user.id would be great 👍
