### ISSUE TITLE
Enhancement: Option to emit debug logs to STDOUT

### ISSUE THREAD

**Issue by shaggy245** [danny-avila/LibreChat#1786]
### What features would you like to see added?

I would like an option to emit debug logs, specifically query logging, to STDOUT.

### More details

As far as I can tell, debug logs are only emitted to debug log files. I am running Librechat in a Kubernetes cluster, and scraping log files from within a running container requires a volume mount and a log-scraping sidecar container. Emitting to STDOUT would allow my K8s cluster-wide logging solution to handle Librechat debug logs.

### Which components are impacted by your request?

General

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks! This is already a feature: https://docs.librechat.ai/features/logging_system.html#setup

It would print to STDOUT, but I noticed the logging doesn't quite match the log file, so will update that in an upcoming PR and close this issue.

**Comment by shaggy245** [comment]
🤦 Thanks for pointing that out. I completely mis-read/mis-interpreted `DEBUG_CONSOLE`
