### ISSUE TITLE
[Bug]: Plugins Store disappears if 5 plugins are installed

### ISSUE THREAD

**Issue by unitedrule** [danny-avila/LibreChat#1788]
### What happened?

If the user installs 5 plugins or more, the plugins tab only shows 5 installed plugins and the store disappears.
It seems like the GUI only allows for 5 elements to show up only.

### Steps to Reproduce

1. Sign in
2. Select plugins
3. Click on Plugins store
4. install 5 plugins
5. Click anywhere on the white area
6. Select plugins again
7. Now there is no store anymore.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
The plugin store should be down the list

https://github.com/danny-avila/LibreChat/assets/32828263/bddb6478-a566-4b8d-8ba7-af963fc933e3

**Comment by danny-avila** [comment]
We should move it to the top, but yeah, it's there you just need to scroll down.
