### ISSUE TITLE
[Bug]: DALLE_API_KEY does not work as expected

### ISSUE THREAD

**Issue by iamNoah1** [danny-avila/LibreChat#1792]
### What happened?

According to the docs, setting this env variable should result in the app not asking the user for an DALLE API KEY when trying to install the plugin. However, for me it did not work, I had to set DALLE2_API_KEY to achieve the desired goal. 

### Steps to Reproduce

1. Uncomment and set DALLE_API_KEY
2. Make sure that ENDPOINTS contain `gptPlugins`
3. Open the app and try to install dalle
4. It will ask for an OPENAI API KEY
5. ... 
6. You could now check the working version by setting DALLE2_API_KEY
7. Repeat the steps before and see that it does ask for the OPENAI API KEY now

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
For the `user_provided` feature this is intended but I will clarify in the docs to close this issue.

`DALLE_API_KEY` will work for either DALLE3 or DALLE2 if set to an actual api key.

**Comment by danny-avila** [comment]
I will also revisit the code to see if I can make an easy switch to make it work more intuitively

**Comment by fuegovic** [comment]
> 1. Uncomment and set DALLE_API_KEY
> ...
> 4. It will ask for an OPENAI API KEY
---
> `DALLE_API_KEY` will work for either DALLE3 or DALLE2 if set to an actual api key.

It does work as expected on my end, try updating to latest if you haven't yet

**Comment by danny-avila** [comment]
> > 1. Uncomment and set DALLE_API_KEY
> >    ...
> > 2. It will ask for an OPENAI API KEY
> 
> > `DALLE_API_KEY` will work for either DALLE3 or DALLE2 if set to an actual api key.
> 
> It does work as expected on my end, try updating to latest if you haven't yet

oh that's right, my bad. it will work on the latest commit.
