### ISSUE TITLE
Enhancement: allow private URL for Azure API

### ISSUE THREAD

**Issue by shalak** [danny-avila/LibreChat#1800]
### What features would you like to see added?

Some of the companies, do not expose the Azure OpenAI API directly for their empoyees, but they put it behind some pass-through proxy. E.g. instead of connecting to:

`https://myCompanyInstance.openai.azure.com/openai/deployments/${azureOpenAIApiDeploymentName}`

We're connecting to:

`https://my-company.dev.ai.internal.domain.xxx/passthrough/openai/deployments/${azureOpenAIApiDeploymentName}`

That way, the company can work off of one Azure API key, but provide their internal tokens for usage tracking etc.

Currently, I need to manually patch the [azureUtils.js](https://github.com/danny-avila/LibreChat/blob/main/api/utils/azureUtils.js) to make LibreChat work properly. If such workflow would become a first-class citizen of LibreChat, it would be great!

### More details

As a bonus, the above private pass-through address usually needs private CA to be present in the system to validate the company's SSL - would be great to make it possible to mount a `.pem` file into the deployment to be used as `NODE_EXTRA_CA_CERTS`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks for checking out the project and the suggestion! Have you seen this feature? Does this work for you? 

https://docs.librechat.ai/install/configuration/ai_setup.html#using-a-specified-base-url-with-azure

> The base URL for Azure OpenAI API requests can be dynamically configured. This is useful for proxying services such as[ Cloudflare AI Gateway ](https://developers.cloudflare.com/ai-gateway/providers/azureopenai/), or if you wish to explicitly override the baseURL handling of the app.
> LibreChat will use the AZURE_OPENAI_BASEURL environment variable, which can include placeholders for the Azure OpenAI API instance and deployment names.

For this:

> As a bonus, the above private pass-through address usually needs private CA to be present in the system to validate the company's SSL - would be great to make it possible to mount a .pem file into the deployment to be used as NODE_EXTRA_CA_CERTS

I could be wrong but couldn't this be configured with NGINX/Caddy?

We have an nginx file that is used by the `deploy-compose.yml` container setup as an example.
https://github.com/danny-avila/LibreChat/blob/04af1cad52e24e720bb36401665e8b4c881c820f/client/nginx.conf

**Comment by dlaporte** [comment]
Thank you, I was literally just searching for how to specify a custom Azure endpoint and stumbled upon this!  In our case, our proxy requires x-api-key be set in the headers, but it otherwise standard Azure OpenAI.  Is there a way to add headers without using an nginx proxy?

**Comment by danny-avila** [comment]
> Thank you, I was literally just searching for how to specify a custom Azure endpoint and stumbled upon this! In our case, our proxy requires x-api-key be set in the headers, but it otherwise standard Azure OpenAI. Is there a way to add headers without using an nginx proxy?

Not at the moment will integrate that soon @dlaporte with this: https://github.com/danny-avila/LibreChat/issues/1390
