### ISSUE TITLE
Enhancement: Searchable Dropdown for Model list

### ISSUE THREAD

**Issue by danny-avila** [danny-avila/LibreChat#1815]
### Discussed in https://github.com/danny-avila/LibreChat/discussions/1813

<div type='discussions-op-text'>

<sup>Originally posted by **peterhoang** February 16, 2024</sup>
This would be a nice QoL improvement for users of Openrouter.ai, like myself. 

I attempted this myself with https://ariakit.org/examples/combobox-radix-select but was unable to get it working nicely with the exsiting code base--I'm not familiar with its inner workings.</div>

**Comment by danny-avila** [comment]
thanks @peterhoang I'll mark it as planned

**Comment by f1yn** [comment]
Happy to be assigned to this one (because of PR #2090

**Comment by danny-avila** [comment]
Closed by https://github.com/danny-avila/LibreChat/pull/2138
