### ISSUE TITLE
Enhancement: Progress UI hook for custom endpoints

### ISSUE THREAD

**Issue by itrase** [danny-avila/LibreChat#1820]
### What features would you like to see added?

Both the Plugins endpoint and the new Assistants endpoint have UI elements that indicate the run/agent is busy using a tool/action/plugin. Custom endpoints allow for custom models that may be using tools in a similar way on the backend - it would be nice to still be able to display that status.

### More details

As far as I understand it, LibreChat gets the status of an Assistant run by polling the OpenAI API, while it always knows the status of a Plugins run because it is managing the ReAct framework internally. Presumably, for custom endpoints, LibreChat would need to send an API request to the custom endpoint to check the status of a completion, which (AFAIK) is not part of the OpenAI API spec.

### Which components are impacted by your request?

UI, Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Yup something like this is planned. I would like to make it so any LLM can run tools in a similar fashion. I learned a lot by implementing agents

**Comment by danny-avila** [comment]
Re-reading this, I may have misread the first time when this issue was posted. I'm not sure I can do this without a standard framework in place (which is defined by both Assistants and Plugins endpoints, which is how I'm able to do this).

In both cases, there are triggers that define the state of actions.
