### ISSUE TITLE
Enhancement: OpenRouter top-level interface category

### ISSUE THREAD

**Issue by curiousclinician** [danny-avila/LibreChat#1832]
### What features would you like to see added?

OpenRouter brings in a pile of models, but they show up in the OpenAI model list, which is cluttered.  It would be helpful to have an OpenRouter listing (i.e. along-side OpenAI, Assistants, Google) at the Endpoint level to keep the OpenRouter models from complicating other lists.

### More details

Making OpenRouter an endpoint (I'm talking about the .env docker based setup here) would be very helpful.  It'd be great if you could define which models show up in the dropdown in the same way that you can with other endpoints.

### Which components are impacted by your request?

UI, Endpoints

### Pictures

<img width="531" alt="Screenshot 2024-02-18 at 11 40 51 PM" src="https://github.com/danny-avila/LibreChat/assets/8451988/817ccb99-ff33-4f03-a383-71c929350435">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Already implemented here: https://docs.librechat.ai/install/configuration/custom_config.html

Also related issue on decluttering #1815

**Comment by curiousclinician** [comment]
^_^

Yeah, I just needed to set up the .yaml settings file.  Thanks!
