### ISSUE TITLE
[Question]: Copy to clipboard in Assistant endpoint not working

### ISSUE THREAD

**Issue by Ricci1518** [danny-avila/LibreChat#1844]
### What is your question?

I tried the copy to clipboard button on answers in the assistant endpoint an it doesn't work (in all the other endpoints it works without a problem). Is this just not implemented yet? And how can I copy the content of the answer otherwise?

### More Details

see above

### What is the main subject of your question?

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
It's not implemented but I will work on it today. See here for the current roadmap specific to Assistants: https://discord.com/channels/1086345563026489514/1207093490740109392
