### ISSUE TITLE
Enhancement: use pre-built Docker images in the installation doc

### ISSUE THREAD

**Issue by jerkstorecaller** [danny-avila/LibreChat#1854]
### What features would you like to see added?

The doc at https://docs.librechat.ai/install/installation/docker_compose_install.html I just followed  uses the local build approach, which is time-consuming on slow/weak systems (my $1/month VPS). I came here to request that you upload the pre-built images to Docker Hub, but I found #531 which shows you already did it long ago!

I think the doc should be updated to use those pre-built binaries by default. Or at least mention their existence in the doc, including the docker pull URL. Perhaps update the docker-compose.yml to use it by default?

It's just weird that you bothered making those images then never mention or use them 🤣 

P.S. I just updated from 0.59 to latest, I was worried the history wouldn't import, but it all went fine. Great job!

### More details

aaa

### Which components are impacted by your request?

General

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
The pre-built images are mainly hosted on GitHub Containers registry: https://github.com/danny-avila?tab=packages&repo_name=LibreChat

I agree, there should at least be mention of it.

I will consider making the pre-built images the default method as they are more environment-friendly (packages for arm and amd builds) and local builds require a network connection anyway.
