### ISSUE TITLE
Enhancement: Desktop App as Electron/Appimage Release

### ISSUE THREAD

**Issue by PhoenixBlade24** [danny-avila/LibreChat#1859]
### What features would you like to see added?

I would like to request an Appimage and/or Flatpak release of LibreChat, for Linux-based users. Both solutions provide an easy way to download and use applications, without having to do any manual setup.

### More details

Appimages are largely distro-agnostic, and can be used across a wide variety of systems without impacting the user's desktop setup, as they contain everything a particular program needs to run in a single package. Similar to a portable Windows .exe file. Flatpaks are hosted on Flathub, a software centre accessed via a system application. Think Apple's App Store or Google's Google Play.

### Which components are impacted by your request?

General, UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leikoilja** [comment]
I have just open-sourced a desktop app wrapper called LibreChat-UI [here](https://github.com/leikoilja/LibreChat-UI) if you are interested. I've been using it for the past 3 weeks and it has been working great for me :)

**Comment by jmaddington** [comment]
Will it auth successfully with openid?

**Comment by leikoilja** [comment]
> Will it auth successfully with openid?

it should. it's just a "wrapper" around the browser session, so i cant see why not. 
i have my libre instance sitting behind google oauth and it works just fine (as it would be in the browser)
