### ISSUE TITLE
Enhancement: better protection of data privacy (Dicebear avatars)

### ISSUE THREAD

**Issue by Marx1st** [danny-avila/LibreChat#1868]
### What features would you like to see added?

As of now LibreChat uses the 3rd party plattform Dicebear to create the svg with the user's initials. For this the full name of the user is send to Dicebear's api (eg. John Doe is send to Dicebear and it returns a svg with the initals JD):
https://api.dicebear.com/6.x/initials/svg?seed=John%20Doe&fontFamily=Verdana&fontSize=36

The same result could be achieved by determaning the initials locally and only sending those to Dicebear. eg:
https://api.dicebear.com/6.x/initials/svg?seed=JD&fontFamily=Verdana&fontSize=36

And is it really neccessary to use a 3rd party api for this, at all? 

### More details

The api call is defined here: client/src/components/Endpoints/Icon.tsx

### Which components are impacted by your request?

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
You're right. When this was implemented, I was unaware dicebear had an opensource library. I'm happy to say we can achieve the same effect without an API call. Thanks for highlighting this.
