### ISSUE TITLE
Enhancement: Private Assistants

### ISSUE THREAD

**Issue by gius** [danny-avila/LibreChat#1926]
### What features would you like to see added?

Created assistants could be either shared, or private for the author

### More details

Currently, users can access any assistant. This allows other users to access the files uploaded to the assistant. Making assistants private should prevent other users from accessing the files.

### Which components are impacted by your request?

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Already implemented: https://docs.librechat.ai/install/configuration/custom_config.html#supportedids

Also they can be completely private if you only allow users to put in their API keys (based off separate OpenAI accounts) rather than sharing the one configured by admin.

**Comment by gius** [comment]
Thank you for your quick response. The use-case I mentioned is right when you configure the API key in env file (so that your users do not need to know/bother).

**Comment by danny-avila** [comment]
> Thank you for your quick response. The use-case I mentioned is right when you configure the API key in env file (so that your users do not need to know/bother).

Gotcha, I see. So you want to limit users to their own created assistants, while sharing API key? That should be possible actually, as long as you're ok with them sharing OpenAI file storage.

**Comment by gius** [comment]
Exactly! I don't think that sharing OpenAI storage would be a problem. It seems to me that only Assistant's configuration and actual prompting are accessible to other users. Files uploaded to the assistant are not visible in the My files, nor the Assistant's Knowledge section.

Do you have any idea how to achieve that without changes to the codebase, or do we need to actually implement this?

**Comment by danny-avila** [comment]
> Exactly! I don't think that sharing OpenAI storage would be a problem. It seems to me that only Assistant's configuration and actual prompting are accessible to other users. Files uploaded to the assistant are not visible in the My files, nor the Assistant's Knowledge section.
> 
> Do you have any idea how to achieve that without changes to the codebase, or do we need to actually implement this?

**Comment by gius** [comment]
Great! I was also thinking about using the [Metadata](https://platform.openai.com/docs/api-reference/assistants/createAssistant#assistants-createassistant-metadata) property to store something like "owner". But if you prefer using the DB, it makes sense as well. If you can provide more detailed guidance about your preferred way, I would like to talk with my colleagues and help with a PR ;-) ...cannot promise anything, though.
