### ISSUE TITLE
Enhancement: Readable model name in drop down lists

### ISSUE THREAD

**Issue by virtuman** [danny-avila/LibreChat#1929]
### What features would you like to see added?

Readable model names, for end users should say GPT-3.5 or GPT-4, etc. while some other models might remain unchanged, there doesn't seem to be a good reason to show user something like gpt-3.5-turbo-0125, etc.

### More details

more user friendly model names in drop down lists

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This is basically the issue raised here so closing this: https://github.com/danny-avila/LibreChat/issues/1617
