### ISSUE TITLE
[Bug]: copy text from MS OneNote or Excel become an image

### ISSUE THREAD

**Issue by JamieWuJinYi** [danny-avila/LibreChat#1934]
### What happened?

There is an issue: when you copy text from MS OneNote or Excel and paste it into the input box of gpt, it becomes an image, but you cannot send it out.

### Steps to Reproduce

1.copy something in locally excel
2.paste it into the input box
3.ask the question.

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/100826652/d5dffd5a-92de-4f4d-a558-40eed6341b73)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dannykorpan** [comment]
Same here with e.g Word.

**Comment by danny-avila** [comment]
this is a known issue for a while, and I have a solution for parity with ChatGPT

### ChatGPT

![image](https://github.com/danny-avila/LibreChat/assets/110412045/449cbb11-269e-4c05-9417-70e9d73d79b2)

### LibreChat

![image](https://github.com/danny-avila/LibreChat/assets/110412045/8252c474-a458-4a73-b165-8bdd221726a6)
