### ISSUE TITLE
Enhancement: Support for new Claude 3 model family (use messages instead of completions for anthropic models) 

### ISSUE THREAD

**Issue by ajkost** [danny-avila/LibreChat#1963]
### What features would you like to see added?

New models were [introduced](https://www.anthropic.com/news/claude-3-family) by Anthropic (claude-3-opus-20240229 and claude-3-sonnet-20240229) and I would love to see support for them in Librechat. 

### More details

Since new models work only with Messages API and the old ones work with both Messages & Text Completions API, also Completions API was marked as _[Legacy]_ [already](https://docs.anthropic.com/claude/reference/complete_post), I think it would be great to switch from Completions to Messages to be able to support also new models. Source: [models overview](https://docs.anthropic.com/claude/docs/models-overview)

![image](https://github.com/danny-avila/LibreChat/assets/10452148/404722aa-6550-4b64-a259-cbc263b6d252)

Here is the message from Librechat if I want to use new model (in this example the sonnet one)
![image](https://github.com/danny-avila/LibreChat/assets/10452148/94f717a2-3a0b-4587-ab37-08f1cc6845e4)

Thank you very much for all of your work! 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks, I'll be working on this

**Comment by ajkost** [comment]
Works like a charm 💪 Fantastic job. Huge thanks for the swift action, it's truly appreciated!

**Comment by muhlba91** [comment]
@danny-avila any estimate on when this fix will be released as part of a container image, apart from the dev one?

**Comment by danny-avila** [comment]
> @danny-avila any estimate on when this fix will be released as part of a container image, apart from the dev one?

the end of this week or next, at this point it will likely be next week.
