### ISSUE TITLE
[Bug]: Gemini Pro is not giving titles to my conversations

### ISSUE THREAD

**Issue by delta-whiplash** [danny-avila/LibreChat#1986]
### What happened?

Hello I was wondering why gemini pro conversations didn't have titles 

### Steps to Reproduce

Start a conversation with gemini pro

### What browsers are you seeing the problem on?

Chrome

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/39416418/ff15b81b-69ec-4aaa-9e60-18e685183aad)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by acerspyro** [comment]
Neither is Anthropic Claude FWIW, not sure what's special about these two AIs. Is there a config we're missing?

![image](https://github.com/danny-avila/LibreChat/assets/4400999/51add5f1-a5b5-4a2b-82be-be120a075950)

**Comment by danny-avila** [comment]
> Neither is Anthropic Claude FWIW, not sure what's special about these two AIs. Is there a config we're missing?

No it's not supported for either but I may add the functionality in the next day or two. Closing in favor of the older issue: https://github.com/danny-avila/LibreChat/issues/1422
