### ISSUE TITLE
Enhancement: Add WebraftAi in the huggingface spaces

### ISSUE THREAD

**Issue by Ohookkk** [danny-avila/LibreChat#2026]
### What features would you like to see added?

Enhancement: Add WebraftAi in the huggingface spaces(https://huggingface.co/spaces/LibreChat/LibreChat)

### More details

Endpoint: https://api.webraft.in/v1/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Berry-13** [comment]
sure,

but please, ask this in the [Discord channel](https://discord.com/channels/1086345563026489514/1136674701431820348) or open an issue on HF. Here, you should only create issues related to LibreChat not the demo, thanks

**Comment by Berry-13** [comment]
@Ohookkk
we need more information about this API:
1. how to get a key?
2. what models does it offer?
3. is it free?

**Comment by Ohookkk** [comment]
https://discord.gg/webraftai
In the discord
It offer 200 models add the more important
I gived the paid endpoint the free is: https://api.webraft.in/freeapi/chat/completions

**Comment by Ohookkk** [comment]
Im new here sorry

**Comment by fuegovic** [comment]
@Ohookkk 
This is a manual process and I don't really have time to do it myself...

Here is the file that the demo uses for the endpoints and models:
https://github.com/fuegovic/lc-config-yaml/blob/main/librechat-firebase.yaml

If you or someone else make a PR to update this file, with all models available from this list: [api.webraft.in/freeapi/models](https://api.webraft.in/freeapi/models), I'll approve it 

The endpoint needs to be `"/v1/chat/completions"`  and we use the model `"id"` (not the model `"name"`)
