### ISSUE TITLE
[Question]: How to add and use Google's Gemini 1.5 Pro?

### ISSUE THREAD

**Issue by Niqnil** [danny-avila/LibreChat#2029]
### What is your question?

I have access to it in Google AI studio and I would like to use it in LibreChat. The other Google models appear and can be selected but not Gemini 1.5 Pro.

### More Details

Relevant settings in my .env:
```
GOOGLE_KEY=[my api key]
# GOOGLE_MODELS=gemini-pro,gemini-pro-vision,chat-bison,chat-bison-32k,codechat-bison,codechat-bison-32k,text-bison,text-bison-32k,text-unicorn,code-gecko,code-bison,code-bison-32k
```

### What is the main subject of your question?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
There is no API access yet, it's only available in Google AI studio

---

![image](https://github.com/danny-avila/LibreChat/assets/32828263/9f6ac16f-9fc0-4fa8-9dc9-6c2e143c8395)
![image](https://github.com/danny-avila/LibreChat/assets/32828263/993fc2d2-05d1-42ae-88d3-2a695a4a6b25)
