### ISSUE TITLE
Enhancement: Assistant file downloads

### ISSUE THREAD

**Issue by davidmarble** [danny-avila/LibreChat#2030]
### What features would you like to see added?

When an assistant returns a response with one or more files to download, I'd like to be able to download them.

### More details

When I get a response from an OpenAI Assistant I created that should contain a link to download a file (e.g. a CSV generated as part of an analysis I requested), the links currently appear as just `javascript:void(0)`. I'm unsure if this is implemented and not working (a bug), or an enhancement request. [Looks like there's some special parsing needed to handle files](https://community.openai.com/t/how-do-download-files-generated-in-ai-assistants/493516/15) in responses from OpenAI's Assistants API.

## Conversation example with OpenAI assistant:

![Screenshot 2024-03-08 at 6 04 14 PM](https://github.com/danny-avila/LibreChat/assets/253443/6d43eb61-b990-42a5-8d9d-f3d10d123063)

## HTML Source:

![Screenshot 2024-03-08 at 6 04 32 PM](https://github.com/danny-avila/LibreChat/assets/253443/a66cc0cb-8b07-46cb-97db-9e793002fde0)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks! Timely because I was working on this yesterday

**Comment by AndreaLeto00** [comment]
I am joining to report this,
is there any news?

**Comment by danny-avila** [comment]
> I am joining to report this, is there any news?

I was finished with this then lost power and vs code decided to discard all my changes, even when I had all the files saved. It will be quicker to implement the second time around but this unfortunate event pushes it back to later this week.

**Comment by PedroGruvhagen** [comment]
Will it also work with Azure assistants? Uploading and downloading files thanks to the code interpreter makes assistants worth it in many scenarios! 

Many thanks for the great job always, @danny-avila

**Comment by danny-avila** [comment]
> Will it also work with Azure assistants? Uploading and downloading files thanks to the code interpreter makes assistants worth it in many scenarios!
> 
> Many thanks for the great job always, @danny-avila

Yes absolutely

**Comment by sathyarajv** [comment]
@danny-avila Is this changes merged to main?

**Comment by danny-avila** [comment]
> @danny-avila Is these changes merged to main?

Not yet

**Comment by sathyarajv** [comment]
Thank you for the great work! @danny-avila

**Comment by danny-avila** [comment]
> Thank you for the great work! @danny-avila

my pleasure!
