### ISSUE TITLE
[Bug]: Performance Degradation Due to Frequent Re-rendering During Text Input

### ISSUE THREAD

**Issue by nakamurau1** [danny-avila/LibreChat#2036]
### What happened?

There appears to be an issue with the Textarea component within the ChatForm where the screen freezes during text input, including when typing in Japanese. This issue seems to be caused by the component frequently re-rendering during text entry.

### Steps to Reproduce

1. Navigate to a page where the ChatForm is displayed.
2. Begin entering text into the Textarea using Japanese input.
3. During the input of longer texts, the screen temporarily freezes.

### Screenshots

This is a video demonstrating the issue that this PR aims to resolve. The screen freezes due to frequent re-rendering of the TextArea during Japanese text input.

https://github.com/danny-avila/LibreChat/assets/1153289/bbe139bd-1259-4ea2-9bd5-81aac812aeb9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nakamurau1** [comment]
@danny-avila 
First off, a massive thank you for creating and maintaining LibreChat! 🎉 It's an incredible project, and I'm truly grateful for the opportunity to contribute to it.

I've noticed an issue where the Textarea component in the ChatForm causes frequent re-rendering during text input, particularly with Japanese text input, which leads to some freezing/lagging. It caught my attention as something that might be improved for a better user experience.

I've taken the liberty of drafting a PR to tackle this issue by integrating React Hook Form for more efficient form state management and to minimize unnecessary re-renders. I'd really value your input on this solution!

Thanks again for all your amazing work on this project. Looking forward to your feedback!

**Comment by danny-avila** [comment]
Thanks so much. I wasn’t aware of this but I’ll run some tests to confirm the re-rendering issue, before and after

**Comment by danny-avila** [comment]
Lost power before I could push up my code. Have a suggested fix
