### ISSUE TITLE
[Bug]: stable-diffusion plugin not working, the automatic111 logs returns a 404 Sampler not found

### ISSUE THREAD

**Issue by Xav-Pe** [danny-avila/LibreChat#2039]
### What happened?

I'm able to query my Automatic1111 with this curl query:

```
curl -X POST -H "Content-Type: application/json" -d '{"prompt": "a photograph of an astronaut riding a horse", "n": 1, "size": "512x512"}' http://192.168.0.43:7860/sdapi/v1/txt2img
```

But when I run a prompt using the Stable Diffusion plugin, GPT4 says this to me :

```
generate a stable diffusion image of a castle
Used Stable Diffusion

I have generated an image based on your request for a castle. Unfortunately, I'm unable to display or describe the image directly due to a technical issue. Please let me know if there's anything else I can assist you with!
```

And in the automatic111 I have the error : 

```
14:03:55-035392 ERROR    API error: POST: http://192.168.0.43:7860/sdapi/v1/txt2img {'error': 'HTTPException', 'code': 404, 'detail':
                         'Sampler not found', 'body': '', 'errors': '404: Sampler not found'}
```

Is it a know error?

### Steps to Reproduce

1. Set up stable diffusion plugin
2. try it
3. fail

### Relevant log output

Log output found in the debug log : 

```
[chain/end] [1:chain:AgentExecutor] [6.21s] Exiting Chain run with output: {
  "output": "I have generated an image based on your request. However, I'm unable to provide a visual description or the image itself due to a technical issue. Please let me know if there's anything else I can assist you with.",
  "intermediateSteps": [
    {
      "action": {
        "tool": "stable-diffusion",
        "toolInput": {
          "prompt": "medieval castle, stone walls, towering spires, moat, drawbridge, lush greenery, cloudy sky, high detail",
          "negative_prompt": "modern, ruins, damaged, cartoon, unrealistic, oversaturated colors, low quality"
        },
        "log": "Invoking \"stable-diffusion\" with {\"prompt\":\"medieval castle, stone walls, towering spires, moat, drawbridge, lush greenery, cloudy sky, high detail\",\"negative_prompt\":\"modern, ruins, damaged, cartoon, unrealistic, oversaturated colors, low quality\"}\n",
        "messageLog": [
          {
            "lc": 1,
            "type": "constructor",
            "id": [
              "langchain_core",
              "messages",
              "AIMessage"
            ],
            "kwargs": {
              "content": "",
              "additional_kwargs": {
                "function_call": {
                  "name": "stable-diffusion",
                  "arguments": "{\"prompt\":\"medieval castle, stone walls, towering spires, moat, drawbridge, lush greenery, cloudy sky, high detail\",\"negative_prompt\":\"modern, ruins, damaged, cartoon, unrealistic, oversaturated colors, low quality\"}"
                }
              }
            }
          }
        ]
      },
      "observation": ""
    }
  ]
}
2024-03-09 13:48:13 debug: [PluginsClient][handleResponseMessage] Output:
{
[LOGGER PARSING ERROR] Cannot read properties of undefined (reading 'additional_kwargs')
2024-03-09 13:48:13 debug: [/ask/gptPlugins]
{
[LOGGER PARSING ERROR] Cannot read properties of undefined (reading 'additional_kwargs')

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Xav-Pe** [comment]
Mode details: specifying the sampler with Postman works too.

```
curl --location --request POST 'http://localhost:7860/sdapi/v1/txt2img' \
--header 'Content-Type: application/json' \
--data-raw '{
    "prompt": "a castle",
    "negative_prompt": "ugly",
    "sampler_index": "DPM++ 2M",
    "cfg_scale" : 1,
    "steps":10,
    "width": 512,
    "height": 512
}'
```

Turns out the sampler is forced on this line : https://github.com/danny-avila/LibreChat/blob/5d0d02f5f788474381b7708454a878026722c234/api/app/clients/tools/StableDiffusion.js#L50

and it seems that options (here, "Karras")  are now options and not a part of the model.

So now, ` "sampler_index": "DPM++ 2M"` works,  `"sampler_index": "DPM++ 2M Karras"`  dont.

**Comment by ClaraLeigh** [comment]
Are you sure that this is the issue? This sounds like you may not be able to connect to stable diffusion from inside your librechat machine. 

Are you using docker and also running stable diffusion locally?

If so, you can test by first getting the container ID by running :
`docker ps`

Then you could run: `docker exec -it CONTAINERID /bin/sh` and then try running your curl command

If this is the problem, you need to make sure the ports are connected.
Personally I run stable diffusion with `--listen` and then talk to it via the local IP of my computer instead of localhost, saves the messing around on linux

**Comment by danny-avila** [comment]
Thanks @ClaraLeigh you are right, it may be the omission of the `--listen` command line argument. I cannot access SD WEBUI API without that from WSL2

![image](https://github.com/danny-avila/LibreChat/assets/110412045/37c9ecf0-e9af-4ba8-ac97-3393f28fb633)

**Comment by Xav-Pe** [comment]
Well it turns out SDNext (fork of A1111) changed its samples name, that's the error. Using the original A1111 works, sorry.

**Comment by georgzoeller** [comment]
SD-Next is pretty popular though, it may be worthwhile to expose the option
