### ISSUE TITLE
Enhancement: Deleting a tool for the OpenAI Assistant requires the user to go through "Add Tools"

### ISSUE THREAD

**Issue by acerspyro** [danny-avila/LibreChat#2047]
### What happened?

Unless I'm missing something, the only way to delete a tool in an Assistant is to go through "Add Tools", which isn't very intuitive.

I would have expected the cog wheel on the right of the tool to let me delete it, but clicking on it does nothing in Firefox and Epiphany.

### Steps to Reproduce

1. Create an Assistant
2. Add a tool
3. Try to delete the tool

### What browsers are you seeing the problem on?

Firefox

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/4400999/2b7b9beb-6095-4c6c-a662-838f35691b62)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks, there are a couple things with the Assistant Builder form that are a work in progress, this being one of them.
