### ISSUE TITLE
[Bug]: Avatar with OIDC not persistent

### ISSUE THREAD

**Issue by Dual-0** [danny-avila/LibreChat#2056]
### What happened?

Hello,

I used authentik to login via OIDC. When I set the avatar and logout and login again the avatar is gone.

### Steps to Reproduce

1. install librechat-dev, mongo and meilisearch container from scratch.
2. login via authentik
3. go to settings -> account -> avatar
4. choose file and upload
5. wait for confirmation
6. notice the avatar in the left-bottom corner
7. logout
8. login via authentik
9. gone

### What browsers are you seeing the problem on?

Vivaldi on Windows

### Relevant log output

sorry I don't see anything in the dev-librechat container log

### Screenshots

login:
![image](https://github.com/danny-avila/LibreChat/assets/37346547/d24bea6e-9c7c-428c-ba76-53f122b0393d)

choose image:
![image](https://github.com/danny-avila/LibreChat/assets/37346547/49bd79d4-d9c1-44f6-adf1-682f98627083)

confirmation:
![image](https://github.com/danny-avila/LibreChat/assets/37346547/73d9abe3-d82c-4daa-8368-485f22d107bb)

avatar:
![image](https://github.com/danny-avila/LibreChat/assets/37346547/92d5eb4a-3c77-4a4a-a70e-dd91f37edef8)

logout and login again... gone:
![image](https://github.com/danny-avila/LibreChat/assets/37346547/c334b2fb-50a2-4c7a-9eee-b4d4bac0d212)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Berry-13** [comment]
in OpenID, many things don't work (including this) since I didn't have time to implement this feature. I'll work on this today 👍

**Comment by danny-avila** [comment]
@berry-13 I think the root issue is that if OIDC avatar fetching fails, we reset the avatar to a blank string. it should be left alone if there is already an avatar and no new image is fetched.

**Comment by danny-avila** [comment]
Hoping to get this fixed with https://github.com/danny-avila/LibreChat/pull/2344 since I'm touching the related file in that update.

**Comment by cmurtaugh** [comment]
@danny-avila  I proposed a solution in draft PR #2984. I'm not really a JS/TS developer so not sure what to do about tests. The code changes are pretty small.

**Comment by danny-avila** [comment]
> @danny-avila I proposed a solution in draft PR #2984. I'm not really a JS/TS developer so not sure what to do about tests. The code changes are pretty small.

Thanks! That's pretty much the fix we need there
