### ISSUE TITLE
[Bug]: If I use assistants, it will allow me to go over token budget

### ISSUE THREAD

**Issue by virtuman** [danny-avila/LibreChat#2105]
### What happened?

When I use OpenAI directly as an endpoint, it will block my requests as i come to the limit of tokens. However, when i use Assistants, it ignores the fact that I went over limit, and continues to process all requests.

is it expected behavior?

### Steps to Reproduce

login to account with minimal or negative credit
try to run request on openai assistant - it should block if runs over allowed limits
then select any assistant with openai backend, and run same request
-> it will continue to process requests as normal, without taking into consideration that the allotted token limits is overused.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks I’ve triaged the issue and will push a fix soon.

**Comment by badcom** [comment]
![2024-03-15_09-52-53](https://github.com/danny-avila/LibreChat/assets/783736/46c9882c-5a47-4cc9-bb6c-2b06b0d76393)

I got this error when using the gpt-4-vision-preview model. Related to this bug?

**Comment by danny-avila** [comment]
> ![2024-03-15_09-52-53](https://private-user-images.githubusercontent.com/783736/313198863-46c9882c-5a47-4cc9-bb6c-2b06b0d76393.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MzM2MzksIm5iZiI6MTcxMDUzMzMzOSwicGF0aCI6Ii83ODM3MzYvMzEzMTk4ODYzLTQ2Yzk4ODJjLTVhNDctNGNjOS1iYjZjLTJiMDZiMGQ3NjM5My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQyMDA4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzZiZGU2MGZhNjFkMzM4NTdkYmEwNWJkYjQ4MWM0NzA3NjRlZWFhNTI1NzMyNmJjNTFhNzc0MDIxNDlhMzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lghqrj2QTX3wD-8FdVrM2hC-LeJm_qY5r1lMKWXYXsY)
> 
> I got this error when using the gpt-4-vision-preview model. Related to this bug?

No, this is specific to OpenRouter and using their "free" account which limits context

**Comment by badcom** [comment]
I'm not using OpenRouter, though. It isn't one of my endpoints. My OPENROUTER_API_KEY does have a key set to it, but I'm not using that endpoint when I get that error message. That's the odd thing.

**Comment by danny-avila** [comment]
> OPENROUTER_API_KEY 

Do not use this variable, see https://github.com/danny-avila/LibreChat/issues/2097
