### ISSUE TITLE
Enhancement: Help add ANTHROPIC_REVERSE_PROXY?

### ISSUE THREAD

**Issue by xjqianqian** [danny-avila/LibreChat#2107]
### What features would you like to see added?

There is REVERSE PROXY for OPENAI and GOOGLE, but it seems there is no config for ANTHROPIC_REVERSE_PROXY

### More details

no config for ANTHROPIC_REVERSE_PROXY

### Which components are impacted by your request?

Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
`ANTHROPIC_REVERSE_PROXY=` exists, I accidentally removed it from the .env.example when I updated the model list. You should be able to configure it, you just need to add it manually to your .env file at the moment

see also:
https://docs.librechat.ai/install/configuration/dotenv.html#anthropic
