### ISSUE TITLE
[Bug]: Not able to download Assistant generated files.

### ISSUE THREAD

**Issue by sathyarajv** [danny-avila/LibreChat#2167]
### What happened?

I'm using an Assistant to generate a csv file with formatted data, but in the UI the download url was empty javascript function. This is the data in the thread:
```json
{
        "_id": "65fc45614",
        "model": "asst_xyxyxy",
        "content": [
            {
                "type": "text",
                "text": {
                    "value": "The JSON data, with grouping by cvr including the corresponding keys, has been successfully converted to a CSV file. You can download the CSV file using the following link:\n\n[Download the CSV file with cvr and keys data](sandbox:/mnt/data/cvr_keys_data.csv)\n\nIf you need any further assistance or modifications, feel free to let me know!",
                    "annotations": [
                        {
                            "type": "file_path",
                            "text": "sandbox:/mnt/data/cvr_keys_data.csv",
                            "start_index": 233,
                            "end_index": 274,
                            "file_path": {
                                "file_id": "file-uUXX"
                            }
                        }
                    ]
                }
            }
        ],
        "isCreatedByUser": false,
        "createdAt": "2024-03-21T14:34:09.069Z",
        "isEdited": false,
        "unfinished": false,
        "error": false
    }
```    
It generates this element in UI, 
`<a href="javascript:void(0)" target="_new">Download the CSV file with cvr and keys data</a>`

How to download the actual file in the file_path of annotations object inside content.

### Steps to Reproduce

1.  Create an assistant with code interpreter and retrieval plugin. 
2. Pass some data to format and create a csv out of it. 
3. 

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Not a bug, just not implemented, please see the open issue: https://github.com/danny-avila/LibreChat/issues/2030

**Comment by sathyarajv** [comment]
Thank you, @danny-avila
