### ISSUE TITLE
[Bug]: Broken links in documentation of “AI Setup”

### ISSUE THREAD

**Issue by fkohrt** [danny-avila/LibreChat#2170]
### What happened?

The links in the section on assistants to the custom config file on `timeoutMs` and `supportedIds` are broken.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
where exactly? I can't find any reference to `timeoutMs` or `supportedIds` in the doc named "[AI Setup](https://docs.librechat.ai/install/configuration/ai_setup.html)"

**Comment by fkohrt** [comment]
The broken links are the following two links called “More info” in the section on assistants:

https://github.com/danny-avila/LibreChat/blob/2ea6e8c18a65ccb9c3aa93ea3e3ba9db9ad4adb5/docs/install/configuration/ai_setup.md?plain=1#L129-L130

See also my commit c3d0ef4

**Comment by fuegovic** [comment]
@fkohrt Just saw the PR, thanks for fixing this!
