### ISSUE TITLE
Enhancement: Keep plugins selected for a particular chat

### ISSUE THREAD

**Issue by fkohrt** [danny-avila/LibreChat#2174]
### What features would you like to see added?

When I start a chat with a particular set of plugins and later revisit this chat, I suggest the same set of plugins is still selected.

### More details

./.

### Which components are impacted by your request?

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I agree this is a long-time coming
