### ISSUE TITLE
Enhancement: Hope to add the upload folder function.

### ISSUE THREAD

**Issue by sgtalh4381** [danny-avila/LibreChat#2179]
### What features would you like to see added?

The Gemini 1.5 Pro model already supports the upload folder function. When will this feature be implemented in LibreChat?

### More details

The Gemini 1.5 Pro model API is coming soon.

### Which components are impacted by your request?

General, Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I understand that Gemini 1.5 has [native file support as discussed in their blog post](emo.librechat.ai/), but general file support is now available in the project, including Google

![image](https://github.com/danny-avila/LibreChat/assets/110412045/6640ed2a-ba4f-48f5-b9eb-1f21ff3678fc)

It will even work with PaLM2 and Codey models (chat-bison, codechat-bison)

![image](https://github.com/danny-avila/LibreChat/assets/110412045/d288ac75-c114-4307-87a3-824c9e3962f5)
