### ISSUE TITLE
Enhancing Compatibility: Upgrading langchain to the latest version to allow support for newer libraries

### ISSUE THREAD

**Issue by arishwin** [danny-avila/LibreChat#2188]
### Discussed in https://github.com/danny-avila/LibreChat/discussions/2187

<div type='discussions-op-text'>

<sup>Originally posted by **arishwin** March 24, 2024</sup>
Hello everyone,

I've been working with `LibreChat` in conjunction with `@pinecone-database/pinecone`, and I've encountered a version compatibility issue that I believe could benefit from community input and possibly lead to an enhancement of `langchain` versions.

**Current Situation:**
The `langchain` versions in this project currently supports up to version 1.x of `@pinecone-database/pinecone`. However, `@pinecone-database/pinecone` has released version 2.x, which introduces serverless support. These enhancements are critical for the development of plugins that rely on the latest database functionalities and performance improvements. Adding version 2.x into the project introduces some dependency conflict with the current versions of `langchain`

**Suggestion:**
I propose that we consider upgrading `langchain` to the latest version so that it can support `@pinecone-database/pinecone` 2.x. This upgrade could provide developers the option to use plugins that support the latest serverless functionalities of Pinecone.

I believe this discussion could pave the way for an enhancement that benefits not only current users but also makes `LibreChat` more appealing to new adopters by ensuring it supports the latest technologies and standards.

Looking forward to your thoughts and feedback!

Best regards,
Arishwin</div>

**Comment by danny-avila** [comment]
I will eventually bump the package as I have something in mind but you don't need to wait for this. Since you likely already work off a fork, you can maintain the package upgrade as needed:

```bash
# from project root
cd api
npm i langchain@latest # or whichever package needed
```
