### ISSUE TITLE
Enhancement: Librechat to be able to send files through request to the rag_api, not only by sharing a temp folder

### ISSUE THREAD

**Issue by Fakamoto** [danny-avila/LibreChat#2204]
### What features would you like to see added?

Librechat to be able to send files through request to the rag_api, not only by sharing a temp folder

### More details

Librechat to be able to send files through request to the rag_api, not only by sharing a temp folder.
because as of now you can only "send" files by storing them in a shared temp folder, its not ideal. Causes many impediments.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Already implemented, see the latest commits of the rag api

**Comment by Fakamoto** [comment]
Thanks
