### ISSUE TITLE
[Bug]: [OpenAIClient] There was an issue generating the title with the completion method this.options.attachments?.then is not a function

### ISSUE THREAD

**Issue by Fakamoto** [danny-avila/LibreChat#2205]
### What happened?

When adding an attatchment to a chat, using azure openai model, with rag_api connection. Its unable to generate a title for the conversation, `LibreChat         | 2024-03-25 19:04:17 error: [OpenAIClient] There was an issue generating the title with the completion method this.options.attachments?.then is not a function` is the error

### Steps to Reproduce

setup rag_api with librechat

setup azure openai model

have a conversation with azure model, attatching a file to your first message

---
Error happens, no title will be set to your converation, just New Chat

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Already fixed on the latest commit of LibreChat

**Comment by danny-avila** [comment]
Thanks again for the reports. With Azure specifically, there can be more going on but no issues with any of these models, titling + files 
![image](https://github.com/danny-avila/LibreChat/assets/110412045/60d8dac4-34da-4c51-bfc3-24172fd5dbda)
