### ISSUE TITLE
[Bug]: Action Calls Failing for Different Users in Assistant. 400 Expected tool outputs for call_ids ['call_xxxxx'], got []

### ISSUE THREAD

**Issue by gloriousknight** [danny-avila/LibreChat#2284]
### What happened?

I've encountered an issue while using the assistant where if a user creates an assistant and adds actions to it, other users are unable to correctly call these actions.

The page throws an error stating:
error: [/assistants/chat/] 400 Expected tool outputs for call_ids ['call_xxxxx'], got []

Upon investigation, I noticed that the issue arises because, in the ToolService.js file, at line 270, the loadActionSets function adds the user's ID as a filter condition:
```
if (!actionSets.length) {
  actionSets =
    (await loadActionSets({
      user: client.req.user.id,
      assistant_id: client.req.body.assistant_id,
    })) ?? [];
}
```
This filtering prevents other users from using the actions. What is the rationale behind adding this filter condition? It seems like it's aimed at adding permission controls for the assistant, but in the right panel, any user can see and edit the assistant. Could you please clarify the future development direction regarding this?

### Steps to Reproduce

Step1. User A creates an assitant with action
Step2. User B uses this assitant with action, got error.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Mobile (iOS), Mobile (Android)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks for looking into this. It was originally not meant to be shared. I changed this during development and forgot to update this piece. I'm removing it now because sharing actions is the future development direction as seen in this PR: https://github.com/danny-avila/LibreChat/pull/2116
