### ISSUE TITLE
Enhancement: Support for new cohere chat model family

### ISSUE THREAD

**Issue by forestsource** [danny-avila/LibreChat#2318]
### What features would you like to see added?

New models were Command-R + by cohereand I would love to see support for them in Librechat.
specification: https://docs.cohere.com/reference/chat

### More details

For some reason unknown to us, cohere's requests use POST. This is unfortunate because the extension described in `librechat.yaml` only supports GET, resulting in an error.

```
LibreChat  | {
LibreChat  |   baseURL: "https://api.cohere.ai/v1",
LibreChat  |     modelOptions.model: "command-r-plus",
LibreChat  |     modelOptions.temperature: 1,
LibreChat  |     modelOptions.top_p: 1,
LibreChat  |     modelOptions.presence_penalty: 0,
LibreChat  |     modelOptions.frequency_penalty: 0,
LibreChat  |     // 3 stop(s)
LibreChat  |     modelOptions.stop: ["||>","\nUser:","<|diff_marker|>"],
LibreChat  |     modelOptions.user: "64b80765ede492ab9fccb5fc",
LibreChat  |     modelOptions.stream: true,
LibreChat  |     // 3 message(s)
LibreChat  |     modelOptions.messages: [{"role":"user","content":"test"},{"role":"assistant","content":"405 status code (no body)"},{"role":"user","content":"test"}],
LibreChat  | }
LibreChat  | 2024-04-05T06:11:45.007Z warn: [OpenAIClient.chatCompletion][stream] API error
LibreChat  | 2024-04-05T06:11:45.010Z error: [handleAbortError] AI response error; aborting request: 405 status code (no body)
LibreChat  | 2024-04-05T06:11:45.024Z debug: [AskController] Request closed
```
Thank you very much for all of your work!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
from a quick glance, I don't think this is the issue

> For some reason unknown to us, cohere's requests use POST. This is unfortunate because the extension described in librechat.yaml only supports GET, resulting in an error.

it is the different "chat" endpoint they are using

`v1/chat` instead of `v1/chat/completions`

I'll see if there is a quick fix for this for easy integration.
