### ISSUE TITLE
Enhancement: Option to disable password reset functionality entirely

### ISSUE THREAD

**Issue by kzar** [danny-avila/LibreChat#2326]
### What features would you like to see added?

I'd rather disable the password reset functionality entirely, since I don't need it and it's a potential vector for attack. It would be great if there was an option to disable it.

### More details

My concerns:
1. The default is the insecure password reset link, which I fear will lead to folks getting compromised.
2. The email flow leaks account emails by complaining when an incorrect email address is entered.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Will address both your concerns today if I can
