### ISSUE TITLE
Enhancement: Allow for the right sidebar to be disabled/hidden

### ISSUE THREAD

**Issue by kzar** [danny-avila/LibreChat#2336]
### What features would you like to see added?

I don't use the right sidebar, I don't have any assistants so I don't think the sidebar can be used for anything. It would be nice to be able to hide it completely.

### More details

Maybe this should happen automatically when `ENDPOINTS` in the configuration doesn't include "assistants"?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
It will be used for regular settings, not just assistants. That is just the current state of it as I iterate it, and the assistants dropdown/builder will only show when assistants is selected. Currently, you can also attach files.

![image](https://github.com/danny-avila/LibreChat/assets/110412045/e17fd2f6-732e-4959-8dd4-7525e8e86b9b)

**Comment by danny-avila** [comment]
> OK got it, thanks @danny-avila 👍

yeah i realize this produces overall better UX especially for mobile. Taking inspiration from together.ai and other playgrounds: 
![image](https://github.com/danny-avila/LibreChat/assets/110412045/7aaf89d2-db06-4a85-bf53-a12246078ed5)
