### ISSUE TITLE
Enhancement: Use avaialble API key when enabling OpenAI plugins

### ISSUE THREAD

**Issue by kzar** [danny-avila/LibreChat#2337]
### What features would you like to see added?

When enabling the OpenAI plugins like Dalle 3, it would be nice if the existing API key was used instead of it being asked for again.

### More details

Especially on mobile, at least for me the prompt appears off-screen at the top of the window and I initially though the install button had broken.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
you can set it in the .env file

```bash
# DALL·E
#----------------
# DALLE_API_KEY=
# DALLE3_API_KEY=
# DALLE2_API_KEY=
# DALLE3_SYSTEM_PROMPT=
# DALLE2_SYSTEM_PROMPT=
# DALLE_REVERSE_PROXY=
# DALLE3_BASEURL=
# DALLE2_BASEURL=
```

**Comment by kzar** [comment]
Cool OK thanks, I just wonder if would folks ever _not_ want to just use the OpenAI API key that's being used if these special options aren't set?

**Comment by danny-avila** [comment]
> Cool OK thanks, I just wonder if folks would ever _not_ want to just use the OpenAI API key that's being used if these special options aren't set?

Indeed, that was the default option for a while but it makes to separate the concern. I'm able to use DALL-E through Azure/reverse proxy this way while ensuring the OpenAI key is serving the official OpenAI API.
