### ISSUE TITLE
Enhancement: Scroll to bottom of session when switching to a different chat session

### ISSUE THREAD

**Issue by kzar** [danny-avila/LibreChat#2338]
### What features would you like to see added?

When I switch between my chat sessions, I'm often left viewing the top of the session and need to scroll down to the bottom to view the most recent messages. This is contrast to the official ChatGPT app (on Android at least), that will display the bottom of session chat right away.

### More details

Another related issue: When I send a message in a chat session on mobile, the view is often scrolled down below my message and where the response is displayed. At least for new chat sessions. I would like the message and response to be visible, so I don't need to close the keyboard and scroll up to view what's happening.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
See in settings, already implemented

![image](https://github.com/danny-avila/LibreChat/assets/110412045/3939e4d5-0220-49fa-b785-2db4279de1a1)

**Comment by kzar** [comment]
> See in settings, already implemented

Oh ace, thanks @danny-avila. Sorry I had missed that option.
