### ISSUE TITLE
[Bug]: Attachment dissapears when editing messages

### ISSUE THREAD

**Issue by HundSimon** [danny-avila/LibreChat#2345]
### What happened?

just like the title, editing message would clear the photo attached

Version: v0.7.0 [https://github.com/danny-avila/LibreChat/releases/tag/v0.7.0](url)
Deployment method: docker compose
Model used: Google Gemini

### Steps to Reproduce

1.upload a photo, llm gives a response
2.edit previous question
3.photo dissapears

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks for pointing this out, it’s a known issue but I have been thinking about addressing it
