### ISSUE TITLE
Use PNG (when submitting to API's) instead of Webp

### ISSUE THREAD

**Issue by henk717** [danny-avila/LibreChat#2346]
### What features would you like to see added?

As discussed on Discord not every backend can easily support the webp format since the libraries they depend on (In our case https://github.com/nothings/stb) do not support this format. To maximize compatibility with various backends, I recommend saving or submitting images as png instead of webp or alternatively allowing the user to choose the image format in the .env file.

### More details

This can be tested using https://koboldai-koboldcpp-tiefighter.hf.space/ which is OpenAI compatible but does not support webp at of the time of writing.

### Which components are impacted by your request?

UI, Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This is planned and should be a simple update!
