### ISSUE TITLE
[Bug]: Title Changing to "New Chat" in Assistant Mode After Second Question 

### ISSUE THREAD

**Issue by gloriousknight** [danny-avila/LibreChat#2354]
### What happened?

When using the Assistant mode, I've encountered an issue where, after the first question is answered and I proceed to ask a follow-up question, the originally generated title automatically changes to "New Chat". 

### Steps to Reproduce

1. Using Assistant with Azure
2. Ask first question and wait for generating title
3. Ask second question，and title will change to New Chat

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/34735844/80acdcdd-fdef-48d8-94da-7cd78544114a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks, this was an issue before in general but looks like it was missed for assistants somehow, will take a closer look.

**Comment by gloriousknight** [comment]
> Thanks, this was an issue before in general but looks like it was missed for assistants somehow, will take a closer look.

Thank you for your prompt response and for looking into this issue. I have checked the useSSE.ts file, but unfortunately, it did not resolve the problem. I appreciate your efforts and am looking forward to your solution. Please let me know if you need any more information from my side. Thank you.
