### ISSUE TITLE
Enhancement: Don't send message on return key for mobile

### ISSUE THREAD

**Issue by njbbaer** [danny-avila/LibreChat#2412]
### What features would you like to see added?

When using LibreChat in a mobile browser, pressing the return key should add a new line rather than send the message.

### More details

By having the return key act as send on mobile, it is very difficult to create messages with manual newlines. You can use shift-enter on desktop browsers, but that is not easy on mobile. 

The behavior of the mobile web version of ChatGPT works this way: the return key creates a new line, and I think LibreChat should match its behavior.

Due to the inconsistency I often accidentally send messages too soon. I believe this should be changed or at least made configurable. Thank you!

### Which components are impacted by your request?

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
There’s a PR open for this to toggle via settings

**Comment by njbbaer** [comment]
Wonderful! Thank you @danny-avila.
