### ISSUE TITLE
[Bug]: Profile pictures downloaded through OpenID (Entra ID) login are saved to images/openid/$ID.png but Nginx says 403 Access denied

### ISSUE THREAD

**Issue by ervet** [danny-avila/LibreChat#2425]
### What happened?

The login through Entra ID via OpenID works flawless. Images are download to ./images/openid/$GUID.png when a profile picture is available from the EntraID Tenant.  

But the images are not disabled as the avatar. Looking at Console with the browser it shows a 
![image](https://github.com/danny-avila/LibreChat/assets/38859987/a4a718ee-e801-4aea-b8e6-2ae711401e24)

Any hints ... According the docker-compose it looks like the images are loaded. 

![image](https://github.com/danny-avila/LibreChat/assets/38859987/0ee50de1-ef43-4070-88c1-4d34d7984662)

Any hints ? 

Thanks for the great tool 

### Steps to Reproduce

- Setup Entra ID 
- Login with a user who has a profile picture
- Look into the console as see if you get a 403

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ervet** [comment]
For whatever reason in the morning I did an update and this is working now - no errors.

**Comment by danny-avila** [comment]
interesting, it could be due to how microsoft and other OIDC providers differ in serving profile pics. Closing this also because it is more generally addressed by this issue: https://github.com/danny-avila/LibreChat/issues/2056
