### ISSUE TITLE
[Bug]: Can't paste text copied to clipboard unless it is plain text

### ISSUE THREAD

**Issue by Theyril** [danny-avila/LibreChat#2526]
### What happened?

Can't paste text copied from MS Word Document/Non-Plain Text after updating to 0.7.1

### Steps to Reproduce

1. I updated to from 0.7.0 to 0.7.1 (docker)
2. Attempted to copy text from a MS Word document and paste into LibreChat, but the paste does not work. Edit: It seems the issue is that the text must be plain text otherwise cannot be pasted.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Theyril** [comment]
Thank you. It still does not seem to work even after updating with this change. I am using my own separate script as a workaround for now to convert my clipboard to plain text after I copy something.

**Comment by danny-avila** [comment]
> Thank you. It still does not seem to work even after updating with this change. I am using my own separate script as a workaround for now to convert my clipboard to plain text after I copy something.

I can't reproduce it after the PR that closed this issue. If you are using docker, it looks like the build image failed, which happens from time to time, that may have been why you didn't get the update.

Once the following action run is complete, you can try updating: 
https://docs.librechat.ai/install/installation/docker_compose_install.html#updating-librechat

https://github.com/danny-avila/LibreChat/actions/runs/8826873828

**Comment by Theyril** [comment]
That did the trick! Thank you!
