### ISSUE TITLE
[Bug]: Reset password email link uses localhost

### ISSUE THREAD

**Issue by jcdiv47** [danny-avila/LibreChat#2527]
### What happened?

I deployed LibreChat with docker compose on an Ubuntu server. I was testing the reset-password service, got the email from my SMTP server set up earlier, but when I clicked the `Reset Password` button, it brings me to a link `http://localhost:3080/reset-password?token=<token>&userId=<userId>`, which of course does not work. I believe the relevant snippet is:

https://github.com/danny-avila/LibreChat/blob/ca9a0fe6294801788b11585d763d170f8c5c725d/api/server/services/AuthService.js#L162

### Steps to Reproduce

1. docker compose deploy on Ubuntu with `ALLOW_EMAL_LOGIN=true`, `ALLOW_REGISTRATION=true`
2. set up custom domain via Cloudflare
3. set up SMTP server for emails
4. register an account and try reset password

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
in your .env, try setting both to your actual domain:
```yaml
DOMAIN_CLIENT=https://example.com
DOMAIN_SERVER=https://example.com
```

**Comment by jcdiv47** [comment]
> in your .env, try setting both to your actual domain:
> 
> ```yaml
> DOMAIN_CLIENT=https://example.com
> DOMAIN_SERVER=https://example.com
> ```

Apologies...You are right I forgot to add these two lines.
