### ISSUE TITLE
[Bug]: The input box must be pasted with plain text

### ISSUE THREAD

**Issue by jingyaogong** [danny-avila/LibreChat#2528]
### What happened?

When I copy code from an IDE like PyCharm, the original format cannot be pasted into the chat input box. I must use Ctrl+Shift+V to paste it in plain text form, otherwise there will be no response

### Steps to Reproduce

When pasting non pure text into an input box, such as the code copied by pychar

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I downloaded PyCharm to confirm this is now closed by https://github.com/danny-avila/LibreChat/pull/2530

Thanks for reporting this.
