### ISSUE TITLE
[Bug]: Update dotenv.md to show correct ShuttleAI key label

### ISSUE THREAD

**Issue by acourter27** [danny-avila/LibreChat#2550]
### What happened?

The documentation currently shows SHUTTLEAI_KEY, but the configuration requires SHUTTLEAI_API_KEY. Changing this in the .env fixes the issue. 

Documentation should be updated to clear up confusion.

### Steps to Reproduce

https://github.com/danny-avila/LibreChat/blob/main/docs/install/configuration/dotenv.md

![image](https://github.com/danny-avila/LibreChat/assets/47721365/3857254e-a87f-47ce-9bb9-1ce14ed81072)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
The latest .env.example is already updated with the correct value

![image](https://github.com/danny-avila/LibreChat/assets/32828263/aa706c94-5bfc-4a61-82fa-5f2f21304751)

![image](https://github.com/danny-avila/LibreChat/assets/32828263/a0c9212b-a3fd-4ea3-b5bb-7d922209b77d)

**Comment by acourter27** [comment]
In the example, but not the documentation. Can it be updated there too? Or has that just not been pulled in yet?

**Comment by fuegovic** [comment]
ohhh, I see, in the dotenv doc!

yeah, I forgot to update it there, it's up to date in thei other doc tho:
https://docs.librechat.ai/install/configuration/ai_endpoints.html#shuttleai

I'll update the docenv.md, thanks!
