### ISSUE TITLE
Enhancement: System prompts preset in the backend configuration

### ISSUE THREAD

**Issue by TheValkyrja** [danny-avila/LibreChat#2568]
### What features would you like to see added?

System prompts are now solely provided by the user. User permissions for system prompts can be added in the settings configuration, as well as pre-system prompts that are permanently added in any scenario.

### More details

In some specific deployment scenarios, deployers may wish to limit system prompt to regulate the behavior of each endpoints in their projects.

The following are possible configuration items and examples of expected behavior:

_`OPENAI_REVERSE_PROXY=https://proxy.example.com`_
> This line is only a reference of others config 

`OPENAI_SYS_PROMPT_ACCESS=default/preset_only`
> This line controls if user has the access to system prompt. 
>When sets to default, user is allowed to access the Input box of system prompt. while setting to preset_only, the input box is disabled and invisible to user and user's system prompt will be fix to be empty.

`OPENAI_SYS_PROMPT_PRESET="you are a helpful assistant"`
> This line sets the preset of syetem prompt.

The actual system prompt of the calling request will be `SYSTEM_PROMPT_PRESET` + \n + user's system prompt. when both setting is empty, send no system prompt.

### Which components are impacted by your request?

General

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Closing in favor of https://github.com/danny-avila/LibreChat/issues/1617 which I'm actively working on at the moment
