### ISSUE TITLE
[Bug]: The Ctrl + V shortcut to paste text copied from IDEA isn't working

### ISSUE THREAD

**Issue by Nihisil** [danny-avila/LibreChat#2615]
### What happened?

Nothing happens when I try to paste text copied from IntelliJ IDEA.

### Steps to Reproduce

1. Open IntelliJ IDEA
2. Copy any text
3. Paste into LibreChat

### What browsers are you seeing the problem on?

This issue occurs in both Firefox and Chrome on a Linux host.

It was working fine with version 0.7.0, so I suspect something went wrong with this commit: https://github.com/danny-avila/LibreChat/commit/692ce3b346b56b60cc0b870c3a5d83173a13e8a9

Also, I haven't found any other issues with copying text. It only seems to happen with IntelliJ IDEA for me.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Hi @Nihisil thanks for the report

This has been fixed already here: https://github.com/danny-avila/LibreChat/pull/2530

I confirmed by successfully downloading IntelliJ IDEA and pasting content from there: 
![image](https://github.com/danny-avila/LibreChat/assets/110412045/9c683ee9-3b19-48ee-a381-e136f6189e7b)

**Comment by danny-avila** [comment]
Will be cutting another release by end of weekend, so if you are updating by tag release, it will be out very soon!

**Comment by Nihisil** [comment]
Ah, I'm glad to hear that it was fixed already. Thank you!
