### ISSUE TITLE
[Bug]: @ command selection effect problem under light theme

### ISSUE THREAD

**Issue by magicdmer** [danny-avila/LibreChat#2668]
### What happened?

In the light theme, you can't see the selected shadow effect, so you can't know which option is selected
![image](https://github.com/danny-avila/LibreChat/assets/5556368/7b4db330-a1d3-4039-9a98-ef18ac5b2b76)

### Steps to Reproduce

Input @ under light theme, you can't find which item be selected

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by magicdmer** [comment]
Is it solved? 

I git pull and docker-compose pull and docker-compose up

The problems still exist

**Comment by danny-avila** [comment]
> Is it solved?
> 
> I git pull and docker-compose pull and docker-compose up
> 
> The problems still exist

it is, ensure you have the latest commit with `git log`

if not, use `git fetch origin`

**Comment by danny-avila** [comment]
@magicdmer sorry about that, missed one item, it's merged now, the docker image may need about 20 minutes to build: https://github.com/danny-avila/LibreChat/pull/2675

**Comment by magicdmer** [comment]
> @magicdmer sorry about that, missed one item, it's merged now, the docker image may need about 20 minutes to build: #2675

check ok
