### ISSUE TITLE
Doc: add a bit more details to help run RAG_API locally using ollama

### ISSUE THREAD

**Issue by mjh-sakh** [danny-avila/LibreChat#2671]
### What features would you like to see added?

The proposal is to update the doc to include one more env variable `OLLAMA_BASE_URL ` to help run rag_api locally.

### More details

Current description provides almost all references to do RAG embeddings locally using ollama. The guide is focused on running RAG_API inside docker. It makes `OLLAMA_BASE_URL` env variable essential and may be easily missed. Providing it right away helps to save users time. 

### Which components are impacted by your request?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mjh-sakh** [comment]
[PR](https://github.com/LibreChat-AI/librechat.ai/pull/9) is in place (not sure if it is picked up automatically)

**Comment by fuegovic** [comment]
I'll review your PR soon, thanks!

**Comment by fuegovic** [comment]
> [PR](https://github.com/LibreChat-AI/librechat.ai/pull/9) is in place (not sure if it is picked up automatically)

Merged, Thanks again!
[/rag_api#configuration](https://www.librechat.ai/docs/configuration/rag_api#configuration)

**Comment by hulkds** [comment]
If RAG API service cannot communicate with Ollama service and cause this error **on Linux**:
```
rag_api           | 2024-07-15 15:19:07,918 - root - ERROR - Error raised by inference endpoint: HTTPConnectionPool(host='host.docker.internal', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70420aba7310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
rag_api           | 2024-07-15 15:19:07,919 - root - INFO - Request POST http://rag_api:8000/embed - 200
LibreChat         | 2024-07-15 15:19:07 error: Error embedding file File embedding failed.
LibreChat         | 2024-07-15 15:19:07 error: [/files] Error processing file: File embedding failed.
```
Consider adding **extra_hosts** in the rag_api service in docker-compose.override.yml file:

```
extra_hosts:
  - "host.docker.internal:host-gateway"
```

PR for the librechat.ai docs: https://github.com/LibreChat-AI/librechat.ai/pull/92
