### ISSUE TITLE
Enhancement: Hide arbitrary plugins in the Plugin store

### ISSUE THREAD

**Issue by shota1998** [danny-avila/LibreChat#2688]
### What features would you like to see added?

In the Plugin store, I want to set the visibility (show/hide) of individual plugins.

### More details

This tool is being used within my company.
From a governance perspective, there are plugins that we don't want employees to use.
We only want to display the plugins in the Plugin store that we allow employees to use.

### Which components are impacted by your request?

UI, Plugins

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Farkie** [comment]
https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/config#filteredtools

you can do this already in the librechat.yml

**Comment by danny-avila** [comment]
> https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/config#filteredtools
> 
> you can do this already in the librechat.yml

Yes, and I meant to add `includedTools` originally and is now being added. Instead of filtering, you can just specify the ones you want; use whichever option is convenient to you (but not both)

New docs will be updated shortly after merging
