### ISSUE TITLE
[Question]: Inquiry on the Availability of ver GPT-4o API 

### ISSUE THREAD

**Issue by rdbox** [danny-avila/LibreChat#2693]
### What is your question?

I am writing to enquire about the roadmap for the GPT API, specifically regarding the release of a GPT-4o version.  the capabilities of the GPT models are critical to the progress and efficiency of my projects.

Please give as many details as possible:
I have been utilizing the current version available, and I'm eager to understand what improvements and new features GPT-4 will bring. 

### More Details

If there is a timeline or any planned release date for GPT-4o, as well as details on how we can prepare to integrate the new API version, it would be immensely helpful.

 
The main subject of my question is the release schedule and feature set of the upcoming GPT-4o API.

### What is the main subject of your question?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rdbox** [comment]
@danny-avila 
https://huggingface.co/spaces/LibreChat/LibreChat use this service, but so far I don't see anything updated in the models here.

**Comment by danny-avila** [comment]
> @danny-avila https://huggingface.co/spaces/LibreChat/LibreChat use this service, but so far I don't see anything updated in the models here.

you will have to wait until the HF space is updated, then.

**Comment by fuegovic** [comment]
> @danny-avila https://huggingface.co/spaces/LibreChat/LibreChat use this service, but so far I don't see anything updated in the models here.

I need to manually update the model list on our demo. I'm outside now but will take care of this when I'm back

**Comment by fuegovic** [comment]
@rdbox It should be live now!

Also, small tip, use one of these URLs to access it and you will not be logged out every time you refresh the page: 
https://demo.librechat.cfd/
https://librechat-librechat.hf.space/
