### ISSUE TITLE
[Bug]: Unable to create or use assistants with gpt-4o

### ISSUE THREAD

**Issue by kneelesh48** [danny-avila/LibreChat#2711]
### What happened?

When trying to create or use assistants with gpt-4o, it should 500 internal server error

### Steps to Reproduce

Create a new assistant with gpt-4o as the model

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Already known, the 500 error is for using Assistants v1. Closing this in favor of https://github.com/danny-avila/LibreChat/issues/2490
