### ISSUE TITLE
[Bug]: The dropdown menu for modelSpecs is behaving abnormally in the mobile view with Chinese language settings

### ISSUE THREAD

**Issue by RedwindA** [danny-avila/LibreChat#2730]
### What happened?

The text in this area is erroneously displayed vertically, obstructing both the text and buttons in the chat area during conversations

### Steps to Reproduce

1. Switch to mobile device view (using phone or devtools)
2. Select language as Chinese

### What browsers are you seeing the problem on?

Microsoft Edge

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/128586631/e92746b3-96e2-46e8-aa3c-1cb6e1cfa946)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RedwindA** [comment]
Thank you for your quick fix! But I've just noticed that this anomaly also occurs in the endpoint button region

**Comment by danny-avila** [comment]
Thanks, I'll apply the same styling soon
