### ISSUE TITLE
Enhancement: Add a manifest.json file so that LibreChat can become a Chrome App

### ISSUE THREAD

**Issue by barronlroth** [danny-avila/LibreChat#2733]
### What features would you like to see added?

[Adding a manifest.json file](https://web.dev/articles/add-manifest) will allow us to define certain components of Chrome apps, and allow Librechat to become a Chrome app via Save & Share -> Create Shortcut

### More details

n/a

### Which components are impacted by your request?

General

### Pictures

<img width="939" alt="Screenshot 2024-05-07 at 1 33 51 PM" src="https://github.com/danny-avila/LibreChat/assets/5567884/c2170c16-c975-4b18-a1a6-db327eec6b86">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
It's already enabled afaik, I have the option to "install" LibreChat in both Chrome and ms Edge

![image](https://github.com/danny-avila/LibreChat/assets/32828263/13658df0-d2ac-4087-b2b2-4d71d09793d3)

**Comment by barronlroth** [comment]
@fuegovic Interesting, I do not. Historically I've used `Create shortcut` button to make these, but clicking it does nothing for me and my colleagues.

**Comment by fuegovic** [comment]
@barronlroth the option has been added about a month ago I believe. Make sure the librechat deployment you're trying to add is updated.

Try visiting our demo, it gives me the option to install it: https://demo.librechat.cfd/

**Comment by danny-avila** [comment]
Can confirm this is in fact working on the latest version: 
![image](https://github.com/danny-avila/LibreChat/assets/110412045/38dcc6ac-2405-4ae9-b462-631dbe826625)

**Comment by fuegovic** [comment]
I can confirm it works as expected in MacOS (tested with Safari, Edge, and Chrome)
![Screenshot 2024-05-21 at 11 57 41 AM](https://github.com/danny-avila/LibreChat/assets/32828263/e3ff0591-d9ae-40a9-af52-6949dfd7db57)
