### ISSUE TITLE
[Bug]: Issue exporting conversation with Assistants

### ISSUE THREAD

**Issue by SiddharthaKambampati** [danny-avila/LibreChat#2756]
### What happened?

Actual : Once you have a conversation with any assistant and export the chat to any available format, the exported artifact doesn't contain any conversation. It only contains the first user prompt and no subsequent messages.

Expected : Expected to view all chats in the exported artifact history.

PS This issue is only for assistants chat exports and other providers chat exports are working as expected.

### Steps to Reproduce

1. Select any assistants and chat with it.
2. Export the convo
3. Open the exported artifact and notice that it doesn't contain chat history. It only contains header and options and empty history.

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
It's a known issue, but thanks for making a post to track it.
