### ISSUE TITLE
[Bug]: Markdown Syntax Included in Copied Search Results

### ISSUE THREAD

**Issue by RedwindA** [danny-avila/LibreChat#2780]
### What happened?

When using LibreChat's search feature, the search results correctly highlight the search terms in bold. However, when copying the search results using the provided copy button, the copied text erroneously includes the Markdown syntax for bold (**), which should not be present in the copied content.

### Steps to Reproduce

1. Open LibreChat and use the search feature to search for a specific term.
2. Observe that the search term is highlighted in bold in the search results.
3. Click the copy button to copy the search result.
4. Paste the copied text into any text editor or input field.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
The search results are emboldened because they literally have the markdown syntax for bold. I suppose I can remove the bold effect entirely

**Comment by RedwindA** [comment]
> The search results are emboldened because they literally have the markdown syntax for bold when retrieved from meilisearch. I suppose I can remove the bold effect entirely

Thank you, it would be great if it could be removed, as I need to quickly copy the previous prompt and do not want LLM to be affected by unexpected markdown syntax
