### ISSUE TITLE
[Bug]: Command+Click doesn't open a new tab on MacOS

### ISSUE THREAD

**Issue by eshack94** [danny-avila/LibreChat#2784]
### What happened?

**NOTE**: This is a very low priority bug report, non-urgent.

**Expectation**:
* Librechat on MacOS (regardless of browser) opens links in a new tab if they're clicked while holding the "command" key.

**Outcome**:
* Librechat on MacOS does not open a new tab when links are clicked while holding "command" key.

**Other Info**:
* Others have said that "ctrl + click" within Windows works as-expected, but have not personally verified. This would indicate that it's an issue with the `metaKey` (command key) being detected and maybe some conditionals need updating (unsure though, might be something else).

### Steps to Reproduce

1. Be on MacOS.
2. Make sure LibreChat is running.
3. Open any web browser.
4. Log into local LibreChat instance.
5. Click any clickable link while holding down "command" (meta key).

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Relevant log output

```shell
N/A
```

### Screenshots

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eshack94** [comment]
I'm testing a proposed fix, if it works I'll open a PR and link to this bug report.

**Comment by eshack94** [comment]
Opened a PR which fixes this: https://github.com/danny-avila/LibreChat/pull/2786

**Comment by danny-avila** [comment]
thanks lgtm, wouldn't have been able to test on mac myself 🙏
