### ISSUE TITLE
[Question]: How to prevent a Huggingface deployment from logging me out every refresh?

### ISSUE THREAD

**Issue by alexlyzhov** [danny-avila/LibreChat#2789]
### What is your question?

I set up a huggingface deployment exactly according to the instructions, but every time the page is refreshed it logs me out. This makes it unusable for me, especially from mobile: page is refreshed every time I open it, login time is 10s and involves a complex workflow with a password manager. I wonder if there's an edit to the Huggingface space I can make.

### More Details

https://www.librechat.ai/blog/2024-05-16_unsecured_http instructs to override `docker-compose.yml `which I can do on my local deployment, but not on huggingface as it doesn't seem to have docker compose configs. I tried editing CMD at the end of Dockerfile to `CMD ["npm", "run", "backend:dev"]`, I'm not sure if this should accomplish the same thing as a docker-compose override, probably not? And indeed it didn't work.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexlyzhov** [comment]
Experimenting with SESSION_EXPIRY and REFRESH_TOKEN_EXPIRY didn't help me here.

**Comment by fuegovic** [comment]
See the conclusion, you need to use the URL without the huggingface website overlay:
https://www.librechat.ai/docs/remote/huggingface#conclusion

**Comment by alexlyzhov** [comment]
This worked, thanks!

**Comment by alexlyzhov** [comment]
I started using the direct space URL. Since then, I have another problem with huggingface deployment that made it very difficult to use the space.

I use their free hardware (cpu basic) and the space "goes to sleep" after a certain time. When that happens, I have to first go to the URL with the huggingface overlay to "wake it up" and _only then_ go to the direct URL.

They write:
> Your Space will automatically be paused after 48h of inactivity.

However, in practice, it always go to sleep after ~4-6h of inactivity. This means that I have to go to the version with overlay to wake the space up and then to go to the version w/o overlay to use it, multiple times per day.

Is this the case for everyone and not just me? If yes, maybe it should not be advertised in librechat docs as a free option?

**Comment by danny-avila** [comment]
> Is this the case for everyone and not just me? If yes, maybe it should not be advertised in librechat docs as a free option?

I don't see why it shouldn't be recommended. While annoying, it's perfectly reasonable for HF to do this. Server cold starts are a pretty common practice for free/cheap tier servers, as they would be warm if you were getting traffic. 

Alternatively, use Digital Ocean & voila, no cold starts: https://www.librechat.ai/docs/remote/digitalocean
