### ISSUE TITLE
[Bug] Only recursive JSON is supported for Conversation Import

### ISSUE THREAD

**Issue by AetherMagee** [danny-avila/LibreChat#2794]
### What is your question?

So there's this "Export conversation" button, right? When setting the file type to .json, this function, among other things, provides you with an option to disable recursiveness for the export, which decreases the output file size.
Then, if you try to go to Settings > Data controls and use "Import conversations from a JSON file", it will only work if you selected "recursive" instead of "sequential" when exporting. Why?

### More Details

> Please provide more details **if needed.**

> Fields marked with an asterisk (*) are required.

sure bro

### What is the main subject of your question?

UI, Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
It's not intended. Thanks, looking into it.
