### ISSUE TITLE
Enhancement: Support Weaviate as a vector database

### ISSUE THREAD

**Issue by shota1998** [danny-avila/LibreChat#2826]
### What features would you like to see added?

Users can chose Weaviate as a vector database.

### More details

Weaviate is an oss vector database.

Weaviate offers APIs.
https://weaviate.io/developers/weaviate/api/rest#description/introduction

merit:
Users can separate the creation and management of vector data from other elements in chat application development.

### Which components are impacted by your request?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
PRs welcome in the rag_api repo https://github.com/danny-avila/rag_api/issues
