### ISSUE TITLE
Enhancement: let users add their own endpoints

### ISSUE THREAD

**Issue by soyelmismo** [danny-avila/LibreChat#2827]
### What features would you like to see added?

I know we can set a fixed reverse proxy in .env file... But it could be great if we can add our own reverse proxy (in user level) to use a customized endpoint per agent preset, cuz alternative API proxies are popular and so useful.

### More details

So yeah, basically a place to add custom endpoint and it's API key per custom agent, it's mostly for "power users" who knows how the custom endpoint works

### Which components are impacted by your request?

UI, Endpoints

### Pictures

![Screenshot_20240522-045203_Firefox](https://github.com/danny-avila/LibreChat/assets/123757457/df742eae-86ee-4a6b-866c-bcbc24deeee3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spinagon** [comment]
This is already possible via librechat.yaml https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/custom_endpoint

**Comment by soyelmismo** [comment]
> This is already possible via librechat.yaml 


Mmm is it only the ones added in that file? Like added by the admin and not by user? Or is there some way to let the user create it's personal ones? I think librechat.yaml method is only the ones allowed by the admin 🤔

**Comment by spinagon** [comment]
Oh, I only thought of self-hosting use, where admin and user are the same people.

**Comment by danny-avila** [comment]
This is already supported:

![image](https://github.com/danny-avila/LibreChat/assets/110412045/14bf3cf6-8604-490a-b6a7-ed6de348e673)

Using the librechat.yaml file:

```yaml
endpoints:
  custom:
    - name: "UserEndpoint"
      apiKey: "user_provided"
      baseURL: "user_provided"
      models:
        default: ["gpt-4o"]
      titleConvo: true
```

The only thing is, it won't fetch models, so you have to define the models list. This will be implemented though.

**Comment by SmartManoj** [comment]
> `baseURL: "user_provided"`

only works if `apiKey: "user_provided"`? Is it by design?
