### ISSUE TITLE
Enhancement: Ability to toggle on/off right-hand sidebar

### ISSUE THREAD

**Issue by Tanvez** [danny-avila/LibreChat#2835]
### What features would you like to see added?

The right-hand sidebar controls has multiple controls to collapse the right-hand sidebar and multiple levels of collapse. Would like to see the option to disable the right-hand sidebar.

### More details

The controls can be confusing to new users of the application so we want to minimize any complicated interactions e.g. multi-level collapse functionality

### Which components are impacted by your request?

UI

### Pictures

![image](https://github.com/danny-avila/LibreChat/assets/29421667/5248b055-1b15-4a88-8097-f729a81fdeb1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This is already implemented.
![image](https://github.com/danny-avila/LibreChat/assets/110412045/0528c45a-b19e-479c-9daa-5dfb85da0a7a)


Also on a global level:
https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/interface#sidepanel

Note, more settings/utilities will added to the side panel, for all endpoints, such as prompts to name one.

**Comment by Tanvez** [comment]
Awesome! Thanks for the quick reply!
