### ISSUE TITLE
[Bug]: NotAllowedError on safari when using external TTS

### ISSUE THREAD

**Issue by Meshkati** [danny-avila/LibreChat#2846]
### What happened?

On safari, when I click on the "read aloud" button of a message, I get the following error on librechat
```
Error playing audio: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
```
and this error on console:
```
NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
```

There is no problem on chrome.

### Steps to Reproduce

1. Click on "Read aloud" option

### Relevant log output

```shell
NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
The tts/stt features are only expected to work on Chrome right now, so you can try using chrome for expected functionality.

Firefox has a separate issue as well. I'm not sure when I'll be able to test Safari since I don't have a mac, would have to pay for a remote mac service.
