### ISSUE TITLE
[Bug]: stt: List of Voices shows empty

### ISSUE THREAD

**Issue by kneelesh48** [danny-avila/LibreChat#2849]
### What happened?

Opening Speech tab in Settings, the voices dropdown is empty

Only tried on Google Chrome on Windows, Mac and Android

### Steps to Reproduce

1. Click on your profile picture > Settings
2. Go to Speech tab
3. Scroll down to Voice in Text to Speech section

### What browsers are you seeing the problem on?

Chrome

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/25109737/930165d3-a09b-4bf1-87bd-4c2eed584e70)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kneelesh48** [comment]
Fixed after changing voice to voices in librechat.yml

tts:
  openai:
    apiKey: '${TTS_API_KEY}'
    model: 'tts-1'
    voices: ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer']

**Comment by Qin-shun-Li** [comment]
I have the same problem.
But my librechat.yaml is the same as you
<img width="871" alt="image" src="https://github.com/danny-avila/LibreChat/assets/128322806/a24b60cd-fbfe-46f2-8b19-d575e374b18e">
<img width="1313" alt="image" src="https://github.com/danny-avila/LibreChat/assets/128322806/4c0e6947-0b3e-4be9-94b4-20bccebf6aa7">

**Comment by danny-avila** [comment]
This was resolved on the latest commit
