### ISSUE TITLE
[Bug]: Your account has been temporarily banned due to violations of our service.

### ISSUE THREAD

**Issue by kneelesh48** [danny-avila/LibreChat#2851]
### What happened?

I'm getting this message when logging in

Your account has been temporarily banned due to violations of our service.

Please tell me how I can fix this

### Steps to Reproduce

1. Go the the page and try to login

### What browsers are you seeing the problem on?

Chrome on Windows

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/25109737/62222bf6-8fda-44e3-9ddb-c10c6c6899a5)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
https://github.com/danny-avila/LibreChat/discussions/1980

**Comment by mansiibm** [comment]
Hey what to do if the user is not present in the logs also? My db's logs does not have the particular user so how can I let him?

**Comment by danny-avila** [comment]
> Hey what to do if the user is not present in the logs also? My db's logs does not have the particular user so how can I let him?

At this point, the server should be restarted. Some management tools for this on the frontend coming out soon!
