### ISSUE TITLE
[Bug]: Partial response displayed with "Continue" button in gpt-4-vision-preview

### ISSUE THREAD

**Issue by ssuzuki-github** [danny-avila/LibreChat#2884]
### What happened?

Upon selecting gpt-4-vision-preview and initiating a chat, version v0.7.1 displays the full response without interruption. However, in version v0.7.2, a "Continue" button appears, interrupting the response. Pressing the "Continue" button then shows the remaining part of the response. I expected the behavior to be consistent with v0.7.1 where the full response is shown without needing additional interaction.

### Steps to Reproduce

1. Select gpt-4-vision-preview
2. Start a chat session.
3. Observe that the response is interrupted by a "Continue" button.

### What browsers are you seeing the problem on?

Microsoft Edge

### Screenshots

![v0 7 1](https://github.com/danny-avila/LibreChat/assets/70100948/2f5dca5f-3d81-4d19-ad38-0ecd7d26b73c)
![v0 7 2](https://github.com/danny-avila/LibreChat/assets/70100948/45955361-a702-49b3-939f-848157d73c05)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This is the second time this is reported, both times with Azure. There's no apparent change that would cause this, but I'm currently triaging the issue. So far with OpenAI (non-azure), seems fine:

![image](https://github.com/danny-avila/LibreChat/assets/110412045/c1cdca43-f894-4f37-9f5c-3e8571e53c4a)

**Comment by danny-avila** [comment]
For now, you can follow the instructions I gave in the other report, which seems to work when manually passing max output tokens: https://github.com/danny-avila/LibreChat/discussions/2875#discussioncomment-9569747
