### ISSUE TITLE
[Bug]: Can't delete the uploaded document file

### ISSUE THREAD

**Issue by magicdmer** [danny-avila/LibreChat#2899]
### What happened?

Version : 0.7.2

I uploaded some documents like main.c, kmdf-doc.pdf , when I used the file manager of librechat to delete them and refresh the page, they re-appeared again, the deletion failed. If I delete a picture file, it can be deleted normally.

After investigation, I found that those undeletable files have the following common features, the `filepath` and `source` are both `vectordb`

### Steps to Reproduce

1. Upload some document like txt, source file or pdf
2. Use file manager delete it
3. Refresh page and find it

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This has been fixed on the latest build

**Comment by danny-avila** [comment]
https://github.com/danny-avila/LibreChat/discussions/2822
