### ISSUE TITLE
Enhancement: Conversation Starters

### ISSUE THREAD

**Issue by nolandubeau** [danny-avila/LibreChat#2909]
### What features would you like to see added?

Ability to display conversation starters "pills/blocks" which inherit from instructions / instruction overrides / or from assistant instructions, similar to the conversation starters in custom GPT's.  If possible provide the ability to add inline "pills/blocks" mid conversation as part of a user guidance framework. The former, conversation starters, would be the priority.

### More details

I'm not able to upload a photo from my corporate account, sorry. But just look at any custom gpt or even the opening screen of chat-gpt and you'll see the conversation starter options.

### Which components are impacted by your request?

UI

### Pictures

I'm not able to upload a photo from my corporate account, sorry. But just look at any custom gpt or even the opening screen of chat-gpt and you'll see the conversation starter options.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
closing in favor of https://github.com/danny-avila/LibreChat/issues/3023
