### ISSUE TITLE
Enhancement: show faulty model name and ban reason in logs

### ISSUE THREAD

**Issue by KiGamji** [danny-avila/LibreChat#2910]
### What features would you like to see added?

Replace "error: [handleAbortError] AI response error; aborting request:" to "error: [handleAbortError] {model} response error; aborting request: {error}".
So, with gpt-4-turbo, it would be: "error: [handleAbortError] gpt-4-turbo response error; aborting request: {error}". This makes it easier to find and debug problems without having to wait for users to report issues.

Add ban reason to ban log entry, and replace the user hash or whatever it is to user's username.
so "info: [BAN] Banning user {user_hash?} @ {IP} for {time}" would be "info: [BAN] Banning user {username} @ {IP} for {time}. Reason: {reason}".

### Which components are impacted by your request?

Other

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by KiGamji** [comment]
huh??

**Comment by AetherMagee** [comment]
ah yes, i love not knowing who or what exactly caused the issue
