### ISSUE TITLE
[Bug]: Setting interface->parameters to false disables Plugin Store

### ISSUE THREAD

**Issue by charltondj** [danny-avila/LibreChat#2947]
### What happened?

In librechat.yaml, I disabled the parameters feature. When in the Plugins section, the Plugin Store becomes inaccessible. 

### Steps to Reproduce

1. Add the following to librechat.yaml:
```
interface:
  parameters: false
```
2. Restart
3. Choose 'Plugins' Endpoint
4. Choose 'Plugin Store'

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Hi, thanks for the report. It’s not a bug, the plugins are technically part of the parameters
