### ISSUE TITLE
Enhancement: CTRL+ENTER improvements

### ISSUE THREAD

**Issue by rcdailey** [danny-avila/LibreChat#2962]
### What features would you like to see added?

When disabling "Enter to send" in the account options, there's some interesting issues:

1. Using SHIFT+ENTER actually enters two newlines, instead of just 1
2. CTRL+ENTER enters a newline, instead of sending the message. The only way to send the message is to click the send button; and personally, I find having to move my hands away from the keyboard to do something like this to be very disruptive and slow.

My expectation is that when disabling enter to send, the user experience should be as follows:

1. Pressing SHIFT+ENTER has no change in behavior; it should enter 1 newline
2. Pressing ENTER by itself should enter a single newline
3. Pressing CTRL+ENTER should send the message.

### More details

No additional details at this time.

### Which components are impacted by your request?

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rcdailey** [comment]
@danny-avila I want to say that after having used this for a while, I really love this improvement. It was enough to keep me on LibreChat (I was using Open WebUI before, and while it is also a great piece of software, without this QoL feature I enjoy LibreChat much more!).

Instead of opening a new issue, I thought I'd mention it here: I think CTRL+ENTER should also work when editing an existing chat message. That way I don't need to move my hand to my mouse to click the save & submit button. If you'd like me to open a separate issue for this let me know.

Thanks again for the great work!

**Comment by danny-avila** [comment]
> Instead of opening a new issue, I thought I'd mention it here: I think CTRL+ENTER should also work when editing an existing chat message. That way I don't need to move my hand to my mouse to click the save & submit button. If you'd like me to open a separate issue for this let me know.

Thanks! Feel free to open a new issue, as it will be easier to track.
