### ISSUE TITLE
[Bug]: Need to report a minor security vulnerability

### ISSUE THREAD

**Issue by kurtseifried** [danny-avila/LibreChat#2963]
### What happened?

Hi, I'd like to report a minor security issue, but going through https://github.com/danny-avila/LibreChat/security the option 1 link is 404, so I'm using option 2. 

Also at https://github.com/danny-avila/LibreChat/issues/new/choose links to the policy but does not allow filing of security issues publicly or privately.

### Steps to Reproduce

Left blank as per "However, please note that initial contact through GitHub Issues should not include any sensitive details."

### Relevant log output

```shell
Left blank as per "However, please note that initial contact through GitHub Issues should not include any sensitive details."
```

### Screenshots

Left blank as per "However, please note that initial contact through GitHub Issues should not include any sensitive details."

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
We need to fix these links, in the meantime you can email at contact@librechat.ai to initiate a private discussion on the subject

**Comment by kurtseifried** [comment]
Email sent, thanks.

**Comment by danny-avila** [comment]
Thank you @kurtseifried will work on the resolution this week
