### ISSUE TITLE
[Bug]: sanitizing formatted text by default

### ISSUE THREAD

**Issue by leondape** [danny-avila/LibreChat#3019]
### What happened?

When pasting large texts, it takes a long time to paste. 
This most likely has to do with how formatted text is handled by the browser. 
The issue persists with chrome and edge. Safari is fine. 

Pasting unformatted text via right-click or keybinding fixes the issue. 

A more global fix would be to remove formatting for all pastes: https://stackoverflow.com/questions/24831286/removing-rich-text-formatting-for-copy-paste-cross-browser

However I don't know if that is more efficient. 

### Steps to Reproduce

1. copy large formatted text (from a pdf for example)
2. paste it into the chat
3. wait many seconds for it to complete

quick fix:
1. copy large formatted text (from a pdf for example)
2. paste it into the chat via cmd+shift+V or right-click: "paste without formatting" or "paste and adjust formatting to target"
3. text is pasted instantly

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks for confirming it happens on Chrome. I thought I fixed this in https://github.com/danny-avila/LibreChat/pull/2530 but there may be something else going on

**Comment by danny-avila** [comment]
I have a fix for this as long as it works on most browsers as well
