### ISSUE TITLE
Enhancement: OpenId Configuration http proxy support

### ISSUE THREAD

**Issue by schnaker85** [danny-avila/LibreChat#3041]
### What features would you like to see added?

Currently, the openid configuration does not allow to set a http proxy, nor the `PROXY`, `HTTP_PROXY`, `HTTPS_PROXY` environment variable is taken into account.

This results in the error msg if no connection can be established directly:
`
{"level":"error","message":"[openidStrategy] outgoing request timed out after 3500ms","name":"RPError","stack":"RPError: outgoing request timed out after 3500ms\n    at /app/node_modules/openid-client/lib/helpers/request.js:140:13\n    at async Issuer.discover (/app/node_modules/openid-client/lib/issuer.js:143:22)\n    at async setupOpenId (/app/api/strategies/openidStrategy.js:69:20)","timestamp":"2024-06-12T08:07:29.863Z"}
`

We would like to be able to configure a dedicated proxy for the OPENID integration or use the existing `PROXY` environment variable.

A suitable solution could also be to have a new configuration variable `OPENID_PROXY=my-proxy:8080` to be independent of the other `PROXY` settings.

### More details

The code could be enhanced at [openIdStrategy.js](https://github.com/danny-avila/LibreChat/blob/08b8ae120ecaf282ec2ca91f59569cd32990a374/api/strategies/openidStrategy.js#L71)

Using the proposed configuration of the [node-openid-client](https://github.com/panva/node-openid-client/blob/main/docs/README.md#customizing-individual-http-requests) docs.

```
// use HTTP(S)_PROXY
// https://nodejs.org/api/http.html#httprequesturl-options-callback
// e.g. using https://www.npmjs.com/package/proxy-agent
// result.agent = agent;
```

We did also consider the the solution of the [discussion 1264](https://github.com/danny-avila/LibreChat/discussions/1264), but we can not / do not want rebuild the project.

I would love to provide a Pull-request for this feature but I am not able to provide javascript code.

### Which components are impacted by your request?

General, Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by btribonde** [comment]
Hello,
I have exactly the same issue.

What i did change (but still unable to confirm it is working as expected due to internal issues).

Line 5 ->

(-) `const { Issuer, Strategy: OpenIDStrategy} = require('openid-client');`
(+) `const { Issuer, Strategy: OpenIDStrategy, custom } = require('openid-client');`

Line 71 ->

(+)
```
    if (process.env.PROXY) {
        const proxyAgent = new HttpProxyAgent(process.env.PROXY);
        custom.setHttpOptionsDefaults({
            agent: proxyAgent
        });
    }
```

Using docker-compose, it seems we can override the file without needing to build the project so easy to try.

For services -> api:

```
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
      - ./images:/app/client/public/images
      - ./logs:/app/api/logs
      - **./openidStrategy.js:/app/api/strategies/openidStrategy.js**
```


I would be happy to know if it works for you.

Regards

**Comment by schnaker85** [comment]
@btribonde perfect thanks a lot! We tried it on the rc-1 release and it works perfectly. Thanks for your contribution.
