### ISSUE TITLE
Enhancement: azure assistant add file_search

### ISSUE THREAD

**Issue by wupengfei0904** [danny-avila/LibreChat#3110]
### What features would you like to see added?

azure assistant add file_search

### More details

The azure api version 2024-05-01-preview already supports a file search tool

### Which components are impacted by your request?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Exioness** [comment]
any progress on this?

**Comment by danny-avila** [comment]
Just realized this is a duplicate: https://github.com/danny-avila/LibreChat/issues/2490

> any progress on this?

No progress but it is planned

**Comment by leadergxg2020** [comment]
May I ask when this plan will be implemented? We also use Azure and are very much looking forward to having support for the Azure Assistant as soon as possible. Thank you.
