### ISSUE TITLE
Enhancement: It should be possible to disable Export and Share functionality globally via librechat.yaml

### ISSUE THREAD

**Issue by ervet** [danny-avila/LibreChat#3126]
### What features would you like to see added?

It should be possible to disable either Export or Share or both via librechat.yaml. 

### More details

for data loss prevention or security or other reasons it should be possible to configure/disable the export and share functionality in a chat globally. 

Something like this in librechat.yaml would be great. 

interface: 
     chatExport: false
     chatShare: false 

### Which components are impacted by your request?

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markpopy** [comment]
+1

**Comment by RedwindA** [comment]
The ultimate goal is to render the entire LibreChat within the canvas, so users can only take photos with their phones, preventing any data leaks😄

**Comment by danny-avila** [comment]
Implemented here if we are referring to shared links: https://github.com/danny-avila/LibreChat/pull/2986
