### ISSUE TITLE
Enhancement: Add new Anthropic Claude 3.5 Sonnet model

### ISSUE THREAD

**Issue by meetpateltech** [danny-avila/LibreChat#3127]
### What features would you like to see added?

Add support for new claude 3.5 sonnet model

### More details

Anthropic announced a new model called Claude 3.5 Sonnet; here it is: [blog post](http://www.anthropic.com/news/claude-3-5-sonnet).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
You don't need to wait for an update.
![image](https://github.com/danny-avila/LibreChat/assets/110412045/efec9aae-976b-476b-b03a-d20afbcb9f6d)

```.env
#============#
# Anthropic  #
#============#
ANTHROPIC_MODELS=claude-3-5-sonnet-20240620 # add other models, separated by comma, no spaces
```

https://docs.anthropic.com/en/docs/about-claude/models
