### ISSUE TITLE
Enhancement: RTL to front end.

### ISSUE THREAD

**Issue by hooking-software** [danny-avila/LibreChat#3158]
### What features would you like to see added?

i would like to see RTL in the UI since it supprts RTL languages.

### More details

the whole chat interface need to have RTL as well to support RTL langs.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markpopy** [comment]
fully agree

**Comment by hooking-software** [comment]
you guys are awesome.
in the next few days, i will commit Hebrew translation for the whole project.
Job well done.
