### ISSUE TITLE
[Question]: Why are there no Gemini 1.5 models in the list ?

### ISSUE THREAD

**Issue by ReEnMikki** [danny-avila/LibreChat#3161]
### What is your question?

Why are there no Gemini 1.5 models in the list ?

### More Details

I see many Issues saying there are indeed Gemini 1.5 models, I must be missing something here. Tried both Gemini API and Vertex API, I just don't see the Gemini 1.5 models anywhere, please help!

### What is the main subject of your question?

Other

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/114931925/1265c27f-924c-4ee1-a448-17f384346b31)
![image](https://github.com/danny-avila/LibreChat/assets/114931925/c5657f75-0ae2-4270-a497-706001f9b112)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ReEnMikki** [comment]
When I manually set the Google API key in .env and save, it still asks me to set key in header menu to chat, then what's the point ?

**Comment by danny-avila** [comment]
I'm not sure what version you are on, but they are shown in the example of the latest version:

https://github.com/danny-avila/LibreChat/blob/aac01df80c9c95eb6a1632258ad6430f8b47aa51/.env.example#L120-L125

> When I manually set the Google API key in .env and save, it still asks me to set key in header menu to chat, then what's the point 

Need more info, which key are you saving (the exact variables) and is it for the Gemini API?
