### ISSUE TITLE
[Bug]: User Deletion cannot be prohibited

### ISSUE THREAD

**Issue by prononext** [danny-avila/LibreChat#3166]
### What happened?

Is there any way to keep users from deleting their accounts?

I saw the ENV ALLOW_ACCOUNT_DELETION but it does not work if set to false. The Account delete button is still visible and working without a problem.

### Steps to Reproduce

use ALLOW_ACCOUNT_DELETION=false as ENV
try to delete a account

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
It works, check your logs:

```bash
2024-06-22 14:45:32 error: [User] [Delete Account] [User cannot delete account] [User: USER_ID_HERE]
```

You should see this on successful blocking. The user may still be logged out after the action.

However, the action is allowed if the user is an admin.

**Comment by prononext** [comment]
ok thanks, I was only testing it with the first user which is of course the admin user. Sorry.
