### ISSUE TITLE
Enhancement: Block Conversation Removal

### ISSUE THREAD

**Issue by prononext** [danny-avila/LibreChat#3167]
### What features would you like to see added?

It would be really nice to have the possibility to block the removal of conversations, like removing the "Delete" Option in the Submenu on every conversation. 

### More details

maybe use a ENV ALLOW_CONVERSATION_DELETE with true and false option. 

### Which components are impacted by your request?

General, UI

### Pictures

<img width="362" alt="image" src="https://github.com/danny-avila/LibreChat/assets/24569958/dade9445-e9cb-4138-9bf6-87862f501a3a">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Not allowing a user to delete their own generated content is a data privacy issue. I understand you might have a use case, but this won't be implemented to the repo.

**Comment by prononext** [comment]
@danny-avila thank you for the quick response. 
Maybe there is a possibility where it is possible when the API key is provided for the whole instance and not by the user himself...
