### ISSUE TITLE
Add Delete Button to Chat Title

### ISSUE THREAD

**Issue by JayDoubleu** [danny-avila/LibreChat#3172]
### What features would you like to see added?

**Current Behavior**

Each chat has an "Archive" button directly exposed on the chat title.

**Proposed Change**

Add a "Delete" button alongside the existing "Archive" button on the chat title.

### More details

**Rationale**

Many users, including myself, frequently use LibreChat for quick tasks like proofreading or grammar-checking short sentences.
These chats often don't need to be kept in the history long-term.
The current process to delete a chat may require additional steps, reducing efficiency.

**Expected Benefits**

Improved user experience by providing quicker access to the delete function.
Easier management of chat history, allowing users to keep their workspace clutter-free.
Consistency with the existing "Archive" button, providing users with clear options for chat management directly from the title.

**Potential Considerations**

Ensure the delete action has a confirmation step to prevent accidental deletions.
Consider using an icon (e.g., a trash can) instead of text to save space if needed.
Evaluate if this change aligns with the overall design philosophy and user interface of LibreChat.

**Impact**
This small change would significantly improve the user experience for those who frequently use LibreChat for quick, disposable tasks.

### Which components are impacted by your request?

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks for the suggestion. The plan is to move the archive to the current dropdown menu: 

![image](https://github.com/danny-avila/LibreChat/assets/110412045/fb03c867-2add-4739-9584-a55ca6437dbe)

**Comment by JayDoubleu** [comment]
@danny-avila IMO that'll make experience worse, can user at least have a choice to select what buttons are visible ?

**Comment by berry-13** [comment]
> @danny-avila IMO that'll make experience worse, can user at least have a choice to select what buttons are visible on the chat title and what's hidden in the menu?

it won't. I also use it for quick stuff that's why we're planning to add a "temp chat" option (with a kb shortcut)

**Comment by JayDoubleu** [comment]
@danny-avila I agree to disagree. Simply copying what ChatGPT has is probably not the best way to provide a good UI. Multiple clicks and temporary chats are among the reasons I'm not using ChatGPT. When I first tried LibreChat, I immediately thought to myself that it's great that the archive button is there, and it was the first thing that I really liked about it, even though I wondered how great it would be to have a delete button. I believe a huge mistake is being made here, but ultimately it's your decision.

**Comment by berry-13** [comment]
> @danny-avila I agree to disagree. Simply copying what ChatGPT has is probably not the best way to provide a good UI. Multiple clicks and temporary chats are among the reasons I'm not using ChatGPT. When I first tried LibreChat, I immediately thought to myself that it's great that the archive button is there, and it was the first thing that I really liked about it, even though I wondered how great it would be to have a delete button. I believe a huge mistake is being made here, but ultimately it's your decision.

Then we could add simply (as you said) an option.

### Normal
- Only three dots

### All buttons
- Archive and delete button in the convo UI and the rename button with just the mouse double-click

All of this probably only in desktop; mobile we will move everything in the three dots menu
