### ISSUE TITLE
Enhancement: Display API Costs for single promts and totals

### ISSUE THREAD

**Issue by prononext** [danny-avila/LibreChat#3178]
### What features would you like to see added?

It would be really nice to have the possibility to know the aproximate API costs when running LibreChat. 
I've been using Chatpad AI a short time and I always liked a aproximate price calculation of my conversations.

Maybe there is a possibility to get a planning for that. 

### More details

I would suggest the following:

- [ ] Add a librechat.yaml or ENV section to activate, define and update pricing information for different models
- [ ] Add a total cost section right on the left side over or under the username
- [ ] Display a total cost of a conversation in the top center right after the presets

### Which components are impacted by your request?

General, UI, Endpoints

### Pictures

Here some screenshots of Chatpad AI, which sadly does not have the possibility to set pricing correctly:

<img width="647" alt="image" src="https://github.com/danny-avila/LibreChat/assets/24569958/15d40021-8807-4786-9c3c-d94c986d3e3e">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Hi thanks, it's already proposed and may work on it soon: https://github.com/danny-avila/LibreChat/issues/1215
