### ISSUE TITLE
[Bug]: selection not correctly shown under plugins

### ISSUE THREAD

**Issue by Omaha2002** [danny-avila/LibreChat#3193]
### What happened?

If you choose plugins and select a plugin the name does not change from "none selected" to the name of the plugin but something like "[object...]" 

### Steps to Reproduce

1. go to plugins 
2. select plugin
3. [object..] shown instead of the name of the plugin

### What browsers are you seeing the problem on?

Firefox

### Screenshots

![afbeelding](https://github.com/danny-avila/LibreChat/assets/3179748/5636d3ac-1083-4d90-86fa-ded5b33ae4f3)
![afbeelding](https://github.com/danny-avila/LibreChat/assets/3179748/2c9260b0-f407-457c-b8c6-7b96b58c24cc)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prononext** [comment]
I guess that error has something to to with that in 

https://github.com/danny-avila/LibreChat/blob/main/api/app/clients/tools/.well-known/askyourpdf.json

The logo path is not correctly resolving. You can see in the plugin store that the logo is also not showing correctly.

**Comment by danny-avila** [comment]
it no longer says "None selected" because the plugin is selected, it's the image that's not being resolved correctly

![image](https://github.com/danny-avila/LibreChat/assets/110412045/2cc7baf3-e786-4505-8380-d443b4a90cf4)
