### ISSUE TITLE
[Bug]: Multi-response Streaming Reverts to Single Response and Images Disappear on Error

### ISSUE THREAD

**Issue by RedwindA** [danny-avila/LibreChat#3194]
### What happened?

When using the Multi-response Streaming feature, if an error occurs in an endpoint, the chat interface reverts to the previous single response mode, and any images sent by the user disappear from the UI.

The chat interface should not revert to single response mode, and user-sent images should remain in the UI even if an error occurs in one of the endpoints.

### Steps to Reproduce

1. Enable the Multi-response Streaming feature.
2. Send a message that includes an image attachment.
3. Encounter an error in one of the endpoints during the conversation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
> Enable the Multi-response Streaming feature.
>  Send a message that includes an image attachment.
>  Encounter an error in one of the endpoints during the conversation.

- It's expected to have an error if one of the settings doesn't support images.
- I cannot reproduce an image disappearing

> The chat interface should not revert to single response mode,

Currently, this was the easiest solution to only maintain multiple response mode while the conversation was active. The messages are all still there in the correct relationship upon revisiting the conversation. 

I understand wanting to see the messages this way upon revisit, but in my opinion, this would be better suited through a mode to toggle the UI and "Explore" the branches, or to press a button to see the next message side by side. The complexity arises when there are more than 2 siblings in a row of messages
