### ISSUE TITLE
Enhancement: don't allow the user to attach images for requests to models that don't support images

### ISSUE THREAD

**Issue by jegraham-amplify** [danny-avila/LibreChat#3202]
### What features would you like to see added?

If a model doesn't support vision, don't let the user try to send an image to that model.

### More details

Currently, there is no indication that only certain models support vision. Additionally, the error message returned is generic and does not tell the user why their request failed. This results in a frustrating user experience.

### Which components are impacted by your request?

UI, Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This involves a bit of maintenance on what models support vision, etc. In my experience, it's always best to let the admin decide and there are already some planned updates for this as well as configuring some other model-specific details. 

I'll keep the UI elements in mind for this.
