### ISSUE TITLE
Assistants: supportedIds and excludeIds not working

### ISSUE THREAD

**Issue by walbercardoso** [danny-avila/LibreChat#3206]
Seems like supportedIds and excludeIds is not working anymore.

endpoints:
  assistants:
    disableBuilder: false # Disable Assistants Builder Interface by setting to `true`
  #   pollIntervalMs: 3000  # Polling interval for checking assistant updates
  #   timeoutMs: 180000  # Timeout for assistant operations
  #   # Should only be one or the other, either `supportedIds` or `excludedIds`
    supportedIds: ["asst_PvlaxDm5FEGjBkyAMEs3g2uZ"]

**Comment by walbercardoso** [comment]
![image](https://github.com/danny-avila/LibreChat/assets/50842245/ed26228b-1670-4206-8134-67b9dd53a773)

**Comment by danny-avila** [comment]
It works, you're using an ADMIN role account.

**Comment by danny-avila** [comment]
user sees:
![image](https://github.com/danny-avila/LibreChat/assets/110412045/224b8213-043b-421c-ac65-b6a2d2745f80)


admin sees:
![image](https://github.com/danny-avila/LibreChat/assets/110412045/608911bd-7436-4ef2-a798-ec04e2f81311)

**Comment by walbercardoso** [comment]
Thank you
