### ISSUE TITLE
Enhancement: Font & Font Size option

### ISSUE THREAD

**Issue by hongkongkiwi** [danny-avila/LibreChat#3207]
### What features would you like to see added?

I have some eyesight issues and I'd like the ability to set the font size of the interface.

If possible, I'd also like the ability to set the interface font (I have some more readable fonts I like to use). That might be a bit difficult, but atleast setting the font size would be chat!

### More details

Be great to have a section in user settings somewhere.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Sorry but this is not very customizable. Is zooming in on your browser not sufficient? I would recommend looking into editing the style sheet for this

**Comment by hongkongkiwi** [comment]
The major problem with this approach is that upon zooming the left and right spacing stays the same, so you have a giant space on left and right and your words get large and mashed into the middle into a small column. It becomes a bit unreadable. Perhaps this spacing issue could be fixed.

**Comment by danny-avila** [comment]
Ok the font size is actually pretty doable as an option, I’m reopening this!

**Comment by krakenftw** [comment]
@danny-avila Can i work on this?
