### ISSUE TITLE
Enhancement: Non-expiring User supplied API keys

### ISSUE THREAD

**Issue by tobiasmuehl** [danny-avila/LibreChat#3241]
### What features would you like to see added?

When a user adds an API key using the header, the user can select the expiry date. The max expiry is 30 days. I'd like to have an option for a permanent API key store that never expires.

### More details

.

### Pictures

<img width="702" alt="Screenshot 2024-07-01 at 16 21 26" src="https://github.com/danny-avila/LibreChat/assets/3341826/7dd8f3b3-0555-49ec-a424-df2e334757db">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TonySimonovsky** [comment]
any updates on this?
