### ISSUE TITLE
[Bug]: "No audio data available" while recording, despite succesful transcription

### ISSUE THREAD

**Issue by teun95** [danny-avila/LibreChat#3250]
### What happened?

When I record auto to have transcribed, a red error box shows up with the text "No audio data available". The error is incorrect given that the transcription is successful. The error only occurs when using Firefox (both on Windows 11 and on Android), also without any extensions enabled.

### Steps to Reproduce

1. Log into Librechat on Firefox
2. Change the settings of Speech to text to use an external engine
3. Click the microphone button and speak
4. The error will be shown while you are recording

### What browsers are you seeing the problem on?

Firefox, Mobile (Android)

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/37039643/d089741a-5005-4389-bc0d-54b4bde271f3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
> but I need to wait for other PRs to merge to avoid conflicts

Is this still true?

**Comment by berry-13** [comment]
> > but I need to wait for other PRs to merge to avoid conflicts
> 
> Is this still true?

fixed in #3431
