### ISSUE TITLE
[Bug]: "limit Plugins" only makes the plugin invisible, access is still possible

### ISSUE THREAD

**Issue by leondape** [danny-avila/LibreChat#3259]
### What happened?

Previous Chats where DallE has been used can be continued. 
Even if DallE is invisible the plugin can be used. 

### Steps to Reproduce

1. Start Chat with a Plugin (tested with Dalle3)
2. Disable Plugin in librechat.yml
3. continue Chat with no plugin visibly enabled. This is also the case after chats have been switched. You can seemingly always come back and continue with generation. 

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks issuing a fix
