### ISSUE TITLE
[Bug]: OpenId Configuration http proxy support for downloading Images (profile picture)

### ISSUE THREAD

**Issue by schnaker85** [danny-avila/LibreChat#3261]
### What happened?

We did configure the openID Strategy successfully and also added the `PROXY` env variable to proxy the requests to Azure Entra ID endpoints. The user can now successfully login with Entra ID and everything works as expected but the Profile Picture can not be downloaded from Microsoft due to the reason, that the `downloadImage` function does not use the proxy for the http request.

The OpenId Proxy support was added with pull request https://github.com/danny-avila/LibreChat/pull/3051 just recently.
 

### Steps to Reproduce

1. Configure Proxy via PROXY Env variable
2. Setup OpenId Strategy
3. Login with a user and check if the profile picture/Image was downloaded

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
{"level":"error","message":"[openidStrategy] downloadImage: Error downloading image at URL \"https://graph.microsoft.com/v1.0/me/photo/$value\": FetchError: request to https://graph.microsoft.com/v1.0/me/photo/$value failed, reason: read ECONNRESET","timestamp":"2024-07-04T07:53:26.444Z"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by berry-13** [comment]
@schnaker85 Can you check this PR #3263 and tell me if it works?

**Comment by schnaker85** [comment]
@berry-13 I verified it with the latest dev docker image version and it does work. Thanks for the update and the fix!

**Comment by berry-13** [comment]
> @berry-13 I verified it with the latest dev docker image version and it does work. Thanks for the update and the fix!

Nice, you're welcome!
