### ISSUE TITLE
Enhancement: right-align user's text in chat for better distinction.

### ISSUE THREAD

**Issue by yoyooyooo** [danny-avila/LibreChat#3286]
### What features would you like to see added?

Hoping that the user's text can be displayed on the right side, currently it's all on the left side, and when the text is long, it's unclear to browse and distinguish.

### More details

Or it can be added as an option to the settings.

### Pictures

just like:
<img width="650" alt="image" src="https://github.com/danny-avila/LibreChat/assets/18062745/5db95474-e451-4140-84a5-e9b260e983a4">

rather than:
<img width="290" alt="image" src="https://github.com/danny-avila/LibreChat/assets/18062745/89aef9cb-ba54-45ea-b6aa-7dd5fa2a4110">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
something like this is planned with the message bubble style
