### ISSUE TITLE
[Bug]: Not work Gemini via proxy

### ISSUE THREAD

**Issue by ZubikIT** [danny-avila/LibreChat#3292]
### What happened?

I get error LibreChat         | 2024-07-08 12:32:14 error: [handleAbortError] AI response error; aborting request: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-pro:streamGenerateContent?alt=sse: [400 Bad Request] User location is not supported for the API use.

### Steps to Reproduce

1. Set PROXY (squid.acl.by:3128 from New Yourk) in .env. Test work model gemini from server
<img width="931" alt="image" src="https://github.com/danny-avila/LibreChat/assets/745561/f12399eb-3531-4264-a35b-86f1af632d37">

2. Setting GOOGLE_KEY and GOOGLE_REVERSE_PROXY (the same as PROXY)
3. Got to Gemini any model 
4. Write text "HI" and get error
 

### Screenshots

<img width="1435" alt="image" src="https://github.com/danny-avila/LibreChat/assets/745561/1f0b0d75-b913-484e-ad51-5881536e2bcb">
<img width="1384" alt="image" src="https://github.com/danny-avila/LibreChat/assets/745561/4aa230ed-9788-409e-89ad-6ff4a9544efe">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
https://github.com/danny-avila/LibreChat/issues/1372
