### ISSUE TITLE
[Bug]: Streaming response drops first token when identical to prompt

### ISSUE THREAD

**Issue by cg-dot** [danny-avila/LibreChat#3322]
### What happened?

I've noticed an odd behavior with the response after updating to the latest commit(326069d). When AI's response starts with the same token as the user's prompt, that first token is not displayed while streaming.

### Steps to Reproduce

1. Enter the prompt "Hello" (without quotes)
2. If the AI's response starts with "Hello", the streaming output will skip this first word

For example, if the full response is "Hello! How can I assist you today?", the streaming output shows:
```
!
! How
! How can
! How can I assist you today?
Hello! How can I assist you today?
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Fixed, thanks!
