### ISSUE TITLE
[Bug]: Filtering plugins using includedTools breaks assistant tools.

### ISSUE THREAD

**Issue by bnord01** [danny-avila/LibreChat#3324]
### What happened?

When using includedTools to filter the available Plugins only the calculator tool remains available for assistants, while plugins are filtered as expected.

The issue seems to be, that filtering in ToolService.loadAndFormatTools, contrary to its documentation, is done based on the file name instead of the pluginKey, as it is done in the PluginController.

### Steps to Reproduce

1. Use a configuration with assistants + plugins enabled.
2. Set `includedTools` to `['calculator', 'azure-ai-search']` in `librechat.yaml`
3. Verify plugins are properly filtered in plugins.
4. Create/Update assistant try to add tool.
5. Observe the Azure AI Search tool being unavailable.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by djuillard** [comment]
I confirm I experience the same issue. I already opened a discussion #3255  for that. I just didn't know it was a bug, I thought it was a misconfiguration on my side.
