### ISSUE TITLE
[Bug]: Librechat doesn't wait until Ollama has loaded model

### ISSUE THREAD

**Issue by vlbosch** [danny-avila/LibreChat#3330]
### What happened?

When starting a conversation with a model served via Ollama, it sometimes happens the prompt stops prematurely with an ETIMEDOUT error. After resending the prompt, it is answered correctly, but only because the model has been loaded by then. With larger models (like Command R Plus), it takes several retries. 

### Steps to Reproduce

1. Start a chat with an Ollama-served model
2. Prompt the model
3. Send the prompt
4. See the general error message appear

### What browsers are you seeing the problem on?

Safari

### Relevant log output

```shell
Librechat error-log: 
{"cause":{"code":"ETIMEDOUT","errno":"ETIMEDOUT","message":"request to http://host.docker.internal:11434/v1/chat/completions failed, reason: read ETIMEDOUT","type":"system"},"level":"error","message":"[handleAbortError] AI response error; aborting request: Connection error.","stack":"Error: Connection error.\n    at OpenAI.makeRequest (/app/api/node_modules/openai/core.js:292:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ChatCompletionStream._createChatCompletion (/app/api/node_modules/openai/lib/ChatCompletionStream.js:53:24)\n    at async ChatCompletionStream._runChatCompletion (/app/api/node_modules/openai/lib/AbstractChatCompletionRunner.js:314:16)"}

Librechat debug-log: 
2024-07-12T05:36:03.543Z debug: [OpenAIClient] chatCompletion
{
  baseURL: "http://host.docker.internal:11434/v1",
    modelOptions.model: "gemma-2-27b-it-Q8_0_L.gguf:latest",
    modelOptions.temperature: 0.7,
    modelOptions.top_p: 1,
    modelOptions.presence_penalty: 0,
    modelOptions.frequency_penalty: 0,
    modelOptions.stop: undefined,
    modelOptions.max_tokens: undefined,
    modelOptions.user: "668d8e6941ec54b9987a6bcc",
    modelOptions.stream: true,
    // 2 message(s)
    modelOptions.messages: [{"role":"system","name":"instructions","content":"Instructions:\nAntwoord uitsluitend in het Nederla... [truncated],{"role":"user","content":"Dit is een test."}],
}
2024-07-12T05:36:03.548Z debug: Making request to http://host.docker.internal:11434/v1/chat/completions
2024-07-12T05:36:15.288Z debug: Making request to http://host.docker.internal:11434/v1/chat/completions
2024-07-12T05:36:27.455Z debug: Making request to http://host.docker.internal:11434/v1/chat/completions
2024-07-12T05:36:38.743Z warn: [OpenAIClient.chatCompletion][stream] API error
2024-07-12T05:36:38.743Z error: [handleAbortError] AI response error; aborting request: Connection error.
2024-07-12T05:36:38.747Z debug: [AskController] Request closed
2024-07-12T06:27:35.786Z debug: [AskController]

Ollama-server log:
level=WARN source=server.go:570 msg="client connection closed before server finished loading, aborting load"
level=ERROR source=sched.go:480 msg="error loading llama server" error="timed out waiting for llama runner to start: context canceled"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vlbosch** [comment]
I tested a bit more. Even when the model is loaded, but prompted with a large prompt, a timeout occurs. I think that the timeout should be removed when using Ollama, and only present an error when Ollama does.

**Comment by vlbosch** [comment]
@danny-avila Did you have a chance to look into this issue? Would be great if timeouts for custom endpoints can be changed and/or disabled completely. Thanks!

**Comment by danny-avila** [comment]
You can try this:

> Increase [`OLLAMA_LOAD_TIMEOUT`](https://github.com/ollama/ollama/blob/da09488fbfc437c55a94bc5374b0850d935ea09f/envconfig/config.go#L244).

source: https://github.com/ollama/ollama/issues/8006#issuecomment-2527493597

There is no timeout on LC side, unless you have a reverse proxy sitting in front of your client connections (like NGINX, or Traefik).

Those services have a 60 second default timeout.

I may add some simple UI for Ollama loading

**Comment by kirys** [comment]
I've probably found the cause it's the openai client, it has it's own internal timeout with a algorithm to decide how many seconds before stopping and making a new request, the after 3 attempts it gives up.

`const sleepSeconds = Math.min(initialRetryDelay * Math.pow(2, numRetries), maxRetryDelay);`

This does not give ollama enough time to load the model hence the api error.

even librechat logs shows the behavior it waits 12 seconds before trying again for 3 times then give the error

```
2024-12-20T09:56:34.835Z debug: Making request to http://---:11434/v1/chat/completions
2024-12-20T09:56:34.836Z debug: [saveConvo] api/app/clients/BaseClient.js - saveMessageToDatabase #saveConvo
2024-12-20T09:56:46.602Z debug: Making request to http://---:11434/v1/chat/completions
2024-12-20T09:56:58.820Z debug: Making request to http://---:11434/v1/chat/completions
2024-12-20T09:57:10.123Z warn: [OpenAIClient.chatCompletion][stream] API error
2024-12-20T09:57:10.124Z error: [handleAbortError] AI response error; aborting request: Connection error.
2024-12-20T09:57:10.126Z debug: [AskController] Request closed
```


on ollama i get this message each time

`
time=2024-12-20T09:56:58.106Z level=WARN source=server.go:562 msg="client connection closed before server finished loading, aborting load"
`

I have no proxy between ollama and librechat, they are just on different machines ollama is on my server and the librechat container is currently on my desktop. 

Hope this helps
K.
