### ISSUE TITLE
Enhancement: Add instance version to config endpoint

### ISSUE THREAD

**Issue by mfreiwald** [danny-avila/LibreChat#3355]
### What features would you like to see added?

It would be good to find out which version of LibreChat is running on an instance.
The API schema can change between versions. The version check would help align the frontend and backend code.

This might not be important for LibreChat and its frontend but it is important for 3rd party developers who want to develop a custom UI/App on top of the LibreChat backend.

### More details

This was already a topic in the discussions panel and Danny agreed on it
https://github.com/danny-avila/LibreChat/discussions/1976

### Which components are impacted by your request?

General

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
You can use 

```ts
import { Constants } from 'librechat-data-provider';
console.log(Constants.CONFIG_VERSION);
console.log(Constants.VERSION);
```
