### ISSUE TITLE
TTS & SST (Speech) configuration shows up a list of all models instead of configured ones

### ISSUE THREAD

**Issue by cfshawnmaholick** [danny-avila/LibreChat#3361]
Hi , thank you very much for updating docs!
I now used `azureOpenAI` instead of `azure` in the speech section, but the problem still exists.

_Originally posted by @cfshawnmaholick in https://github.com/danny-avila/LibreChat/issues/3360#issuecomment-2232818275_

**Comment by berry-13** [comment]
https://github.com/danny-avila/LibreChat/issues/3360#issuecomment-2232827708
