### ISSUE TITLE
[Bug]: Hugging Face deployed Libre Chat app not opening

### ISSUE THREAD

**Issue by Amitpatil215** [danny-avila/LibreChat#3371]
### What happened?

Expected it to open Libre chat UI

### Steps to Reproduce

Navigate to earlier working hf libre chat instance and see white screen

### What browsers are you seeing the problem on?

Arc, chrome

### Relevant log output

```shell
The deferred DOM Node could not be resolved to a valid node.
webauthn.js:1 Uncaught (in promise) BridgeTimeout
    at I (chrome-extension://ghmbeldphafepmbegfdlkpapadhbakde/webauthn.js:1:8762)
    at v (chrome-extension://ghmbeldphafepmbegfdlkpapadhbakde/webauthn.js:1:8823)
    at chrome-extension://ghmbeldphafepmbegfdlkpapadhbakde/webauthn.js:1:9475
I @ webauthn.js:1
v @ webauthn.js:1
(anonymous) @ webauthn.js:1
```

### Screenshots

<img width="671" alt="image" src="https://github.com/user-attachments/assets/95d2e475-20e8-4108-8099-1e8036ab8818">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Amitpatil215** [comment]
Closing this issue as issue is no more producible

**Comment by berry-13** [comment]
@Amitpatil215 if you meant the DEMO, please don't open issues. DM me or @fuegovic on Discord, or open an #issue (on discord)
