### ISSUE TITLE
Enhancement: "Continue Chat Branch off at this point / UI Self-Selecting Chat Messages to Use"

### ISSUE THREAD

**Issue by yosun** [danny-avila/LibreChat#3375]
### What features would you like to see added?

Sometimes it seems that a series of conversations leads the LLM very offshore. It would be nice to be able to go back to a previous point in chat. Effectively, on the API, this just involves not sending N messages. Or, this can be implemented as a checklist where the user un-checkboxes the last context-window sized messages they do not want sent. 

### More details

Sometimes it seems that a series of conversations leads the LLM very offshore. It would be nice to be able to go back to a previous point in chat. Effectively, on the API, this just involves not sending N messages. Or, this can be implemented as a checklist where the user un-checkboxes the last context-window sized messages they do not want sent. 

### Which components are impacted by your request?

UI, Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This is mostly possible already: 

https://www.librechat.ai/docs/user_guides/fork
