### ISSUE TITLE
[Bug]: wrong App Title when adding to Apple Device Homescreen

### ISSUE THREAD

**Issue by leondape** [danny-avila/LibreChat#3382]
### What happened?

Probably the Apps title needs apple-mobile-web-app-title set in order to be correctly rendered on apple devices. 

### Steps to Reproduce

1. try to add librechat with custom app name to homescreen of an i-Device
2. App Title is librechat instead of the custom Title

### What browsers are you seeing the problem on?

Mobile (iOS)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leondape** [comment]
probably it is due to the fact that the manifest in vite.config.ts has it hard coded to LibreChat?

**Comment by danny-avila** [comment]
For this, you should be editing `index.html` and committing it to your fork

**Comment by leondape** [comment]
I changed everything and added metadata name tags but still it does not to the job. 
Is a manifest.json required for that? I mean where do iOS devices  currently get "LibreChat" from?

**Comment by leondape** [comment]
I tried changing: 
/index.html
/client/index.html

In the end the only thing that worked was changing 
/client/vite.config.ts

**Comment by joseph-holland** [comment]
Quick question @leondape as I'm having the same issue. When you changed the vite.config.ts what did you have to do for it to take effect? Was it a case that you had to build the image, or are you using the deploy-compose and docker overrides?
Thanks

**Comment by joseph-holland** [comment]
I actually got this sorted using the docker-compose.override.yml by copying the existing manifest.webmanifest and editing it, then adding the below to the volumes for api service:
`services:
  api:
    volumes:
     ...
      - ./client/manifest.webmanifest:/app/client/dist/manifest.webmanifest`

**Comment by leondape** [comment]
After you edit the vite.config.ts you need to rebuild the frontend.
In development you do that `npm run build:client`
Or if you use docker in production rebuild the image using [this](https://github.com/danny-avila/LibreChat/blob/2d62eca612115a6176c35f992593bcbca9cff76a/docker-compose.override.yml.example#L35)

**Comment by joseph-holland** [comment]
Thanks. I'm trying to rebuilding the image for now if I'm just doing small tweaks.
