### ISSUE TITLE
Artifacts addition to llm models(claude)

### ISSUE THREAD

**Issue by moksha-hub** [danny-avila/LibreChat#3394]
### What features would you like to see added?

Enhancement: anthropic of claude ai in librechat didn't have "Artifacts" feature available can you update it also if possible i heard that it could be added to other llm models too try to add the feature.

### More details

Enhancement: anthropic of claude ai in librechat didn't have "Artifacts" feature available can you update it also of possible i heard that it could be added to other llm models too try to add the feature.

### Which components are impacted by your request?

Plugins

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by berry-13** [comment]
https://github.com/danny-avila/LibreChat/issues/3139
