### ISSUE TITLE
[Bug]: Typo in Docs

### ISSUE THREAD

**Issue by taowang1993** [danny-avila/LibreChat#3398]
### What happened?

https://www.librechat.ai/docs/development/tools_and_plugins

It says the files are in .\api\app\langchain\tools

I think you mean .\api\app\clients\tools?

### Steps to Reproduce

https://www.librechat.ai/docs/development/tools_and_plugins

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
The docs are referring to the Tool class from the `langchain/tools` library
