### ISSUE TITLE
[Bug]: Meilisearch Textbox Strange Behavior

### ISSUE THREAD

**Issue by taowang1993** [danny-avila/LibreChat#3402]
### What happened?

When you are done with search, you delete the old query, the pointer automatically jump to the chat text input box.

I expected the pointer to stay in the meilisearch input box, because when users manually delete the old query, it means they want to input a new search query. 

If they don't want to conduct a new search query, they may not mannually press the backspace button to delete it. 

### Steps to Reproduce

Open Librechat Demo.
Do a search as normal.
Press backspace to delete the query.
Once the last character is deleted, the mouse pointer jumps to chat input box.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This is expected behavior. chat input autofocus is a separate digital accessibility issue that is being tracked separately, unrelated to the Search bar.
