### ISSUE TITLE
[Bug]: System Theme resets

### ISSUE THREAD

**Issue by reka7490** [danny-avila/LibreChat#3405]
### What happened?

System Theme resets specifically to the one set in system on browser restart.

### Steps to Reproduce

Set the LibreChat theme to System.
Switch the theme in Windows.
Close the browser.
Switch the theme back again.
Launch the browser.
Depending on the system theme set previously, it will set to "Light" or "Dark".

### What browsers are you seeing the problem on?

Opera GX

### Screenshots

![1s](https://github.com/user-attachments/assets/52d48cf2-e391-4982-a1ce-52dbb0e16e23)
![2s](https://github.com/user-attachments/assets/eea3b582-ae6d-4478-aa0c-ff9e7ce02da3)
![3s](https://github.com/user-attachments/assets/35499994-6289-4911-8926-676954d0fd6d)
![4s](https://github.com/user-attachments/assets/9106a58a-0af6-45ce-a6f1-56cc0be331f6)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
System refers to the browser
