### ISSUE TITLE
How to close the registration function？

### ISSUE THREAD

**Issue by voctot** [danny-avila/LibreChat#341]
Opening registration is not a wise move

**Comment by fuegovic** [comment]
I'm sorry, I am not certain of what you are asking. Do you mean that you would like to have the option to make registration unavailable after the creation of the admin account since it could be a security issue to have it open when deployey on the web?

**Comment by danny-avila** [comment]
> I'm sorry, I am not certain of what you are asking. Do you mean that you would like to have the option to make registration unavailable after the creation of the admin account since it could be a security issue to have it open when deployey on the web?

I think this is what they're asking. I'm adding it to the task list since it's been requested a few times before.

**Comment by voctot** [comment]
> I think this is what they're asking. I'm adding it to the task list since it's been requested a few times before.

Thank you~, I think you should understand what I mean, if the registration function is not controlled, it is the same as public.

**Comment by danny-avila** [comment]
This is being worked on in #346

**Comment by danny-avila** [comment]
With the latest update, you can now close registration by either omitting this env variable or setting it to false

```
# ALLOW_REGISTRATION=true
# ...or 
ALLOW_REGISTRATION=false
```

See the latest release here for more info, as there are many breaking changes with the update. 

https://github.com/danny-avila/LibreChat/releases/tag/v0.5.0
