### ISSUE TITLE
New Enhancement: add gpt 4o mini from open ai

### ISSUE THREAD

**Issue by moksha-hub** [danny-avila/LibreChat#3418]
### What features would you like to see added?

There is a new model which is named gpt 4o which was released by open ai.can you add this yo librechat 

### More details

As gpt 4o is priced the lowest of all ai models on top it's good to use.

### Which components are impacted by your request?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Already implemented https://github.com/danny-avila/LibreChat/pull/3384
