### ISSUE TITLE
[Bug]: Assistants sources footnote rendered in a weird way: 【10:13†source】

### ISSUE THREAD

**Issue by leondape** [danny-avila/LibreChat#3437]
### What happened?

Using Assistants in librechat, it tries to deliver the sources. The first footnote always works as it writes and upper-index ^1. 
All other sources are rendered wrong, like: 【10:13†source】
See attached image.

### Steps to Reproduce

1. question assistant with sources
2. wait for the response
3. observe issue

### What browsers are you seeing the problem on?

Microsoft Edge

### Screenshots

I have deleted output for privacy reasons. Just the rendering of the footnote index is relevant.

<img width="705" alt="sources" src="https://github.com/user-attachments/assets/58675128-0d17-4557-8111-f93db77bd8f7">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This is just the default rendering for citations from OpenAI. This totally depends on them providing all the details for replacing their default citations, and this can vary from model/settings/instructions, etc.

![image](https://github.com/user-attachments/assets/f017e282-a4ac-4db6-9718-c26e13a820e6)
