### ISSUE TITLE
Enhancement: Fetching models from text-generation-webui (oobabooga)

### ISSUE THREAD

**Issue by Backroads4Me** [danny-avila/LibreChat#3448]
### What features would you like to see added?

The ability to change models when using text-generation-webui (oobabooga) as the backend.

### More details

With the Ollama backend the app fetches the names of all of the available models and allows switching between models.  When using the text-generation-webui backend, the only "model" shown is "text-embedding-ada-002" and fetch doesn't work.  (Inference does work).  This request is to create a custom fetcher for text-generation-webui that works similarly to Ollama's.  Ideally, it would also unload models which would allow you to use both backends and switch between them.

### Which components are impacted by your request?

UI, Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
> This is a limitation of ooba's `v1/models` endpoint. [Relevant code line](https://github.com/oobabooga/text-generation-webui/blob/cc8c7ed2093cbc747e7032420eae14b5b3c30311/extensions/openai/script.py#L149) and [closed "stale" issue](https://github.com/oobabooga/text-generation-webui/issues/5675).

Seems like an easy fix from ooba's part, but for whatever reason, it is not implemented (even with an open PR) : https://github.com/oobabooga/text-generation-webui/pull/5720
