### ISSUE TITLE
Enhancement: Preserve new lines for prompt variables

### ISSUE THREAD

**Issue by ianks** [danny-avila/LibreChat#3464]
### What features would you like to see added?

Currently, when pasting a variable’s value into a prompt form, LibreChat will insert the text into the message body *without* new lines. It would be nice if we could have a text area to paste text that preserves new lines, so long blocks of text can be pasted.

### More details

My partner uses Librechat for grammar corrections and likes to paste multiple paragraphs at a time. Without preserving new lines, the LLM returns text as one long line without paragraph distinction.

### Which components are impacted by your request?

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
duplicate https://github.com/danny-avila/LibreChat/issues/3284

**Comment by danny-avila** [comment]
fix just merged!
