### ISSUE TITLE
Button icons have low contrast

### ISSUE THREAD

**Issue by derekjackson-das** [danny-avila/LibreChat#3470]
**Issue Description:** The different icons under the replies to do not have a contrast ratio of at least 3:1, which is the WCAG requirement for non-text color contrast for items like buttons and key visual elements.

**WCAG Criteria:** [1.4.11 Non-text Contrast - AA](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast)

**Screenshot or Snippet:** [Link to Screenshot](https://share.zight.com/YEuwv22Y)

**Notes:** Making the icon colors darker is the easiest way to address this issue. The contrast is 2.9:1 and almost meets the requirement of 3:1. Rather than making it slightly darker to meet the WCAG criteria, it would be better to darken them significantly and make them clearly distinguishable and more usable.

**Comment by Tanvez** [comment]
looks like this was fixed in this PR #3568 
 
<img width="1526" alt="Screenshot 2024-08-15 at 2 14 04 PM" src="https://github.com/user-attachments/assets/89b10bb0-2797-4621-83ec-e55e7d6eda57">

**Comment by danny-avila** [comment]
Sweet thank you for confirming @Tanvez
