### ISSUE TITLE
Enhancement: Alternate access to the prompts feature (for those that like to hide the sidebar)

### ISSUE THREAD

**Issue by GOvEy1nw** [danny-avila/LibreChat#3478]
### What features would you like to see added?

I like to hide the sidebar as it feels cleaner, and while that's fine for the attached files feature (as you can also access it in the settings), there's no alternative way to access the prompt manager.

### More details

I think we could access prompt manager via a few different options:

1. A button to the left of the chat input bar.
2. when you enter '/' a 'manage prompts' button could appear in the prompt list popover.
3. Add it to the settings (though I think that might be a little too out the way for prompts)

it'd also be nice if the prompts manager was 'windowed' like the attached files manager is, as it helps keep the user oriented, whereas it currently fills the whole screen, and it takes a second to realise how to get back to the chat screen, so it feels a little unintuitive than the files manager.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by berry-13** [comment]
true but a lot of new features will be there. Best option it's to just partially hide it like this:
![image](https://github.com/user-attachments/assets/70206b55-6cb2-47a8-a991-2e951bd0e759)

**Comment by GOvEy1nw** [comment]
> true but a lot of new features will be there. Best option it's to just partially hide it like this:
> 
> ![image](https://github.com/user-attachments/assets/70206b55-6cb2-47a8-a991-2e951bd0e759)
> 
> 

Yep I'm happy to do that, is it possible to set it like that by default for all users?

**Comment by danny-avila** [comment]
> Yep I'm happy to do that, is it possible to set it like that by default for all users?

Yea, it needs to be that way, thanks for your feedback!

**Comment by danny-avila** [comment]
> Yea, it needs to be that way, thanks for your feedback!

The proposed "default" sidebar view has been implemented for new users.
