### ISSUE TITLE
All page content is not in landmarks

### ISSUE THREAD

**Issue by derekjackson-das** [danny-avila/LibreChat#3515]
Issue Description: It is a best practice to include all the page content in a landmark role of some kind. This improves page navigation and makes the structure clear.

Related to Navigation Landmarks need accessible names #3514 

WCAG Criteria: [Landmark Best Practice](https://dequeuniversity.com/rules/axe/4.9/region?application=AxeChrome)

Notes: The image below outlines the regions and names that could be used to identify all content on the page.

<img width="1972" alt="Screenshot 2024-08-01 at 3 35 50 PM" src="https://github.com/user-attachments/assets/1c0d1ceb-07f2-4446-b2a0-1745d5492d7b">

**Comment by derekjackson-das** [comment]
I think this corrects the issue described in this ticket and we can close it. 

To handle follow up issues and continue improvements I created tickets #3571 , #3572  and #3573

**Comment by danny-avila** [comment]
thanks!
