### ISSUE TITLE
[Bug]: Can't close sidebars on mobile view (iPhone SE)

### ISSUE THREAD

**Issue by fuegovic** [danny-avila/LibreChat#3534]
### What happened?

Can't close either sidebar on my iPhone SE

### Steps to Reproduce

It can be reproduced from the browser DevTool mobile view

### Screenshots

https://github.com/user-attachments/assets/b96dbe34-51e6-4321-888e-20fb9d916d21

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
thanks I know the issue, fixing now
