### ISSUE TITLE
[Bug]: Only the first citation is properly formatted

### ISSUE THREAD

**Issue by zsturgess** [danny-avila/LibreChat#3563]
### What happened?

I'm seeing a fairly consistent issue where, when using an assistant with file-search and a response that requires the model to cite multiple times that only first citation is properly formatted, the others being returned raw in the form presented by the OpenAI API: `【4:2†source】`

I have pasted a sample of the message stored in Mongo in the "log output" section below

### Steps to Reproduce

1. Create an assistant with file-search capabilities and at least one file to retrieve from
2. Present a query that requires the assistant to cite the same file multiple times (i.e. different chunks)
3. Observe only the first citation is properly formatted

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
... snip ...
- Click the "Redraft" button to put the PO back into draft status^1^【4:2†source】.
... snip ...
^1.^ case_emails_redacted.txt
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks, there are a couple of gotchas with this but finally have a robust method, now merged.
