### ISSUE TITLE
Navigation landmark accessible name includes role.

### ISSUE THREAD

**Issue by derekjackson-das** [danny-avila/LibreChat#3571]
**Issue Description:** The name for the navigation is "chat-history-nav". To make the name as concise and clear as possible and to avoid the possibility of mispronunciation, the name should not repeat the role information and does not need to be hyphenated. A clear, human-readable string is preferable.

**WCAG Criteria**: [2.4.6 Headings and Labels - AA](https://www.w3.org/WAI/WCAG21/Understanding/headings-and-labels)

**Notes**: Change the aria-label value to "Chat History".
<img width="1780" alt="Screenshot 2024-08-07 at 1 00 43 PM" src="https://github.com/user-attachments/assets/9ab199ee-b8e6-439e-aec4-c39aafa5646c">

**Screenshot or Snippet**: [Link to Screenshot](https://share.zight.com/mXuQ9j8R)

**Comment by danny-avila** [comment]
Closed by https://github.com/danny-avila/LibreChat/pull/3604
