### ISSUE TITLE
Incorrect role for controls-nav landmark

### ISSUE THREAD

**Issue by derekjackson-das** [danny-avila/LibreChat#3572]
**Issue Description**: The navigation role isn't quite appropriate for this landmark. It would be better described as a region and provide a descriptive name to provide more context.

**WCAG Criteria**: [2.4.6 Headings and Labels - AA](https://www.w3.org/WAI/WCAG21/Understanding/headings-and-labels)

**Notes**: Make this a "region" landmark using the `role="region"` or using the `<section>` HTML element. With this change, a more appropriate name for the `aria-label` attribute could be "Controls" to not repeat or contradict the role details. See #3571 

 [MDN Guide on Region Role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/region_role).

<img width="1512" alt="Screenshot 2024-08-07 at 1 09 11 PM" src="https://github.com/user-attachments/assets/a2b3c244-7bcf-4f33-bd37-61dc560f02c0">

**Screenshot or Snippet**: [Link to Screenshot](https://share.zight.com/4guGwzxk)

**Comment by danny-avila** [comment]
Closed by https://github.com/danny-avila/LibreChat/pull/3604
