### ISSUE TITLE
[Enhancement]: Heartbeat for UI connection to prevent connection errors

### ISSUE THREAD

**Issue by gafda** [danny-avila/LibreChat#3579]
### What happened?

LibreChat UI does not keep the connection alive when it is inactive for a long time and is not enough to auto-logout.
Using v0.7.4-rc1 docker image.

### Steps to Reproduce

1. Login to LibreChat (e.g.: Social login)
2. Create a new chat (e.g.: Azure OpenAI - gpt-4o)
3. Send something (e.g.: Hi!)
4. Wait a while leaving the tab just as it is... you may open other browser tabs for other stuff...
5. Come back after a long while. Let's say you configured your login to last 30 minutes, come back after about 10 minutes, and try to send another message in the opened chat. The UI will fail without even contacting the server, and showing the picture in the screenshot section.

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Relevant log output

```shell
Since no call is eventually made to the server, no logs are available for it.

Aside from selected browsers, more were tested:
- Opera
- Opera GX
- DuckDuckGo Browser
- Brave

All with the same result.
```

### Screenshots

![image](https://github.com/user-attachments/assets/b66399dd-9550-4088-b156-01953ffb4d77)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks for the report. You're right, LibreChat doesn't currently maintain connections during inactivity. This is standard for many web apps to save resources.

To fix this, I plan to:
1. Add a quick connection check when users start typing after inactivity.
2. Implement a periodic "heartbeat" to keep sessions alive.
3. Improve error handling and user feedback.

These changes will be in an upcoming release. For now, refreshing the page should fix the issue.
