### ISSUE TITLE
Enhancement: Enhanced Placeholder Configuration in LibreChat Prompt Library

### ISSUE THREAD

**Issue by kmeshcheryakov** [danny-avila/LibreChat#3597]
### What features would you like to see added?

# What features would you like to see added?

**Current Behavior:** Currently, placeholders in the Prompt Library are displayed as one-line input fields when using a prompt. The configuration options for these placeholders are limited, and their order on the prompt screen is fixed.

**Proposed Behavior:** Enhance the placeholder configuration in the Prompt Library to support:
1. Multiline input fields
2. Dropdown lists
3. Ability to change the order of placeholder fields on the prompt screen

**Use Case:**
* Users can create more complex and versatile prompts with different types of input fields (single-line, multiline, dropdown).
* Prompt creators can specify the most appropriate input type for each placeholder, improving user experience and prompt accuracy.
* Users can customize the order of placeholder fields to create a more logical or user-friendly flow when filling out prompts.

### More details

This enhancement would require changes to both the prompt creation interface and the prompt usage interface. The prompt creation process would need to be updated to allow for more detailed placeholder configuration. The prompt usage interface would need to be modified to render different types of input fields based on the placeholder settings.

### Which components are impacted by your request?

General, UI

### Pictures

![image](https://github.com/user-attachments/assets/bcbec894-6e93-4a21-819a-95cb56377f11)

For example, the {{original_email}} placeholder would benefit from being a multiline field, and the {{tone}} as a dropdown list.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thank you for the excellent write up. Thinking out loud here, it's definitely possible even with just text alone, for example, if I wanted a dropdown:

```md
<tone:formal|casual|business casual>

or for multi-line inputs:
{{textarea:email}}
```

While convenient from a dev perspective, this would be somewhat advanced usage and it may be easier to have interface elements to help create "special" variables.

Any help, even landing on a format for variable, would be really helpful.

**Comment by kmeshcheryakov** [comment]
``` 
<tone:formal|casual|business casual>

or for multi-line inputs:
{{multi-line:email}}
``` 

I think it's a great suggestion. In this case, the backend part will not need to be changed.  

I don't know what type of input would be a sensible default, though.

**Comment by kmeshcheryakov** [comment]
I have created a PR for this feature: https://github.com/danny-avila/LibreChat/pull/3618

**Comment by danny-avila** [comment]
Closing, resolved by https://github.com/danny-avila/LibreChat/pull/3681

I'm sure we can add more like this, but this is a good start and any others should be scoped to their own issues.
