### ISSUE TITLE
[Bug]: The `@` Command for Switching Endpoints/Models Sends Messages Before Choosing the Model

### ISSUE THREAD

**Issue by jcdiv47** [danny-avila/LibreChat#3613]
### What happened?

When using the `@` command to switch endpoints/models, it prematurely/wrongly sends the "@" as a message out before user is able to choose the model. (I am not familiar with and not sure which part of log output is relevant but I can fetch it upon request and guidance.)

### Steps to Reproduce

1. Enters `@` in input box.
2. Choose one endpoint/model provider, e.g., openai.
3. The model selection list is shortly prompted before the message "@" is automatically sent without user choosing the model.
4. The assistant replies to this meaningless message, i.e., a single @.

### What browsers are you seeing the problem on?

Chrome, Mobile (iOS)

### Screenshots

https://github.com/user-attachments/assets/ba33bb0f-483c-4335-8c90-44cd3ee762cf

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks for reporting this!
