### ISSUE TITLE
Enhancement: Add Support for chatgpt-4o-latest Model

### ISSUE THREAD

**Issue by QuintinShaw** [danny-avila/LibreChat#3642]
### What features would you like to see added?

I would like to request support for the chatgpt-4o-latest model from OpenAI in the LibreChat application. The chatgpt-4o-latest model is a dynamic version of the GPT-4o model, continuously updated to reflect the latest enhancements and research from OpenAI. This model is particularly useful for developers and researchers who want to work with the most current capabilities of GPT-4o.

### More details

This model has already been demonstrated to perform exceptionally well on various platforms, achieving a high Arena Score of 1314 on LMSYS, indicating its effectiveness in real-world applications. 

chatgpt-4o-latest this model is different from gpt-4o-2024-08-06:

gpt-4o-2024-08-06: This is the latest static snapshot supporting structured outputs, optimized for API usage.
chatgpt-4o-latest: This is a dynamic model that represents the cutting-edge capabilities of GPT-4o, intended for research and evaluation purposes.

For reference, you can learn more about the chatgpt-4o-latest model and its capabilities [here](https://platform.openai.com/docs/models/gpt-4o).

### Which components are impacted by your request?

Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by debitCredit** [comment]
You can modify your .env file to add support for this without waiting for an update:
https://www.librechat.ai/docs/configuration/dotenv#openai

Un-comment `OPENAI_MODELS` and add `chatgpt-4o-latest` to the list.

**Comment by danny-avila** [comment]
> You can modify your .env file to add support for this without waiting for an update: https://www.librechat.ai/docs/configuration/dotenv#openai
> 
> Un-comment `OPENAI_MODELS` and add `chatgpt-4o-latest` to the list.

yup and if you fetch the list anyway, you should have it, too. An update to LibreChat would just recognize the model for pricing/context purposes, but I think it's already being recognized the same way as "gpt-4o" which is the same pricing

---

@debitCredit also an aside, I used to work in accounting so you gave me some t-account throwbacks lol

| .env File Modifications |                    |
|-------------------------|---------------------|
| Assets                  | Liabilities         |
| OPENAI_MODELS:          | Tech Debt: $9000    |
| - chatgpt-4             |                     |
| - chatgpt-3.5           |                     |
| - chatgpt-4o            |                     |
| - chatgpt-4o-latest     |                     |
| Patience: $100          | Waiting for         |
|                         | Updates: $99        |
