### ISSUE TITLE
Enhancement: multi-response button

### ISSUE THREAD

**Issue by burson-huit** [danny-avila/LibreChat#3660]
### What features would you like to see added?

testing the new 0.7.4, the button that "adds" an LLM to a multi-response chat session has no label. I had no idea what it does until I started experimenting.

### More details

suggestion: label the button

### Which components are impacted by your request?

UI

### Pictures

<img width="348" alt="Screenshot 2024-08-15 at 15 30 43" src="https://github.com/user-attachments/assets/8f30c722-884d-4118-90bf-5a3926b5814f">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by berry-13** [comment]
forgot to close this. This was added a while back when doing the Tooltip UI refactor
