### ISSUE TITLE
[Bug]: Prompt Dropdown Variable

### ISSUE THREAD

**Issue by kukoboris** [danny-avila/LibreChat#3688]
### What happened?

I created a prompt and utilised the Prompt Dropdown Variable to substitute options from a dropdown list into the text of the prompt. When one of the options is selected, that option is substituted into the prompt in the preview. However, when the prompt is submited into the chat - some strange list is inserted instead of one desired variable.

### Steps to Reproduce

1. Create a prompt
2. Insert Dropdown Variable {{variable_name:option1|option2|option3}}
3. Save it
4. Start a new conversation with this prompt
5. Chose an option in the dropdown menu
6. Submit
7. Check you prompt

### What browsers are you seeing the problem on?

Firefox

### Screenshots

<img width="1038" alt="изображение" src="https://github.com/user-attachments/assets/a1d4dc29-4641-4bb3-9a37-50fd50fb4eb2">

<img width="788" alt="изображение" src="https://github.com/user-attachments/assets/856cbebd-87c4-4bd2-b766-d54ed48634db">

<img width="746" alt="изображение" src="https://github.com/user-attachments/assets/b143e6dc-d1d1-4eeb-9670-9fee5183fcf0">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
@kmeshcheryakov Can you take a look? it should be an easy fix, looks like we were missing the submission piece in https://github.com/danny-avila/LibreChat/pull/3618

I will address this if I can soon

**Comment by danny-avila** [comment]
I want to improve the dropdown for this anyway, can probably touch on it soon

**Comment by danny-avila** [comment]
now resolved, added a better dropdown too

https://github.com/user-attachments/assets/bfa57c76-714c-4870-895d-7cff23633f2f
