### ISSUE TITLE
[Bug]: Android phone when click Setting-> Speech  crash

### ISSUE THREAD

**Issue by pxz2016** [danny-avila/LibreChat#3701]
### What happened?

When clicking Settings-Speech on an Android phone, an error occurs.
Cannot read property 'getVoices' of undefined
![Screenshot_20240820_092839](https://github.com/user-attachments/assets/3f0c95ca-3ace-460a-ab8f-1d1aefb92b25)

### Steps to Reproduce

1. login
2. click user
3. click setting
4. click Speech

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This was already resolved, are you on the latest version?

**Comment by danny-avila** [comment]
Should be fixed as of this PR

**Comment by pxz2016** [comment]
I tested it on https://librechat-librechat.hf.space

**Comment by fuegovic** [comment]
@pxz2016 
I just updated the HF demo, you can give it another try
https://demo.librechat.cfd/

**Comment by pxz2016** [comment]
> @pxz2016 I just updated the HF demo, you can give it another try https://demo.librechat.cfd/

not crash
But it cannot perform speech recognition

**Comment by fuegovic** [comment]
@pxz2016 It's working for me on the demo, using Microsoft Edge

https://github.com/user-attachments/assets/69a48da8-99ca-4d9f-9e3d-9093d5ad382a

Here's the app settings on my account

![image](https://github.com/user-attachments/assets/39ab9b72-f9e7-4fb3-acf2-38f5bb80e507)

**Comment by pxz2016** [comment]
android can use External  speech to text
can not use browser

**Comment by danny-avila** [comment]
> android can use External speech to text can not use browser

There are incompatibility issues with android at the moment

> Speech synthesis is not yet supported in Android apps because it's not supported in the WebView. Follow this issue for updates: https://bugs.chromium.org/p/chromium/issues/detail?id=487255
