### ISSUE TITLE
[Question]: Add custom instruction and context to openai api

### ISSUE THREAD

**Issue by rivindubandara** [danny-avila/LibreChat#3703]
### What is your question?

How do I add some custom instruction and context to start off with?

![image](https://github.com/user-attachments/assets/f8348c24-04ee-4ed8-b54a-d42e23436c8f)

### More Details

Right now its the default, I want to make it specific context like a programming chatgpt etc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jacobcolyvan** [comment]
@rivindubandara use a preset to give it custom/system instructions:
<img width="1024" alt="Screenshot 2024-08-20 at 15 15 13" src="https://github.com/user-attachments/assets/635df297-e66d-4381-800a-fb21e250d97a">

**Comment by rivindubandara** [comment]
Does this applied to all users who sign up or just the specific user. I need the presets to be global and default if possible

**Comment by jacobcolyvan** [comment]
@rivindubandara you can share import/export presets, but as far as I know you can't make the preset global and/or default.
Hopefully someone will jump in to tell you otherwise.

**Comment by berry-13** [comment]
@rivindubandara answered here: https://github.com/danny-avila/LibreChat/discussions/3706?converting=1#discussioncomment-10393752
