### ISSUE TITLE
[Bug]: Unable to return to conversation history after removing the last conversation bookmark

### ISSUE THREAD

**Issue by ChaitanyaParekh77** [danny-avila/LibreChat#3717]
#### Buggy behaviour

When there is only one conversation bookmarked, say in the Saved category, and this conversation is removed while the user is viewing the Saved bookmarked conversations in the left sidebar, the user cannot return to the conversation history. The "Bookmarks" button in the left sidebar disappears when the last bookmarked conversation is removed, so the user cannot click on the "Clear All" option. The only way to navigate back to the conversation history is to either delete the conversation thread or refresh the page. 

#### Expected behaviour

The "Bookmarks" button should persist even after the user unbookmarks the last conversation so they can "Clear All" and return to the conversation history. 

### Steps to Reproduce

1. Ensure that there is only one conversation bookmarked in the Saved category.
2. Navigate to the Saved bookmarks via the left sidebar and select the only bookmarked conversation to view it.
3. Unbookmark this last conversation.

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amir-ghasemi** [comment]
I can confirm this issue. Any ideas @berry-13 ?

**Comment by berry-13** [comment]
> I can confirm this issue. Any ideas @berry-13 ?

yea, looks like an easy fix
