### ISSUE TITLE
[Bug]: Session disconnects after 5 minutes

### ISSUE THREAD

**Issue by cod3d-dev** [danny-avila/LibreChat#3729]
### What happened?

I'm running LibreChat in a docker container, but after 5 minutes without writing in a chat, the session disconnects and I have to login again.

### Steps to Reproduce

1. Log in
2. Interact with any chat provided (OpenAI, Together, Ollama)
3. Wait around 5 minutes without interacting
4. When I write something in the active chat, the login screen appears

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Please read through the following discussions:

https://github.com/danny-avila/LibreChat/discussions/572
https://github.com/danny-avila/LibreChat/discussions/3001
