### ISSUE TITLE
[Bug]: error when using `@` command

### ISSUE THREAD

**Issue by RedwindA** [danny-avila/LibreChat#3737]
### What happened?

https://github.com/user-attachments/assets/cff424d5-de18-4c11-a275-93f55bd669a3

### Steps to Reproduce

press @ in the input area

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Screenshots

![image](https://github.com/user-attachments/assets/13a196b8-0b68-442a-bb77-1433beb16d7b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kukoboris** [comment]
I have the same problem too

**Comment by maxesse** [comment]
Yeah me too, just tried

**Comment by danny-avila** [comment]
Apologies for this, made some changes here. Any time this happens, it's not a mystery. Going into dev mode shows the stack trace more clearly:
![image](https://github.com/user-attachments/assets/e9a018ed-f6f4-403f-aeca-cb8b71693a08)
