### ISSUE TITLE
Enhancement: Add Button with fullscreen mode (for huggingface space important especially)

### ISSUE THREAD

**Issue by DoS007** [danny-avila/LibreChat#3775]
### What features would you like to see added?

Motivation:
1. Fullscreen-mode is more immersive, not showing the browser.
2. Using a **private huggingface space isn't so nice to use librechat** , the screen is more filled especially on mobile (see pic).

### More details

Implementation:
1. Set the own body (not huggingface space body) with `id="fullscreenElement"`, because that is what should be "fullscreened".

2. Add a `<button id="fullscreenButton">Vollbild</button>` e.g. beside the "new chat" button.

3. Add code for the fullscreen function
```
document.addEventListener('DOMContentLoaded', function() {
    var fullscreenButton = document.getElementById('fullscreenButton');
    var fullscreenElement = document.getElementById('fullscreenElement');

    fullscreenButton.addEventListener('click', function() {
        if (!document.fullscreenElement) {
            if (fullscreenElement.requestFullscreen) {
                fullscreenElement.requestFullscreen();
            } else if (fullscreenElement.mozRequestFullScreen) { // Firefox
                fullscreenElement.mozRequestFullScreen();
            } else if (fullscreenElement.webkitRequestFullscreen) { // Chrome, Safari und Opera
                fullscreenElement.webkitRequestFullscreen();
            } else if (fullscreenElement.msRequestFullscreen) { // Internet Explorer/Edge
                fullscreenElement.msRequestFullscreen();
            }
        } else {
            if (document.exitFullscreen) {
                document.exitFullscreen();
            } else if (document.mozCancelFullScreen) {
                document.mozCancelFullScreen();
            } else if (document.webkitExitFullscreen) {
                document.webkitExitFullscreen();
            } else if (document.msExitFullscreen) {
                document.msExitFullscreen();
            }
        }
    });
});
```

### Which components are impacted by your request?

UI

### Pictures
![grafik](https://github.com/user-attachments/assets/c47900e3-b6e5-4ddd-9ea1-064df4b5e6ef)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
you can already access your deployment on HF in "fullscreen", you just need to use the proper URL

example, for our demo the url is: 
embedded: https://huggingface.co/spaces/LibreChat/LibreChat
fullscreen: https://librechat-librechat.hf.space

the format is as followed:
`https://username-projectname.hf.space/`

**Comment by berry-13** [comment]
you can install a PWA app on both the demo and your own LibreChat on both your phone and PC (or just press F11). also, as @fuegovic mentioned, accessing HF in fullscreen is very easy with the right URL. What might need redesigning is the top bar on mobile, I don't like it. We should definitely remove the chat title and instead place the provider and model buttons

**Comment by DoS007** [comment]
@fuegovic Yeah, I already disabled registration. But I wouldn't like to make it public despite that because this way it's more open for hacks for security gaps.

@berry-13 Wow, thanks for your effort :). I tried it, but it does nothing for the private space in hugging space (just a shortcut to the website and still showing with brave - and hugging face header).
