### ISSUE TITLE
Enhancement: Add large pasted text as a file upload (similar to Claude UI)

### ISSUE THREAD

**Issue by AnshulJ999** [danny-avila/LibreChat#3791]
### What features would you like to see added?

In the Claude UI, if you paste a large piece of text, it automatically gets attached and treated like a document. This is very easy to use as I can just paste large pieces of text from different sources, they get treated as separate documents, and then chat with them. 

But LibreChat is more like ChatGPT, where any amount of pasted text gets added in the text box like a normal message. So having the above behavior I think is beneficial in many ways, at least as a toggle switch in the settings. 

Sorry if this is duplicated; I couldn't find anything like this in the Issues. Loving LibreChat so far; really great alternative to paying for ChatGPT, Claude, and Gemini separately.  Thanks!

### More details

Paste a large amount of text (threshold could be customizable maybe) and it will get uploaded as a TXT file instead of appearing in the chatbox. 

Second, when clicking on such a file, a UI popup opens up where we can check the file. 

### Pictures

![image](https://github.com/user-attachments/assets/6fbf480f-cf7e-4884-ab50-85ca3800f60b)

This is what I'm referring to. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks this is planned for the short-term, closing due to duplicate issue: https://github.com/danny-avila/LibreChat/issues/2755
