### ISSUE TITLE
[Bug]: Select UI never trigger with latest @headlessui/react 2.1.3

### ISSUE THREAD

**Issue by maskinoshita** [danny-avila/LibreChat#3863]
### What happened?

Select UI with @headlessui/react 2.1.3 never trigger action.
![select_ui](https://github.com/user-attachments/assets/f7ee53ae-ac2c-4473-a669-3fce9bf9c875)

workaround: downgraded @headlessui/react to 2.1.2 worked
```diff
--- a/client/package.json
+++ b/client/package.json
@@ -31,7 +31,7 @@
     "@ariakit/react": "^0.4.5",
     "@dicebear/collection": "^7.0.4",
     "@dicebear/core": "^7.0.4",
-    "@headlessui/react": "^2.1.2",
+    "@headlessui/react": "2.1.2",
     "@radix-ui/react-accordion": "^1.1.2",
     "@radix-ui/react-alert-dialog": "^1.0.2",
     "@radix-ui/react-checkbox": "^1.0.3",
```

### Steps to Reproduce

1. build and run with latest codes (I checked tagged version v0.7.4)

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
https://github.com/danny-avila/LibreChat/blob/2ce4f66218ebd8acf5cbb4c1f3c23831ffc5c737/client/package.json#L35
