### ISSUE TITLE
[Bug]: When using the plugins feature, I noticed that no matter which model type I select, the value of agentOptions.model is always gpt-4o-2024-05-13.

### ISSUE THREAD

**Issue by ptozys2** [danny-avila/LibreChat#3878]
### What happened?

When using the plugins feature, I noticed that no matter which model type I select, the value of agentOptions.model is always gpt-4o-2024-05-13.

### Steps to Reproduce

![1725196795829](https://github.com/user-attachments/assets/86aea2d6-d5a5-478b-95e5-7d6cdaa04865)

bug  reproduce :
Clear the browser cache and restart the backend service.

file : client/src/hooks/Chat/useChatFunctions.ts
func: const ask: TAskFunction
.
.

const submission: TSubmission = {
  conversation: {
    ...conversation,
    conversationId,
  },
  endpointOption,
  userMessage: {
    ...currentMsg,
    generation,
    responseMessageId,
    overrideParentMessageId: isRegenerate ? messageId : null,
  },
  messages: currentMessages,
  isEdited: isEditOrContinue,
  isContinued,
  isRegenerate,
  initialResponse,
};
**console.log('ask: Prepared submission object:', submission);** => output :model: 'gpt-4o-2024-05-13',

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
You have to go into "Agent Settings" to change the agent model. If you'd like it to be a specific model every time, I would make use of a preset and/or default preset:

https://github.com/user-attachments/assets/a95909a2-ffc3-47e0-abde-43a6a4d25d7c

**Comment by ptozys2** [comment]
nice,  good job! can work.
