### ISSUE TITLE
[Question]: How to decrease token after successfully generate DALL-E image?

### ISSUE THREAD

**Issue by nayakayp** [danny-avila/LibreChat#3901]
### What is your question?

How to decrease token after successfully generate DALL-E image?

### More Details

I know the cost for every dall-e image generation is about 3 cent per successfully generation. I want to manually decrease token like 150,000 token for every successfull image generation. 

Because currently the token will decrease only for prompt and completion. I'm thinking of that if I have to manually add some function to decrease the token after each successfully generation.

Thank you.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Not implemented, will be soon: https://github.com/danny-avila/LibreChat/discussions/1479
