### ISSUE TITLE
Enhancement: Enable function call based tools besides Assistant Endpoint

### ISSUE THREAD

**Issue by happyZYM** [danny-avila/LibreChat#3911]
### What features would you like to see added?

As more and more models other than assistant support function-calling, it will be better if external tools in OpenAPI in schema can be easily added.

### More details

For models that support function-calling, users can easily add an OpenAPI compatible tools in the right panel, just like in the Assistant Endpoint.

### Which components are impacted by your request?

UI, Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
It's in the works! https://github.com/danny-avila/LibreChat/issues/3607

![image](https://github.com/user-attachments/assets/26198fab-0e40-4c8a-88f3-6e2dafa3b4c5)
