### ISSUE TITLE
[Question]: Focus on Prompt Entry with Keyboard Only

### ISSUE THREAD

**Issue by nnnnicholas** [danny-avila/LibreChat#3923]
### What is your question?

I love LibreChat, but one thing bugs me. I can't figure out how to move cursor focus to the prompt entry text input with my keyboard. Tab key never reaches the text area. **Is there a way to focus on the text input area with the keyboard only?** i.e. cmd+k or tab key. 

### More Details

Ideally, LibreChat would open with the prompt input already focused (text cursor blinking and ready to input text).

### What is the main subject of your question?

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks for raising this issue! I will implement this sooner rather than later, there is an open issue I'm tracking and this is one of many a11y improvements I hope to get in soon: https://github.com/danny-avila/LibreChat/issues/3664
