### ISSUE TITLE
Focus does not return to settings/parameters button on dialog closure.

### ISSUE THREAD

**Issue by derekjackson-das** [danny-avila/LibreChat#3934]
**Issue Description:**
The focus moves to the top of the page when the settings/parameters dialog is closed. Expected behavior is that the focus returns to the settings/parameters button when the dialog is closed. [APG on modal/dialog patterns](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/) which describes expected pattern - see item 2 in the Notes: "When a dialog closes, focus returns to the element that invoked the dialog ... ".

**WCAG Criteria**:
[2.4.3: Focus Order (Level A)](https://www.w3.org/WAI/WCAG21/Understanding/focus-order.html)

**Screenshot or Screen Recording**:
[Screen Recording](https://share.zight.com/JruZWZ4x)

**Notes**:
The focus returns to the control element on the other buttons that have pop-up elements in the LLM controls. This will make the UI of the settings/parameters consistent with the rest of the controls.

**Comment by danny-avila** [comment]
Closing as this UI element is now deprecated
