### ISSUE TITLE
Enhancement: Redirect to chat permalink when creating a new chat

### ISSUE THREAD

**Issue by spiffytech** [danny-avila/LibreChat#3943]
### What features would you like to see added?

Once I submit a prompt for a new chat, I'd like the page URL to automatically change from `/c/new` to `/c/<chat_id>`.

This will ensure that if I reload the page, or restart my browser, I still see the same chat I was using, rather than having to fish it out of the sidebar.

### More details

This would be nice QoL on desktop, but it's even bigger on mobile, where Android loves to unload background pages if I switch to another app for too long.

### Which components are impacted by your request?

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Already implemented!
