### ISSUE TITLE
[Bug]: Copying in dark mode copies the dark style

### ISSUE THREAD

**Issue by adoxentor** [danny-avila/LibreChat#3954]
### What happened?

When copying text from an answer in dark mode, the copied content retains the dark mode styling (light text on dark background) when pasted into other applications like Google Docs.
This is unlike other writing assistance platforms, such as ChatGPT, which have implemented a fix for this issue. 

Expected behavior: The copied text should paste with default styling in the destination application, regardless of the current theme mode in our application.  

I'm opening a PR with a fix

### Steps to Reproduce

1. set to dark mode
2. copy text from an answer
3. paste into Google Docs

### Screenshots

![image](https://github.com/user-attachments/assets/c954b594-1bdb-4a4a-8598-e1b6326c158c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Nothing we can do about this, it’s a browser feature. Use the copy to clipboard buttons (below the message, or top right of code lock) or export to markdown

**Comment by fuegovic** [comment]
You can try <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>v</kbd> to paste text without any formatting

**Comment by adoxentor** [comment]
> You can try ctrl+shift+v to paste text without any formatting

It also removes semantic formatting like headings, numbering, or tables.

**Comment by adoxentor** [comment]
@danny-avila it works in ChatGPT and I copied the behavior in the pull request
