### ISSUE TITLE
[Bug]: Creating/inviting a user does not work properly with email verification/invite

### ISSUE THREAD

**Issue by RAPHCVR** [danny-avila/LibreChat#3979]
### What happened?

Using google auth to send email (thanks to the librechat doc), email are well sent for verification or invite (using npm invite-user in the docker shell). But once the user try to sign up/authenticate, an error happens, this is what I have in my LibreChat-API container logs:
- with invite-user: error: [getInvite] Error getting invite Invite not found or email does not match
- with create-user, or when signing up with verification enabled : warn: [verifyEmail] [Invalid or expired email verification token] [Email:...]

### Steps to Reproduce

1. Using librechat-api (deploy-compose)
2. Using google gmail as email sender (as mentioned here: [Gmail Setup with LibreChat](https://www.librechat.ai/docs/configuration/authentication/email#setup-with-gmail))
3. Trying to create a user/invite one, with an email interaction needed
4. I also add that I am using nginx currently for https (using the container, and the let's encrypt certificate provided by certbot)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Are you using Google Oauth2 as the sign-in option?

**Comment by RAPHCVR** [comment]
> ~~Are you using Google Oauth2 as the sign-in option?~~ 
> 
> Nevermind, I see that it's using the `crypto` package instead of `node:crypto` introduced here: https://github.com/danny-avila/LibreChat/pull/3357
> 
> Should resolve this sooner rather than later

Okey. So I am using gmail as the email povider. And I am not using another identification method, apart from the email method (but it seems there is an issue with tokens management), and Azue Entra ID (working fine).

**Comment by RAPHCVR** [comment]
Hey, I do not understand, I always have the same token error: warn: [verifyEmail] [Invalid or expired email verification token] [Email: ***]

when someone try for example to verify his email (or to answer an invite from invite-user), with a link like that:
https://website.com/verify?token=ec8747a009de2be299b97c0b713473f7f41d5435a7a471604334bcc68fbbcd8d&email=[email]

**Comment by danny-avila** [comment]
@RAPHCVR Did you update?

**Comment by RAPHCVR** [comment]
@danny-avila yeah, pulled the last docker image, tried the api and the normal one.

To mention: invite-user mail works fine, but email vérification does not.

**Comment by RAPHCVR** [comment]
@danny-avila I've set this:

 Registration and Login #
#========================#

ALLOW_EMAIL_LOGIN=true
ALLOW_REGISTRATION=false
ALLOW_SOCIAL_LOGIN=true
ALLOW_SOCIAL_REGISTRATION=true
ALLOW_PASSWORD_RESET=true
# ALLOW_ACCOUNT_DELETION=true # note: enabled by default if omitted/commented out
ALLOW_UNVERIFIED_EMAIL_LOGIN=true

SESSION_EXPIRY=1000 * 60 * 15
REFRESH_TOKEN_EXPIRY=(1000 * 60 * 60 * 24) * 7

# Email Password Reset   #
#========================#

EMAIL_SERVICE=gmail
EMAIL_HOST=
EMAIL_PORT=25
EMAIL_ENCRYPTION=
EMAIL_ENCRYPTION_HOSTNAME=
EMAIL_ALLOW_SELFSIGNED=
EMAIL_USERNAME= [sensitive]@gmail.com
EMAIL_PASSWORD=[sensitive]
EMAIL_FROM_NAME=Wonka Chat
EMAIL_FROM=[sensitive]@@gmail.com

**Comment by RAPHCVR** [comment]
@danny-avila some ideas ?
