### ISSUE TITLE
Focus on the settings tabs does not follow the applications focus.

### ISSUE THREAD

**Issue by derekjackson-das** [danny-avila/LibreChat#3981]
**Description**:  When navigating the setting tab panel with the the left and right arrow keys focus follows the applications focus and the currently active tab panel, but if I use the up and down arrow keys the focus doesn’t move to the currently active tab panel and even though the menu is changing. Expected behavior would be that the up and down arrow keys work just as the left and right arrow keys and keyboard focus moves to the currently selected tab item. 

**WCAG Criteria**: [2.1.1 Keyboard - A](https://www.w3.org/WAI/WCAG21/Understanding/keyboard)

**Screenshot**: [Screen Recording](https://share.zight.com/xQuJDzY8)

**Comment by danny-avila** [comment]
This was fixed in #4091
