### ISSUE TITLE
[Bug]: Bedrock: Dual pane Window does not work with Bedrock

### ISSUE THREAD

**Issue by dirkpetersen** [danny-avila/LibreChat#4009]
### What happened?

If I switch to dual pane/column with different models both panes produce identical output ...... then if you switch to another chat and come back to this one later the dual pane window has disappeared 

### Steps to Reproduce

1. Select Bedrock - anthropic.claude-3-5-sonnet-20240620-v1:0
2. Select new Chat 
3. Select anthropic.claude-3-5-sonnet-20240620-v1:0 if not selected 
4. Enter "Who is the most famous person in the history of Oregon. Also say which exact name and version of LLM produced the answer" (SCR1) 
5. Select meta.llama3-1-405b-instruct-v1:0
6. Hit the + sign next to the model (Note : If I hover over the plus sign to figure out what it does there is no tooltip, other things are pretty clear but this button is very useful and unique to Librechat and would deserve a tooltip) 
7.  Enter "Who is the most famous person in the history of Oregon. Also say which exact name and version of LLM produced the answer. (SCR2)
8.  verify that the output in both columns is the same 

### Relevant log output

```shell
no log output
```

### Screenshots

SCR1:
![image](https://github.com/user-attachments/assets/7cabd0eb-b9f3-4155-ac19-c57eac01260b)

SCR2:
![image](https://github.com/user-attachments/assets/34e3c30b-7d10-476c-ae34-55b9090861a2)

SCR3:
![image](https://github.com/user-attachments/assets/d2065ef8-9963-4c79-9a8c-25f5dd4b99ec)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
> then if you switch to another chat and come back to this one later the dual pane window has disappeared

For more info on this: https://github.com/danny-avila/LibreChat/issues/3659

> If I hover over the plus sign to figure out what it does there is no tooltip, other things are pretty clear but this button is very useful and unique to Librechat and would deserve a tooltip

Already noted here: https://github.com/danny-avila/LibreChat/issues/3660

> verify that the output in both columns is the same

I do not observe this:

![image](https://github.com/user-attachments/assets/28edbcf3-28b6-4073-bf01-87a9cd16d698)
![image](https://github.com/user-attachments/assets/af7bbc11-f8df-419b-a94b-5a0d0ed5ec0d)
