### ISSUE TITLE
Enhancement: Enable support for o1-preview and o1-mini

### ISSUE THREAD

**Issue by mralexhenry** [danny-avila/LibreChat#4029]
### What features would you like to see added?

Support for the new OpenAI o1-preview and o1-mini models

### More details

It looks like the logic in the OpenAIClient.JS is incorrectly categorising the new o1 models as needing to use the completions endpoint instead of the chat completions endpoint, causing an error. There may also need to be some additional logic to ensure that Librechat does not pass system prompts to the o1 models, as only user and assistant prompts are supported. 

### Which components are impacted by your request?

Endpoints

### Pictures

![image](https://github.com/user-attachments/assets/9024ee05-2b64-4f0d-a230-8d1dc924b6a9)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Already implemented: https://github.com/danny-avila/LibreChat/pull/4019
