### ISSUE TITLE
[Bug]: Bedrock: Iterator value A is not an entry object

### ISSUE THREAD

**Issue by dirkpetersen** [danny-avila/LibreChat#4053]
### What happened?

Picking and using some of the Bedrock models (e.g. ai21.jamba-instruct-v1:0) causes UI errors: `Something went wrong. Here's the specific error message we encountered: An error occurred while processing your request. Please contact the Admin.`

### Steps to Reproduce (use latest LibreChat from Github main )

1. Submit a prompt to verify the model works
2. Pick model ai21.jamba-instruct-v1:0 and submit a prompt 
3. note error
4. Switch back to previously functioning model and submit prompt
5. note error 

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
2024-09-14 18:31:26 info: Server listening on all interfaces at port 3080. Use http://localhost:3080 to access it
2024-09-14 18:36:53 error: [api/server/controllers/agents/client.js #sendCompletion] Unhandled error type The provided model identifier is invalid.
2024-09-14 18:36:53 error: [handleAbortError] AI response error; aborting request: The provided model identifier is invalid.
2024-09-14 18:38:23 error: [api/server/controllers/agents/client.js #sendCompletion] Unhandled error type Iterator value A is not an entry object
2024-09-14 18:38:23 error: [handleAbortError] AI response error; aborting request: Iterator value A is not an entry object
```

### Screenshots

![image](https://github.com/user-attachments/assets/7afe0ff6-8e78-456c-8ae0-0617a0d5e572)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Can't reproduce:
![image](https://github.com/user-attachments/assets/e1cec177-0703-413a-893c-59eafefe9ae1)

Switched bedrock models, switched endpoints, 

Working here, looks like this previous issue already addressed?

https://github.com/danny-avila/LibreChat/issues/4006

**Comment by danny-avila** [comment]
The root of the issue is this:

> 2024-09-14 18:36:53 error: [handleAbortError] AI response error; aborting request: The provided model identifier is invalid.

You may be trying to use a model only available to you in a specific region?

To really account for this, you need to make use of presets. Some backend feature to determine this for you would still need to be implemented.

**Comment by dirkpetersen** [comment]
There was no way i could get this to work at us-west-2, so i am now yanking out the ai21.jamba-instruct-v1:0 model 

```
sed -i "/^[[:space:]]*'ai21.jamba-instruct-v1:0',/s/^[[:space:]]*/&\/\/ /" \
              ${LIBRECHAT_PATH}/packages/data-provider/src/config.ts
```

and now run with "npm run backend" under systemd instead of docker.
