### ISSUE TITLE
Enhancement: Support for C# files

### ISSUE THREAD

**Issue by Nevrai** [danny-avila/LibreChat#4056]
### What features would you like to see added?

I was quite disappointed with the lack of support for C# files (.cs), as I wanted to use LibreChat for C# programming.

Is there a way to get around this, without manually converting each file to text? ChatGPT and Claude.ai both support C# files, so it's a shame that LibreChat doesn’t. I’m very impressed with LibreChat so far, but I would definitely love support for C# file attachments to be implemented, and I doubt I’m the only one who feels that way.

### More details

When attempting to attach a C# file:
![image](https://github.com/user-attachments/assets/c5d1a1c6-240e-4e3b-9528-419e036e1905)

**LibreChat version**: LibreChat v0.7.5-rc2

### Which components are impacted by your request?

General, UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
It shouldn't be a shame because we can add it :)

**Comment by danny-avila** [comment]
And technically, looking at the code, this is meant to be supported already, but the mimetype is a mismatch:

```js
  'text/x-c',
  'text/x-c++',
```

**Comment by Nevrai** [comment]
Thank you. Is there a way to fix this by configuring a file, or do I have to wait for an update to LibreChat?
