### ISSUE TITLE
Enhancement: Function calling for custom endpoint (on LiteLLM)

### ISSUE THREAD

**Issue by prachimore1406** [danny-avila/LibreChat#4060]
### What features would you like to see added?

I have deployed LiteLLM proxy for one of my nonprod environment, it is integrated with AWS Bedrock, I would like to see function/tool calling for this custom endpoint in Librechat.

### More details

It should support bring your own functions.
Basically what I am trying to do is execute some langchain based tools like from langchain's github toolkit for github operations from Librechat interface during the chat..the llm should be able to execute it from the backend based on his decisions through LiteLLM + bedrock

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prachimore1406** [comment]
Basically what I am trying to do is execute some langchain based tools like from langchain's github toolkit for github operations from Librechat interface during the chat..the llm should be able to execute it from the backend based on his decisions through LiteLLM + bedrock

**Comment by danny-avila** [comment]
See this issue: https://github.com/danny-avila/LibreChat/issues/3607
