### ISSUE TITLE
Enhancement: Google Env Var - GOOGLE_LOC

### ISSUE THREAD

**Issue by jona7o** [danny-avila/LibreChat#4065]
### What features would you like to see added?

Add GOOGLE_LOC as location environment variable for Google AI endpoint.

### More details

GoogleClient.js defines the location for all calls to us-central1. It would be great if an environment (e.g. GOOGLE_LOC) variable could be added to allow you to switch to a different location for the ai api calls. For example, as a European user, **_europe-west3_** would be a better choice due to GDPR.

```js
const loc = process.env.GOOGLE_LOC || 'us-central1' //current: const loc = 'us-central1';
const publisher = 'google';
const endpointPrefix = 'https://${loc}-aiplatform.googleapis.com';
```

### Which components are impacted by your request?

GoogleClient.js

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by schnaker85** [comment]
can you make sure this is used for the vertex AI calls? see my comment: https://github.com/danny-avila/LibreChat/discussions/3275
