### ISSUE TITLE
Enhancement: Private Assistants sharing with other users

### ISSUE THREAD

**Issue by leondape** [danny-avila/LibreChat#4073]
### What features would you like to see added?

- [X] 1. create private assistants
- [ ] 2. still leave access to organisation wide assistants specified in librechat.yml
- [ ] 3. give ability to share private assistants with other users

### More details

As this is just a vague first description I have nothing more to add. 
Happy to discuss your thoughts on this.

### Which components are impacted by your request?

UI, Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Currently not planned as this functionality will be built in for Agents
