### ISSUE TITLE
Unclear Name and Role for File Type Options in Export Modal

### ISSUE THREAD

**Issue by derekjackson-das** [danny-avila/LibreChat#4098]
**Issue Description**:
The name for the file type options in the export modal is currently set to "Select an option," which is not descriptive or unique for this button. The purpose of the button is unclear, leading to confusion for users relying on accessible names.

**WCAG Criteria**:
[2.4.6 Headings and Labels - AA](https://www.w3.org/WAI/WCAG21/Understanding/headings-and-labels.html)

**Snippet:**
```
<button data-testid="dropdown-menu" class="btn-neutral focus:ring-offset-ring-offset relative inline-flex w-auto items-center justify-between rounded-md border-border-light bg-header-primary py-2 pl-3 pr-8 text-text-primary transition-all duration-100 ease-in-out hover:bg-header-hover focus:ring-ring-primary" aria-label="Select an option" id="headlessui-listbox-button-:rbi:" type="button" aria-haspopup="listbox" aria-expanded="false" data-headlessui-state=""></button>

```
<img width="1407" alt="Screenshot 2024-09-17 at 4 41 18 PM" src="https://github.com/user-attachments/assets/936c5949-470e-497e-8a93-1904dbafadfa">

**Note**:
A more accurate name would be "File Type." The visible label above the button should also match the accessible name, so the text above the button should read "File Type" as well.

If reconfiguring with Ariakit components, the select component looks like a viable replacement. See [Ariakit Select](https://ariakit.org/components/select).

**Comment by danny-avila** [comment]
Closed by https://github.com/danny-avila/LibreChat/pull/4091
