### ISSUE TITLE
[Question]: Define Parameters for Custom Endpoints

### ISSUE THREAD

**Issue by lestremm** [danny-avila/LibreChat#4103]
### What is your question?

Is there currently any way to add custom parameters to a custom endpoint?

### More Details

We are currently investigating LibreChat as a possible frontend for our custom LLM, which will function as a RAG. So far we are very pleased and congratulations on this great work!

What I have not yet been able to fully understand is how I can work with the parameters. The last commit #4092 has already clarified a lot, but it is still unclear whether and how I can add custom parameters. Specifically, our custom endpoint uses a number of additional parameters, e.g. "ID". I would like to configure these on the right in the SidePanel and then pass them in the Api call. In the latest version, I can at least use the instructions for this, but I would like to have a more user-friendly version with several fields and validation.

So far I have tried to adjust the components/SidePanel/Parameters/settings.ts and the field appears but the entered value disappears immediately. Furthermore, I suspect that I would also have to adapt the API.

I think for many with a custom endpoint this would be a great thing and I look forward to a short feedback!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
not yet: https://github.com/danny-avila/LibreChat/issues/4027
