### ISSUE TITLE
[Bug]: Unable to edit or delete bookmark tags containing '#' character

### ISSUE THREAD

**Issue by rnavarroz** [danny-avila/LibreChat#4161]
### What happened?

Creating bookmarks with '#' character will make  all its functionality is broken. When you want to edit it or delete it will throws  the message "There was an error updating the bookmark."

### Steps to Reproduce

1. Click on the "Bookmarks" module in the right sidebar to expand it.
2. Click button "New Bookmark" under "Bookmarks" in the right sidebar to open a dialog.
3. In the dialog, enter a title that contains a character like # (for example, "Test #1").
4. Click the "Save" button in the dialog to dismiss it.
5. Find your new bookmark tag in your list of bookmarks and click the edit icon (a pencil) next to it to open the "Bookmark" dialog again.
6. Edit the title or description, then click the "Save" button on the dialog to dismiss.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Screenshots

![bookmark-v0 7 5-rc2](https://github.com/user-attachments/assets/f4dadbcb-996c-4903-96b4-3da76bc3e18d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks, I see the issue and will resolve it soon
