### ISSUE TITLE
Low contrast on slider buttons.

### ISSUE THREAD

**Issue by derekjackson-das** [danny-avila/LibreChat#4163]
**Issue Description**:
The slider buttons in the Controls side bar do not have sufficient contrast for non-text elements. According to WCAG 2.1, the required minimum contrast ratio is 3:1, but the toggles in the "off" state currently have a contrast ratio of about 1.3:1. Low-vision users may have difficulty identifying and using the controls. This contrast issue also affects other toggle buttons and some sliders across the application.

related to #4162 

WCAG Criteria:
[1.4.11 Non-text Contrast - AA](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast)

**Screenshot**
<img width="356" alt="Screenshot of sliders in the control panel" src="https://github.com/user-attachments/assets/9a14be42-eaef-483e-8ecd-a86aab4b6296">

<img width="1109" alt="Screenshot of contrast analyser showing contrast of buttin slider is 1.5 to 1." src="https://github.com/user-attachments/assets/30e87d1e-7421-4696-a858-531a96d0dbb4">

**Action and Notes**:

Adding an outline to the slider button or the entire control should help meet WCAG requirements.
This contrast issue also occurs with other toggle buttons and sliders across the application.
Example fixes:
<img width="347" alt="Screenshot 2024-09-20 at 11 03 06 AM" src="https://github.com/user-attachments/assets/95d2dee7-b637-42ce-8a9c-1824388cabd7">

<img width="351" alt="Screenshot 2024-09-20 at 11 09 15 AM" src="https://github.com/user-attachments/assets/ee16c152-ac03-4c72-a7e0-ccb12d9c239b">

**Comment by danny-avila** [comment]
Closed by https://github.com/danny-avila/LibreChat/pull/4091
