### ISSUE TITLE
Enhancement: Function Naming Capability in Assiattn

### ISSUE THREAD

**Issue by hanna-daoud** [danny-avila/LibreChat#4185]
### What features would you like to see added?

Add the option to name the function being generated in OpenAI side.

### More details

In the attached images, the name being generated is following the API name and endpoint along with he prefix action. We need to have the option to name it manually.

### Which components are impacted by your request?

General, UI

### Pictures

![image](https://github.com/user-attachments/assets/45001131-1987-4776-81b1-2f1808ec0ade)
![image](https://github.com/user-attachments/assets/cdd898cb-bced-4768-a51b-da1234e7b353)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
The current naming pattern is required. 

First, the schema method, then an "action" placeholder, followed by the domain (or an encoded version of the domain).

This is all necessary for actions to work the way they do in LibreChat
