### ISSUE TITLE
Enhancement: Fill-Out Chat using Query parameters

### ISSUE THREAD

**Issue by leondape** [danny-avila/LibreChat#4186]
### What features would you like to see added?

I thought it would be cool to being able to to insert things into the chat, probably the easiest via query parameters (though this could lead to long urls).
That way, chats could be "prepared" by other chats, agents or even other apps, and then with a simple click, added to a new chat. 
Then the user can further edit the chat and send it. 

### More details

https://chatservice.tld/insertRoute?ChatContent=What+is+the+meaning+of+life+?
Clicking on the url would open LeoChat with the chat filled out with the Content. 
Also possible: A dialogue like with the prompts from sidebar? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Already implemented, see https://github.com/danny-avila/LibreChat/issues/1343, where I wrote:

this is already possible with prompts:

`your-librechat-instance/c/new?prompt=Hello+World`

I have not added supported for models/endpoints, though. I will and then close this issue
