### ISSUE TITLE
[Bug]: Unarchiving a chat requires 2 attempts and creates a blank chat

### ISSUE THREAD

**Issue by KiGamji** [danny-avila/LibreChat#4188]
### What happened?

When I try to unarchive a chat, it almost immediately gets moved back to the archived chats list. Additionally, a blank "New Chat" without any icon is created. This "New Chat" persists across different browsers but is unclickable; nothing happens in the debug logs when I attempt to delete, rename, or open it — not even a string appears after /c in the address bar. The chat is successfully unarchived on the second try without exiting the tab, and the "New Chat" remains until I archive it (however, nothing is then added to the archived chats list).

### Steps to Reproduce

1. Archive a chatю
2. Try to unarchive the chat by pressing the button once. It will then revert to being archived, and you will see a bugged "New Chat" in your chat list.
3. Go to the archived chats again and try pressing the unarchive button two or more times. The chat will eventually get unarchived, still leaving a bugged chat.

### Screenshots

![image](https://github.com/user-attachments/assets/57a33cbd-3e4d-42e3-809f-2fe391531e68)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I'm looking into this, thanks for the report

**Comment by danny-avila** [comment]
Fixed in #4189, and those "bugged" conversations should be automatically removed next time you start the app with the latest update.
