### ISSUE TITLE
Enhancement: Delete button for messages

### ISSUE THREAD

**Issue by nxfi777** [danny-avila/LibreChat#4236]
### What features would you like to see added?

It's great that you can edit messages, but it would be nice to be able to delete them (like with v0)

### More details

.

### Which components are impacted by your request?

General, UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This issue exists already: https://github.com/danny-avila/LibreChat/issues/2673
