### ISSUE TITLE
[Bug]: Deleting account in german

### ISSUE THREAD

**Issue by MarcelRei** [danny-avila/LibreChat#4262]
### What happened?

If you switch your account to german and try to delete your account the delete process doesn't accept the word LÖSCHEN for some reason and you are not able to delete your account.
Switching the language to english allows you to delete your account. 
I guess the Ö is the issue somewhere

### Steps to Reproduce

1. Login to your account in the webfrontend
2. Switch the language to german
3. follow the instructions under account to delete the account

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by berry-13** [comment]
Thank you for reporting this. While I believe users should type "DELETE" regardless of their language, I understand the need for a more inclusive solution. I'll work on addressing this issue and test it with several Latin-based languages as well as Chinese.

If anyone encounters a similar problem with a language not mentioned above, please let us know in this thread

**Comment by MarcelRei** [comment]
Yes, DELETE works, and changing the language to french and spanish asks to type DELETE.

**Comment by danny-avila** [comment]
@berry-13 in my opinion, I think it's enough to write your email, this reduces the complexity and the discrepancy in languages.

**Comment by danny-avila** [comment]
and perhaps to keep a "second step" we can make sure the button requires 2 clicks, with a "confirm" step saying "are you sure?"

**Comment by MarcelRei** [comment]
I think a confirm step like you suggested would be easier.

**Comment by berry-13** [comment]
fixed in #4438
