### ISSUE TITLE
[Bug]: Google tool missing from assistant endpoints (assistants, azureAssistants) in 0.7.5-rc2

### ISSUE THREAD

**Issue by dareima** [danny-avila/LibreChat#4272]
### What happened?

After updating to 0.7.5-rc2, the 'Google' tool is missing from the assistants and azureAssistants endpoints.
The Google search tool is still available to be used with the Plugins endpoint but not with the mentioned assistants endpoints.
This worked great in 0.7.4 and 0.7.5-rc1.

The Google tool still works as long as the assistant isn't updated through the LibreChat UI. However, as soon as one clicks on 'Save' in the Assistant Builder, the tool will be removed from the Azure assistant (or OpenAI assistant).

### Steps to Reproduce

1. Make sure to have `includedTools: ["google","azure-ai-search", "dalle"] ` set in `librechat.yaml`.
2. Update LibreChat to the `latest` release to get `0.7.5-rc2`.
3. Make sure to have no ModelSpecs in place and enable the Assistant Builder in the right sidebar.

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Screenshots

![image](https://github.com/user-attachments/assets/f0f2f356-914a-492e-8178-e6e29929a03c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Pushing a fix for this tmrw

**Comment by dareima** [comment]
Thank you!
