### ISSUE TITLE
[Bug]: Newline sends prompt instead of adding a newline on mobile 

### ISSUE THREAD

**Issue by darkBuddha** [danny-avila/LibreChat#4277]
### What happened?

Hi, it is not possible to add new lines in the prompt while on mobile. If you want to grow / enterprise use, mobile must be supported.

### Steps to Reproduce

Enter a prompt and press “return” on iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This is already implemented. You have to enable the option from Account settings

**Comment by danny-avila** [comment]
https://github.com/user-attachments/assets/e858e6a2-349d-4c66-9ab4-bc53170c0479

**Comment by danny-avila** [comment]
It’s based on local storage so it’s browser specific
