### ISSUE TITLE
[Bug]: Modal Terms of Service Buttons are not visible when signing up using firefox.

### ISSUE THREAD

**Issue by johnm-dta** [danny-avila/LibreChat#4285]
### What happened?

When signing up using firefox and there are modal terms of service enforced, the box pops up but the two boxes for accept and reject are not visible. 

They are rendering and you can drag select to highlight and then click on them to accept.

### Steps to Reproduce

1. Setup librechat using the latest container. Configure it with a modal terms of service.
2. Try to sign on using google oauth.
3. The buttons for accept and reject are the same colour as the background.

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MarcelRei** [comment]
The problem is also present in Chrome

**Comment by danny-avila** [comment]
This is already fixed here: https://github.com/danny-avila/LibreChat/pull/4169

**Comment by johnm-dta** [comment]
Thanks, sorry for the spam!
