### ISSUE TITLE
[Bug]: cannot set user provided API key to expire "never" if key previously had an expiry date

### ISSUE THREAD

**Issue by normunds-wipo** [danny-avila/LibreChat#4293]
### What happened?

If we use _user_provided_ keys, we have an option to set the key from UI and provide the expiry period. However once we set a particular expiry period we cannot set it to "never" anymore, the expiry period stays as it was.

This is just for the record, I have a fix that we use in our deployment and I will submit a pull request to fix this issue

### Steps to Reproduce

1. enter custom API key and set the expiry to say 12 hours
2. check the key in database, the expireAt date is set correctly 12 hours ahead
3. enter the same custom API key and set the expiry to "never"
4. check the key in database, the expireAt date has not changed (expected no expireAt field)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thank you!
