### ISSUE TITLE
[Bug]: Attaching files to assistants does not work

### ISSUE THREAD

**Issue by OskarVismaDev** [danny-avila/LibreChat#4295]
### What happened?

I uploaded several files to an assistant using the assistant builder in the right side-panel with the expectation that I would be able to use these files in my chats with the assistant. It's my understanding that this is supposed to work through the code interpreter. However, no matter what I do, the assistant can't seem to access these files. Also when I refresh the page any uploaded files are gone from the assistant.
I would expect the files to stay uploaded to the assistant and be accessible through the assistants code interpreter abilities.

### Steps to Reproduce

Step 1. Upload one or more files to a new assistant, that has code interpreter enabled, using the Assistant builder.
Step 2. Save and update the assistant.
Step 3. Try to ask something about the files or what files the assistant has access to.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Mobile (iOS), Mobile (Android)

### Screenshots

<img width="332" alt="Screenshot 2024-09-30 at 19 45 08" src="https://github.com/user-attachments/assets/1041a778-5a6d-4c75-b43c-95eca3877e40">
<img width="1233" alt="Screenshot 2024-10-01 at 14 48 18" src="https://github.com/user-attachments/assets/d6d96a14-d9c3-42f7-aaa9-147a00c3bc8d">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RodrigoX1** [comment]
I also agree that this feature is very important for the assistants. As a workaround, I am uploading the files directly through the OpenAI assistant constructor at https://platform.openai.com/playground/assistants.

**Comment by danny-avila** [comment]
It used to work but something happened on OpenAI’s side in the last few weeks. I am aware and will investigate when I can.
