### ISSUE TITLE
[Bug]: Experimental Agents with custom endpoints breaking if return type not string

### ISSUE THREAD

**Issue by hanna-daoud** [danny-avila/LibreChat#4325]
### What happened?

After my fix in PR #4324, I tried my endpoint that returns a boolean, it was executed on my endpoint successfully but the assistant threw the error in the screenshot

### Steps to Reproduce

1. Add an action to the assistant that returns a boolean
2. tell the assistant to execute it
3. it will run till the end, execute it, but fail with the provided error

This is the action I was trying to run

```
openapi: 3.0.3
info:
  title: Execute action on Local machine
  version: '1.0.0'
servers:
  - url: http://localhost:3000
paths:
  /gateway/execute:
    post:
      summary: Execute action on Local machine
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: string
                  description: The action to execute.
              required:
                - data
      responses:
        '200':
          description: Successful execution
          content:
            application/json:
              schema:
                type: boolean
                description: A boolean indicating the success or failure of the execution.
        '400':
          description: Bad request
        '500':
          description: Internal server error
components:
  schemas:
    ExecuteSqlParams:
      type: object
      properties:
        data:
          type: string
      required:
        - data
```

### What browsers are you seeing the problem on?

Chrome

### Screenshots

![image](https://github.com/user-attachments/assets/40c6b732-7328-4e6f-b911-02f6bc9e348f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
See this message: https://github.com/danny-avila/LibreChat/discussions/4303#discussioncomment-10815563
