### ISSUE TITLE
[Bug]: Actions having same domain but different ports issue

### ISSUE THREAD

**Issue by hanna-daoud** [danny-avila/LibreChat#4378]
### What happened?

When attempting to add two separate actions, both hosted on localhost (with either the same or different ports), the second action overrides the first one in the "OpenAI Functions" section of the assistant settings dashboard. Despite this issue, both actions remain visible in LibreChat's UI, and there are no display issues there.

I have verified that chaining multiple routes under a single OpenAPI configuration works without issue, whether using the same or different hostnames. The problem specifically arises when adding distinct actions bith having the same server url with different port, where the second action replaces the first in the OpenAI functions area.

### Steps to Reproduce

1. Create two separate actions with different functionality, both hosted on localhost (can use the same or different ports).
2. Observe that the second action overrides the first action in the assistant settings, though both actions remain visible in LibreChat's UI.
3. Go to the first action (which function is already wiped from OpenAI), and press update, it will override the second action's function

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I don't see a strong use case for taking into account `localhost`. Actions on the same domain should share openapi specs, and production servers should not expose ports. PRs welcome but I won't work on this.

**Comment by hanna-daoud** [comment]
I agree, cheers!
