### ISSUE TITLE
Enhancement: Update Token Values for gpt-4o because it now points to the gpt-4o-2024-08-06

### ISSUE THREAD

**Issue by hongkai-neu** [danny-avila/LibreChat#4386]
### What features would you like to see added?

Update the token calculations for the `gpt-4o` model to use the `gpt-4o-2024-08-06` model's pricing because `gpt-4o` now points to the `gpt-4o-2024-08-06` model.

### More details

`gpt-4o` has been pointed to the  `gpt-4o-2024-08-06` since Oct 3rd, 2024. Source: [X](https://x.com/edwinarbus/status/1841934440140046596), [API Docs](https://platform.openai.com/docs/models/gpt-4o).

The token caculations for `gpt-4o` should now be based on the `gpt-4o-2024-08-06` model, which is $2.50/1m prompt tokens and $10/1m completion tokens. The legacy model `gpt-4o-2024-05-13` should be caculated as $5/1m prompt tokens and $15/1m completion tokens.

### Which components are impacted by your request?

Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Closed by https://github.com/danny-avila/LibreChat/pull/4387
