### ISSUE TITLE
[Bug]: Google does not allow TOP_K to be a float, fix the UI slider type

### ISSUE THREAD

**Issue by Originalimoc** [danny-avila/LibreChat#4403]
### What happened?

```
{
  "attemptNumber": 1,
  "level": "error",
  "message": "[GoogleClient] There was an issue generating the title [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-pro:generateContent: [400 Bad Request] Invalid value at 'generation_config.top_k' (TYPE_INT32), 37.35 [{\"@type\":\"type.googleapis.com/google.rpc.BadRequest\",\"fieldViolations\":[{\"field\":\"generation_config.top_k\",\"description\":\"Invalid value at 'generation_config.top_k' (TYPE_INT32), 37.35\"}]}]",
  "retriesLeft": 2,
  "stack": "Error: [400 Bad Request] Invalid value at 'generation_config.top_k' (TYPE_INT32), 37.35 [{\"@type\":\"type.googleapis.com/google.rpc.BadRequest\",\"fieldViolations\":[{\"field\":\"generation_config.top_k\",\"description\":\"Invalid value at 'generation_config.top_k' (TYPE_INT32), 37.35\"}]}]\n    at makeRequest (/app/node_modules/@google/generative-ai/dist/index.js:216:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async generateContent (/app/node_modules/@google/generative-ai/dist/index.js:525:22)\n    at async /app/node_modules/@langchain/google-genai/dist/chat_models.cjs:206:26\n    at async RetryOperation._fn (/app/node_modules/p-retry/index.js:50:12)",
  "status": 400
}
```

### Steps to Reproduce

Use default Google endpoint and set top_k to a float.
I guess everyone maybe not just Google might through an error anyway since it does not makes sense since unit is 1 token?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ed-parsadanyan** [comment]
I second this. Same for Claude models (i.e. 3.5-sonnet)
![image](https://github.com/user-attachments/assets/01e58ea0-8577-4653-bafe-1fc73be10a60)

**Comment by scpedicini** [comment]
There also needs to be a way to turn off parameters from being sent at all - Top P / Top K are unnecessary when sending a temperature value to Anthropic. From a UI/UX perspective either a "checkbox" or dragging slider all the way down goes from `0.0` to `N/A`.

**Comment by danny-avila** [comment]
> There also needs to be a way to turn off parameters from being sent at all - Top P / Top K are unnecessary when sending a temperature value to Anthropic. From a UI/UX perspective either a "checkbox" or dragging slider all the way down goes from `0.0` to `N/A`.

They are not sent if they are not configured., but I agree there should be some way to disable them.

**Comment by danny-avila** [comment]
> I second this. Same for Claude models (i.e. 3.5-sonnet)

this only happens when you explicitly set a non-integer

**Comment by danny-avila** [comment]
the Google endpoint needs some more TLC but I resolved the step issue with the topk slider.

**Comment by scpedicini** [comment]
@danny-avila When you create a custom preset based off a third party LLM, how do you not "configure" those values? Because I created a custom preset off Sonnet with a Temp of 0.5 and did not alter the `top_k/top_p` values but it looks like those values are still being sent to Anthropic at least according to the logs.

```
2024-10-23T21:39:03.073Z debug: [AnthropicClient]
{
  model: "claude-3-5-sonnet-20241022",
  stream: true,
  stop_sequences: undefined,
  temperature: 0.5,
  metadata.user_id: "158199ee0d641f70157e4",
  top_p: 0.7,
  top_k: 5,
  // 5 message(s)
  messages: [snip],
  max_tokens: 8192,
  // 1 system(s)
  system: [{"type":"text","text":"\nYou are Claude Coder","cache_control":{"type":"ephemeral"}}],
}
```

**Comment by danny-avila** [comment]
@scpedicini This is not observed in the latest updates:

![image](https://github.com/user-attachments/assets/dc8dd739-3f39-4011-9831-638943823479)

![image](https://github.com/user-attachments/assets/fcab01fd-e079-494b-a066-9bf800dffccf)

```bash
2024-10-24T14:18:20.260Z debug: [AnthropicClient]
{
  model: "claude-3-5-sonnet-20241022",
  stream: true,
  stop_sequences: undefined,
  temperature: 0.5,
    metadata.user_id: "6640b7d73f29bdd33b5b8882",
  top_p: undefined,
  top_k: undefined,
  // 1 message(s)
  messages: [{"content":"hi","role":"user"}],
  max_tokens: 8192,
}
```

I'll be issuing a release today so you can update.

**Comment by danny-avila** [comment]
You may need to create a new preset with the latest updates installed.
