### ISSUE TITLE
[Bug]: Google Endpoint Balance Issues

### ISSUE THREAD

**Issue by mattj2332** [danny-avila/LibreChat#4408]
### What happened?

When CHECK_BALANCE is set to true, users are able to bypass the lack of tokens assigned to their account by switching to Google.  OpenAI, Anthropic and all other providers honour the CHECK_BALANCE setting.

Currently running 0.7.5-rc2

### Steps to Reproduce

1. Set CHECK_BALANCE=true in .env
2. Ensure that a valid API Key is present for Google and any other providers that will be tested.
3. Start LibreChat
4. Login with a user who has no balance assigned or insufficient balance
5. Change the provider to Google
6. Send a message

Step 6 should respond with insufficient funds.

Repeating steps 5 and 6 with OpenAI results in Insufficient Funds message as per screenshot

### Screenshots

![image](https://github.com/user-attachments/assets/49e708c6-9bb5-4f5b-857b-4819575ca0ba)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chihebIA** [comment]
I think the issue is caused by this snippet in api/app/clients/BaseClient.js
`    if (
      isEnabled(process.env.CHECK_BALANCE) &&
      supportsBalanceCheck[this.options.endpointType ?? this.options.endpoint]
    ) {
      await checkBalance({
        req: this.options.req,
        res: this.options.res,
        txData: {
          user: this.user,
          tokenType: 'prompt',
          amount: promptTokens,
          model: this.modelOptions.model,
          endpoint: this.options.endpoint,
          endpointTokenConfig: this.options.endpointTokenConfig,
        },
      });
    }
`

**Comment by danny-avila** [comment]
Also #4580

The root cause of these issues is that Google had not published their prices for a long time when it was implemented, as their models were in "free trial."

I have a series of changes planned for the Google Endpoint that should address this.

**Comment by KiGamji** [comment]
@mattj2332 as it is solved, you can close the issue

**Comment by mattj2332** [comment]
Brilliant, thanks for the awesome work.
