### ISSUE TITLE
[Bug]: code artifact - DependencyNotFoundError Could not find dependency: 'vue' relative to '/App.tsx'

### ISSUE THREAD

**Issue by sambazhu** [danny-avila/LibreChat#4414]
### What happened?

when i make Vue 3 Investment Product Page

### Steps to Reproduce

1 prompt
2 code
3 preview

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This is not a reproducible issue and doesn’t pertain to the codebase at main branch. Please start a troubleshooting discussion with more information
