### ISSUE TITLE
Enhancement: Support for Vertex AI model 'gemini-1.5-pro-002'

### ISSUE THREAD

**Issue by schnaker85** [danny-avila/LibreChat#4440]
### What features would you like to see added?

hi guys, 

Currently, the supported models are for Vertex AI are

```
# Vertex AI
# GOOGLE_MODELS=gemini-1.5-flash-preview-0514,gemini-1.5-pro-preview-0514,gemini-1.0-pro-vision-001,gemini-1.0-pro-002,gemini-1.0-pro-001,gemini-pro-vision,gemini-1.0-pro,gemini-1.5-pro-001
```

We would like to use the _gemini-1.5-pro-002_. We already tried and it resulted in an error while processing the response.  (We simply switched the model from gemini-1.5-pro-001 to gemini-1.5-pro-002).
See the attached Screenshot and the log entries.

Thanks and Cheers
dani

### More details

Log Output: 
```
2024-10-17T08:11:11.229Z debug: Creating VertexAI client
2024-10-17T08:11:11.236Z debug: [saveConvo] api/app/clients/BaseClient.js - saveMessageToDatabase #saveConvo
2024-10-17T08:11:18.338Z error: [handleAbortError] AI response error; aborting request: Aborted
2024-10-17T08:11:18.339Z warn: AI Response error for conversation a6f672c3-713e-4510-84d2-9b045d40a7e5 likely caused by Google censor/filter
2024-10-17T08:11:18.339Z error: [handleAbortError] error while trying to abort message Cannot set headers after they are sent to the client

```

### Pictures

![image](https://github.com/user-attachments/assets/99265220-6d8d-4d61-aa60-1f2018aa3284)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Dual-0** [comment]
works on my site:

![image](https://github.com/user-attachments/assets/81adc3e8-9cdc-44bc-8e02-1a74a37dc1b6)

**Comment by JeongJuhyeon** [comment]
> works on my site:
> 
> ![image](https://private-user-images.githubusercontent.com/37346547/378877862-81adc3e8-9cdc-44bc-8e02-1a74a37dc1b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NDkwODksIm5iZiI6MTcyOTY0ODc4OSwicGF0aCI6Ii8zNzM0NjU0Ny8zNzg4Nzc4NjItODFhZGMzZTgtOWNkYy00NGJjLThlMDItMWE3NGEzN2RjMWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDAxNTk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4MGE1NmI5NWM3ZDdjYWNlYWYzOWJmYjg3ZDU4ZWNmN2Y3OTY5NzhiYWFiZjJmMzE2MzFmNWI4MDEzOGRkNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WCNzdwtk_ONzq1b7q_LTo_JO_mTALb2YeuMROF6j_k0)

Try with a longer prompt that will generate a longer completion. As you can in see the original post it works until a certain point where it stops generating.

I can confirm that I am seeing the same issue: https://github.com/danny-avila/LibreChat/discussions/4283

Similar here: https://github.com/danny-avila/LibreChat/discussions/4358

**Comment by djuillard** [comment]
Thanks Danny. 
Yet, I updated the app, but I still have the issue. What is strange is that the first completion was particularly long (whereas there used to be an error after a few lines). And when I tested even more while asking for an even longer response, the second completion crashed after a few lines. Same error code as before : 

![image](https://github.com/user-attachments/assets/da02bc36-78be-47d4-b898-227a3068dc95)


And I still the same error messages in the log.

![image](https://github.com/user-attachments/assets/c00a42d1-3b22-4d19-8cde-3a1b06cab758)

**Comment by mansiibm** [comment]
Hi, yes I am also experiencing the same issue with the model - 
![image](https://github.com/user-attachments/assets/b2e33196-891a-416d-a7ce-1a015b13dc45)

**Comment by danny-avila** [comment]
@mansiibm you need to update, several users have confirmed the issue is fixed

**Comment by mansiibm** [comment]
Hi Danny thanks for replying, I am using the v07.6-rc1 version in the picture I shared above. Thanks

**Comment by danny-avila** [comment]
![chrome_FnFpsGC1uQ](https://github.com/user-attachments/assets/b7ac37a9-060d-4eaf-ada0-5979aa118f74)

Tried on Vertex AI, using `gemini-1.5-pro-preview-0409`

https://www.librechat.ai/docs/local/docker#update-librechat
