### ISSUE TITLE
[Bug]: delete conversation modal UI error

### ISSUE THREAD

**Issue by zjjxwhh** [danny-avila/LibreChat#4469]
### What happened?

When the language is set to Chinese, the "Delete Conversation" modal UI is incorrect

### Steps to Reproduce

1. Settings - General - Language, switch language to Chinese ("中文")
2. Try deleting any conversation and a confirmation modal will appear
3. The "Cancel" ("取消") button's UI has become a vertical rectangle, whereas it should actually be horizontal like the "Delete" ("删除") button on the right.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
None
```

### Screenshots

![image](https://github.com/user-attachments/assets/370cd499-2b0f-40d9-b648-f1dd0779f8ae)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks for your report! We will address it today
