### ISSUE TITLE
Enhancement: Support Numbered Lists

### ISSUE THREAD

**Issue by darkBuddha** [danny-avila/LibreChat#4472]
### What features would you like to see added?

Hi, is it planned that LibreChat will support numbered lists on the most popular kind of devices (mobile)? 

### More details

A numbered list shall show the numbers of the list, e.g. `10.` shall be shown as `10.` and not as `.0.`, which doesn't make any sense.

### Which components are impacted by your request?

UI

### Pictures

![IMG_9563](https://github.com/user-attachments/assets/ed83c2ce-9a2f-423b-a5a7-3b7ffa48dcfa)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
There's an open issue about this already: https://github.com/danny-avila/LibreChat/issues/4120
