### ISSUE TITLE
[Bug]: User accounts without finishing e-mail verification unintendedly removed

### ISSUE THREAD

**Issue by tak-kanno** [danny-avila/LibreChat#4473]
### What happened?

First of all, thank you for developing such an outstanding tool! I really appreciate the effort and skill that has gone into making it so useful and effective.

It is unclear whether this is a bug, or intended behavior, or just our misunderstanding. However, we appreciate if you would check the following behavior.

User accounts with unverified email addresses are suddenly being deleted. This issue occurs when Email Password Reset is enabled and the email-related settings are active in the .env file, and the setting ALLOW_UNVERIFIED_EMAIL_LOGIN is set to true.

Under these conditions, when a new account is created, the user should be able to use LibreChat without email verification. However, in practice, an expiresAt field is added to the database, causing the account to be deleted one week after the expiration period.

This phenomenon leads to two UX-related issues:

Since users can log in without completing email verification, they may be unaware that their email address remains unverified.

Administrators may use these settings not for the purpose of enhancing security through user authentication, but merely to provide a password reset service. When these settings are configured with the latter intention, user accounts may be deleted contrary to the administrator's intent.

### Steps to Reproduce

1. Configure .env file as follows:
ALLOW_EMAIL_LOGIN=true
ALLOW_REGISTRATION=true
ALLOW_SOCIAL_LOGIN=false
ALLOW_SOCIAL_REGISTRATION=false
ALLOW_PASSWORD_RESET=true
ALLOW_UNVERIFIED_EMAIL_LOGIN=true

EMAIL_SERVICE=
EMAIL_HOST=smtp.example.com
EMAIL_PORT=465
EMAIL_ENCRYPTION=tls
EMAIL_ENCRYPTION_HOSTNAME=
EMAIL_ALLOW_SELFSIGNED=
EMAIL_USERNAME=LibreChat@example.com
EMAIL_PASSWORD=example_password
EMAIL_FROM_NAME=MyOrganizationName_LibreChat_Admin
EMAIL_FROM=LibreChat@example.com
2. Create user account, but ignore the received email and do not push the `Verify Email` button in the mail body.
3. Wait two weeks after account creation, or just check the raw database record which contains `expriesAt` field.

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell
I could not find the log about user deletion, but the raw mongodb record of the unverified user is following (I modified some fields for privacy reasons.)

  {
    _id: ObjectId('12345678901234567890'),
    name: 'User Name',
    username: 'example',
    email: 'example@example.com',
    emailVerified: false,
    password: '12345678901234567890',
    avatar: null,
    provider: 'local',
    role: 'USER',
    plugins: [],
    expiresAt: ISODate('2024-10-16T01:48:34.263Z'),
    termsAccepted: false,
    refreshToken: [],
    createdAt: ISODate('2024-10-09T01:48:34.265Z'),
    updatedAt: ISODate('2024-10-09T01:48:34.265Z'),
    __v: 0
  },
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by berry-13** [comment]
thanks for reporting. while implementing email verification, I didn't think about this

**Comment by danny-avila** [comment]
@berry-13 I think this might've been fixed already, but I will have to test it to be sure.

**Comment by tak-kanno** [comment]
Sorry, I was using older version #4291.

**Comment by danny-avila** [comment]
@tak-kanno No worries, I can see this is indeed happening as you said.

This is a bit of an edge case, since it's implied that enabling email services would require email verification. However, to boost customization and since configuration allows many options for this, I will follow the logic you expect.

It should be relatively easy to fix, but I'm sorry your users were affected.

**Comment by danny-avila** [comment]
Closing with #4482:

1. If the system is set to allow unverified email logins, it will no longer set an expiration date for new user accounts.

2. For existing users created before this change, if unverified emails are now allowed, the system will remove any expiration date from their account.

3. The system will still send verification emails if email services are enabled, even if unverified logins are allowed.

**Comment by danny-avila** [comment]
> Since users can log in without completing email verification, they may be unaware that their email address remains unverified.

I agree on this point, that users should be reminded on every login that their email remains unverified. @berry-13 maybe you can help with this.
