### ISSUE TITLE
[Bug]: The application crashes when switching the Agent's model

### ISSUE THREAD

**Issue by RedwindA** [danny-avila/LibreChat#4485]
### What happened?

.

### Steps to Reproduce

https://github.com/user-attachments/assets/4e8e4769-94e9-48bf-8a38-42a2f7689487

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Custom endpoints are not yet supported, that is the root cause of this issue.

**Comment by RedwindA** [comment]
> Custom endpoints are not yet supported, that is the root cause of this issue.
 
OPENAI_REVERSE_PROXY is also not working
