### ISSUE TITLE
Enhancement: Upload of Documents/files to use as input in models (not using RAG)

### ISSUE THREAD

**Issue by schnaker85** [danny-avila/LibreChat#4502]
### What features would you like to see added?

We would like the ability to upload any type of file or document to LibreChat's local storage (similar to images approach). We then intend to use these files as input context in our models, particularly when the `RAG_API_URL` is not set. Setting up RAG is not a viable workaround for us.

There are already a few similar issues, such as https://github.com/danny-avila/LibreChat/issues/2755, but with slightly different preferred solutions or workflows.

For us, the two approaches, RAG and file input context, are not mutually exclusive. Therefore, we are not criticizing the current implementation, but we believe that LibreChat users should be able to configure how files are used in their models and within librechat. 
This would be an addition to the current setup options.

### More details

We will provide a workable "draft" implementation to show what would need to be enhanced/changed to make this work. We can also discuss about further or different implementations for the file upload.

### Which components are impacted by your request?

Endpoints, Other

### Pictures

Here is a screen recording of our local librechat with the relevant changes.

https://github.com/user-attachments/assets/45d9648c-6d0f-4629-a011-bc3a225eab72

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
https://github.com/danny-avila/LibreChat/issues/2755#issuecomment-2429418819
