### ISSUE TITLE
[Bug]: Numbers Displayed as "a" Character Instead of Actual Values

### ISSUE THREAD

**Issue by rio2dev** [danny-avila/LibreChat#4527]
### What happened?

When numerical values are expected to be displayed, only the character "a" is shown instead.

Visual representation in the frontend:

I see in frontend this: 
![image](https://github.com/user-attachments/assets/8a6bde57-7958-414e-8ac4-b41d8d87bb61)

When copying the message using the copy button, this is what appears:
![image](https://github.com/user-attachments/assets/4303b3e0-ba69-4485-ad01-306d9ecd4810)

### Steps to Reproduce

1) Prompt: Please give me a random list with numeric centuries in Latvian.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Tried it several times, the issue couldn't be reproduced:

![image](https://github.com/user-attachments/assets/7aaa4006-f979-46bf-9f17-650f006087d7)

**Comment by danny-avila** [comment]
The content is: 

Here's a random list of centuries in Latvian:

> 14. gadsimts
> 3. gadsimts
> 19. gadsimts
> 7. gadsimts
> 12. gadsimts
> 1. gadsimts
> 16. gadsimts
> 5. gadsimts
> 21. gadsimts
> 9. gadsimts
> 4. gadsimts
> 18. gadsimts
> 11. gadsimts
> 6. gadsimts
> 15. gadsimts
> 
> Note: In Latvian, "gadsimts" means "century"

The markdown rendering will output an ordered list with any kind of list numeration and this is expected behavior

**Comment by rio2dev** [comment]
It seams we have some different AI attribute values. Could you please use my edited prompt for Claude 3.5 Sonnet:
Please give me a numeric list with a random numeric centuries in Latvian language.

**Comment by rio2dev** [comment]
IDK, could you please tell, should I add a new bug report with fixed prompt and screenshots?

**Comment by danny-avila** [comment]
I used claude-3.5-sonnet

**Comment by rio2dev** [comment]
Here's a numeric list with random centuries in Latvian:

1. 16. gadsimts
2. 3. gadsimts
3. 9. gadsimts
4. 21. gadsimts
5. 7. gadsimts
6. 12. gadsimts
7. 18. gadsimts
8. 5. gadsimts
9. 14. gadsimts
10. 1. gadsimts

Note: In Latvian, "gadsimts" means "century."

**Comment by rio2dev** [comment]
Noo. :D

Github gives now other values. :/

**Comment by rio2dev** [comment]
Expected values was:
1. 4. gadsimts
2. 9. gadsimts
3. 5. gadsimts
etc.

**Comment by rio2dev** [comment]
No way. Github also changes my text. 

Here is my original expected values:
![image](https://github.com/user-attachments/assets/61a57ebf-30c9-4295-a0b0-d67ed1d6077b)

**Comment by rio2dev** [comment]
@danny-avila Could you please leave this as a bug? It is not normal to get an incorrect display of the AI answer.

I used the same updated prompt, "Please give me a numeric list with random centuries in Latvian language," in ChatGPT, and it gave me an answer displayed in the correct way:

![image](https://github.com/user-attachments/assets/6d9d200b-e2d2-42be-9085-98f2b4b6aff2)

I tried the same prompt in LibreChat and got an incorrect display of the AI answer with "a." instead of real numbers.

**Comment by rio2dev** [comment]
@danny-avila 
This is just an example. I have seen many other answers badly displayed. :/
