### ISSUE TITLE
I added the o1-preview model to the .env file, but I got an error when using it:

### ISSUE THREAD

**Issue by wtzwls** [danny-avila/LibreChat#4549]
I added the o1-preview model to the .env file, but I got an error when using it:
![image](https://github.com/user-attachments/assets/2e7723da-ec59-4540-9e79-7061dc32fdb8)
![image](https://github.com/user-attachments/assets/5badbf9d-72eb-4d7c-ac6a-a2c6f4dbc108)

_Originally posted by @lam584 in https://github.com/danny-avila/LibreChat/discussions/4037_

**Comment by danny-avila** [comment]
https://github.com/danny-avila/LibreChat/discussions/4037#discussioncomment-11051552
