### ISSUE TITLE
Same problem for us. We have Tier-5 but in OpenAI the o1-mini model is listed and the others are listed as text models. Is that the problem? We get the same error message.

### ISSUE THREAD

**Issue by wtzwls** [danny-avila/LibreChat#4550]
Same problem for us. We have Tier-5 but in OpenAI the o1-mini model is listed and the others are listed as text models. Is that the problem? We get the same error message.

```
OPENAI_MODELS=gpt-3.5-turbo,gpt-4,gpt-4-turbo,gpt-4o,gpt-4o-mini,o1-preview,o1-mini,o1-mini-2024-09-12
DEBUG_OPENAI=true
# TITLE_CONVO=false
# OPENAI_TITLE_MODEL=gpt-3.5-turbo
OPENAI_SUMMARIZE=true
OPENAI_SUMMARY_MODEL=gpt-3.5-turbo
# OPENAI_FORCE_PROMPT=true
# OPENAI_REVERSE_PROXY=
```

<img width="749" alt="image" src="https://github.com/user-attachments/assets/5ea8931c-b941-4258-a746-6947d8ccf6d4">

Version is Librechat 7.5.-rc2

_Originally posted by @fbaeumer in https://github.com/danny-avila/LibreChat/discussions/4037#discussioncomment-10668516_

**Comment by danny-avila** [comment]
https://github.com/danny-avila/LibreChat/discussions/4037#discussioncomment-11051552
