### ISSUE TITLE
Enhancement: Adding the copy code button when code is output

### ISSUE THREAD

**Issue by rxmgjosh** [danny-avila/LibreChat#456]
### Contact Details

j.schuler@rxmg.com

### What features would you like to see added?

It would be nice to update the output similar to how GPT works currently as it pertains to printing out code.

### More details

N/A

### Which components are impacted by your request?

UI

### Pictures

LibreChat
![CleanShot 2023-06-05 at 14 57 58](https://github.com/danny-avila/LibreChat/assets/89093543/c00b4e09-44ec-4bf3-bd09-94127da609d7)

GPT
![CleanShot 2023-06-05 at 14 57 49](https://github.com/danny-avila/LibreChat/assets/89093543/42f67127-88fb-4118-bad6-794217e383a0)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
we already have this button on code output : 
![image](https://github.com/danny-avila/LibreChat/assets/32828263/a75509d6-4ef5-4831-9fc7-729aedc0869d)

**Comment by rxmgjosh** [comment]
Does it maybe only support certain languages? Could you try this prompt in either gpt-3.5 or gpt-4? `In laravel how do I do a migration?` when I did that there was no formatting. I just cloned the repo and spun it up via docker 30 mins before I sent the issue topic. Maybe I setup something wrong? 
![CleanShot 2023-06-05 at 16 43 53](https://github.com/danny-avila/LibreChat/assets/89093543/83cd9fcd-3b24-4919-b1e8-98da770b789f)

**Comment by rxmgjosh** [comment]
Oh never mind. When I did it again I was able to get that output.
