### ISSUE TITLE
[Bug]: Insufficient Funds error with Gemini despite having available balance

### ISSUE THREAD

**Issue by Mrs-cmd** [danny-avila/LibreChat#4580]
### What happened?

Prompt tokens and cost undefined blocking usage

### Steps to Reproduce

Modify Configuration: In packages/data-provider/src/config.ts, update the supportsBalanceCheck configuration to include Google.

Add Balance: Ensure that a balance is correctly added and reflected in the relevant configuration or database.

Run Application: Start the application or service that uses the Gemini API to initiate a prompt request.

Attempt Prompt Task: Try executing a prompt task to see if it registers the balance correctly.

Observe Issue: Note if the "Insufficient Funds" error persists, despite the configured balance, with undefined prompt tokens and cost

### Screenshots

<img width="1611" alt="Screenshot 2024-10-30 at 12 14 38 PM" src="https://github.com/user-attachments/assets/429780f6-a332-4b5e-95f3-2e19644834c9">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks for your report. I"m reconciling Google balance issues here: https://github.com/danny-avila/LibreChat/issues/4580
