### ISSUE TITLE
[Question]: API Key not working

### ISSUE THREAD

**Issue by MGD713** [danny-avila/LibreChat#459]
### Contact Details

mgd713@outlook.com

### What is your question?

Hello, when I try and use the clone, it told me I needed to set the token (I used the same one as the is in the .emv) so I did that but am getting this error. Any help would be greatly appreciated, thank you!

-Matt

![image](https://github.com/danny-avila/LibreChat/assets/114160422/315cfc2f-6534-4bd1-bac4-a9deef67eaff)

### More Details

![image](https://github.com/danny-avila/LibreChat/assets/114160422/f46b6e41-3bf2-485b-8bb7-504a42032725)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
if you want you can set it as `user_provided` in the .env and update it from the UI with this menu:

![image](https://github.com/danny-avila/LibreChat/assets/32828263/6313ba80-1d5c-4237-a8e6-053bc048059c)

You are currently trying to use the ChatGPT Endpoint, in the .env file it's this one: 

![image](https://github.com/danny-avila/LibreChat/assets/32828263/a10f771c-89ae-47ad-aa51-81e00bf851fe)

It seems that you have an invalid token, be sure that you are logged in and able to access : [https://chat.openai.com/](https://chat.openai.com/) before you copy your token.

Your token starts after `"accessToken":"` in this section:

![image](https://github.com/danny-avila/LibreChat/assets/32828263/e894c184-3ae9-4262-97b8-d681ffea0f17)

 and ends before `","error":"RefreshAccessTokenError","authProvider":"auth0"}` here :
 
![image](https://github.com/danny-avila/LibreChat/assets/32828263/35a09096-5b5a-4d0e-a0a5-0ef7996eac18)

**Comment by MGD713** [comment]
The ChatGPT API key works, but the OpenAI one is saying that the default API key has reached its limit, do I have to pay for something here (hence the $)?

**Comment by fuegovic** [comment]
Yes, you need to pay for API access, you can setup a monthly limit if you want (it's not that expensive, I spend 5$ to 10$ per month and I use it quite a lot)

**Comment by MGD713** [comment]
ok great, thank you!
