### ISSUE TITLE
[Bug]: can't run the service

### ISSUE THREAD

**Issue by Maddaxman** [danny-avila/LibreChat#460]
### What happened?

![50c0f163fc3a089ab81f7ff7104ae7e3](https://github.com/danny-avila/LibreChat/assets/31379908/a637e059-787b-4c22-869a-5ffb6cd6e8e8)

### Steps to Reproduce

I run in the linux service

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Can you post the full logs, it seems they’re cut off.

what did you run before npm run backend?

you may also need to upgrade npm, and run `npm cache clean —force`

**Comment by danny-avila** [comment]
I realized what the issue was. This is a known issue where you provided a wrongly formatted MongoDB URI

If you're using atlas, it may look like this: `MONGO_URI="mongodb+srv://username:password@chatgpt-clone.qwertyq.mongodb.net/?retryWrites=true"`

This has been brought up multiple times, will need to handle it so it prints out a meaningful error message

**Comment by Maddaxman** [comment]
> I realized what the issue was. This is a known issue where you provided a wrongly formatted MongoDB URI
> 
> If you're using atlas, it may look like this: `MONGO_URI="mongodb+srv://username:password@chatgpt-clone.qwertyq.mongodb.net/?retryWrites=true"`
> 
> This has been brought up multiple times, will need to handle it so it prints out a meaningful error message

**I tried to modify it but still got the same error message. Here is the complete error message:**

(chatgpt-clone) ➜  LibreChat git:(main) ✗ npm run frontend

> LibreChat@0.4.8 frontend
> cd client && npm run build


> chat-frontend@0.4.8 build
> vite build

vite v4.3.8 building for production...
transforming (5) ../node_modules/recoil/es/index.jsError when using sourcemap for reporting an error: Can't resolve original location of error.
transforming (9) src/routes/Root.jsx
../fonts/signifier-light.woff2 referenced in /root/miniconda3/envs/chatgpt-clone/LibreChat/client/src/style.css didn't resolve at build time, it will remain unchanged to be resolved at runtime

../fonts/signifier-light-italic.woff2 referenced in /root/miniconda3/envs/chatgpt-clone/LibreChat/client/src/style.css didn't resolve at build time, it will remain unchanged to be resolved at runtime

../fonts/signifier-bold.woff2 referenced in /root/miniconda3/envs/chatgpt-clone/LibreChat/client/src/style.css didn't resolve at build time, it will remain unchanged to be resolved at runtime

../fonts/signifier-bold-italic.woff2 referenced in /root/miniconda3/envs/chatgpt-clone/LibreChat/client/src/style.css didn't resolve at build time, it will remain unchanged to be resolved at runtime

../fonts/soehne-buch.woff2 referenced in /root/miniconda3/envs/chatgpt-clone/LibreChat/client/src/style.css didn't resolve at build time, it will remain unchanged to be resolved at runtime

../fonts/soehne-buch-kursiv.woff2 referenced in /root/miniconda3/envs/chatgpt-clone/LibreChat/client/src/style.css didn't resolve at build time, it will remain unchanged to be resolved at runtime

../fonts/soehne-kraftig.woff2 referenced in /root/miniconda3/envs/chatgpt-clone/LibreChat/client/src/style.css didn't resolve at build time, it will remain unchanged to be resolved at runtime

../fonts/soehne-kraftig-kursiv.woff2 referenced in /root/miniconda3/envs/chatgpt-clone/LibreChat/client/src/style.css didn't resolve at build time, it will remain unchanged to be resolved at runtime

../fonts/soehne-halbfett.woff2 referenced in /root/miniconda3/envs/chatgpt-clone/LibreChat/client/src/style.css didn't resolve at build time, it will remain unchanged to be resolved at runtime

../fonts/soehne-halbfett-kursiv.woff2 referenced in /root/miniconda3/envs/chatgpt-clone/LibreChat/client/src/style.css didn't resolve at build time, it will remain unchanged to be resolved at runtime

../fonts/soehne-mono-buch.woff2 referenced in /root/miniconda3/envs/chatgpt-clone/LibreChat/client/src/style.css didn't resolve at build time, it will remain unchanged to be resolved at runtime

../fonts/soehne-mono-halbfett.woff2 referenced in /root/miniconda3/envs/chatgpt-clone/LibreChat/client/src/style.css didn't resolve at build time, it will remain unchanged to be resolved at runtime

../fonts/soehne-mono-buch-kursiv.woff2 referenced in /root/miniconda3/envs/chatgpt-clone/LibreChat/client/src/style.css didn't resolve at build time, it will remain unchanged to be resolved at runtime
transforming (17) src/mobile.cssError when using sourcemap for reporting an error: Can't resolve original location of error.
Error when using sourcemap for reporting an error: Can't resolve original location of error.
Error when using sourcemap for reporting an error: Can't resolve original location of error.
Error when using sourcemap for reporting an error: Can't resolve original location of error.
Error when using sourcemap for reporting an error: Can't resolve original location of error.
Error when using sourcemap for reporting an error: Can't resolve original location of error.
Error when using sourcemap for reporting an error: Can't resolve original location of error.
Error when using sourcemap for reporting an error: Can't resolve original location of error.
Error when using sourcemap for reporting an error: Can't resolve original location of error.
Error when using sourcemap for reporting an error: Can't resolve original location of error.
Error when using sourcemap for reporting an error: Can't resolve original location of error.
transforming (47) ../node_modules/@tanstack/react-query-devtools/build/lib/styledComponents.mjsError when using sourcemap for reporting an error: Can't resolve original location of error.
transforming (59) ../node_modules/@tanstack/react-query-devtools/build/lib/Explorer.mjsError when using sourcemap for reporting an error: Can't resolve original location of error.
Error when using sourcemap for reporting an error: Can't resolve original location of error.
Error when using sourcemap for reporting an error: Can't resolve original location of error.
transforming (76) ../node_modules/@tanstack/react-query/build/lib/errorBoundaryUtils.mjsError when using sourcemap for reporting an error: Can't resolve original location of error.
Error when using sourcemap for reporting an error: Can't resolve original location of error.
transforming (186) src/components/Messages/Message.jsxError when using sourcemap for reporting an error: Can't resolve original location of error.
transforming (207) src/components/Endpoints/EditPresetDialog.jsxError when using sourcemap for reporting an error: Can't resolve original location of error.
transforming (1346) ../node_modules/downloadjs/download.jsError when using sourcemap for reporting an error: Can't resolve original location of error.
transforming (1362) src/components/Messages/Content/SubRow.jsxError when using sourcemap for reporting an error: Can't resolve original location of error.
Error when using sourcemap for reporting an error: Can't resolve original location of error.
Error when using sourcemap for reporting an error: Can't resolve original location of error.
transforming (1451) ../node_modules/@radix-ui/react-id/dist/index.module.js[plugin:vite:resolve] Module "node:path" has been externalized for browser compatibility, imported by "/root/miniconda3/envs/chatgpt-clone/LibreChat/node_modules/filenamify/filenamify-path.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
✓ 2005 modules transformed.
dist/index.html                     0.81 kB │ gzip:   0.39 kB
dist/assets/index-2d0b2650.css    119.16 kB │ gzip:  17.66 kB
dist/assets/index-9ac28e55.js     191.53 kB │ gzip:  46.28 kB │ map: 541.50 kB
dist/assets/vendor-37fb2373.js  1,541.86 kB │ gzip: 458.21 kB │ map:   0.59 kB

(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 39.73s
(chatgpt-clone) ➜  LibreChat git:(main) ✗ npm run backend

> LibreChat@0.4.8 backend
> cd api && npm run start


> chat-backend@0.4.8 start
> node server/index.js

Meilisearch error, search will be disabled
There was an uncaught error: bad auth : authentication failed
Clearing sync timeouts before exiting...
npm ERR! Lifecycle script `start` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: chat-backend@0.4.8
npm ERR!   at location: /root/miniconda3/envs/chatgpt-clone/LibreChat/api

**Comment by Maddaxman** [comment]
> Can you show how it looks in your env file, you can replace your actual username and password with "username:password" for showing

sure
<img width="1141" alt="image" src="https://github.com/danny-avila/LibreChat/assets/31379908/9a2183b3-2def-4e7e-92a9-fb9a62cbacf8">

it's ok now  >..<

i delete "< >"
