### ISSUE TITLE
[Bug]: icon for xAI that matches the colour theme of the rest of the icons

### ISSUE THREAD

**Issue by kneelesh48** [danny-avila/LibreChat#4640]
### What happened?

xAI icon looks out of place among all other icons

![image](https://github.com/user-attachments/assets/e8714cc1-edc9-4319-95d6-a275be3f1889)

### Steps to Reproduce

1. Add xAI to librechat.yml
2. Click on provider dropdown

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kneelesh48** [comment]
I propose using this svg icon instead which I copied from xAI website

![xai](https://github.com/user-attachments/assets/ee261e85-c088-41b1-b893-f0b426a0fcfc)

**Comment by danny-avila** [comment]
the SVG is being used.
