### ISSUE TITLE
[Bug]: Chat title not generated properly when using `claude-3-5-haiku-20241022` as Anthropic title model

### ISSUE THREAD

**Issue by nkahnfr** [danny-avila/LibreChat#4652]
### What happened?

Expected title: one generated based on the chat prompt.

Actual title: `NO TOOL INVOCATION: <function_calls><invoke name="submit_title"><parameter name="title">AI Search Capabilities Explained</parameter></invoke>`

That text seems to be generated by the `parseParamFromPrompt` function in the `api/app/clients/prompts/titlePrompts.js` file.

### Steps to Reproduce

1. Set `ANTHROPIC_TITLE_MODEL` option to `claude-3-5-haiku-latest` or `claude-3-5-haiku-20241022` in the `.env` file.
2. Start a new chat using any Anthropic's model.

### What browsers are you seeing the problem on?

Chrome

### Screenshots

![Capture d’écran 2024-11-06 à 19 20 13](https://github.com/user-attachments/assets/fe9b303b-7e80-4aad-b094-2f8cdd1bb2da)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nkahnfr** [comment]
Thanks @danny-avila 🙏

**Comment by SHLE1** [comment]
This problem still exists
<img width="257" alt="image" src="https://github.com/user-attachments/assets/d4120027-58b6-440f-82f4-56244be2fc6c">

**Comment by SHLE1** [comment]
This issue still exists when using the latest dev version
<img width="262" alt="image" src="https://github.com/user-attachments/assets/9937ec0c-87cb-44be-8c51-fd9fed306d60">
