### ISSUE TITLE
[Bug]: Generated images don't show up in new agents chat view 

### ISSUE THREAD

**Issue by thingersoft** [danny-avila/LibreChat#4669]
### What happened?

Images generated by agents (experimental) can't be seen in chat view.

### Steps to Reproduce

1. configure an agent with DALL-E-3 tool enabled
2. ask for image generation

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mootfrost** [comment]
+1

**Comment by mootfrost** [comment]
As a workaround you can add this to agent's system prompt: `Return all images with https://<domain>/images prefix , not with https://your-image-link.com/images/`

**Comment by thingersoft** [comment]
> As a workaround you can add this to agent's system prompt: `Return all images with https://<domain>/images prefix , not with https://your-image-link.com/images/`

@mootfrost 
Sometimes the agent returns a link rather than embedding the image into the chat but all in all the workaround seems to work for now, thank you.

**Comment by danny-avila** [comment]
This will be fixed soon

**Comment by leondape** [comment]
@danny-avila can you shortly outline how you solved agent image handling? I am trying to fix it for a future flux plugin: in #5410 but can only do it over the prompt engineering workaround. It would be very helpful if you could elaborate on that so that I can transfer that to flux.
