### ISSUE TITLE
[Question]: Insufficient Funds! Balance: 0.

### ISSUE THREAD

**Issue by morphmind** [danny-avila/LibreChat#4672]
### What is your question?

I deployed via Railway. I entered my Openai and Claude API keys. I checked my balances and they are sufficient. But I get this error in LibreChat. Insufficient Funds! Balance: 0. Prompt tokens: 112. Cost: 336.
How do I fix this?

### More Details

Insufficient Funds! Balance: 0. Prompt tokens: 112. Cost: 336.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
disable `CHECK_BALANCE` in the env var

https://www.librechat.ai/docs/configuration/token_usage

**Comment by morphmind** [comment]
> disable `CHECK_BALANCE` in the env var
> 
> https://www.librechat.ai/docs/configuration/token_usage

Yes, I saw this, but how do I configure this in railway? There’s no information available. I just want to use it for myself. I don’t care about the balance; how can I completely disable it?
