### ISSUE TITLE
Enhancement: Add Ability to Modify AI Providers/Models in Running LibreChat Instance

### ISSUE THREAD

**Issue by TedLin1993** [danny-avila/LibreChat#4674]
### What features would you like to see added?

Currently, to add or modify models in LibreChat, one must:

1. Modify Environment Variables: Some models require changes in the .env file.
2. Edit Configuration Files: Certain configurations need to be set in librechat.yaml.
3. Redeploy the Application: After making these changes, the entire application needs to be redeployed to use the new models.

This process is quite cumbersome and not user-friendly:

- User Experience: It disrupts workflow as users need to stop the service, change configurations, and then restart or redeploy the application.
- Flexibility: Users cannot dynamically adjust or test new models without going through this cycle.

Proposed Feature:

I propose adding functionality where:

- Frontend Configuration: Users can add or modify AI models directly from the LibreChat frontend interface without needing to dive into configuration files or environment variables.
- Persistent Changes: These modifications should persist through redeployments, ensuring that the settings are not lost when the application is updated or restarted.

Benefits:

- Improved UX: Allows for real-time adjustments to AI providers and models, enhancing experimentation and usability.
- Simplification: Reduces the technical barrier for users who might not be familiar with server-side configurations or deployments.

### More details

Possible Implementation:

- New Config Table in DB: Introduce a new config table in the database. When this table is empty:
- Use the existing settings from .env and librechat.yaml files.
- Automatically populate this table with the current configurations from these files.
- Prioritize Config Table: If the config table is not empty, the application should use the settings stored in this table for AI providers and models, overriding any settings in .env or librechat.yaml.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Something like this is planned, closing in favor of https://github.com/danny-avila/LibreChat/issues/3137
