### ISSUE TITLE
[Bug]: maxContextTokens in Agents is not correctly set when the model != deploymentName

### ISSUE THREAD

**Issue by peeeteeer** [danny-avila/LibreChat#4700]
### What happened?

in our case the model configuration in the librechat.yaml file is using the the deploymentName parameter. The model name (e.g. gpt-4o) is not equal the deploymentName. With this when commuicating with an Agent the maxContextTokens is not defined and results in an error.

### Steps to Reproduce

1. name a deployment of a model different than the model name
2. set the deploymentName in the librechat.yaml
3. use it in an Agent

### Screenshots

I'm new to js - but this change e.g. fixes the issue - but I'm actually not sure if it is the right thing to do...

![image](https://github.com/user-attachments/assets/0d90b4d9-788d-413d-9e9d-3e895c28c4ef)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Closed by https://github.com/danny-avila/LibreChat/pull/5035
