### ISSUE TITLE
Enhancement: Handle images in plugins

### ISSUE THREAD

**Issue by mootfrost** [danny-avila/LibreChat#4706]
### What features would you like to see added?

Implement handling images in plugins section. It is useful when you need to generate image with similar style with DALL-E 

### More details

-

### Which components are impacted by your request?

Plugins

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Plugins will be deprecated in favor of Agents (#3607), which already support this.

**Comment by mootfrost** [comment]
@danny-avila Thanks for your reply. I upgraded my instance to new version and created new agent. It generates images, but returns not valid url like this: ```https://your-image-link.com/images/66f5b187c0716239d51b3fce/img-382b0b68-c088-40a8-ac7d-acda31503dc4.png```(domain is wrong). I tried to look for any env variables that set base domain, but came to nothing.

**Comment by danny-avila** [comment]
There's an open issue on this already, thanks: https://github.com/danny-avila/LibreChat/issues/4669
