### ISSUE TITLE
[Bug]: Dalle Results not showing in Agent Chat

### ISSUE THREAD

**Issue by leondape** [danny-avila/LibreChat#4726]
### What happened?

When using Dalle3 in agents the image request seems to get sent and received but is not displayed in chat.
Request is fulfilled, yet console say that an api key is missing. Getting this error with dalle3 plugin as well. there it works. 

### Steps to Reproduce

1. create agent with dalle tool
2. let generate image 
3. response is received but not shown in chat.

### What browsers are you seeing the problem on?

Edge

### Relevant log output

```
},
                "finish_reason": "function_call"
              }
            }
          }
        ]
      },
      "observation": "![generated image](/images/66b31911bca0395728652570/img-7cd7224a-b846-48ba-a8ac-94489ffb7b78.png)"
    }
  ]
}
2024-11-14 11:39:01 error: [getUserPluginAuthValue] No plugin auth DALLE3_API_KEY found for user 66b31911bca0395728652570
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Duplicate issue, I'm tracking: https://github.com/danny-avila/LibreChat/issues/4669
