### ISSUE TITLE
[Bug]: Attaching files to message in agents chat causes API error

### ISSUE THREAD

**Issue by thingersoft** [danny-avila/LibreChat#4739]
### What happened?

Trying to attach a document file inside a chat with an agent causes an API error.

### Steps to Reproduce

1. configure RAG
2. configure an agent
3. start a chat with the agent and attach a file

### Relevant log output

```shell
error: [/agents/:undefined] Error retrieving agent during build options step Cannot read properties of null (reading 'author')
error: [handleAbortError] AI response error; aborting request: Agent not found
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Not implemented yet, but already taken care of in the dev build: 

![image](https://github.com/user-attachments/assets/7165adee-f099-4f18-9f0e-b8516746dda5)

**Comment by thingersoft** [comment]
> Not implemented yet, but already taken care of in the dev build:

I'm running from sources and I see recent activity on main branch only, where are the dev builds sources located?

**Comment by danny-avila** [comment]
It’s not published yet, though you can try it at https://preview.librechat.ai

**Comment by thingersoft** [comment]
> It’s not published yet, though you can try it at https://preview.librechat.ai

@danny-avila 
Ok thank you, so that preview it's built from a private source repository I guess.
I know from your other comments that you want to keep code interpreter feature closed source, but when do you expect to merge other agents fixes into the public repo?
