### ISSUE TITLE
[Bug]: Previous conversations missing custom icons and model spec on v0.7.5

### ISSUE THREAD

**Issue by bstanic** [danny-avila/LibreChat#4749]
### What happened?

We use custom icons for various models. Since the upgrade to version 0.7.5, the saved chats are missing custom model icons after the chat is saved. Also, the model spec is not saved either so when continuing conversation it shows as "None selected". 

I suspected that some of the data is not recorded in the DB. So I ran a test with 0.7.4 and then with 0.7.5 and noticed that there is missing data in the 'conversations' collection. Some of the missing fields are `spec:` and `iconURL:` but there is more. 

Example using version 0.7.4:
```
{
	"_id" : ObjectId("673aedf38452abac33969696"),
	"conversationId" : "52cac484-1321-4576-8e7a-5bae4ecfddd3",
	"user" : "671ef534b28a596957f7bf3f",
	"__v" : 0,
	"chatGptLabel" : "ChatGPT-4o",
	"createdAt" : ISODate("2024-11-18T07:34:11.980Z"),
	"endpoint" : "azureOpenAI",
	"frequency_penalty" : 0,
	"iconURL" : "https://example-site.net/assets/icon-gpt.png",
	"imageDetail" : "auto",
	"isArchived" : false,
	"messages" : [
		ObjectId("673aedf38452abac33969695"),
		ObjectId("673aedf48452abac33969697"),
		ObjectId("673aee3c8452abac33969698"),
		ObjectId("673aee3d8452abac33969699")
	],
	"model" : "gpt-4o",
	"presence_penalty" : 0,
	"promptPrefix" : null,
	"resendFiles" : true,
	"spec" : "gpt-4o",
	"tags" : [ ],
	"temperature" : 1,
	"title" : "New Chat",
	"top_p" : 1,
	"updatedAt" : ISODate("2024-11-18T07:35:25.745Z")
}
```

Example (broken icons and empty model selections) on 0.7.5:
```
{
	"_id" : ObjectId("673aef3caac9e3027061653f"),
	"user" : "671ef534b28a596957f7bf3f",
	"conversationId" : "dc3cb9b5-de11-44d3-a063-7b0930f0d953",
	"__v" : 0,
	"createdAt" : ISODate("2024-11-18T07:39:40.120Z"),
	"endpoint" : "azureOpenAI",
	"isArchived" : false,
	"messages" : [
		ObjectId("673aef3caac9e3027061653e"),
		ObjectId("673aef3eaac9e30270616540")
	],
	"model" : "gpt-4o",
	"resendFiles" : true,
	"tags" : [ ],
	"title" : "Test of the Test",
	"updatedAt" : ISODate("2024-11-18T07:39:42.273Z")
}
```

Issue seems to be with recording all the fields in the DB in the version 0.7.5

### Steps to Reproduce

1. Run version 0.7.4 with customization file as per the [LibreChat documentation](https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/custom_endpoint#iconurl)
2. Do some test chats
3. Upgrade to version 0.7.5
4. Do some more test chats.
5. Observe that old chats still have correct icons and model spec in history, but the new one created post upgrade do not. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bstanic** [comment]
After some further testing and playing with options, it seems that the issue is present if the [model spec enforcement](https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/model_specs#enforce) is set to `true`. When set to `false`, the issue is no longer present.

**Comment by danny-avila** [comment]
Thanks, the issue is now resolved.

**Comment by maxesse** [comment]
Hello @danny-avila , I'm on the very latest main branch with the commits from today and I have added custom icons to the modelSpecs, I still see this behaviour for some reason. As you do the chat and it gets stored in the conversation history, it has the icon, but when i refresh it gets replaced with the agent feather icon? Do you also see it?

**Comment by danny-avila** [comment]
@maxesse agents and assistants use their respective avatars, they don’t save the iconURL properties from model specs but I can see about implementing that

**Comment by maxesse** [comment]
I have put the avatar in both the modelSpec and in the agent builder, same for the assistant, but they still seem to revert to a generic icon?

`    - name: "web-search-assistant"
      label: "Web Search Assistant"
      description: |
        Research topics on the web with GPT-4o and the help of Bing.
      iconURL: "https://icy-flower-023f19103.4.azurestaticapps.net/assets/search.png"
      preset:
        default: true
        endpoint: "agents"
        agent_id: "agent_w25fgQ4AiTfX14Vbv0cBb"`

<img width="389" alt="image" src="https://github.com/user-attachments/assets/5093cdbe-9467-444e-9c9b-bc0450276102" />

**Comment by danny-avila** [comment]
If you mean in the conversation list, that has to be implemented still

**Comment by maxesse** [comment]
Ah ok perfect, yes i meant in the conversation list, see the screenshots from 2 comments ago - base models get their icon, but agents and assistants show the feather and the sparkles.
