### ISSUE TITLE
Enhancement: Support Custom Model Rates

### ISSUE THREAD

**Issue by Takumilove** [danny-avila/LibreChat#4789]
### What features would you like to see added?

I would like to see support for customizable model rates, allowing users to adjust rates for different models flexibly. This feature is crucial for adapting to various scenarios and requirements.

### More details

Steps to Reproduce:

Modify the rate logic in the file.tx.js
Deploy the changes, but observe no effect.
Further investigation reveals that some models lack rate definitions.
Expected Outcome:

The system should correctly read and apply customized model rates.
All models' rate information should be clearly displayed in the interface or configuration files.

### Which components are impacted by your request?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Duplicate issue: #1633 

I would like to see this as well, and I will see to this soon as the idea has not been implemented for a while

**Comment by Takumilove** [comment]
thanks！
