### ISSUE TITLE
[Bug]: Opening LibreChat with prompt URL search parameter crashes with "malformed URI sequence" (percent sign)

### ISSUE THREAD

**Issue by maxbraeutigam** [danny-avila/LibreChat#4794]
### What happened?

If I am opening the application with the search parameter `prompt` containing a “%” sign, _i.e._ https://librechat.example.com/c/new?prompt=6%25, which should be simply start with the prompt being “6%”, the whole app crashes with a client side exception and the error message:

```
Unexpected Application Error!
malformed URI sequence
```

### Steps to Reproduce

I am constructing the URL like so in TypeScript:

```ts
const url = new URL("https://librechat.example.com/c/new");
url.searchParams.set("prompt", "6%");
console.log(url.toString());

// => https://librechat.example.com/c/new?prompt=6%25
```

**LibreChat**
Version 0.7.5
Installed on Railway.app using the following container:
[ghcr.io/danny-avila/librechat-dev:latest](https://ghcr.io/danny-avila/librechat-dev)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
Unexpected Application Error!
malformed URI sequence

E5/<@https://librechat.example.com/assets/index.DBAuqaeP.js:3068:1019
bE@https://librechat.example.com/assets/vendor.B494yHh0.js:40:24324
zm@https://librechat.example.com/assets/vendor.B494yHh0.js:40:42516
xSe@https://librechat.example.com/assets/vendor.B494yHh0.js:40:41335
_d@https://librechat.example.com/assets/vendor.B494yHh0.js:40:40372
sB@https://librechat.example.com/assets/vendor.B494yHh0.js:40:36960
Kf@https://librechat.example.com/assets/vendor.B494yHh0.js:38:3288
Vo/<@https://librechat.example.com/assets/vendor.B494yHh0.js:40:34327
```

### Screenshots

![Bildschirmfoto vom 2024-11-26 17-57-56](https://github.com/user-attachments/assets/ab29383d-e504-4473-b0dc-e292f82806a2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxbraeutigam** [comment]
@danny-avila, nevertheless I love LibreChat and I thank you very much for developing such a great product.

**Comment by danny-avila** [comment]
thanks! this should be an easy fix, will get to it soon
