### ISSUE TITLE
Enhancement: Define Default Vision Model with ENV variable

### ISSUE THREAD

**Issue by bsu3338** [danny-avila/LibreChat#4839]
### What features would you like to see added?

use a variable like OPENAI_VISION_MODLE=llama-3.2-11b to define a vision fallback instead of using the static in line 153 of api/app/clients/OpenAIClient.js 
gpt-4-vision-preview

### More details

I would prefer to fallback to a local model if possible if the user chooses a model that does not support vision

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
duplicate: https://github.com/danny-avila/LibreChat/issues/1634
