### ISSUE TITLE
[Bug]: Requests Routed to Unexpected Models Despite Configuration in .env

### ISSUE THREAD

**Issue by ArcCal** [danny-avila/LibreChat#4863]
### What happened?

I specified in the .env file to only use chatgpt-4o-latest, but through the Cloudflare AI Gateway, I detected that some requests were being sent to gpt-3.5-turbo-**** without my knowledge. This is really strange.

When using Anthropic, I’ve encountered similar issues where my queries were unknowingly handed over to older models for processing.

### Steps to Reproduce

1.Configure the .env file to use chatgpt-4o-latest as the model. For example:

    MODEL=chatgpt-4o-latest

    Deploy LibreChat with the above configuration.
    Send queries through the chat interface, expecting all requests to use the specified model (chatgpt-4o-latest).
    Use Cloudflare AI Gateway to observe the outgoing API requests.
    Notice that some requests are unexpectedly routed to gpt-3.5-turbo-**** instead of the configured model (chatgpt-4o-latest).

Additional Observations

    Similar behavior has been observed with Anthropic models, where queries are sometimes routed to older models, contrary to the specified configuration.
    The issue occurs intermittently and without clear patterns.

### Screenshots

<img width="868" alt="image" src="https://github.com/user-attachments/assets/77e88542-c0b4-4524-b8be-4134b2ceb67d">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArcCal** [comment]
<img width="671" alt="image" src="https://github.com/user-attachments/assets/aeeb2e3f-183d-468a-a75f-dd1154d9c5f5">
<img width="643" alt="image" src="https://github.com/user-attachments/assets/bb26e6b0-05fc-4387-8886-04b3ef5877f2">

**Comment by fuegovic** [comment]
This happens at the beginning of a new conversation, the smaller model is used for the conversation title generation. You can configure the title models in the .env file
