### ISSUE TITLE
[Bug]: Error when I configure the rag, using text-embedding-3-large

### ISSUE THREAD

**Issue by harrisonhxy** [danny-avila/LibreChat#4878]
### What happened?

First of all, I would like to state that I am using the proxy api, not the official api. i am sure that the api service provider offers `text-embedding-3-small` and `text-embedding-3-large`.

I configured the RAG in .env as follows
<img width="544" alt="image" src="https://github.com/user-attachments/assets/83b79f77-3da0-414e-8a03-d349da2c44da">

But the following error occurs when using it in librechat
![image](https://github.com/user-attachments/assets/4a1e0bc5-a440-4d2c-b91d-435508d05a62)

**But it's worth noting that when I set `EMBEDDINGS_MODEL` to `text-embedding-3-small`, it functioned correctly.**
**Now I want to use `text-embedding-3-large`, how do I implement it?**

### Steps to Reproduce

1. my .env setting about rag
![image](https://github.com/user-attachments/assets/ba5c562e-9547-499d-bc49-f60299dbfbac)

2. when setting `text-embedding-3-large` the librechat display
![image](https://github.com/user-attachments/assets/2a4973a3-eda1-4b2c-adbd-5eeed533be30)

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
This is the log of the rag_api container

2024-12-06 05:52:28,812 - httpx - INFO - HTTP Request: POST https://api.oaipro.com/v1/embeddings "HTTP/1.1 200 OK"
2024-12-06 05:52:29,184 - root - ERROR - (psycopg2.errors.DataException) different vector dimensions 1536 and 3072

[SQL: SELECT langchain_pg_embedding.collection_id AS langchain_pg_embedding_collection_id, langchain_pg_embedding.embedding AS langchain_pg_embedding_embedding, langchain_pg_embedding.document AS langchain_pg_embedding_document, langchain_pg_embedding.cmetadata AS langchain_pg_embedding_cmetadata, langchain_pg_embedding.custom_id AS langchain_pg_embedding_custom_id, langchain_pg_embedding.uuid AS langchain_pg_embedding_uuid, langchain_pg_embedding.embedding <=> %(embedding_1)s AS distance 
FROM langchain_pg_embedding JOIN langchain_pg_collection ON langchain_pg_embedding.collection_id = langchain_pg_collection.uuid 
WHERE langchain_pg_embedding.collection_id = %(collection_id_1)s::UUID AND (langchain_pg_embedding.cmetadata ->> %(cmetadata_1)s) = %(param_1)s ORDER BY distance ASC 
 LIMIT %(param_2)s]
[parameters: {'embedding_1': '[0.0009258708450943232,-0.03693574294447899,-0.017960036173462868,0.013265654444694519,0.014628139324486256,0.03527598828077316,-0.030866488814353943 ... (65552 characters truncated) ... 021168069913983345,0.0018068415811285377,-0.013872579671442509,0.006917710416018963,-0.007016800343990326,-0.019731266424059868,0.013984055258333683]', 'collection_id_1': UUID('f2421108-5a3c-4635-ba28-dfec34104f72'), 'cmetadata_1': 'file_id', 'param_1': '0bfee7e9-b086-4bd6-a05f-e185e51ffc00', 'param_2': 4}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
2024-12-06 05:52:29,186 - root - INFO - Request POST http://rag_api:8000/query - 500
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harrisonhxy** [comment]
self-answer: After replacing `EMBEDDINGS_MODEL`, need to re-upload the file and re-index it, and then it will work fine.
Additionally, can `EMBEDDINGS_MODEL` be passed multiple models?Let the user choose which one to use at the time of us ing.

Administrators can close this issue

**Comment by danny-avila** [comment]
> Additionally, can EMBEDDINGS_MODEL be passed multiple models?Let the user choose which one to use at the time of us ing.

It's not advisable because embeddings need to be uniform by model in a semantic vector db, unless you have clearly defined documents by embedding model, which is not the case here and would be pretty niche. Basically, you need to decide which embedding model to use from the outset, and migrate data when changing models.
