### ISSUE TITLE
[Bug]: "user_provided" token for ChatGPT Endpoint is not working

### ISSUE THREAD

**Issue by fuegovic** [danny-avila/LibreChat#488]
### What happened?

Entering the token from the UI returns token: null in the console

(It's working fine when provided in the .env)

### Steps to Reproduce

in the .env file:
`CHATGPT_TOKEN="user_provided"`

in the UI:
provide the token

### Relevant log output

```shell
endpointOption: { model: 'text-davinci-002-render-sha', token: null },
```

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/32828263/5f421a51-4859-47fe-ab44-70b340269c3d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SphaeroX** [comment]
Same here

**Comment by danny-avila** [comment]
I'm not able to reproduce this issue

```js
endpointOption: { model: 'gpt-4', token: 'hello' },
```

**Comment by fuegovic** [comment]
You're right, some other update must've fixed this. It's working fine now, closing the issue!
