### ISSUE TITLE
[Bug]: is the model already supported?

### ISSUE THREAD

**Issue by shouwei** [danny-avila/LibreChat#4882]
### What happened?

the model **claude-3-5-haiku-20241022** does not work.

### Steps to Reproduce

choose the model and send a request

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Something went wrong. Here's the specific error message we encountered: Operation failed after 3 attempts: 400 {"type":"error","error":{"type":"invalid_request_error","message":"prompt: Input should be a valid string"}}
```

### Screenshots

![image](https://github.com/user-attachments/assets/34471a80-f7a2-4f8c-9260-ae5d4dd4a542)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Yes, you will need to update:
![image](https://github.com/user-attachments/assets/667a22b6-d2d3-434f-a9a6-383f1f3e7db2)
