### ISSUE TITLE
Enhancement: Different settings of "parameters" for admin

### ISSUE THREAD

**Issue by dvejsada** [danny-avila/LibreChat#4910]
### What features would you like to see added?

Currently the UI settings in librechat.yaml apply to all users without difference whether it is admin or regular user. However, in some cases, this may create issues. 

For example, if I want to use Assistant or Agent as ModelSpec endpoint, I have to first enable "parameters" for all to be able to create respective Assistant or Agent, then change librechat.yaml and restart to disable parameters. If I want to edit the Agent later, I have to again enable parameters for all, change the Agent, and disable them again (having to restart the container twice in the process).

Therefore, it will be nice to have a **different settings of "parameters" with respect to admin and to regular users**, to allow editing assistants/agents on the fly without exposing the settings to regular users.

### More details

The above may also be useful in case of other settings as well, this case is however I believe the most prominent (other settings usually disable whole feature so there is no point for different settings for admin).

### Which components are impacted by your request?

UI, Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxesse** [comment]
Hi there, I implemented this in my instance, I didn't push it as a PR because I assume it will be done more cleanly in future with the upcoming admin panel. It's a small change though, you can apply this diff to UseSidenavLinks.ts and assistantbuilder will appear for admins regardless of the settings in the config - i had the same issue as you.

[assistantBuilderForAdmins.patch](https://github.com/user-attachments/files/18060052/assistantBuilderForAdmins.patch)

**Comment by danny-avila** [comment]
This is already implemented for Agents: 

![image](https://github.com/user-attachments/assets/ddb77a54-1bf2-4f66-9298-bdc7ac798b66)
![firefox_NdjgZgoLAV](https://github.com/user-attachments/assets/12816a5e-7ef5-4ab9-9929-fec032f27f55)

I will be adding a dropdown specifying the role to make this more clear which role these settings are being applied to

**Comment by danny-avila** [comment]
In regards to Agents/Prompts, this is addressed by https://github.com/danny-avila/LibreChat/pull/4922

Also, in general, role-based librechat.yaml settings are planned for https://github.com/danny-avila/LibreChat/issues/3137
