### ISSUE TITLE
Enhancement: Add supprt for Google AI Studio (Top ranking LLM)

### ISSUE THREAD

**Issue by petercunha** [danny-avila/LibreChat#4921]
### What features would you like to see added?

Google's [gemini-exp-1206](https://aistudio.google.com/app/prompts/new_chat?model=gemini-exp-1206) recently rose to the top of the LMSYS community leaderboard, I think it would be great if we could use this model from Librechat.

### More details

- https://lmarena.ai

### Which components are impacted by your request?

General

### Pictures

<img width="941" alt="image" src="https://github.com/user-attachments/assets/86a3753d-2751-44dd-bef0-1ac724c6dcf4">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
it can be added to the list of models with the `GOOGLE_MODELS` environment variable in .env file

![image](https://github.com/user-attachments/assets/8ec4f7fb-27e8-4375-8b5c-d83f4965b25b)
