### ISSUE TITLE
Enhancement: Add Support for Additional Models from GitHub Models

### ISSUE THREAD

**Issue by eric15342335** [danny-avila/LibreChat#4959]
### What features would you like to see added?

Hi guys,

I’d love to see more models from [*GitHub Models*](https://github.com/marketplace/models/catalog) supported in LibreChat. Right now, only GPT-4o and some Phi models are there. Can we add:

- OpenAI o1-mini
- OpenAI o1-preview
- Llama 3.2 Vision Models

I'm willing to help with this, but I’m not sure where to start.

Thanks!

### More details

Github Models catalog: https://github.com/marketplace/models/catalog
The LibreChat v0.7.5 online instance I use: https://librechat-librechat.hf.space/c/new

### Which components are impacted by your request?

Endpoints

### Pictures

Current LibreChat v0.7.5 supported models:
![image](https://github.com/user-attachments/assets/8d6538f6-4121-44e8-8260-e3a804b6ec69)

Current models available on GitHub Models:
![image](https://github.com/user-attachments/assets/01c8d952-8693-49cd-a816-6fc55ae52a4b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eric15342335** [comment]
Nevermind guys, sorry I didn't read the documentation.
https://www.librechat.ai/docs/configuration/librechat_yaml/setup

**Comment by harrisonhxy** [comment]
> Nevermind guys, sorry I didn't read the documentation.算了，对不起，我没看文档。 https://www.librechat.ai/docs/configuration/librechat_yaml/setup

So, can librechat support the o1 series of GitHub models by way of custom endpoint?(o1-mini, o1-preview)
