### ISSUE TITLE
[Bug]: npm run user-stats

### ISSUE THREAD

**Issue by DeeDrop** [danny-avila/LibreChat#4960]
### What happened?

When running: docker exec -it LibreChat npm run user-stats i get this error:
-----------------------------
Show the stats of all users
-----------------------------
There was an uncaught error:
TypeError: Conversation.count is not a function
    at /app/config/user-stats.js:22:50
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Steps to Reproduce

1. run npm run user-stats

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Already addressed, thanks!
