### ISSUE TITLE
Enhancement: Gemini 2.0 Flash support

### ISSUE THREAD

**Issue by w95** [danny-avila/LibreChat#4972]
### What features would you like to see added?

https://developers.googleblog.com/en/the-next-chapter-of-the-gemini-era-for-developers/

### More details

https://developers.googleblog.com/en/the-next-chapter-of-the-gemini-era-for-developers/

### Which components are impacted by your request?

General

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Already implemented here: #4951
