### ISSUE TITLE
Enhancement: Button to toggle Canvas in the message box

### ISSUE THREAD

**Issue by kneelesh48** [danny-avila/LibreChat#4976]
### What features would you like to see added?

Can we have a button to toggle Canvas in the message box similar to chatgpt and mistral app?

### More details

Currently it's in settings and I forget it's on and results in sending a lot more input tokens even when it's not necessary

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
For Artifacts, I will implement something like this, likely a conversation parameter.
