### ISSUE TITLE
[Bug]: Agents - Uploaded documents for File search not shared

### ISSUE THREAD

**Issue by dvejsada** [danny-avila/LibreChat#4999]
### What happened?

If you create an Agent and upload documents for the File Search, and then as Admin share the agent to all users, the **uploaded documents are not shared to other users** and the file search will thus return no result. Tried both with or without editing of agent by other users enabled, with no success.

What I am trying to achieve is to have an internal chatbot grounded with internal regulations. I had similar set up with both OpenAI and Azure assistants with success.

### Steps to Reproduce

1. Create new Agent
2. Enable File Search and Upload Document
3. In sharing settings, share the agent to all users
4. Log in as different user and use this agent with question pertaining to the uploaded documents.
5. Agent will run file search but returns no result and the answer is clearly not based on the documents.

### Relevant log output

```shell
No relevant logs.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks, I'll address this within the next 24 hours.

**Comment by dvejsada** [comment]
> Thanks, I'll address this within the next 24 hours.

Great, thank you very much.

Just one suggestion. It should be differentiated between the documents uploaded to the agent at the creation window (which should be shared if the agent is shared), and documents uploaded as a part of specific conversation with agent which should not be shared and be used only for this specific conversation.

**Comment by danny-avila** [comment]
I understand, this is on my list today, did not mean to delay

**Comment by danny-avila** [comment]
Closed by #5028.

Requires RAG API to be at latest build: https://github.com/danny-avila/rag_api/pull/107
