### ISSUE TITLE
Enhancement: Add to bar select assistant (Cont. 1343)

### ISSUE THREAD

**Issue by OriNachum** [danny-avila/LibreChat#5033]
### What features would you like to see added?

When adding 'prompt=...' librechat injects the prompt to the assistant.
I suggest adding also "&assistant=..." to pre-select assistant and send it to the assistant directly.

This can streamline assistants through links and can integrate LibreChat use in any workflow.

### More details

Example url and usecase:
Url: https://.../new?assistant=calendar-manager&prompt=What%20are%20my%20tasks%20for%20today?

Now can ask in the predefined address bar: "What are my tasks today?" and get an assistant that has access to my calendar and can provide a summary.

### Which components are impacted by your request?

UI, Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks, I’ll add your comment to the existing issue about query params
