### ISSUE TITLE
[Bug]: No agent ID provided for agent file upload

### ISSUE THREAD

**Issue by mootfrost** [danny-avila/LibreChat#5046]
### What happened?

When trying to upload non image file to agent, i receive this error: Error processing file: No agent ID provided for agent file upload.
The only fields in req.body  in processAgentFileUpload are: endpoint and file_id. no message_file or agent_id

### Steps to Reproduce

1. Enable agents
2. Try to upload file

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Non-image file requires a "tool resource" selection:

![firefox_7J8QXxt31D](https://github.com/user-attachments/assets/1f4f3e84-4303-4898-bfc9-9c48b4a8fdad)

If you're not seeing this new menu, you will need to update.

In any case, I handled the exact issue you were having in #5048 to make this more apparent.
