### ISSUE TITLE
[Question]: Can I put agents into the endpoint dropdown alongside with other endpoints?

### ISSUE THREAD

**Issue by khfung** [danny-avila/LibreChat#5094]
### What is your question?

Can I put agents into the endpoint dropdown alongside with other endpoints?

### More Details

Instead of choosing the agents in the side bar, is there any ways to put agent into the endpoint dropdown alongside with other endpoints?
![image](https://github.com/user-attachments/assets/1c0a58ad-3784-4800-8abe-1a4b6a736014)
Like if i have a agent called Code Interpreter, i can put in there
I understand that I can use 
modelSpecs:
  enforce: true
  prioritize: true
  list:
however, I want to have other endpoints like the one show in the image too, instead of using the model specs one by one

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Please see: https://github.com/danny-avila/LibreChat/issues/5000
