### ISSUE TITLE
[Bug]: a11y: side panel buttons still reachable with a screenreader when sidebar is collapsed

### ISSUE THREAD

**Issue by fcnjd** [danny-avila/LibreChat#5118]
### What happened?

I'm blind and use a screenreader. Since the last update, the button to expand and collapse the side panel is well-labeled and as the correct attributes that inform the screenreader about the current state. When it is expanded, all controls are labelled as well. However, when it's collapsed, the corresponding buttons are still present on the interface, but not with their labels. but e.g. com_sidepanel_conversation_tags. I'd expect the bar to be closed, so the buttons shouldn't stay in the interface.

### Steps to Reproduce

1. Open Librechat
2. Collapse the side bar
3. Use the tab key which still focuses the buttons
4. If you need, turn on a screenreader to confirm that they're read out

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks for your feedback and glad you can use LibreChat. When the side panel is collapsed, the buttons should still be present with their collapsed versions. 

There are 3 states for the side panel:
1. Expanded, controls have full view
2. Collapsed, control buttons are still present and when pressed, switches the panel to expanded state to bring selected control to full view
3. Hidden, side panel is completely hidden, this is triggered by selecting "Hide Panel" button within the side panel.

Using NVDA, I see they are not properly labeled in their collapsed versions as you said, so I will close this issue when that is resolved.

**Comment by fcnjd** [comment]
Thank you for clarifying this, I didn't know about those three states. I can definitely use LibreChat with NVDA and am now a happy user for almost a year. Thank you for all your work in this, and I'm glad to see you already addressed those accessibility issues, it's very cool you're so much into that.
