### ISSUE TITLE
Enhancement: automatically build/release docker images

### ISSUE THREAD

**Issue by jinzishuai** [danny-avila/LibreChat#531]
### What features would you like to see added?

It would be great if the docker images are made available directly, especially upon every [release/tag](https://github.com/danny-avila/LibreChat/releases).

### More details

This should be fairly easy to do using github actions and the images can be pushed to github packages or docker hub.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

###### edited for clarity

**Comment by ClaraLeigh** [comment]
Sounds like you know what to do? free to open a pr with the required GitHub action and notes on secret setup required

**Comment by danny-avila** [comment]
I usually update the dockerhub image just before release the tag, but yes I can look into this as this would save me a bit of pain

**Comment by jinzishuai** [comment]
> Sounds like you know what to do? Feel free to open a pr with the required GitHub action and notes on secret setup required

I created PR https://github.com/danny-avila/LibreChat/pull/536
