### ISSUE TITLE
Enhancement:

### ISSUE THREAD

**Issue by kuangxiaoye** [danny-avila/LibreChat#556]
### Contact Details

w258765@gmail.com

### What features would you like to see added?

 The problem that the speed of opening the website on the mobile terminal is too slow

### More details

I found a problem with slow opening of projects on mobile devices in the initial version. After updating to the latest version, I found a problem:

The speed of opening the project on the mobile side is not only not improved, but also more serious.

Is there a good solution?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I just loaded up on mobile and it was near instant on all fronts. This must be an issue with your local configuration or device and nothing to do with the app.

**Comment by danny-avila** [comment]
Also it's worth mentioning that nothing has been added to the frontend recently that would cause a slowdown. I only made minor optimizations recently to dialogs and the popover, which should actually help with speed on mobile.

**Comment by kuangxiaoye** [comment]
> Also it's worth mentioning that nothing has been added to the frontend recently that would cause a slowdown. I only made minor optimizations recently to dialogs and the popover, which should actually help with speed on mobile.

Maybe I'm not clear. I'm referring to a new device that has never accessed the project's browser and loads slowly the first time I use the project....

💔

**Comment by danny-avila** [comment]
> Maybe I'm not clear. I'm referring to a new device that has never accessed the project's browser and loads slowly the first time I use the project....
> 
> 💔

I'm just not sure how to help this issue. I've tried on 3 different browser with completely new hosted endpoints each time and I have no issue. This is almost like being on a new device, especially since one of the mobile browsers blocks cookies and caching.

My hosted server latency is 27 ms.

**Comment by kuangxiaoye** [comment]
I may have locked the question, is the online js file referenced in the project? 

This may affect the loading speed depending on the country.

**Comment by danny-avila** [comment]
> I may have locked the question, is the online js file referenced in the project?
> 
> This may affect the loading speed depending on the country.

can you tell me which js file exactly? That is perhaps an issue

**Comment by danny-avila** [comment]
@kuangxiaoye still haven't heard which js file may be causing the issue for you. As far as I know, nothing is being fetched on the frontend that may have a delay based on location.

**Comment by danny-avila** [comment]
Haven't heard anything, issue isn't clearly identified.
