### ISSUE TITLE
[Bug]: Password length checks on signup page are inconsistent (and short)

### ISSUE THREAD

**Issue by Infinoid** [danny-avila/LibreChat#561]
### Contact Details

mark-github@glines.org

### What happened?

I tried to quickly try out the LibreChat service locally, using `docker-compose` on Linux.  I hadn't even fully configured it yet when I hit this issue.

When attempting to sign up for the service, there's no indication (at first) of what constraints the password has.
So I used my password manager to generate one, and its length was set to 127 characters.
I tried it, it failed, it told me the limit was <40.
So I generated another one, length 40.  (Note: *equal* to 40, not "less than 40" as the message says.)
I tried it, it failed, now it tells me the limit is <=20.

See screenshot.  I drew some arrows on it.

I guess the length is validated by both your frontend and backend, and they don't agree on the length.  Why the inconsistency?

And why limit it to such a short length?  In 2023, long passwords are cheap and easy, why not support them?  Where does the actual constraint come from?  Some string field in a mongodb object?  This is my completely subjective impression, but 20 characters seems very short; most sites seem to accept 60+ characters these days.

### Steps to Reproduce

1. `git clone https://github.com/danny-avila/LibreChat/`
2. `cd LibreChat`
3. `cp .env.example .env`
4. `docker-compose up -d`
5. pointed my web browser at http://localhost:3080/
6. I see a login page with a signup link.  I click the signup link.
7. I set up a password in my password app (bitwarden), which was set to use 127-character passwords at the time.
8. I try to use it.  I get `Password must be less than 40 characters`
9. I set up a second password in my password app, with the length set to 40 characters.
10. I try to use it.  I get `"password" length must be less than or equal to 20 characters long`

### What browsers are you seeing the problem on?

Google Chrome | 114.0.5735.133 (Official Build) (64-bit)

### Relevant log output

```shell
40623ce13e8b No 'auth.json' file (service account key) found in /api/data/ for PaLM models
40623ce13e8b Route: register - Joi Validation Error {
40623ce13e8b   name: 'Request params:',
40623ce13e8b   value: {
40623ce13e8b     name: 'Mark Glines',
40623ce13e8b     username: 'infinoid',
40623ce13e8b     email: 'mark@glines.org',
40623ce13e8b     password: '[40-character password was here]',
40623ce13e8b     confirm_password: '[40-character password was here]'
40623ce13e8b   }
40623ce13e8b } {
40623ce13e8b   name: 'Validation error:',
40623ce13e8b   value: [
40623ce13e8b     {
40623ce13e8b       message: '"password" length must be less than or equal to 20 characters long',
40623ce13e8b       path: [Array],
40623ce13e8b       type: 'string.max',
40623ce13e8b       context: [Object]
40623ce13e8b     }
40623ce13e8b   ]
40623ce13e8b }
```

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/50254/e89f9da6-d1d7-4d78-b0ac-2d9fcba81211)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
There's no reason in particular. I'm sure this was just overlooked, should be an easy fix.

**Comment by danny-avila** [comment]
Completed by #564
