### ISSUE TITLE
Enhancement: Add a feature to render LaTeX-formatted equations

### ISSUE THREAD

**Issue by yuanmu0814** [danny-avila/LibreChat#571]
### Contact Details

yuanmu.email@gmail.com

### What features would you like to see added?

Could you add a feature to render LaTeX-formatted equations? The equations generated by ChatGPT are difficult to understand. Thanks!

### More details

Could you add a feature to render LaTeX-formatted equations? The equations generated by ChatGPT are difficult to understand. Thanks!

### Which components are impacted by your request?

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Sure, this should be easy. Can you give me some examples of prompts I can use for testing?
