### ISSUE TITLE
Enhancement: Auto scroll to bottom of conversation when opening

### ISSUE THREAD

**Issue by javon27** [danny-avila/LibreChat#573]
### What features would you like to see added?

In ChatGPT, when you open an existing conversation, it loads it with it already scrolled to the last message (no scroll animation). I'd like us to have something similar. I've played around with the code and got it to work like that. 

### More details

The change just requires calling `scrollToBottom()` when the Messages component is loaded.

```
  useEffect(() => {
    const timeoutId = setTimeout(() => {
      const { scrollTop, scrollHeight, clientHeight } = scrollableRef.current;
      const diff = Math.abs(scrollHeight - scrollTop);
      const percent = Math.abs(clientHeight - diff) / clientHeight;
      const hasScrollbar = scrollHeight > clientHeight && percent > 0.2;
      setShowScrollButton(hasScrollbar);
      // Scroll to bottom when conversation loads
      if (hasScrollbar) {
        scrollToBottom();
      }
    }, 650);
```

### Which components are impacted by your request?

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This is definitely a preference thing for me, since I actually prefer the way it works now. However, now that we have a settings dialog, this can be toggled on/off. Will look it into, and I really appreciate you highlighting a solution.

**Comment by javon27** [comment]
I look forward to seeing that option! I would do it myself, but I'm really a novice when it comes to React. Took me way too long to even find where to make that change. For now, I'm fine with making custom changes to my own deployments

**Comment by kuangxiaoye** [comment]
> This is definitely a preference thing for me, since I actually prefer the way it works now. However, now that we have a settings dialog, this can be toggled on/off. Will look into, and I really appreciate you highlighting a solution.

Dear Danny, I noticed that there is a branch currently maintaining Claude. I would like to know when it will be merged into the main branch and go live?(✧∀✧)

**Comment by danny-avila** [comment]
> > This is definitely a preference thing for me, since I actually prefer the way it works now. However, now that we have a settings dialog, this can be toggled on/off. Will look into, and I really appreciate you highlighting a solution.
> 
> Dear Danny, I noticed that there is a branch currently maintaining Claude. I would like to know when it will be merged into the main branch and go live?(✧∀✧)

You should not thread hijack and you can comment on the relevant PR #552
