### ISSUE TITLE
Confirm or cancel option when deleting a conversation

### ISSUE THREAD

**Issue by Root-FTW** [danny-avila/LibreChat#602]
### What features would you like to see added?

When you go to edit the name of a conversation it gives you the option to confirm, it is possible that when you go to delete a conversation it also gives you the option to confirm or cancel.

![2023-07-07 09_53_35](https://github.com/danny-avila/LibreChat/assets/108767514/9f7d76c5-d674-48b9-b9a1-e212edb47bad)

![2023-07-07 09_53_47](https://github.com/danny-avila/LibreChat/assets/108767514/e4c96766-72ba-49e3-b46f-3bac6cc176ed)

### More details

When you go to edit the name of a conversation it gives you the option to confirm, it is possible that when you go to delete a conversation it also gives you the option to confirm or cancel.

### Which components are impacted by your request?

UI

### Pictures

![2023-07-07 09_53_47](https://github.com/danny-avila/LibreChat/assets/108767514/ae5f832e-1060-4b93-b2a4-7eae7af8ea7b)
![2023-07-07 09_53_35](https://github.com/danny-avila/LibreChat/assets/108767514/a31ec0b3-3ce3-4ef4-871a-2b4277c8590e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Berry-13** [comment]
I directly created a dialogue so that we are equal to OpenAI
