### ISSUE TITLE
[Bug]: can't deleted the conversation

### ISSUE THREAD

**Issue by Maddaxman** [danny-avila/LibreChat#608]
### What happened?

can't deleted the conversation

### Steps to Reproduce

the lastest version
<img width="1246" alt="image" src="https://github.com/danny-avila/LibreChat/assets/31379908/eadd1cfc-9a2a-4cab-a3d0-2f23826a95c4">

<img width="995" alt="image" src="https://github.com/danny-avila/LibreChat/assets/31379908/750a00a0-f517-42a0-8b1a-8ce63492735e">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks for catching this. I'm applying a fix now.
