### ISSUE TITLE
[Bug]: After returning to the previous page, the login page is skipped

### ISSUE THREAD

**Issue by temapskov** [danny-avila/LibreChat#623]
### Contact Details

psk@ro.ru

### What happened?

Redirect without login page
![bug](https://github.com/danny-avila/LibreChat/assets/11812920/46b85785-c60f-4a1f-856b-47c4a0322d48)

### Steps to Reproduce

On login page
1. Enter incorrect credentials;
2. Press return to previous page

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Screenshots

![bug](https://github.com/danny-avila/LibreChat/assets/11812920/46b85785-c60f-4a1f-856b-47c4a0322d48)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks, this is known for a bit. The good news is even though you access the page, your session isn’t authorized, so you wouldn’t actually be able to send messages

**Comment by danny-avila** [comment]
Update: I have a fix for this but I'm just doing my due diligence and testing across multiple environments
