### ISSUE TITLE
[Bug]: there is no default system message

### ISSUE THREAD

**Issue by SailFlorve** [danny-avila/LibreChat#630]
### What happened?

If the Prompt Prefix field is left blank, there will be no system messages with the "role: system" sent.

### Steps to Reproduce

send a message, and see logs.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I'm not sure what you're referring to, which endpoint, what is the desired/expected result, can you provide an example of what you mean? 

If we're talking about OpenAI specifically, it's not expected that there should be a default system message. They are not required in the payload. This allows for a raw interaction between user/assistant roles, unless a system message is explicitly defined.

**Comment by SailFlorve** [comment]
Indeed, it is the OpenAI endpoint. However, the placeholder for 'prefix' in the settings does say something like "default to: you are chatgpt...."
![Screenshot_2023-07-14-10-46-41-893_com microsoft emmx](https://github.com/danny-avila/LibreChat/assets/25448499/d0632231-ec4e-40bb-abb0-1e4026778211)

**Comment by danny-avila** [comment]
> Indeed, it is the OpenAI endpoint. However, the placeholder for 'prefix' in the settings does say something like "default to: you are chatgpt...."
> ![Screenshot_2023-07-14-10-46-41-893_com microsoft emmx](https://user-images.githubusercontent.com/25448499/253457255-d0632231-ec4e-40bb-abb0-1e4026778211.png)

Ah I see.thank you for sharing the screenshot and clarifying. Good point, I’ll have to remove this placeholder text because it’s not accurate anymore. I find it better to omit a system message completely and let the user decide.
