### ISSUE TITLE
Enhancement: Modify the AI's side of the conversation

### ISSUE THREAD

**Issue by njbbaer** [danny-avila/LibreChat#639]
### Contact Details

njbbaer@gmail.com

### What features would you like to see added?

Allow the user to modify the AI's side of the conversation.

### More details

I know this isn't a part of the official ChatGPT, but it's extremely useful to me that the OpenAI Playground can modify both sides of the conversation. Could it be possible to do this with Libre Chat?

### Which components are impacted by your request?

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Interesting idea, it's very possible. There's multiple ways of approaching this so will have to think about it.

**Comment by njbbaer** [comment]
Awesome. Thank you @danny-avila!
