### ISSUE TITLE
Improved UI and Functionality for Language Selection and Model Endpoint in Lirbechat

### ISSUE THREAD

**Issue by techwithanirudh** [danny-avila/LibreChat#640]
### Contact Details

hello@techwithanirudh.com

### What features would you like to see added?

Enhancements to the language selection functionality and model endpoint selection in LibreChat, including:

1. Translation of the "New Chat" button in the sidebar.
2. Increased spacing between the "New Chat" button and the conversations.
3. Improved hover behavior for the open sidebar button.
4. Ability to change the current language through the settings modal.
5. ChatGPT's capability to generate new translations from English.
6. Ability to change the model by clicking on the top model endpoint select.
7. Ensure model selection functionality works for all endpoints, not just for OpenAI.

### More details

The current UI in Librechat has some minor issues that impact the user experience. The "New Chat" button in the sidebar is not translated when the language is changed, which can cause confusion for multilingual users. Additionally, there is insufficient spacing between the "New Chat" button and the conversations, making the UI feel cluttered.

Furthermore, when dismissing the sidebar, the hover behavior is applied to the icon instead of the entire button, which can be misleading. It would be more intuitive if the hover effect is applied to the button itself.

The language selection functionality is limited to the settings modal, and users cannot change the current language through this modal. It would greatly improve the user experience if a language selection option is provided within the settings, allowing users to switch languages seamlessly.

Additionally, it would be beneficial if ChatGPT could generate new translations from English, expanding its capabilities for internationalization (i18n).

Lastly, the model endpoint selection could be improved. Currently, users can change the model from the select box below, but it is not possible to do so by clicking on the top model endpoint select. Enabling this functionality and ensuring it works for all endpoints, not just for OpenAI, would provide a more consistent and user-friendly experience.

### Which components are impacted by your request?

General, UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Changing models in the message header is not planned.

And I think you handled the icon issue in https://github.com/danny-avila/LibreChat/pull/643

Internationalization is not a priority but I will welcome PRs.
