### ISSUE TITLE
Enhanced UI and Functionality for Sidebar, Button Presentation, and Help Documentation in ChatGPT Clone

### ISSUE THREAD

**Issue by techwithanirudh** [danny-avila/LibreChat#641]
### Contact Details

hello@techwithanirudh.com

### What features would you like to see added?

Enhancements to the ChatGPT Clone's user interface and functionality, including:

1. Smooth transitions while opening and closing the sidebar.
2. Improved presentation of the "Regenerate" and "Stop Responding" buttons.
3. Addition of a "Help" and "FAQ" sidebar item linking to the documentation.

### More details

1. Smooth transitions for opening and closing the sidebar: Implement smooth animations or transitions when opening and closing the sidebar. This will provide a more visually appealing and seamless experience for users.
 
2. Improved presentation of "Regenerate" and "Stop Responding" buttons: Make the "Regenerate" and "Stop Responding" buttons more prominent and easily accessible. This can be achieved by using visually distinct styling or positioning the buttons in a more noticeable manner, similar to how ChatGPT presents these buttons.
 
3. "Help" and "FAQ" sidebar item linking to the documentation: Add a dedicated "Help" or "FAQ" item in the sidebar that, when clicked, takes users directly to the documentation or FAQ section. This will provide quick access to relevant information and assist users in finding answers to common queries.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
1. should be easy, I'll get to it when I can
2. Need to think about how to do this while keeping the current conversation settings somewhere
3. is handled by you in https://github.com/danny-avila/LibreChat/pull/643
