### ISSUE TITLE
Enhancement: Playground interface for text completion

### ISSUE THREAD

**Issue by elinorgodzilla** [danny-avila/LibreChat#658]
### What features would you like to see added?

Hi! I would like to request a feature that gives a text completion feature like it is on on OpenAI Playground and Claude console. This way we could continuously generate text, it would be tremendous help for writers and gives opportunity for more creative ways of text generation. I would like to request that it should continue text from the last character as it is available on Anthropic's Claude console. That way we could edit the full conversation and force the AI to continue from where it left off or make it produce longer responses or steer the responses in way we want.

Are you familiar with Claude Console? That way we can edit or have the conversation in a text format instead of just on the chat interface and when I press  "generate" it makes the ai continue exactly where it left off. Please kindly reconsider my recommendation!

### More details

Example is claude console, picture included.
In this example I make it talk about cats then I delete part of it, add the word "dinosaur" and the AI is now forced to continue the text completion from there. This allows full control on the text, the direction where the AI will have to steer. I believe this would be crucial to give us full control over the conversation/text completion

### Which components are impacted by your request?

General

### Pictures

![claude console](https://github.com/danny-avila/LibreChat/assets/106490429/6494eca8-dcc8-428a-9713-56ee64993a6e)
![dinosaurs](https://github.com/danny-avila/LibreChat/assets/106490429/8af4b4cc-fea1-4941-8b70-a23a09d13996)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by techwithanirudh** [comment]
https://nat.dev/ has this functionality, this project is focused on cloning the UI/UX of ChatGPT.

**Comment by danny-avila** [comment]
It’s possible and I’m open to doing this. Will add it to the roadmap

**Comment by fuegovic** [comment]
Here's another reference on the subject:

https://docs.anthropic.com/claude/docs/ask-claude-to-think-step-by-step

**Comment by danny-avila** [comment]
@elinorgodzilla I am introducing the initial functionality for this very soon through a "continue regenerating" button, similar to chatgpt. 

You can see my progress [on discord here](https://discord.com/channels/1086345563026489514/1133371441035870349)

This initial logic will release today. And then the next step is to edit the AI messages themselves, which a lot of the work for this is done now since it will use the same logic.

This is related to #639
