### ISSUE TITLE
[Bug]: Jailbreak to enable Sydney; the "main" branch of LibreChat does not contain the path client/defaultSystemMessage.md

### ISSUE THREAD

**Issue by GalexGX** [danny-avila/LibreChat#665]
### What happened?

When using Bing AI and turning on Sydney, if you click on the button "System message", (it's blue and right below the checkbox to enable Sydney) it returns to a 404 page of the LibreChat repository with the error "the "main" branch of LibreChat does not contain the path client/defaultSystemMessage.md"

### Steps to Reproduce

1. Select Bing AI as your Chatbot
2. Go to session settings 
3. Turn on Sydney (click on the checkbox "Jailbreak to enable Sydney")
4. Click on "System Message" (a blue button right below the checkbox)
5. You're done reproducing.

### Screenshots

![](https://cdn.discordapp.com/attachments/1115668246830530622/1130447297524793394/image.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
Thanks for letting us know, the documentation has changed, this was an oversight. 
You can find the relevent doc here:
https://docs.librechat.ai/features/bing_jailbreak.html

or here:
https://github.com/danny-avila/LibreChat/blob/main/docs/features/bing_jailbreak.md#default-system-message-for-jailbreak-mode-sydney
