### ISSUE TITLE
[Bug]: Palm2: Text-Bison-001 is no longer working

### ISSUE THREAD

**Issue by MontDawgg** [danny-avila/LibreChat#666]
### Contact Details

montediaz@live.com

### What happened?

Text-Bison is no longer working under the Palm2 model selection. Chat Bison is working fine. Text Bison is giving "bad request" error message. 

*Additional Context*
Text Bison is interesting because it allows for the changing of safety parameters to get more or less censored outputs. It is unclear whether its specific implementation in LibreChat allows this. Clarification/implementation here would be useful. 

### Steps to Reproduce

1. Select Palm2
2. Select Text-Bison
3. Submit a query. 

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell
},
    paramsSerializer: [Function: paramsSerializer],
    body: '{"instances":[{}],"parameters":{"model":"text-bison","modelLabel":null,"temperature":0.2,"maxOutputTokens":1024,"topP":0.95,"topK":40}}',
    validateStatus: [Function: validateStatus],
    responseType: 'json'
  },
  code: 400,
  errors: [
    {
      message: 'Invalid instance: struct_value \t {\n}\n',
      domain: 'global',
      reason: 'badRequest'
    }
  ]
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Was resolved with the recent google update, just forgot to close this: https://github.com/danny-avila/LibreChat/commit/583e978a820225c4dda94d35d6058e8106efb3e8
