### ISSUE TITLE
Enhancement: Ability to change the order of the presets

### ISSUE THREAD

**Issue by fuegovic** [danny-avila/LibreChat#685]
### What features would you like to see added?

Having the ability to rearrange presets would be incredibely useful

### More details

[insert picture of a profile with a lot of presets here]

### Which components are impacted by your request?

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
You can somewhat do this now as presets are ordered by last updated, with recent at the top, as well as the default preset being at the top.
