### ISSUE TITLE
[Bug]: Error: Cannot find module 'langchainplus-sdk' using Docker

### ISSUE THREAD

**Issue by justjoehere** [danny-avila/LibreChat#711]
### Contact Details

joseph.ours@gmail.com

### What happened?

Pulled latest
Ran 
```bash
docker-compose build --no-cache
docker-compose up -d
```

Docker container constantly reboots with the error Error: Cannot find module 'langchainplus-sdk' 

### Steps to Reproduce

See description

To fix locally, I added this to line 6 of the Dockerfile
`RUN npm install langchainplus-sdk`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Donavan** [comment]
@danny-avila  I ran into this same issue a while back and forgot to mention it.  I completely forgot about this hack I had done until @justjoehere  ran into it.

**Comment by fuegovic** [comment]
@justjoehere @Donavan 

we have a documented fix for that:
https://github.com/danny-avila/LibreChat/blob/main/docs/general_info/breaking_changes.md#v055
