### ISSUE TITLE
Enhancement: Support for the new Bing image recognition

### ISSUE THREAD

**Issue by Mitman93** [danny-avila/LibreChat#718]
### What features would you like to see added?

Pretty self-explanatory. Bing recently had an update where you can now upload images in your chats, and it does a decent job at understanding them. This functionality (image upload) on the frontend shouldn't be too difficult to implement into LibreChat, no? Just wondering. Thanks for all that you do on this great project!

### More details

![image](https://github.com/danny-avila/LibreChat/assets/123063442/f6188997-9792-4bbf-81e6-00c9c88ea9c3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Hi @Mitman93 thanks for requesting this.

Unfortunately, it may not be so simple since Bing access is very hacky, using unofficial access to the backend api of bing.com, and something I haven't personally worked as I use a dependency to use it with this project.

Even so, it's not yet implemented in one of the more popular projects: https://github.com/acheong08/EdgeGPT/issues/573

I will have to defer this feature to a 3rd party.

I am working on file support, and we may get image interpretation by way of another means sooner.

**Comment by UnknownErrorCodes** [comment]
> Hi @Mitman93 thanks for requesting this.
> 
> Unfortunately, it may not be so simple since Bing access is very hacky, using unofficial access to the backend api of bing.com, and something I haven't personally worked on as I use a dependency to use it with this project: https://github.com/waylaidwanderer/node-chatgpt-api
> 
> Even so, it's not yet implemented in one of the more popular projects: [acheong08/EdgeGPT#573](https://github.com/acheong08/EdgeGPT/issues/573)
> 
> I will have to defer this feature to a 3rd party.
> 
> I am working on file support, and we may get image interpretation by way of another means sooner.

Thank you for your hard work. 
I noticed that someone has implemented the new Bing image recognition feature in the issue you mentioned at  [acheong08/EdgeGPT#573](https://github.com/acheong08/EdgeGPT/issues/573). Here's the project link: [renqabs/ChatSydney-react-img](https://github.com/renqabs/ChatSydney-react-img). You may have noticed it already, but I hope it could be helpful to your work.

**Comment by Airkek** [comment]
@danny-avila what do you think about this PR?: https://github.com/waylaidwanderer/node-chatgpt-api/pull/452
It would be nice if LibreChat supported this

**Comment by danny-avila** [comment]
> @danny-avila what do you think about this PR?: [waylaidwanderer/node-chatgpt-api#452](https://github.com/waylaidwanderer/node-chatgpt-api/pull/452) It would be nice if LibreChat supported this

I can look into it!
