### ISSUE TITLE
Enhancement: Move system message to the top of message list

### ISSUE THREAD

**Issue by SailFlorve** [danny-avila/LibreChat#752]
### What features would you like to see added?

Now, the system message is positioned between the historical messages and the most recent message sent by the user. Can the system message be moved to the top, so that the order is now system message first, followed by historical messages, and then the new message sent by the user?

### More details

no more.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
>  between the historical messages and the most recent message 

From my testing, this yielded the best adherence to the system message in almost all cases across different LLMs (namely Claude and OpenAI). 

Do you have a reason for this?

**Comment by SailFlorve** [comment]
I'm just not sure if placing the system message in different positions would affect the quality of responses, because generally speaking and in official examples, the system message is at the very top.

**Comment by danny-avila** [comment]
Official examples do this but changing position, and even including instructions in the most recent user message does affect it, especially after a long string of messages. In OpenAI’s backend, these messages end up getting formatted into a conversational “document,” with the message role and label preceding each of its content. When the LLM sees the system instructions just before where it should predicting/generating text, it’s likely to generate text closer in proximity to what it saw just before.

This may be a bigger discussion where I should allow the editing of AI/assistant messages along with roles. This is planned for sure

**Comment by RodolfoCastanheira** [comment]
> Official examples do this but changing position, and even including instructions in the most recent user message does affect it, especially after a long string of messages. In OpenAI’s backend, these messages end up getting formatted into a conversational “document,” with the message role and label preceding each of its content. When the LLM sees the system instructions just before where it should predicting/generating text, it’s likely to generate text closer in proximity to what it saw just before.
> 
> This may be a bigger discussion where I should allow the editing of AI/assistant messages along with roles. This is planned for sure

Models are typically trained with the system message at the top, so some may overreact to this ordering with it as the second most recent. OpenAI doesn't seem to be bothered, but less sophisticated (and open) models exhibit lower performance with this, in my personal experience.

Maybe this could be a togglable option?

**Comment by SailFlorve** [comment]
According to some researches, moving system message to bottom makes models generating more effective response, otherwise the model has posibility forget the system mrssage. So this is reasonable put system message at bottom.

**Comment by danny-avila** [comment]
> According to some researches, moving system message to bottom makes models generating more effective response, otherwise the model has posibility forget the system mrssage. So this is reasonable put system message at bottom.

the system message is always kept within context, and never discarded though. I never have issue with it following the system message (or custom instructoins). Do you mind sharing your sources?
