### ISSUE TITLE
Pull Request Ideas

### ISSUE THREAD

**Issue by techwithanirudh** [danny-avila/LibreChat#759]
### Contact Details

hello@techwithanirudh.com

### What features would you like to see added?

**Difficulty Level: Easy**
- Remove the extra padding from the setting sliders.

![image](https://github.com/danny-avila/LibreChat/assets/70373803/19d68e02-e184-4f81-b145-e028cf1d5267)

- Making the top bar sticky (like OpenAI). 

![image](https://github.com/danny-avila/LibreChat/assets/70373803/8870581a-15ef-4f7a-9f7d-7f6b5ef86410)

**Difficulty Level: Medium**
- Adding the new login page, which OpenAI uses.

![image](https://github.com/danny-avila/LibreChat/assets/70373803/afb54c78-42a7-4747-8b6f-b155134a285b)

- Adding OpenAI styled selects for the settings modal.

Before:
![image](https://github.com/danny-avila/LibreChat/assets/70373803/90453b54-d90a-4eef-90b4-dc529710035f)

After:
![image](https://github.com/danny-avila/LibreChat/assets/70373803/adec4dc2-3478-4424-bb60-9049eb544d67)

- Adding keyboard shortcuts with the help icon.

![image](https://github.com/danny-avila/LibreChat/assets/70373803/03f49b35-6ebd-4fb8-96d9-cc6f5e7a94f6)
![image](https://github.com/danny-avila/LibreChat/assets/70373803/b8aad768-9227-4288-9447-854333c560f9)

**Difficulty Level: Hard**
- Using dynamic prompts / queries on the login page.

[https://veed.io/view/f6510754-0f26-485d-8d61-98f9e66b08bf](Video Demo)

- Adding the new examples, which OpenAI uses on the homepage.

Before: 
![image](https://github.com/danny-avila/LibreChat/assets/70373803/3907ef94-34db-429b-be75-538b77bf451d)

After:
![image](https://github.com/danny-avila/LibreChat/assets/70373803/cc60a1e3-ba5c-4aa4-9210-8f388d83b237)

- Auto recommending new questions to the AI, from the current chat, Like OpenAI.

![image](https://github.com/danny-avila/LibreChat/assets/70373803/028c632b-7709-41b3-881a-063e42d8d7a4)

- Making the model select like OpenAI.
**E.g.: When OpenAI is selected, show two models gpt-3.5 and gpt-4, there will be a dropdown for each model, which will allow you to change the model version and plugins.**

Before:
![image](https://github.com/danny-avila/LibreChat/assets/70373803/8eca63c1-8ff4-43c1-a5cf-e73e7703a016)

After:
![image](https://github.com/danny-avila/LibreChat/assets/70373803/9558f07d-7484-4434-9fbd-41f5f79a1e59)

**Difficulty Level: Extreme**

**Extreme Level:**
- Adding share convos support.

![image](https://github.com/danny-avila/LibreChat/assets/70373803/430fbb12-d5c2-475d-93d2-ec781b503051)
![image](https://github.com/danny-avila/LibreChat/assets/70373803/a7e342ac-84da-46f3-9760-c063670700fc)

- Allowing the user to like/dislike the AI response, and the AI would learn from it.

Before:
![image](https://github.com/danny-avila/LibreChat/assets/70373803/6f6a6c95-c862-4c6a-916d-65a119e2d089)

After:
![image](https://github.com/danny-avila/LibreChat/assets/70373803/dd58d5b7-6984-4431-86e5-e0c245c551bf)

### Which components are impacted by your request?

General, UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Berry-13** [comment]
wow a lot of things😅. I just don't like removing the help and faq. I really appreciate the search message below and also the login page, although we could do the whole login page like that. Putting the like button would make little sense since they don't use the api to train their models. splitting templates with gpt 3 and gpt 4 is not a bad idea as text-davinci-002 will also be removed in January.


I'm working these days to improve the dropdown menu and make it like OpenAI
