### ISSUE TITLE
[Bug]: Error 'JSON.parse: unexpected end of data at line 1 column 1 of the JSON data'

### ISSUE THREAD

**Issue by justjoehere** [danny-avila/LibreChat#762]
### Contact Details

joseph.ours@gmail.com

### What happened?

I pulled the latest and rebuilt the application.  Upon launching I received this following error

Unexpected Application Error!
JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

fl/<@http://localhost:3080/assets/index-f060b99d.js:41:8935
Km@http://localhost:3080/assets/vendor-c916abd2.js:40:24283
Ru@http://localhost:3080/assets/vendor-c916abd2.js:40:42408
cH@http://localhost:3080/assets/vendor-c916abd2.js:40:41228
xA@http://localhost:3080/assets/vendor-c916abd2.js:40:40275
F6@http://localhost:3080/assets/vendor-c916abd2.js:40:36885
cA@http://localhost:3080/assets/vendor-c916abd2.js:38:3279
ti/<@http://localhost:3080/assets/vendor-c916abd2.js:40:34263

Docker logs only show
23-08-05 15:02:02 
2023-08-05 15:02:02 > LibreChat@0.5.6 backend
2023-08-05 15:02:02 > cross-env NODE_ENV=production node api/server/index.js
2023-08-05 15:02:02 
2023-08-05 15:02:23 Connected to MongoDB
2023-08-05 15:02:24 There are 520 messages in the database, 520 indexed
2023-08-05 15:02:24 There are 82 convos in the database, 82 indexed
2023-08-05 15:02:25 Server listening on all interface at port 3080. Use http://localhost:3080 to access it
2023-08-05 15:02:35 User will provide key for PaLM models
2023-08-05 15:02:23 Warning: JWT_SECRET is set to default value

### Steps to Reproduce

1. `git pull`
2. `docker-compose build --no-cache`
3. `docker-compose up -d`
4. Open http://localhost:3080
5. Error received is
```text
Unexpected Application Error!
JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

fl/<@http://localhost:3080/assets/index-f060b99d.js:41:8935
Km@http://localhost:3080/assets/vendor-c916abd2.js:40:24283
Ru@http://localhost:3080/assets/vendor-c916abd2.js:40:42408
cH@http://localhost:3080/assets/vendor-c916abd2.js:40:41228
xA@http://localhost:3080/assets/vendor-c916abd2.js:40:40275
F6@http://localhost:3080/assets/vendor-c916abd2.js:40:36885
cA@http://localhost:3080/assets/vendor-c916abd2.js:38:3279
ti/<@http://localhost:3080/assets/vendor-c916abd2.js:40:34263
```

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/793205/7460bcda-acc9-42f4-8538-56978321ea51)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Did you try what's suggested here? 

https://github.com/danny-avila/LibreChat/blob/main/docs/general_info/breaking_changes.md#v055

**Comment by danny-avila** [comment]
i also recommend running this to update: `npm run update:docker`, which does the what the docs recommend

I just ran this command with no issue on startup.

**Comment by justjoehere** [comment]
I followed both
https://github.com/danny-avila/LibreChat/blob/main/docs/general_info/breaking_changes.md#v055

and 

` npm run update:docker'

I'm still getting the exact same error.

**Comment by justjoehere** [comment]
Ok, so I was trying to replicate what did I do differently prior to updating the code.  And I remembered I was going to try out plugins.  So here's what I learned

- If I clear browser data (cache/cookies) the error goes away.  If I chat with only models, I don't get the error
- If I attempt to enable plugins, as soon as I click on Plug-ins I get the error.  The only way to clear it is to get rid of browser cache/cookies

So I'm operational again, but I can't use plugins.

**Comment by danny-avila** [comment]
> Ok, so I was trying to replicate what did I do differently prior to updating the code. And I remembered I was going to try out plugins. So here's what I learned
> 
>     * If I clear browser data (cache/cookies) the error goes away.  If I chat with only models, I don't get the error
> 
>     * If I attempt to enable plugins, as soon as I click on Plug-ins I get the error.  The only way to clear it is to get rid of browser cache/cookies
> 
> 
> So I'm operational again, but I can't use plugins.

Awesome, these instructions were just what I needed to reproduce it. Fixed it and pushing soon

**Comment by danny-avila** [comment]
Confident this is fixed now, along with another unrelated Application error!

**Comment by justjoehere** [comment]
Fixed!  Thank you!

**Comment by danny-avila** [comment]
> Fixed! Thank you!

You’re welcome! Sorry for the issue, it’s always those one liner oversights

**Comment by looeee** [comment]
I ran into this exact issue today when upgrading from around 7.5 to 7.8. 

All I had to do to resolve it was to clear the site data in the browser and then log in again.
