### ISSUE TITLE
Enhancement: Document installation with vanilla docker (podman)

### ISSUE THREAD

**Issue by f1yn** [danny-avila/LibreChat#785]
### Contact Details

dev@flyn.ca

### What features would you like to see added?

I don't use docker (or Docker Desktop), and instead typically opt for install scripts that will create the container locally and then allow me to do what I wish with it. [I use podman, the libre alternative to docker](https://podman.io/), which supports 99% of the OCI commands that docker does.

In the case of the docker instructions, they are heavily geared towards using docker-compose - which isn't something every user who using using a container based installation will have or want to use, due to the extra overhead.

I'm going to be doing this myself, and I'll be making a PR that's referring to this issue - but essentially:

- Make a PR that adds podman/docker instructions (for both the local git repo, but also for the image you've added to the docker hub)

### More details

I will be working on this issue, likely over the next few days.

### Which components are impacted by your request?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Awesome, thank you for bringing this up. If it's worthwhile to you, you should look at Dockerfile.multi as well, which creates a leaner docker image (sub 700 mb) and is the main strategy for deploy-compose.yml.

Thanks again, and look forward to seeing and learning from this.

**Comment by f1yn** [comment]
Ended up using the local image build instead of documenting the docker hub one as it's not as up to date as source.

**Comment by danny-avila** [comment]
Dockerhub is no longer used in favor of GitHub containers, unless you meant that one!
