### ISSUE TITLE
[Bug]: The mailbox setting does not seem to work

### ISSUE THREAD

**Issue by voctot** [danny-avila/LibreChat#791]
### What happened?

I set up the Gmail mailbox, which came from the document. This error appeared when reset the password, and I did not receive the email

### Steps to Reproduce

1、reset the password,
2、Email Sent

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (node:internal/errors:717:14)
    at TLSSocket.onConnectEnd (node:_tls_wrap:1613:19)
    at TLSSocket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
```

### Screenshots

![1691829027651](https://github.com/danny-avila/LibreChat/assets/36097179/98b877c2-0057-4b2d-b860-2cc6c77bc4c1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Berry-13** [comment]
Are you sure EMAIL_SERVICE is correct? Can you also check your firewall or network restrictions?

**Comment by voctot** [comment]
> Are you sure EMAIL_SERVICE is correct? Can you also check your firewall or network restrictions?

gmail

**Comment by Berry-13** [comment]
I also use Gmail to reset the password and I just tried it on a clean install and everything works correctly. Have you tried updating Node.js? Is it running in Docker or on normal Windows/Linux/Mac? Are you hosting LibreChat on localhost or on a custom domain?

**Comment by voctot** [comment]
> I also use Gmail to reset the password and I just tried it on a clean install and everything works correctly. Have you tried updating Node.js? Is it running in Docker or on normal Windows/Linux/Mac? Are you hosting LibreChat on localhost or on a custom domain?

I'm using docker. Can you show me your configuration demo?

**Comment by Berry-13** [comment]
Sure!

EMAIL_SERVICE=gmail
EMAIL_USERNAME=my-email
EMAIL_PASSWORD=my-app-password (not your gmail password account )
EMAIL_FROM=noreply@my-domain.com

**Comment by voctot** [comment]
EMAIL_FROM=[noreply@my-domain.com](mailto:noreply@my-domain.com)
Can this be filled in casually?

**Comment by Berry-13** [comment]
sure
