### ISSUE TITLE
[Question]: Copy Code seems to be broken

### ISSUE THREAD

**Issue by githubdebugger** [danny-avila/LibreChat#804]
### What is your question?

Copy Code button seems to be broken, as it is not copying any code from the code snippet.

### More Details

Copy Code button seems to be broken, as it is not copying any code from the code snippet box. It errors out like this:

CodeBlock.tsx:25 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'writeText')
    at onClick (CodeBlock.tsx:25:35)
    at Object.IQ (vendor-c916abd2.js:37:9864)
    at FQ (vendor-c916abd2.js:37:10018)
    at kQ (vendor-c916abd2.js:37:10075)
    at n6 (vendor-c916abd2.js:37:31482)
    at bx (vendor-c916abd2.js:37:31899)
    at vendor-c916abd2.js:37:36812
    at ZE (vendor-c916abd2.js:40:36956)
    at V_ (vendor-c916abd2.js:37:8999)
    at f5 (vendor-c916abd2.js:37:33186)
    
I remember this was working earlier. The docker image was built yesterday fresh from git clone.

Also, I tried the "copy to clipboard" for AI chat response and that is working fine without any issues.

### What is the main subject of your question?

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I can't reproduce it, I'll look into it further 
![image](https://github.com/danny-avila/LibreChat/assets/110412045/ddf8a059-5fd6-4386-a0eb-641cf582d38d)

**Comment by danny-avila** [comment]
what browser are you on?
