### ISSUE TITLE
[Question]: Web Search plugin doesn't work

### ISSUE THREAD

**Issue by SuperMario22922** [danny-avila/LibreChat#817]
### Contact Details

supermario229@outlook.com

### What is your question?

I tried to use the web search plugin with gpt-4 but it always fails with this error. The AI doesn't seem to know that it has plugins and when I tell it to use it it fails to use web search. Did i configure something wrong? I attached an image of what i mean.

![CleanShot 2023-08-18 at 19 48 10@2x](https://github.com/danny-avila/LibreChat/assets/44635763/cc6ec640-ba4d-425d-83a1-d96400bee781)

### More Details

I also attached my log file if that helps.

[log.txt](https://github.com/danny-avila/LibreChat/files/12378003/log.txt)

### What is the main subject of your question?

Installation, Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Note that you're using ChimeraGPT which is a reverse proxy and may default to a model that doesn't support OpenAI functions. Try messing with the Settings next to the model selection, in particular the "agent settings" and try different models.

Even though the Web Search plugin is not developed by me, and issues specific to it or any 3rd party plugin will generally be dismissed, I can confirm it's working the official API 

![image](https://github.com/danny-avila/LibreChat/assets/110412045/bb5b63a9-02ea-4893-bcb3-0929c9dc9395)

**Comment by SuperMario22922** [comment]
Thanks for the help! I messed around with the agent settings and it works now
