### ISSUE TITLE
[Question]: Why is there no longer an option to register an account on the login page?

### ISSUE THREAD

**Issue by 20090601** [danny-avila/LibreChat#822]
### Contact Details

not important

### What is your question?

For some reason, the login interface for Librechat no longer has the option to register an account. When I enter my previously registered account, it says it cannot find the user information, resulting in being unable to use it.

### More Details

no more

### What is the main subject of your question?

User System/OAuth

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
You need to explicitly allow registration in your .env file like this:

```yaml
ALLOW_REGISTRATION=true
```

Most who copy .env.example will have it set as such since it's listed as needed

**Comment by 20090601** [comment]
However, I am accessing LibreChat on the website and cannot make changes to the site.

**Comment by danny-avila** [comment]
> However, I am accessing LibreChat on the website and cannot make changes to the site.

are you hosting it yourself? I can't help you if you're not.
