### ISSUE TITLE
Enhancement: Plugin Description

### ISSUE THREAD

**Issue by Falven** [danny-avila/LibreChat#834]
### What features would you like to see added?

More robust LangChain Tool/Plugin support.

### More details

Currently, we have a couple of plugins with long descriptions so that GPT responds in the manner we would expect.
The problem is that we just updated to 0.5.7 and now it is trying to use the FunctionsAgent insetad of the CustomAgent and there is a limitation where the `functions.description` property can not be very long (I think it may be between 1000-1500 tokens). I was wondering what you thought of implementing a solution where if any LangChain Tool/Plugin description exceeds the description token limit, it gets split up and applied as part of the pre-prompt? Or is there a better solution?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I’m presently working on this! The current plugin implementation leaves much to be desired considering what is possible. To more closely match the official implementation, tool/plugin descriptions should go in the system message

**Comment by danny-avila** [comment]
As of #845 we can use the `description_for_model` property in a Tool class as instructions to be given to the system message
- This is necessary as the OpenAI API limits the character length of function descriptions and allows us to use shorter, more general descriptions for the function itself, and pass along detailed guidelines to the system message.
- This more closely resembles how ChatGPT works with plugins
- The best example I made for this can be seen here: api\app\clients\tools\structured\Wolfram.js
- I also updated the 'make your own plugin' docs accordingly: https://docs.librechat.ai/features/plugins/make_your_own.html#step-2-define-your-tool-class
