### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by egcash** [danny-avila/LibreChat#836]
### What happened?

I entered correct 💯 bing token of _U cookie 🍪.

All other models are working fine.

But still facing this while generating this message on Librachat to Bing.

Error originates with both Sydney and Bing AI.

### Steps to Reproduce

Selected bing option.
I send message : "hi there"
While generating response,i encountered this error /.

### Relevant log output

```shell
Oops! Something went wrong. Please try again in a few moments. Here's the specific error message we encountered: /turing/conversation/create: failed to parse response body.
```

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/85733533/6a1d5c9c-7a57-4002-97e7-ca9166c4be67)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
You can search previous issues for this, as well as look for common solutions posted on our discord. @fuegovic has organized these into a discord thread https://discord.com/channels/1086345563026489514/1143941308684177429

You can also search the issues there.

**Comment by egcash** [comment]
> You can search previous issues for this, as well as look for common solutions posted on our discord. @fuegovic has organized these into a discord thread https://discord.com/channels/1086345563026489514/1143941308684177429
> 
> You can also search the issues there.

Can you please check your invite url?

**Comment by danny-avila** [comment]
> > You can search previous issues for this, as well as look for common solutions posted on our discord. @fuegovic has organized these into a discord thread https://discord.com/channels/1086345563026489514/1143941308684177429
> > You can also search the issues there.
> 
> Can you please check your invite url?

It's not an invite link, it's a link to the thread with bing solutions

to join the discord server, use https://discord.librechat.ai
