### ISSUE TITLE
[Bug]: Error when trying to generate with BingAI

### ISSUE THREAD

**Issue by Auditormadness9** [danny-avila/LibreChat#847]
### Contact Details

armenemra9@gmail.com

### What happened?

It shows this error:

![image](https://github.com/danny-avila/LibreChat/assets/71278545/03ec7c79-1f20-422f-b013-ba62fd72f9ef)

### Steps to Reproduce

1. Just chat with Sydney however you want.
2. After a while it starts to do this no matter how you message it.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

None

### Screenshots

Attached

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
This is not reproducible on my end, as is the case with many Bing issues. However, there are certainly many things you can try.

You can search previous issues for this, as well as look for common solutions posted on our discord. To join the discord server, use this link: https://discord.librechat.ai/

Once you join, @fuegovic has organized these into a discord thread which you can visit here: https://discord.com/channels/1086345563026489514/1143941308684177429

You can also search the issues on discord.

It would help to note what you have tried once visiting possible solutions. I'll implement SOCKS5 proxy support which should help assuming you have an IP outside of the US as well.
