### ISSUE TITLE
[Bug]: Zapier plugin error

### ISSUE THREAD

**Issue by beddows** [danny-avila/LibreChat#863]
### What happened?

I followed the [Plugin Setup Instructions](https://github.com/danny-avila/LibreChat/blob/v0.5.8/docs/features/plugins/introduction.md) for Zapier and used my API key with the plugin. At Zapier, I have NLA Development actions for Gmail and Google Calendar.

When asking any question with the plugin active, I get the message:
_Encountered an error while attempting to respond. Error: Cannot read properties of undefined (reading 'toLowerCase')_

It doesn't matter if the question is related to the Zapier actions - any question triggers the error. The NLA logs are empty, so it doesn't look like the API is called.

### Steps to Reproduce

1. Create Zapier account and get [API Key from NLA](https://nla.zapier.com/credentials/). Connect Zapier account to NLA development provider.
2. Create [NLA Development actions](https://nla.zapier.com/dev/actions/).
3. In LibreChat, install Zapier plugin and include API key.
4. Check [NLA logs](https://nla.zapier.com/logs/).

### What browsers are you seeing the problem on?

Chrome, Safari

### Relevant log output

```shell
LibreChat         | [chain/error] [1:chain:AgentExecutor] [5ms] Chain run errored with error: "Cannot read properties of undefined (reading 'toLowerCase')"
LibreChat         | TypeError: Cannot read properties of undefined (reading 'toLowerCase')
LibreChat         |     at /app/api/node_modules/langchain/dist/agents/executor.cjs:129:78
LibreChat         |     at Array.map (<anonymous>)
LibreChat         |     at AgentExecutor._call (/app/api/node_modules/langchain/dist/agents/executor.cjs:129:59)
LibreChat         |     at AgentExecutor.call (/app/api/node_modules/langchain/dist/chains/base.cjs:106:26)
LibreChat         |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
LibreChat         |     at async PluginsClient.executorCall (/app/api/app/clients/PluginsClient.js:188:23)
LibreChat         |     at async PluginsClient.sendMessage (/app/api/app/clients/PluginsClient.js:312:5)
LibreChat         |     at async /app/api/server/routes/ask/gptPlugins.js:163:22
LibreChat         | getTokenCountForMessage {
LibreChat         |   role: 'assistant',
LibreChat         |   content: "Encountered an error while attempting to respond. Error: Cannot read properties of undefined (reading 'toLowerCase')"
LibreChat         | }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Will take a look soon! I remember reading that the default prompts provided by Zapier are not the best so I can also take the time of reviewing the prompts

**Comment by danny-avila** [comment]
This is what I'm referring to. I don't think the JS library has parity with this feature yet, but could look at implementing it https://github.com/langchain-ai/langchain/pull/4213
