### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Falven** [danny-avila/LibreChat#865]
### What happened?

There's a big issue with the presets route. That causes the API to crash and never work again for most endpoints unless the DB is cleared.

The issue is with the following lines:
```jsx
const presets = (await getPresets(req.user.email)).map((preset) => {
      return preset.toObject();
});
```

You're calling `toObject` on objects and it causes the API to crash. Not sure if this was leftover code before a DB schema change or why sometimes these preset variables would come back as strings.

We added these defensive checks for now:

```jsx
const presets = (await getPresets(req.user.email)).map((preset) =>
    typeof preset !== 'object' ? preset.toObject() : preset
);
```

### Steps to Reproduce

Not really sure.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I see, probably because the controllers used to receive a mongoose document object, but no longer do with the lean method, and this was missed. However, I’m surprised it would go unnoticed this long and I’m not sure how a retrieval route would necessitate clearing the database. This hasn’t been the case for me and I use the app daily, including/adding presets.

The toObject method should never be needed and seems like an easy patch. Feel free to PR or I can get it done later tonight

**Comment by Falven** [comment]
> I see, probably because the controllers used to return* a mongoose document object, but no longer do with the lean method, and this was missed. However, I’m surprised it would go unnoticed this long and I’m not sure how a retrieval route would necessitate clearing the database. This hasn’t been the case for me and I use the app daily, including/adding presets.
> 
> The toObject method should never be needed and seems like an easy patch. Feel free to PR or I can get it done later tonight

So it's not needed even for backwards compatibility? That should be a priority as there could be users with old conversations or presets.

**Comment by danny-avila** [comment]
> So it's not needed even for backwards compatibility? That should be a priority as there could be users with old conversations or presets. I can PR it tomorrow, I'm currently mobile.

Actually, it was removed here in #698. Backwards compatibility should not be affected by the change made in the PR, but you made me realize the mapping still in the code is a useless operation.

I can't comment on your fork's code as I'm not knowledgeable of what else may be causing the issue.

**Comment by Falven** [comment]
> > So it's not needed even for backwards compatibility? That should be a priority as there could be users with old conversations or presets. I can PR it tomorrow, I'm currently mobile.
> 
> Actually, it was removed here in #698. Backwards compatibility should not be affected by the change made in the PR, but you made me realize the mapping still in the code is a useless operation.
> 
> I can't comment on your fork's code as I'm not knowledgeable of what else may be causing the issue.

I think it may have just been an auto-merge issue. Thanks for your comments!
