### ISSUE TITLE
Enhancement: Add change bing ws link features

### ISSUE THREAD

**Issue by Nothingness-Void** [danny-avila/LibreChat#866]
### Contact Details

nothingnessvoid@outlook.com

### What features would you like to see added?

Recently, Microsoft has blocked certain IP addresses of data centers, which has caused some servers to be unable to access Bing's official access point directly. However, there are projects on GitHub, such as https://github.com/adams549659584/go-proxy-bingai, that allow users to set up their own Bing access point. Is it possible to add a customizable Bing access point function?

### More details

no more details

### Which components are impacted by your request?

Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I can look into it this weekend. Looks like this proxy service requires a socks5 proxy so this issue is related to #580. I’m closing this in favor of the earlier issue and will refer to the project you linked there
