### ISSUE TITLE
[Question]: Online MongoDB error 

### ISSUE THREAD

**Issue by Jack2Spiece-nn** [danny-avila/LibreChat#878]
### Contact Details

arjaysiega94@gmail.com

### What is your question?

Online MongoDB instruction do not exist : https://github.com/danny-avila/LibreChat/blob/main/docs/deployment/..%5Cinstall%5Cmongodb.md

### More Details

Can't open this link : https://github.com/danny-avila/LibreChat/blob/main/docs/deployment/..%5Cinstall%5Cmongodb.md

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Berry-13** [comment]
Here's the doc

https://github.com/danny-avila/LibreChat/blob/main/docs/install/mongodb.md

**Comment by Berry-13** [comment]
Where did you find this [link](https://github.com/danny-avila/LibreChat/blob/main/docs/deployment/..%5Cinstall%5Cmongodb.md)?

**Comment by danny-avila** [comment]
As was said, we would need to know where the incorrect link is. The doc you're looking for is here: https://docs.librechat.ai/install/mongodb.html#create-an-account

**Comment by Jack2Spiece-nn** [comment]
Thanks I found the link here
[(https://github.com/danny-avila/LibreChat/blob/main/docs/deployment/render.md)

**Comment by danny-avila** [comment]
> Thanks I found the link here (https://github.com/danny-avila/LibreChat/blob/main/docs/deployment/render.md)
> 
> on the part : "Create and Configure your Database"

thank you i fixed it!
