### ISSUE TITLE
Enhancement: Consensus plugin support

### ISSUE THREAD

**Issue by kuangxiaoye** [danny-avila/LibreChat#881]
### What features would you like to see added?

ChatGPT published a new plug-in "Thesis Search Artifact" called Consensus

https://consensus.app/

### More details

Can we support this feature?

### Pictures

<img width="1188" alt="image" src="https://github.com/danny-avila/LibreChat/assets/43713316/a1ef233f-4ac8-4bcd-be40-3fe9ce24d088">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I can try to add it when I have the time, but the guide to adding chatgpt plugins is somewhat simple if you want to give it a try: 
https://docs.librechat.ai/features/plugins/chatgpt_plugins_openapi.html#adding-a-plugin
