### ISSUE TITLE
Enhancement: Cache images (and/or serve with CDN)

### ISSUE THREAD

**Issue by finnless** [danny-avila/LibreChat#910]
### What happened?

Temporary images created by plugins can expire. This could be fixed with an option to cache returned images locally or some other option.

### Steps to Reproduce

Prompt a plugin to respond with an image.

### Screenshots

<img width="921" alt="image" src="https://github.com/danny-avila/LibreChat/assets/6785029/27f46c54-aab6-436f-a0e2-cb5cb1200412">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I thought about adding caching/CDN services for profile pictures, I guess it could apply here, too. I'll add this to the roadmap

**Comment by finnless** [comment]
It could use a similar approach to the DALL-E plugin where images are saved to `/images`
