### ISSUE TITLE
OpenRouter model fetching and assignment

### ISSUE THREAD

**Issue by jordantgh** [danny-avila/LibreChat#971]
### What is your question?

I am trying to access the gpt-4-32k model via openrouter. I have set my openrouter api key and from a couple of test messages confirm I am able to communicate with gpt4 via the LibreChat interface:

However, I'd like to access the 32k model. Is it as simple as uncommenting the OPENAI_MODELS key and adding gpt-4-32k? I will try that now and report back, but I thought it's worth logging an issue either way since it's non transparent.

### More Details

N/A

### What is the main subject of your question?

Documentation, Endpoints

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/56029559/b69d7d85-4b58-473a-a63e-bb0f24426f53)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jordantgh** [comment]
OK, it seems that my hypothesis was right - when you set an openrouter API key, it still draws from the list of models specified by OPENAI_MODELS, and changing this is all you need.

**Comment by danny-avila** [comment]
> OK, it seems that my hypothesis was right - when you set an openrouter API key, it still draws from the list of models specified by OPENAI_MODELS, and changing this is all you need.

it should be fetching the openrouter api for a list of models to show all of its supported models, was it not doing that for you? they are formatted differently, `openai/gpt-xxx`

**Comment by danny-avila** [comment]
In this case, i didn't even have to refresh the page after first server restart, and I don't have OPENAI_MODELS set

![image](https://github.com/danny-avila/LibreChat/assets/110412045/53d5c745-b499-45a2-9517-d9f19248c796)

**Comment by jordantgh** [comment]
Hm, it's not what I see.

Here is how things look with the relevant OPENAI_MODELS commented out and OPENROUTER_API_KEY set:

![image](https://github.com/danny-avila/LibreChat/assets/56029559/dda626f1-1413-4274-a8b0-0ac167198651)

And here is an example where I set both:

*.env*
![image](https://github.com/danny-avila/LibreChat/assets/56029559/bdf15d7c-cf27-4f75-81c0-ad950ad0c915)

*UI*
![image](https://github.com/danny-avila/LibreChat/assets/56029559/bb9623d1-3548-4f81-84c7-07135d11a212)

Note that I fully restarted the container and clear browser cache after any changes.

I am using Docker Desktop and Windows.

I'd note that it does appear to be working, and the chats are showing up in my openrouter activity.

**Comment by jordantgh** [comment]
IDK if this is helpful, but it seems that the model is automatically appended to the `openai/` route, hence:

![image](https://github.com/danny-avila/LibreChat/assets/56029559/d2705636-1478-4317-84e2-7fa981df6f08)

**Comment by danny-avila** [comment]
> Hm, it's not what I see.
> 
> Here is how things look with OPENAI_MODELS commented out and OPENROUTER_API_KEY set:
> 

Try refreshing the page to see if the list updates. Also I guess it appends on their end, that's good to know.

**Comment by jordantgh** [comment]
>Try refreshing the page to see if the list updates.

As I said, I was fully restarting the container and clearing browser cache after any changes. I can confirm that, at least on my system, setting the OPENROUTER_API_KEY variable alone isn't sufficient to populate the web frontend with the list of openrouter models; I require to do this manually.

**Comment by jordantgh** [comment]
I haven't set any openai keys in the first place as I just went straight to openrouter.  Hence the page still prompts me to `Set API Key First`

![image](https://github.com/danny-avila/LibreChat/assets/56029559/956d921e-b74d-4e27-8843-8eb1d524a5d3)

Is it possible there is some path dependency where you are assuming that first an openai key is present and being overwritten?

**Comment by jordantgh** [comment]
From quickly scanning around the code base it isn't clear to me how `modelsConfig` gets updated if OPENROUTER_API_KEY is set; if you can point me in the right direction I can take a closer look and see if I can't figure something out.

**Comment by danny-avila** [comment]
> Is it possible there is some path dependency where you are assuming that first an openai key is present and being overwritten?

Oh I see, yes you need an OPENAI_API_KEY variable set, and then models will fetch

**Comment by jordantgh** [comment]
I see - does this need looking at further? I can open another issue if so. Otherwise it's fine. For myself the issue is solved :)

**Comment by danny-avila** [comment]
> I see - does this need looking at further? I can open another issue if so. Otherwise it's fine. For myself the issue is solved :)

it was a quick fix so im pushing it with my new PR!
