### ISSUE TITLE
[Question]: Once the first user is created, it is not possible to generate new ones.

### ISSUE THREAD

**Issue by sontr-n** [danny-avila/LibreChat#976]
### What is your question?

How to create a second account without getting error?

### More Details

I was able to create a new user successfully on the first attempt but encountered an error when trying to create another user with a different email address. Upon further investigation, I discovered that the social network IDs (such as googleId and discordId) in the _User_ collection must be unique.
It appears that the issue occurred because the social network IDs were null during the second account creation, resulting in the error.

### What is the main subject of your question?

Documentation, User System/OAuth

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/27716315/6aca0b52-7b58-4f7e-b225-6441d9fb0d61)

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Can you let me know how to reproduce this? For example, I'm using Google OAuth on a fresh database collection:
- I login with the first gmail account, no problem
- I login with a different gmail account, no problem
- I inspect the database, and they indeed have unique googleId's.

**Comment by sontr-n** [comment]
1. I **create** the first gmail account (OK)
2. I **create** a new account with a different gmail (Error)

I inspected the source code and noticed used `{sparse: true}` yet still encountered the errors

MongoDB version: 3.6

**Comment by danny-avila** [comment]
> @danny-avila Thanks for getting back to me so quickly.
> 
> Step to reproduce
> 
> 1. I **create** the first gmail account (OK)
> 2. I **create** a new account with a different gmail (Error)
> 
> I inspected the source code and noticed that `{sparse: true}` was used, yet still encountered the errors
> 
> MongoDB version: 3.6

Of course, I want to help! Hmm maybe there’s a scoping issue with the way your OAuth is setup, because the IDs are returning null in all cases. I think maybe we could implement a fallback ID in case it’s null from the provider, with a warning issued that the provider did not issue an ID and one was generated so the user could be created uniquely.

I was going to say maybe it’s mongo acting up since you have an old version but what I said before is more likely

**Comment by sontr-n** [comment]
@danny-avila 
I've updated the new MongoDB version to 4.2 but it still faced the errors.

FYI
Environment: Azure

**Comment by sontr-n** [comment]
After researching, I discovered that Azure MongoDB does not support sparse indexes. Therefore, I am closing this.
![image](https://github.com/danny-avila/LibreChat/assets/27716315/16b59a02-1678-4eeb-a430-51cab41421a1)

Thanks

**Comment by danny-avila** [comment]
> After researching, I discovered that Azure MongoDB does not support sparse indexes. Therefore, I am closing this. ![image](https://user-images.githubusercontent.com/27716315/269564047-16b59a02-1678-4eeb-a430-51cab41421a1.png)
> 
> Thanks

I see, perhaps we can remove use of `sparse` for compatibility as I would like it to be compatible with cosmosDB
