### ISSUE TITLE
Max password length is still 40 on login screen

### ISSUE THREAD

**Issue by rmeekers** [danny-avila/LibreChat#978]
On the login screen I receive an error when entering a password of 50 chars that it should be less than 128.

It seems that the max length isn't updated here:
https://github.com/danny-avila/LibreChat/blob/1d3e336e1c06c2a8797368846ea3287fe4d6e749/client/src/components/Auth/LoginForm.tsx#L79C21-L79C21

**Comment by danny-avila** [comment]
Thank you for pointing this out, I'll work on it now!
