### ISSUE TITLE
[Bug]:  Auto-scroll on mobile browser prevents reading GPT reply until it's completed

### ISSUE THREAD

**Issue by jerkstorecaller** [danny-avila/LibreChat#983]
### What happened?

It's a minor bug tbh.

The auto-scrolling makes it impossible to read a reply until GPT has finished answering, which wastes the user's time. You scroll up to try to read the first sentence, but then the view is brought back to the last line Librechat received. I easily lose 1 minute per question when I use Librechat on my phone, just waiting for the reply to finish streaming before I can start reading the reply.

Recommended solution: the standard UI behavior in these sort of apps is to disable auto-scroll if the user scrolled up (i.e. not at the bottom of the page).

I tried this on Brave for Android (which means it's probably the same on all Chromium-based mobile browsers), and Librechat is unusable until the reply has completed. Note that desktop Firefox doesn't seem to have this issue. 

### Steps to Reproduce

1. Access Librechat using Brave for android, ask a question with a long answer, and try to read the first paragraph while the answer is still being received

### What browsers are you seeing the problem on?

Mobile (Android)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Hi @jerkstorecaller, I tested on my device and #984 should close it. Once it's merged, let me know if you're still experiencing this.
