### ISSUE TITLE
Enhancement: [Failed] Logins log for Fail2Ban

### ISSUE THREAD

**Issue by XHyperDEVX** [danny-avila/LibreChat#985]
### What features would you like to see added?

A function that writes all logins or at least all failed logins to a file or to the console log.

### More details

Since it would be great especially for Fail2Ban, I think that would be quite a suitable log format:

`[Mon Feb 17, 2023 18:25] [Login] [Login failed] [Username: <Username>] [Request-IP: <IP>]`

For Fail2Ban only the IP is really important, but I think it would be nice to have the whole thing a bit more detailed.

For anyone from the future hoping to find a Fail2Ban regex here, I think this one works:
`^\[.*\] \[Login\] \[Login failed\] \[.*\] \[Request-IP: <HOST>\]`

### Which components are impacted by your request?

General, Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Berry-13** [comment]
I hope this is what you mean :)

**Comment by XHyperDEVX** [comment]
> I hope this is what you mean :)

i think that is exactly
